### ISSUE TITLE
Loopback4096 address of iBGP peer was not programmed correctly in HW

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#10093]
I encountered the issue when running sonic-mgmt fib/test_fib.py on VOQ chassis with T2 topo.

The chassis has 3 LCs: LC3, LC4, and LC5. Each LC has only 1 ASIC.  The address of Loopback4096 of LC5 was 8.0.0.7:
root@cmp210-5:/# ifconfig Loopback4096                                                                 
Loopback4096: flags=195<UP,BROADCAST,RUNNING,NOARP>  mtu 65536                                         
        inet 8.0.0.7  netmask 255.255.255.255  broadcast 0.0.0.0                                       
        inet6 2603:10e2:400::7  prefixlen 128  scopeid 0x0<global>                                     
        inet6 fe80::74f6:92ff:fe59:8b17  prefixlen 64  scopeid 0x20<link>                           
        ether 76:f6:92:59:8b:17  txqueuelen 1000  (Ethernet)                                        
        RX packets 0  bytes 0 (0.0 B)                                                                  
        RX errors 0  dropped 0  overruns 0  frame 0                                                 
        TX packets 0  bytes 0 (0.0 B)             
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0_                                     

The inband address of LC5 is 1.1.1.5:
root@cmp210-5:/# ifconfig Ethernet-IB0
Ethernet-IB0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9100
        inet 1.1.1.5  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fc00:3000::5  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::febd:67ff:fe67:de55  prefixlen 64  scopeid 0x20<link>
        ether fc:bd:67:67:de:55  txqueuelen 1000  (Ethernet)
        RX packets 6977  bytes 46039941 (43.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 289596  bytes 61482171 (58.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

The above loopback was installed correctly in both kernel and APPL_DB/HW in LC4:
admin@cmp210-4:$ ip route show 8.0.0.7
8.0.0.7 via 1.1.1.5 dev Ethernet-IB0 proto bgp src 10.1.0.2 metric 20 onlink 
admin@cmp210-4:$ sonic-db-cli APPL_DB hgetall "ROUTE_TABLE:8.0.0.7"
{'ifname': 'Ethernet-IB0', 'nexthop': '1.1.1.5'}
admin@cmp210-4:$ 

However, on LC3, the above loop was installed correctly only in kernel, but not APPL_DB/HW.  Based on the following output from APPL_DB, it felt like 8.0.0.7 was learnt from eBGP peers. However, we checked the received routes from corresponding eBGP peers and couldn't find 8.0.0.7 at all.
admin@cmp210-3:$ ip route show 8.0.0.7
8.0.0.7 via 1.1.1.5 dev Ethernet-IB0 proto bgp src 10.1.0.2 metric 20 onlink 
admin@cmp210-3:$ sonic-db-cli APPL_DB hgetall "ROUTE_TABLE:8.0.0.7"                       
{'ifname': 'PortChannel0002,PortChannel0010,PortChannel0012,Ethernet108,Ethernet112,Ethernet116,Ethernet120,Ethernet124,Ethernet128,Ethernet132,Ethernet136,Ethernet140,Ethernet144,Ethernet148,Ethernet152,
Ethernet156,Ethernet164,Ethernet176,Ethernet180', 'nexthop': '10.0.0.1,10.0.0.17,10.0.0.21,10.0.0.33,10.0.0.35,10.0.0.37,10.0.0.39,10.0.0.41,10.0.0.43,10.0.0.45,10.0.0.47,10.0.0.49,10.0.0.51,10.0.0.53,10.
0.0.55,10.0.0.57,10.0.0.59,10.0.0.61,10.0.0.63'}            

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by rlhui** [comment]
@ysmanman  - is this still an issue or can be closed. Please update/remind here the latest. Thanks.

**Comment by ysmanman** [comment]
> @ysmanman - is this still an issue or can be closed. Please update/remind here the latest. Thanks.

Hi @rlhui we hadn't seen the issue anymore in recent testing. I am closing the issue.
