### ISSUE TITLE
[yang-models] can't use leaf-list when add test case into the sample_config_db.json

### ISSUE THREAD

**Issue by StormLiangMS** [sonic-net/sonic-buildimage#10116]
#### Description
Failed to compile the target - sonic_yang_mgmt-1.0-py3-none-any.whl, the reason is that the current function (src/sonic-yang-mgmt/sonic_yang_ext.py) which parsing the sample_config_db.json can't tackle with leaf-list type. 

#### Steps to reproduce the issue:
1. Add one configuration sample with leaf-list data into the sample_config_db.json
        "BGP_ALLOWED_PREFIXES" :{
            "DEPLOYMENT_ID|4|123:123": {
                "default_action": "permit",
                "prefixs_p4": "10.10.0.0/24",
                "prefixs_p6": "fc00:f1::/64"
            }
        }
3. compile the target -  target - sonic_yang_mgmt-1.0-py3-none-any.whl, it will failed to compile and drop error for key issues.
error log like bellowing
sonic_yang(3):All Keys are not parsed in BGP_ALLOWED_PREFIXES
dict_keys(['DEPLOYMENT_ID|4|123:123', 'DEPLOYMENT_ID|5'])
sonic_yang(3):exceptionList:["'prefixs_p4'", 'Value not found for deployment id community in DEPLOYMENT_ID|5', 'Value not found for deployment id in DEPLOYMENT_ID|4|123:123', "'prefixs_p4'"]
sonic_yang(3):Data Loading Failed:All Keys are not parsed in BGP_ALLOWED_PREFIXES
dict_keys(['DEPLOYMENT_ID|4|123:123', 'DEPLOYMENT_ID|5'])

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by praveen-li** [comment]
@[StormLiangMS](https://github.com/StormLiangMS) config must be in config_db.json format not in db schema format. Also plz add a link to yang model for same config. Thx.

**Comment by zhangyanzhao** [comment]
@StormLiangMS can you please help to reply Praveen's comments?
