### ISSUE TITLE
Media type is not displayed in show interface status when DPB  is done. 

### ISSUE THREAD

**Issue by aravindmani-1** [sonic-net/sonic-buildimage#10144]
#### Description
Media Type is not displayed in "show interface status" when DPB is configured.
STATE_DB didn't populate TRANSCEIVER_INFO for breakout ports.

        root@sonic:~# redis-cli -n 6 hgetall "TRANSCEIVER_INFO|Ethernet2"
        (empty array)
        root@sonic:~# redis-cli -n 6 hgetall "TRANSCEIVER_INFO|Ethernet4"
        (empty array)
        root@sonic:~# redis-cli -n 6 hgetall "TRANSCEIVER_INFO|Ethernet6"
        (empty array)
        root@sonic:~#

xcvrd doesn't seems to be triggered when breakout is done.
          
#### Steps to reproduce the issue:
1. Configure interface breakout EthernetX <breakout_mode>
2. After few minutes, check "show interface status"

#### Describe the results you received:
        root@sonic:~# show interface status
          Interface                            Lanes    Speed    MTU    FEC    Alias    Vlan    Oper    Admin                                             Type    Asym PFC
        -----------  -------------------------------  -------  -----  -----  -------  ------  ------  -------  -----------------------------------------------  ----------
          Ethernet0                            33,34     100G   9100    N/A    etp1a  routed    down     down  QSFP-DD Double Density 8X Pluggable 
         Transceiver         N/A
         Ethernet2                            35,36     100G   9100    N/A    etp1b  routed    down     down                                              N/A         N/A
         Ethernet4                            37,38     100G   9100    N/A    etp1c  routed    down     down                                              N/A         N/A
         Ethernet6                            39,40     100G   9100    N/A    etp1d  routed    down     down                                              N/A         N/A

#### Describe the results you expected:
        
          Ethernet0                           41,42     100G   9100    N/A    etp2a  routed    down     down  QSFP-DD Double Density 8X Pluggable Transceiver         N/A
         Ethernet2                            43,44     100G   9100    N/A    etp2b  routed    down     down  QSFP-DD Double Density 8X Pluggable Transceiver         N/A
         Ethernet4                            45,46     100G   9100    N/A    etp2c  routed    down     down  QSFP-DD Double Density 8X Pluggable Transceiver         N/A
         Ethernet6                            47,48     100G   9100    N/A    etp2d  routed    down     down  QSFP-DD Double Density 8X Pluggable Transceiver         N/A
#### Output of `show version`:
        root@sonic:~# show ver
        
        SONiC Software Version: SONiC.master.77221-3bb87c03a
        Distribution: Debian 11.2
        Kernel: 5.10.0-8-2-amd64
        Build commit: 3bb87c03a
        Build date: Wed Mar  2 19:53:17 UTC 2022
        Built by: AzDevOps@sonic-build-workers-00182P
        
        Platform: x86_64-dellemc_z9332f_d1508-r0
        HwSKU: DellEMC-Z9332f-O32
        ASIC: broadcom
        ASIC Count: 1
        Serial Number: 1QHXCW2
        Model Number: 04CN21
        Hardware Revision: A00
        Uptime: 08:37:27 up  1:02,  1 user,  load average: 0.52, 0.72, 0.73
        
        Docker images:
        REPOSITORY                    TAG                      IMAGE ID       SIZE
        docker-dhcp-relay             latest                   c00b5bf64d48   448MB
        docker-sonic-telemetry        latest                   6c44cda09c36   527MB
        docker-sonic-telemetry        master.77221-3bb87c03a   6c44cda09c36   527MB
        docker-database               latest                   e97523390582   439MB
        docker-database               master.77221-3bb87c03a   e97523390582   439MB
        docker-orchagent              latest                   f5d1f1222dbc   461MB
        docker-orchagent              master.77221-3bb87c03a   f5d1f1222dbc   461MB
        docker-sflow                  latest                   51d36fe8b890   442MB
        docker-sflow                  master.77221-3bb87c03a   51d36fe8b890   442MB
        docker-macsec                 latest                   c0528e1e37d7   444MB
        docker-macsec                 master.77221-3bb87c03a   c0528e1e37d7   444MB
        docker-fpm-frr                latest                   be9f576ebb2c   459MB
        docker-fpm-frr                master.77221-3bb87c03a   be9f576ebb2c   459MB
        docker-nat                    latest                   f7649eef16b5   444MB
        docker-nat                    master.77221-3bb87c03a   f7649eef16b5   444MB
        docker-teamd                  latest                   0d71b16b35ba   441MB
        docker-teamd                  master.77221-3bb87c03a   0d71b16b35ba   441MB
        docker-sonic-mgmt-framework   latest                   8db6ee819264   582MB
        docker-sonic-mgmt-framework   master.77221-3bb87c03a   8db6ee819264   582MB
        docker-syncd-brcm             latest                   bb3d0c4d9437   805MB
        docker-syncd-brcm             master.77221-3bb87c03a   bb3d0c4d9437   805MB
        docker-platform-monitor       latest                   39e606b24df3   540MB
        docker-platform-monitor       master.77221-3bb87c03a   39e606b24df3   540MB
        docker-snmp                   latest                   5e8908307018   470MB
        docker-snmp                   master.77221-3bb87c03a   5e8908307018   470MB
        docker-router-advertiser      latest                   2e038661370e   426MB
        docker-router-advertiser      master.77221-3bb87c03a   2e038661370e   426MB
        docker-lldp                   latest                   0510934d8083   466MB
        docker-lldp                   master.77221-3bb87c03a   0510934d8083   466MB
        docker-gbsyncd-credo          latest                   80434040f216   443MB
        docker-gbsyncd-credo          master.77221-3bb87c03a   80434040f216   443MB
        docker-mux                    latest                   7dc8ad026425   479MB
        docker-mux                    master.77221-3bb87c03a   7dc8ad026425   479MB

**Comment by prgeor** [comment]
@shyam77git FYI

**Comment by aravindmani-1** [comment]
I observed that xcvrd crash trace are seen once DPB is done in Dell Z9332f platform.
**Logs:**
        config interface breakout Ethernet56 "4x100G[50G]" -y -f
        
        Running Breakout Mode : 1x400G
        Target Breakout Mode : 4x100G[50G]
        
        Ports to be deleted :
         {
            "Ethernet56": "400000"
        }
        Ports to be added :
         {
            "Ethernet56": "100000",
            "Ethernet58": "100000",
            "Ethernet60": "100000",
            "Ethernet62": "100000"
        }
        
        After running Logic to limit the impact
        
        Final list of ports to be deleted :
         {
            "Ethernet56": "400000"
        }
        Final list of ports to be added :
         {
            "Ethernet56": "100000",
            "Ethernet58": "100000",
            "Ethernet60": "100000",
            "Ethernet62": "100000"
        }
        Breakout process got successfully completed.
        Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
        root@sonic:~#

        Process Process-2:
        Traceback (most recent call last):
          File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
            self.run()
          File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
            self._target(*self._args, **self._kwargs)
          File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1741, in task_worker
            port_mapping.handle_port_config_change(sel, asic_context, stopping_event, self.port_mapping, helper_logger, port_change_event_handler)
          File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd_utilities/port_mapping.py", line 177, in handle_port_config_change
            read_port_config_change(asic_context, port_mapping, logger, port_change_event_handler)
          File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd_utilities/port_mapping.py", line 214, in read_port_config_change
            port_change_event_handler(port_change_event)
        TypeError: on_port_config_change() takes 2 positional arguments but 3 were given
        Process Process-1:
        Traceback (most recent call last):
          File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
            self.run()
          File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
            self._target(*self._args, **self._kwargs)
          File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1315, in task_worker
            self.port_dict[lport]['host_tx_ready'] = self.get_host_tx_status(lport)
          File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1240, in get_host_tx_status
            state_port_tbl = self.xcvr_table_helper.get_state_port_tbl(asic_index)
          File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 2306, in get_state_port_tbl
            return self.state_port_tbl[asic_id]
        KeyError: None

**Comment by aravindmani-1** [comment]
**Update on this issue:**
There are 3 tasks running in xcvrd (SfpStateUpdate, CMIS Manager, DomInfoUpdate).
When breakout is done, CMIS Manager task tries to access the state port table before the port change event is triggered.
State port table/ASIC/logical port lists are all updated either by SfpStateUpdate and DomInfoupdate tasks( on_port_config_change() ).

•	https://github.com/sonic-net/sonic-platform-daemons/blob/e119b69ef305d8ae5e3989e63644a55f4ebb3126/sonic-xcvrd/xcvrd/xcvrd.py#L1655 
•	https://github.com/sonic-net/sonic-platform-daemons/blob/e119b69ef305d8ae5e3989e63644a55f4ebb3126/sonic-xcvrd/xcvrd/xcvrd.py#L1832 
•	https://github.com/sonic-net/sonic-platform-daemons/blob/e119b69ef305d8ae5e3989e63644a55f4ebb3126/sonic-xcvrd/xcvrd/xcvrd_utilities/port_mapping.py#L46 

I believe following things has to be done to resolve this issue:
1. Ideally, CMIS manager has to wait until port change event deletion/addition gets completed by other tasks(SfpStateUpdate,DomInfoUpdate) which is not happening in this case.
2. Also, on_add_logical_port() can be added here: https://github.com/sonic-net/sonic-platform-daemons/blob/e119b69ef305d8ae5e3989e63644a55f4ebb3126/sonic-xcvrd/xcvrd/xcvrd.py#L2033 which would resolve media type display issue.
3. Orchagent crashes while trying to set media settings for breakout ports. 
Port argument has to be passed properly as notify_media_settings tries to configure 8 lanes settings for 2 lanes(logical port) and causing the orchagent crash
https://github.com/sonic-net/sonic-platform-daemons/blob/e119b69ef305d8ae5e3989e63644a55f4ebb3126/sonic-xcvrd/xcvrd/xcvrd.py#L2155
