### ISSUE TITLE
[yang-models] Type or pattern enforcement for BGP community

### ISSUE THREAD

**Issue by StormLiangMS** [sonic-net/sonic-buildimage#10145]
#### Description
Currently, in yang-model files, the type of community is a string and no pattern enforcement, it would be always good to have enforcement of pattern for yang model element. 

#### Steps to reproduce the issue:
1. 
2.
3.

#### Describe the results you received:
code snippet for community yang model type.
        container COMMUNITY_SET {

            list COMMUNITY_SET_LIST {
                key "name";

                leaf name {
                    type string;
                    description "Community name";
                }

                leaf set_type {
                    type enumeration {
                        enum STANDARD;
                        enum EXPANDED;
                    }
                    description "Community type";
                }

                leaf match_action {
                    type enumeration {
                        enum ANY;
                        enum ALL;
                    }
                    description "Match action any/all";
                }

                leaf action {
                    type routing-policy-action-type;
                    description
                        "Permit/Deny action for the community";
                }

                leaf-list community_member {
                    type string;
                    description
                        "members of the community set.";
                }
            }
        }

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@StormLiangMS  can you please close this issue if it has been fixed ? Thanks.

**Comment by zhangyanzhao** [comment]
@StormLiangMS  can you please raise PR for the pattern of BGP_Community
