### ISSUE TITLE
Monit container_checker swss/syncd/teamd containers not running error in supervisor

### ISSUE THREAD

**Issue by SuvarnaMeenakshi** [sonic-net/sonic-buildimage#10170]
#### Steps to reproduce the issue:
1. Bringup chassis with n-asic sup , where few asics are not present.
2. swss/syncd/teamd services will come up in namespace corresponding to the asics that are available.
3. for the asics that are NOT available, swss/syncd/teamd service will come up, but dockers will not be up as asic is not present.
4. systemctl service will be in "active" state:
```
sudo systemctl status swss@<n>
â— swss@<n>.service - switch state service
     Loaded: loaded (/lib/systemd/system/swss@.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/swss@<n>.service.d
             â””â”€auto_restart.conf
     Active: active (running) since Mon 2022-03-07 19:38:55 UTC; 13min ago
    Process: 3905339 ExecStartPre=/usr/local/bin/swss.sh start <n> (code=exited, status=0/SUCCESS)
   Main PID: 3906818 (swss.sh)
      Tasks: 2 (limit: 38087)
     Memory: 11.7M
     CGroup: /system.slice/system-swss.slice/swss@<n>.service
             â”œâ”€3906818 /bin/bash /usr/local/bin/swss.sh wait <n>
             â””â”€3906832 python3 /usr/local/bin/asic_status.py swss <n>
             
```
#### Describe the results you received:
Syslog contains:
ERR monit[3108314]: 'container_checker' status failed (3) -- Expected containers not running: swss<n>, syncd<n>, teamd<n>
Also, affects the test_container_checker test case.

#### Describe the results you expected:
monit should not complain about the swss/syncd/teamd containers of the asics which are not present.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prsunny** [comment]
@abdosi to triage and identify next steps for this issue.

**Comment by SuvarnaMeenakshi** [comment]
PR raised to fix https://github.com/sonic-net/sonic-buildimage/pull/11442
