### ISSUE TITLE
[DPB]Orchagent crashes in master image while configuring DPB in DellEMC Z9332f

### ISSUE THREAD

**Issue by aravindmani-1** [sonic-net/sonic-buildimage#10174]
#### Description
OA crashes in z9332f while configuring breakout for multiple interfaces in master image. 
Used debug image here to get OA back traces.

#### Steps to reproduce the issue:
1. config interface breakout Ethernet0 4x100G[50G] -y -f
2. Repeat step 1 for multiple interfaces
3. Check whether OA crashes

#### Describe the results you received:
OA core is generated.
**Crash trace:**
[core trace.txt](https://github.com/Azure/sonic-buildimage/files/8202650/core.trace.txt)
**OA logs:**
[OA_logs.txt](https://github.com/Azure/sonic-buildimage/files/8202656/OA_logs.txt)

#### Describe the results you expected:
OA should not crash

#### Output of `show version`:
        root@sonic:~# show ver
        
        SONiC Software Version: SONiC.master.78388-b2409be2f
        Distribution: Debian 11.2
        Kernel: 5.10.0-8-2-amd64
        Build commit: b2409be2f
        Build date: Sun Mar  6 17:37:28 UTC 2022
        Built by: AzDevOps@sonic-build-workers-0018IU
        
        Platform: x86_64-dellemc_z9332f_d1508-r0
        HwSKU: DellEMC-Z9332f-O32
        ASIC: broadcom
        ASIC Count: 1
        Serial Number: 1QHXCW2
        Model Number: 04CN21
        Hardware Revision: A00
        Uptime: 04:10:11 up 23:41,  1 user,  load average: 0.59, 0.81, 0.90```
#### Output of `show techsupport`:
[sonic_dump_sonic_20220307_044357.tar.gz](https://github.com/Azure/sonic-buildimage/files/8202719/sonic_dump_sonic_20220307_044357.tar.gz)

**Comment by aravindmani-1** [comment]
@zhenggen-xu Could you please help on this issue?.

**Comment by zhangyanzhao** [comment]
@aravindmani-1 will try the suggestion. @praveen-li
