### ISSUE TITLE
make init fail. Help please!

### ISSUE THREAD

**Issue by zhengbiqing** [sonic-net/sonic-buildimage#10357]
#### Steps to reproduce the issue:
1. Follow the steps of Usage section in https://github.com/Azure/sonic-buildimage.  in Ubuntu 20.04. system.
2. in make init, almost dead after: "Cloning into '/home/zbq/sonic/sonic-buildimage/platform/mellanox/sdk-src/sx-kernel/Switch-SDK-drivers'... "  so I enter /home/zbq/sonic/sonic-buildimage/platform/mellanox/sdk-src/sx-kernel and use command "git clone https://github.com/Mellanox/Switch-SDK-drivers ", try several times, git clone success.  For other clone failed modules of "make init" I fix them as ''Switch-SDK-drivers".
3. 
4. 
5.

#### Describe the results you received:

After all modules cloned ok. make init fail:

zbq@ubuntu:~/sonic/sonic-buildimage$ make init
+++ Making init +++
make -f Makefile.work init
make[1]: Entering directory '/home/zbq/sonic/sonic-buildimage'
Submodule path 'src/sonic-sairedis/SAI/bm/behavioral-model': checked out '55b2b04fb3dbeb2762142db73627f3918f7bf7f2'
Submodule path 'src/sonic-sairedis/SAI/test/ptf': checked out '10a2d4b7d704a430218adc8accf8115376a356eb'
Submodule path 'src/sonic-sairedis/SAI/test/saithrift/ctypesgen': checked out '3d2d9803339503d2988382aa861b47a6a4872c32'
Submodule path 'src/sonic-snmpagent': checked out '6f2d8d2110967d813053bcfcd8b34c42c5d0cda2'
Submodule path 'src/sonic-swss': checked out '6a6b7118ff2496d49676e82a9884aefbfbd08273'
Submodule path 'src/sonic-swss-common': checked out 'a1abaa83c0326e3fa65ac70d394ef9db3554d43d'
Submodule path 'src/sonic-telemetry': checked out 'e56e9b44e4a7e3b211f070c298041951c543885b'
Submodule path 'src/sonic-utilities': checked out '9968d603e6e9b417b96598a4022da7a98e8b331e'
Submodule path 'src/wpasupplicant/sonic-wpa-supplicant': checked out '986a835153b3df3a37492fbd3a83fc8e38a40c10'
Entering 'platform/barefoot/sonic-platform-modules-arista'
Entering 'platform/broadcom/saibcm-modules-dnx'
Entering 'platform/broadcom/sonic-platform-modules-arista'
Entering 'platform/broadcom/sonic-platform-modules-nokia'
Entering 'platform/mellanox/hw-management/hw-mgmt'
Entering 'platform/mellanox/mlnx-sai/SAI-Implementation'
Entering 'platform/mellanox/sdk-src/sx-kernel/Switch-SDK-drivers'
**_fatal: run_command returned non-zero status for platform/mellanox/sdk-src/sx-kernel/Switch-SDK-drivers_**
.
make[1]: *** [Makefile.work:373: init] Error 128
make[1]: Leaving directory '/home/zbq/sonic/sonic-buildimage'
make: *** [Makefile:64: init] Error 2

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by dgsudharsan** [comment]
@zhengbiqing  Can you please specify the branch you are using in sonic-buildimage? Can you also please check if you are synced to the head of the branch in sonic-buildimage?
make init should also be accomplished by "git submodule update --recursive". Can you please try this?

**Comment by zhengbiqing** [comment]
Thanks!  I fix the problem by hand.   but don't know the real reason. 

I find something wrong with .git directory and .git file of many modules.  the modules are links in sonic-buildimg will have wrong:

[Switch-SDK-drivers @ 37475d9](https://github.com/Mellanox/Switch-SDK-drivers/tree/37475d91930e3aae3490a4423da280a5cae72407)

maybe my git not configured normally?
