### ISSUE TITLE
[Vxlanmgrd] vxlan tunnel map netdev creation fails when the dev name length crosses IFNAMSIZ  

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#10466]
#### Description

Vxlan Tunnel Map Netdev creation fails when the length of vxlan_dev_name crosses IFNAMSIZ . 

#### Steps to reproduce the issue:
```
1. config vlan add 10 && config vlan member add 10 Ethernet8
2. sudo config vxlan add neighbor_advertiser 1.1.1.1
3. config vxlan map add neighbor_advertiser 10 1
4. ip link show vxlan
```

Note: This is seen in 202012 & 202111 and master as well. 

#### Describe the results you received:

No vxlan netdev is created.

In syslog:
```
root@sonic:/home/admin# show logging -f | grep vxlan
Apr  4 22:44:37.778893 r-lionfish-16 NOTICE swss#vxlanmgrd: :- doVxlanTunnelCreateTask: Create vxlan tunnel neighbor_advertiser
Apr  4 22:46:24.964017 r-lionfish-16 INFO swss#/supervisord: vxlanmgrd Error: argument "neighbor_advertiser-10" is wrong: "dev" not a valid ifname
Apr  4 22:46:24.965238 r-lionfish-16 WARNING swss#vxlanmgrd: :- doVxlanTunnelMapCreateTask: Vxlan Net Dev creation failure for neighbor_advertiser VNI(1) VLAN(10)
```

#### Describe the results you expected:

These commands must be executed succesfully [Code](https://github.com/Azure/sonic-swss/blob/master/cfgmgr/vxlanmgr.cpp#L983)

and no errors should be seen on syslog

**Comment by dgsudharsan** [comment]
@prsunny  FYI. There is a test in sonic-mgmt that results in vxlan netdev crossing IFNAMSIZ and thus leading to errors. Can you please assign someone to investigate?

**Comment by prsunny** [comment]
@vivekreddynv , @dgsudharsan , can you point me to the test where they create vxlan netdevs crossing the name size limit

**Comment by vivekreddynv** [comment]
Hi @prsunny, after a recheck it seems the test isn't configuring a netdev name greater than IFNAMSIZ. We did see these logs in out test but unclear where the config came from. 

So, no issue in the test, it is configuring names under the IFNAMSIZ. This is a general issue for vxlanmgr source code

**Comment by gord1306** [comment]
@vivekreddynv  Could you provide the info that IFNAMSIZ being enlarged to 256? In the [linux github repo](https://github.com/torvalds/linux/blob/v5.10/include/uapi/linux/if.h#L33) the IFNAMSIZ is still defined to 16. Thanks.

**Comment by vivekreddynv** [comment]
> @vivekreddynv Could you provide the info that IFNAMSIZ being enlarged to 256? In the [linux github repo](https://github.com/torvalds/linux/blob/v5.10/include/uapi/linux/if.h#L33) the IFNAMSIZ is still defined to 16. Thanks.

You're right. Thanks for correcting. This fails on bullseye as well.

**Comment by prsunny** [comment]
@vivekreddynv , Could you close the issue if a fix is currently not expected? Thanks.

**Comment by dgsudharsan** [comment]
> @vivekreddynv , Could you close the issue if a fix is currently not expected? Thanks.

Prince, this issue is still a functional one. The test we thought introduced the config is not present. However we can manually create the issue and there is no check in vxlanmgr preventing invalid name
