### ISSUE TITLE
[yang] Need Yang for DEVICE_NEIGHBOR_METADATA table

### ISSUE THREAD

**Issue by ganglyu** [sonic-net/sonic-buildimage#10545]
#### Description

We don't have Yang model for DEVICE_NEIGHBOR_METADATA table.

#### Steps to reproduce the issue:
1. Run 'config apply-patch' command
2. We can get below info:
sonic_yang(6):Note: Below table(s) have no YANG models: CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, KDUMP, RESTAPI, SNMP, SNMP_COMMUNITY, TELEMETRY

#### Describe the results you received:
sonic_yang reports no Yang models.

#### Describe the results you expected:
sonic_yang reports no Yang models.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@StormLiangMS  please help to create YANG model

**Comment by zhangyanzhao** [comment]
@StormLiangMS  a kind reminder

**Comment by StormLiangMS** [comment]
Start to work on this, and ETA would be end of Aug'2022
