### ISSUE TITLE
[yang] Need Yang for SNMP_COMMUNITY table

### ISSUE THREAD

**Issue by ganglyu** [sonic-net/sonic-buildimage#10550]
#### Description

We don't have Yang model for SNMP_COMMUNITY table.

#### Steps to reproduce the issue:
1. Run 'config apply-patch' command
2. We can get below info:
sonic_yang(6):Note: Below table(s) have no YANG models: CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, KDUMP, RESTAPI, SNMP, SNMP_COMMUNITY, TELEMETRY

#### Describe the results you received:
sonic_yang reports no Yang models.

#### Describe the results you expected:
sonic_yang reports ok.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by adyeung** [comment]
@ganglyu @zhangyanzhao BRCM will post PR, ETA mid May

**Comment by zhangyanzhao** [comment]
Thanks @adyeung and BRCM for the help

**Comment by adyeung** [comment]
Support added in #10828
