### ISSUE TITLE
[BGP]SONiC advertises Loopback0 IPv6 address with "/128" subnet as IPv6 routes with "/64" subnet

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#10603]
#### Description
When loopback interface in SONiC has IPv6 address as ‘/128’ subnet it is advertised as ‘/64’ subnet. This behavior is hardcoded due to the below j2 template which does the replacement

https://github.com/Azure/sonic-buildimage/blob/3522ac61fe967ed1ae8bd091345a67980e4ece6f/dockers/docker-fpm-frr/frr/bgpd/bgpd.main.conf.j2#L14

Due to this if two devices have IPv6 in Loopback with different /128 prefix but that falls within the same /64 prefix it would lead to issues in the network. If there are protocols that use loopback network then there would be reachability issues.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
make the template changeable to be able to support both /128 and /64 advertisement. MSFT can help to provide some help.

**Comment by dgsudharsan** [comment]
This problem can be overcome using the changes defined in https://github.com/sonic-net/sonic-buildimage/pull/10958. However SONiC by default would advertise /128 as /64
