### ISSUE TITLE
[FDB] [VLAN] Error log "Failed to get port by bridge port ID" seen 

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#10629]
#### Steps to reproduce the issue:
1.  This is hard to repro and is seen when fdb learn events are received and at the same timewhen the corresponding VLAN member is removed from VLAN 

#### Describe the results you received:

In Syslog:
```
Apr  3 21:01:27.202472 r-spider-05 ERR swss#orchagent: :- update: Failed to get port by bridge port ID 0x3a000000000bb0.
Apr  3 21:01:27.202472 r-spider-05 ERR swss#orchagent: message repeated 2 times: [ :- update: Failed to get port by bridge port ID 0x3a000000000bb0.]
```

Notifications:
```
2022-04-03.21:01:27.170794|VLAN_MEMBER_TABLE:Vlan50:PortChannel1111|DEL
2022-04-03.21:01:27.170898|r|SAI_OBJECT_TYPE_VLAN_MEMBER:oid:0x27000000000bb1
2022-04-03.21:01:27.172221|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x26000000000bad\",\"mac\":\"0C:42:A1:5A:57:90\",\"switch_id\":\"oid:0x21000000000000\"}",

"fdb_event":"SAI_FDB_EVENT_LEARNED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a000000000bb0"},{"id":"SAI_FDB_ENTRY_ATTR_TYPE","value":"SAI_FDB_ENTRY_TYPE_DYNAMIC"},{"id":"SAI_FDB_ENTRY_ATTR_PACKET_ACTION","value":"SAI_PACKET_ACTION_FORWARD"}]},{"fdb_entry":"{\"bvid\":\"oid:0x26000000000013\",\"mac\":\"0C:42:A1:5A:57:91\",\"switch_id\":\"oid:0x21000000000000\"}",

"fdb_event":"SAI_FDB_EVENT_LEARNED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a000000000bb0"},{"id":"SAI_FDB_ENTRY_ATTR_TYPE","value":"SAI_FDB_ENTRY_TYPE_DYNAMIC"},{"id":"SAI_FDB_ENTRY_ATTR_PACKET_ACTION","value":"SAI_PACKET_ACTION_FORWARD"}]},{"fdb_entry":"{\"bvid\":\"oid:0x26000000000013\",\"mac\":\"0C:42:A1:5A:57:90\",\"switch_id\":\"oid:0x21000000000000\"}",

"fdb_event":"SAI_FDB_EVENT_LEARNED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a000000000bb0"},{"id":"SAI_FDB_ENTRY_ATTR_TYPE","value":"SAI_FDB_ENTRY_TYPE_DYNAMIC"},{"id":"SAI_FDB_ENTRY_ATTR_PACKET_ACTION","value":"SAI_PACKET_ACTION_FORWARD"}]}]|

2022-04 03.21:01:27.176626|f|SAI_OBJECT_TYPE_FDB_FLUSH:oid:0x21000000000000|SAI_FDB_FLUSH_ATTR_BRIDGE_PORT_ID=oid:0x3a000000000bb0|SAI_FDB_FLUSH_ATTR_BV_ID=oid:0x26000000000bad
2022-04-03.21:01:27.180131|F|SAI_STATUS_SUCCESS
2022-04-03.21:01:27.180873|s|SAI_OBJECT_TYPE_BRIDGE_PORT:oid:0x3a000000000bb0|SAI_BRIDGE_PORT_ATTR_ADMIN_STATE=false
2022-04-03.21:01:27.186855|s|SAI_OBJECT_TYPE_HOSTIF:oid:0xd000000000975|SAI_HOSTIF_ATTR_VLAN_TAG=SAI_HOSTIF_VLAN_TAG_STRIP
2022-04-03.21:01:27.188379|s|SAI_OBJECT_TYPE_HOSTIF:oid:0xd000000000993|SAI_HOSTIF_ATTR_VLAN_TAG=SAI_HOSTIF_VLAN_TAG_STRIP

```

#### Triage:

There are three SAI_FDB_EVENT_LEARNED fdb_events coming from syncd. But before fdborch operates on these, the PortChannel1111 is removed from the VLAN50 and thus removing the sai bridge_port object internally in the OA.

By the time fdborch gets to handle the notification https://github.com/Azure/sonic-swss/blob/202012/orchagent/fdborch.cpp#L172, the bridge_port is missing and thus the logs. 

#### Output of `show version`:

Was initially seen on 202012, but can be seen irrespective of image version.

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[sysdump_test_core_functionality_with_reboot.tar.gz](https://github.com/Azure/sonic-buildimage/files/8523946/sysdump_test_core_functionality_with_reboot.tar.gz)

**Comment by zhangyanzhao** [comment]
Race condition happened.  The expected operation logic: set admin false firstly then fdb flush. BRCM will fix this issue.

**Comment by anilkpan** [comment]
@zhangyanzhao, currently, admin state is set to false, then fdb flush is done and then the bridgeport is removed. This sequence is already in place for the case when the last vlan is removed from the port.
Fdb learn events can be already in flight to OA even before admin state is disabled and these events can cause the error to be logged if they arrived at OA after bridgeport is removed.

**Comment by zhangyanzhao** [comment]
The message can be ignored for now.
