### ISSUE TITLE
[DellEMC]Failed to set pre-emphasis settings 

### ISSUE THREAD

**Issue by aravindmani-1** [sonic-net/sonic-buildimage#10638]
#### Description
In latest master image, pre-emphasis settings failure message is seen in Dell platforms.
Even though the pre-emp settings are present in PORT_TABLE, swss fails to push it to NPU.

#### Steps to reproduce the issue:
1. Load latest master image.
2. Look for swss logs and notice the failure.
3. Issue is seen for all the ports.

#### Describe the results you received:
        Apr 21 13:07:32.632489 sonic-z9332f-01 ERR swss#orchagent: :- doPortTask: Failed to set port Ethernet0 pre-emphasis
        Apr 21 13:07:32.633311 sonic-z9332f-01 ERR swss#orchagent: :- doPortTask: Failed to set port Ethernet8 pre-emphasis

#### Describe the results you expected:
        Apr 12 21:33:18.777068 sonic-z9332f-01 NOTICE swss#orchagent: :- doPortTask: Set port Ethernet0  preemphasis is success
        Apr 12 21:33:18.780017 sonic-z9332f-01 NOTICE swss#orchagent: :- doPortTask: Set port Ethernet8  preemphasis is success

#### Output of `show version`:
root@sonic:~# show ver

SONiC Software Version: SONiC.master.91660-598ab9946
Distribution: Debian 11.3
Kernel: 5.10.0-8-2-amd64
Build commit: 598ab9946
Build date: Tue Apr 19 22:41:06 UTC 2022
Built by: AzDevOps@sonic-build-workers-001F5I

Platform: x86_64-dellemc_z9332f_d1508-r0
HwSKU: DellEMC-Z9332f-O32
ASIC: broadcom
ASIC Count: 1
Serial Number: 1PPXCW2
Model Number: 04CN21
Hardware Revision: A00
Uptime: 11:24:20 up 0 min,  1 user,  load average: 3.37, 0.88, 0.30
Date: Thu 21 Apr 2022 11:24:20

#### Output of `show techsupport`:
[sonic_dump_sonic_20220421_112505.tar.gz](https://github.com/Azure/sonic-buildimage/files/8527571/sonic_dump_sonic_20220421_112505.tar.gz)

**Comment by aravindmani-1** [comment]
@prgeor Could you please help to resolve this issue?.

**Comment by zhangyanzhao** [comment]
Please investigate if this is because of SAI issue.

**Comment by gechiang** [comment]
Investigated this issue and found this is a SAI issue where it is failing to get the port serdis ID and it gets stuck there forever (perhgaps due to the way OA  will keep retrying...:
```
2022-05-19.02:30:23.961348|g|SAI_OBJECT_TYPE_PORT:oid:0x100000000001f|SAI_PORT_ATTR_PORT_SERDES_ID=oid:0x0
2022-05-19.02:30:23.962144|G|SAI_STATUS_ITEM_NOT_FOUND|
2022-05-19.02:30:23.962463|g|SAI_OBJECT_TYPE_PORT:oid:0x100000000001f|SAI_PORT_ATTR_PORT_SERDES_ID=oid:0x0
2022-05-19.02:30:23.963403|G|SAI_STATUS_ITEM_NOT_FOUND|
2022-05-19.02:30:24.065278|g|SAI_OBJECT_TYPE_PORT:oid:0x100000000001f|SAI_PORT_ATTR_PORT_SERDES_ID=oid:0x0
2022-05-19.02:30:24.066054|G|SAI_STATUS_ITEM_NOT_FOUND|
2022-05-19.02:30:24.066586|g|SAI_OBJECT_TYPE_PORT:oid:0x1000000000026|SAI_PORT_ATTR_PORT_SERDES_ID=oid:0x0
2022-05-19.02:30:24.067391|G|SAI_STATUS_ITEM_NOT_FOUND|
```
I have filed CSP case CS00012246105 with BRCM on this issue.

**Comment by aravindmani-1** [comment]
Just an update, this issue is seen in latest SAI too.
root@sonic:~# bcmcmd "bsv"
bsv
BRCM SAI ver: [7.1.0.0], OCP SAI ver: [1.10.2], SDK ver: [sdk-6.5.24]
drivshell>
root@sonic:~#

**Comment by aravindmani-1** [comment]
verified that this issue is fixed in latest master image. Hence, closing it.
