### ISSUE TITLE
[chassis] Removing a nbr causes orchagent to exit on remote asics with error SAI_STATUS_OBJECT_IN_USE

### ISSUE THREAD

**Issue by mannytaheri** [sonic-net/sonic-buildimage#10734]
#### Description
If any test bring downs a local eBGP neighbor (like bgp shutdown, link flap etc.), then sometimes we see orchagent exit on the remote asics with the following error in syslog:

Orchagent exits on a remote
Encountered failure in remove of a eBGP neighbor, exiting orchagent, SAI API: SAI_API_NEIGHBOR, status: SAI_STATUS_OBJECT_IN_USE

handleSaiRemoveStatus: Encountered failure in remove operation, exiting orchagent, SAI API: SAI_API_NEIGHBOR, status: SAI_STATUS_OBJECT_IN_USE

#### Steps to reproduce the issue:
Run any testcases that includes negative actions like config bgp shutdown/startup all, link flap, or deleting/re-adding portchannel. Example:

test_po_cleanup
test_port_toggle
test_cont_link_flap

#### Describe the results you received:
The cause of this problem is that is neighbor reference count mismatch between orchagent and SAI in the remote asics.
Sometimes in orchagent the reference count of a neighbor became 0 while SAI still has some routes referenced to it.
So when orchagent tries to remove this SAI returns this error.
There are no errors or ochagent crash on the asic (asic0 in this case) where the neighbors are removed.

Below are syslog messages seen upon deletion of eBGP neighbor on PortChannel101 on asic0:

**May 1 11:15:11.913020 ixre-egl-board27 NOTICE swss0#orchagent: :- removeLagMember: Remove member Ethernet4 from LAG PortChannel102 lid:200000000071d lmid:1b00000000071f
May 1 11:15:11.914635 ixre-egl-board27 NOTICE swss1#orchagent: :- removeLagMember: Remove member ixre-egl-board27|asic0|Ethernet4 from LAG ixre-egl-board27|asic0|PortChannel102 lid:102000000000720 lmid:11b00000000074d**
May 1 11:15:12.009272 ixre-egl-board27 NOTICE swss0#orchagent: :- addNextHopGroup: Create next hop group 10.0.0.5@Ethernet17,10.0.0.7@Ethernet-IB0,10.0.0.11@Ethernet-IB0
May 1 11:15:12.147431 ixre-egl-board27 INFO syncd0#syncd: [06:00.0] SAI_API_FDB:_brcm_sai_fdb_event_cb:209 fdbEvent: learn event (3) for mac 36-77-13-45-F1-FA vid:0x0, port:0x6c00002f lagid:0x0 flags:0x0 flags2:0x0 lag:false station flags 0x0
May 1 11:15:12.162520 ixre-egl-board27 WARNING syncd0#syncd: :- checkRidExists: removed RID oid:0x1003a00000005 exists
May 1 11:15:12.162520 ixre-egl-board27 ERR syncd0#syncd: :- process_on_fdb_event: invalid OIDs in fdb notifications, NOT translating and NOT storing in ASIC DB
May 1 11:15:12.162520 ixre-egl-board27 ERR syncd0#syncd: :- process_on_fdb_event: FDB notification was not sent since it contain invalid OIDs, bug?
May 1 11:15:12.260848 ixre-egl-board27 NOTICE swss0#orchagent: :- addNextHopGroup: Create next hop group fc00::a@Ethernet17,fc00::e@Ethernet-IB0,fc00::16@Ethernet-IB0
May 1 11:15:12.301057 ixre-egl-board27 NOTICE swss1#orchagent: :- addNextHopGroup: Create next hop group 10.0.0.5@Ethernet-IB1,10.0.0.7@PortChannel106,10.0.0.11@Ethernet30
May 1 11:15:12.344504 ixre-egl-board27 NOTICE swss1#orchagent: :- addNextHopGroup: Create next hop group fc00::a@Ethernet-IB1,fc00::e@PortChannel106,fc00::16@Ethernet30
May 1 11:15:12.353696 ixre-egl-board27 INFO syncd0#syncd: [06:00.0] SAI_API_FDB:_brcm_sai_fdb_event_cb:209 fdbEvent: learn event (3) for mac 36-77-13-45-F1-FA vid:0x0, port:0x6c00002f lagid:0x0 flags:0x0 flags2:0x0 lag:false station flags 0x0
May 1 11:15:12.375695 ixre-egl-board27 WARNING syncd0#syncd: :- checkRidExists: removed RID oid:0x1003a00000005 exists
May 1 11:15:12.375695 ixre-egl-board27 ERR syncd0#syncd: :- process_on_fdb_event: invalid OIDs in fdb notifications, NOT translating and NOT storing in ASIC DB
May 1 11:15:12.375695 ixre-egl-board27 ERR syncd0#syncd: :- process_on_fdb_event: FDB notification was not sent since it contain invalid OIDs, bug?
May 1 11:15:12.382523 ixre-egl-board27 NOTICE swss0#orchagent: :- removeNextHopGroup: Delete next hop group 10.0.0.1@PortChannel102,10.0.0.5@Ethernet17
May 1 11:15:12.382523 ixre-egl-board27 WARNING swss0#orchagent: :- removeNextHopGroup: NHFLAGS_IFDOWN set for next hop group member 10.0.0.1@PortChannel102 with next_hop_id 2d000000000766
May 1 11:15:12.387821 ixre-egl-board27 NOTICE swss0#orchagent: :- removeNextHopGroup: Delete next hop group 10.0.0.1@PortChannel102,10.0.0.5@Ethernet17,10.0.0.7@Ethernet-IB0,10.0.0.11@Ethernet-IB0
May 1 11:15:12.387821 ixre-egl-board27 WARNING swss0#orchagent: :- removeNextHopGroup: NHFLAGS_IFDOWN set for next hop group member 10.0.0.1@PortChannel102 with next_hop_id 2d000000000799
May 1 11:15:12.389653 ixre-egl-board27 NOTICE swss0#orchagent: :- removeNextHopGroup: Delete next hop group fc00::2@PortChannel102,fc00::a@Ethernet17,fc00::e@Ethernet-IB0,fc00::16@Ethernet-IB0
May 1 11:15:12.389760 ixre-egl-board27 WARNING swss0#orchagent: :- removeNextHopGroup: NHFLAGS_IFDOWN set for next hop group member fc00::2@PortChannel102 with next_hop_id 2d0000000007a4
May 1 11:15:12.394991 ixre-egl-board27 NOTICE swss0#orchagent: :- removeNeighbor: Removed next hop 10.0.0.1 on PortChannel102
**May 1 11:15:12.396275 ixre-egl-board27 NOTICE swss0#orchagent: :- removeNeighbor: Removed neighbor 36:77:13:45:f1:fa on PortChannel102**
May 1 11:15:12.420264 ixre-egl-board27 NOTICE swss0#orchagent: :- removeNextHopGroup: Delete next hop group fc00::2@PortChannel102,fc00::a@Ethernet17
May 1 11:15:12.420264 ixre-egl-board27 WARNING swss0#orchagent: :- removeNextHopGroup: NHFLAGS_IFDOWN set for next hop group member fc00::2@PortChannel102 with next_hop_id 2d000000000788
May 1 11:15:12.420929 ixre-egl-board27 NOTICE syncd0#syncd: :- inc: 10116 (calls 60) Syncd::syncUpdateRedisBulkQuadEvent op took: 280 ms
May 1 11:15:12.423482 ixre-egl-board27 NOTICE swss0#orchagent: :- removeNeighbor: Removed next hop fc00::2 on PortChannel102
May 1 11:15:12.424685 ixre-egl-board27 NOTICE swss0#orchagent: :- removeNeighbor: Removed neighbor 36:77:13:45:f1:fa on PortChannel102
May 1 11:15:12.489633 ixre-egl-board27 NOTICE swss1#orchagent: :- removeNextHopGroup: Delete next hop group 10.0.0.1@Ethernet-IB1,10.0.0.5@Ethernet-IB1
May 1 11:15:12.491815 ixre-egl-board27 NOTICE swss1#orchagent: :- removeNextHopGroup: Delete next hop group 10.0.0.1@Ethernet-IB1,10.0.0.5@Ethernet-IB1,10.0.0.7@PortChannel106,10.0.0.11@Ethernet30
May 1 11:15:12.494287 ixre-egl-board27 NOTICE swss1#orchagent: :- removeNextHopGroup: Delete next hop group fc00::2@Ethernet-IB1,fc00::a@Ethernet-IB1
May 1 11:15:12.496122 ixre-egl-board27 NOTICE swss1#orchagent: :- removeNextHopGroup: Delete next hop group fc00::2@Ethernet-IB1,fc00::a@Ethernet-IB1,fc00::e@PortChannel106,fc00::16@Ethernet30
May 1 11:15:12.500510 ixre-egl-board27 NOTICE swss1#orchagent: :- removeNeighbor: Removed next hop 10.0.0.1 on ixre-egl-board27|asic0|PortChannel102
May 1 11:15:12.501002 ixre-egl-board27 ERR syncd1#syncd: [07:00.0] SAI_API_NEIGHBOR:brcm_sai_remove_neighbor_entry:418 Neighbor vr_id 1 NH 1 references found.
**May 1 11:15:12.501002 ixre-egl-board27 ERR syncd1#syncd: :- sendApiResponse: api SAI_COMMON_API_REMOVE failed in syncd mode: SAI_STATUS_OBJECT_IN_USE
May 1 11:15:12.501258 ixre-egl-board27 ERR swss1#orchagent: :- remove: remove status: SAI_STATUS_OBJECT_IN_USE
May 1 11:15:12.501258 ixre-egl-board27 ERR swss1#orchagent: :- removeNeighbor: Failed to remove neighbor 36:77:13:45:f1:fa on ixre-egl-board27|asic0|PortChannel102, rv:-17
May 1 11:15:12.501258 ixre-egl-board27 ERR swss1#orchagent: :- handleSaiRemoveStatus: Encountered failure in remove operation, exiting orchagent, SAI API: SAI_API_NEIGHBOR, status: SAI_STATUS_OBJECT_IN_USE**

#### Describe the results you expected:
No orchagent exiting

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by rlhui** [comment]
@sanmalho-git would you please help to see if this one could be taken up by Nokia?  Thanks.

**Comment by sanmalho-git** [comment]
@rlhui  @judyjoseph  - We are not seeing this issue in our pipeline runs for the last 3 months. Can we close this issue for now.

**Comment by abdosi** [comment]
Based on above comment as the issue not seen recently (especially in 202205 branch) we can close this.
