### ISSUE TITLE
[MASIC] [CLI] "show ip route" not parsing correctly for ip with prefix

### ISSUE THREAD

**Issue by wenyiz2021** [sonic-net/sonic-buildimage#10897]
#### Description
Seeing issue on multi-asic platform test_bgpmon.py test, where it calls "show ip route {random ip} json".
When random ip is a non-existing ip, for single asic, an '{}' is returned. However, for multi-asic "show ip route {random ip}" says "Network not in table" and not able to parse it.

Issue seems to be in:
https://github.com/Azure/sonic-utilities/blob/494dd62efb56614ed2409b89fe57ce33a603b7f9/show/bgp_common.py#L379

#### Steps to reproduce the issue:
1.on single asic:  
>>show ip route '11.0.0.1/24' json
{}

2.on multi-asic:
>>show ip route '11.0.0.1/24' json
asic0:
{}

asic1:
{}

asic2:
{}

asic3:
{}

>> $ show ip route '11.0.0.1/24'
% Network not in table
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by abdosi** [comment]
@wenyiz2021 will create further and create PR for this if needed.

**Comment by wenyiz2021** [comment]
issue seen since Jan/2022:
13/01/2022 04:30:57 __init__._fixture_generator_decorator    L0078 ERROR  | 
ValueError('No JSON object could be decoded',)
Traceback (most recent call last):
  File "/azp/agent/_work/1/s/tests/common/plugins/log_section_start/__init__.py", line 74, in _fixture_generator_decorator
    res = next(it)
  File "/azp/agent/_work/1/s/tests/bgp/test_bgpmon.py", line 54, in common_setup_teardown
    peer_addr = generate_ip_through_default_route(duthost)
  File "/azp/agent/_work/1/s/tests/common/helpers/generators.py", line 52, in generate_ip_through_default_route
    if route_through_default_routes(host, ip_addr):
  File "/azp/agent/_work/1/s/tests/common/helpers/generators.py", line 34, in route_through_default_routes
    routes_info = json.loads(output)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")

**Comment by wenyiz2021** [comment]
on multi-asic:
> /usr/lib/python2.7/dist-packages/show/main.py(204)run_command()
-> output = proc.communicate()[0].decode("utf-8")
(Pdb) 
> /usr/lib/python2.7/dist-packages/show/main.py(205)run_command()
-> return output
(Pdb) output
u'% Network not in table\n'
(Pdb) proc
<subprocess.Popen object at 0x7fb9a7881390>
(Pdb)  proc.communicate()
*** ValueError: I/O operation on closed file
(Pdb) proc.communicate()[0]
*** ValueError: I/O operation on closed file

**Comment by wenyiz2021** [comment]
closing as it is not an image issue, more a testcase issue that doesn't support multi-asic

admin@str2-7050cx3-acs-02:~$ show ip route '11.0.0.1/24'
% Network not in table
