### ISSUE TITLE
Add yang model unit test for check_up_status field type

### ISSUE THREAD

**Issue by qiluo-msft** [sonic-net/sonic-buildimage#11110]
Could you add yang model unit test?
We recently fixed a bug https://github.com/Azure/sonic-buildimage/pull/10986

_Originally posted by @qiluo-msft in https://github.com/Azure/sonic-buildimage/pull/10479#discussion_r894871729_

**Comment by qiluo-msft** [comment]
@sg893052 Could you help this issue?

**Comment by sg893052** [comment]
@[yxieca](https://github.com/yxieca) Could you please help assign someone to review fix PR https://github.com/Azure/sonic-buildimage/pull/11243

**Comment by zhangyanzhao** [comment]
#11243 is merged. @qiluo-msft  please close this issue.
