### ISSUE TITLE
[chassis][supervisor] containers bgp,  teamd, macsec, asic lldp and radv should not be run on Supervisor cards 

### ISSUE THREAD

**Issue by mlok-nokia** [sonic-net/sonic-buildimage#11165]
#### Description
There is no front panel ports  on Supervisor card,  containers bgp,  teamd, macsecm,  asic lldp and radv should not be created and started on Supervisor card.

#### Steps to reproduce the issue:
Using 'docker ps  -a' , show all containers.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by abdosi** [comment]
working on this.

**Comment by abdosi** [comment]
PR's should fix this:
https://github.com/sonic-net/sonic-buildimage/pull/11796
https://github.com/sonic-net/sonic-buildimage/pull/11795
https://github.com/sonic-net/sonic-host-services/pull/14

**Comment by abdosi** [comment]
cc @rlhui
