### ISSUE TITLE
Feature request to enable P4RT App at the build time and allow P4RT App to read configs from CONFIG_DB

### ISSUE THREAD

**Issue by ntoorchi** [sonic-net/sonic-buildimage#11211]
This is a feature request to include P4RT App at the build time and allow P4RT App to read configs from CONFIG_DB. There are 3 open PRs that cover this issue and are ready for review:

| PR Title | PR # | Owner | Shepherd |
| --- | --- | --- | --- |
| Enable P4RT at build time and disable at startup | <a href="https://github.com/Azure/sonic-buildimage/pull/10499"><img src="https://img.shields.io/github/pulls/detail/state/Azure/sonic-buildimage/10499?label=10499" height="100%"></a>| @ntoorchi | @bocon13, @bhagatyj <br> @prsunny|
| Allow P4RT App to read configs from CONFIG_DB | <a href="https://github.com/Azure/sonic-buildimage/pull/10725"><img src="https://img.shields.io/github/pulls/detail/state/Azure/sonic-buildimage/10725?label=10725" height="100%"></a> | @rhalstea | @bocon13, @bhagatyj <br> @prsunny|
| Adding P4RT App Configuration to HLD | <a href="https://github.com/sonic-net/SONiC/pull/1054"><img src="https://img.shields.io/github/pulls/detail/state/sonic-net/SONiC/1054?label=1054" height="100%"></a> | @ntoorchi <br> @tonytitus | @bocon13, @bhagatyj <br> @prsunny |

Currently at the Azure build system, the P4RT container is disabled by default at the build time. Here the goal is to include the P4RT container at the build time while disabling it at the runtime. The user can enable/disable the p4rt app through the config based on the preference. The PR #[10499](https://github.com/Azure/sonic-buildimage/pull/10499) addresses this issue.  

Second, the initial commit for the P4RT docker hard coded all the flags which makes it difficult to configure at runtime. Reading them from the CONFIG_DB allows for more flexibility. PR #[10725](https://github.com/Azure/sonic-buildimage/pull/10725) addresses this issue by updating the p4rt.sh startup script to first read from CONFIG_DB then apply any configs it finds. If a config is not set then a default (specified by the executable) is used.

Third, the HLD PR #[1054](https://github.com/sonic-net/SONiC/pull/1054) updates the P4RT App HLD corresponding to the updates in code PR #[10725](https://github.com/Azure/sonic-buildimage/pull/10725).

**Comment by yxieca** [comment]
@prsunny  please help tag this issue to PINS team.

**Comment by prsunny** [comment]
@bocon13, @bhagatyj to analyze/review
