### ISSUE TITLE
[202012 branch] UART issue on booting stage

### ISSUE THREAD

**Issue by dereksun01** [sonic-net/sonic-buildimage#11238]
#### Description
The number b9a3edd8 of commit-ID that UART parameter of Cisco linux kernel configuration  will  cause our platform not to dump any message on booting stage.

Fail parameter:
"CONFIG_SERIAL_8250_RUNTIME_UARTS=32"

Pass parameter:
"CONFIG_SERIAL_8250_RUNTIME_UARTS=4"

#### Steps to reproduce the issue:
1. Download lastly 202012 SONiC image on Accton as5835_54x.
2. Booting platform.

#### Describe the results you received:
- On initial ramdisk stage, console port will not to dump any messages.

#### Describe the results you expected:
- Platform will dump any messages on booting stage.

#### Output of `show version`:

```
SONiC Software Version: SONiC.202012.108060-4f19945b4
Distribution: Debian 10.12
Kernel: 4.19.0-12-2-amd64
Build commit: 4f19945b4
Build date: Thu Jun  9 14:25:37 UTC 2022
Built by: AzDevOps@sonic-build-workers-001LPY

Platform: x86_64-accton_as5835_54x-r0
HwSKU: Accton-AS5835-54X
ASIC: broadcom
ASIC Count: 1
Serial Number: 583554X1218123
```
#### Output of `show techsupport`:

```
```

**Comment by zhangyanzhao** [comment]
Can Accton team help to take a look? Is this Accton platform specific or applicable to other platforms? Please work with Cisco if required.

**Comment by zhangyanzhao** [comment]
@dereksun01 can you please join the issue triage meeting next time if the issue stil there?

**Comment by dereksun01** [comment]
@zhangyanzhao  ,  It's great and what's the meeting time? My location is Taiwan.

**Comment by saiarcot895** [comment]
The kernel config that was causing this issue has been reverted in 3d81b61fa1b4ce219b7f61b3ec561e956268bed3. Closing this issue.
