### ISSUE TITLE
Everflow  mirror session is not active if the mirror destination is in remote asic & monitor_port is not always Ethernet-Rec port

### ISSUE THREAD

**Issue by saksarav-nokia** [sonic-net/sonic-buildimage#11457]
#### Description
1) If the destination IP of the everflow mirror is in the remote asic in the chassis,  orchagent never activates the mirror. When the nexthop is resolved, it calls the function updatenextHop->updateSession->getNeighborInfo.  In getNeighborInfo function, it takes the nexthop  and compares the ip address and alias of nexthop with neighbor entry.  But for remote nexthops, the alias stored in nexthop table is the name of Inb port, but the alias in the neighbor entry is full system port. So the alias check always fails and hence the getNeighborInfo always returns false and the mirror is not activated.

2)In orchagent mirror code function activateSession , the MONITOR_PORT is set to Rec port if the switch_type is voq. But in  the function updateSessionDstPort, the switch_type is not checked and the MONITOR_PORT is set to destport of nexthop.

#### Steps to reproduce the issue:
1. configure the ERSPAN mirror with destip pointing to remote asic.
2. configure the ingress Acl with the ERSPAN mirror as Acl action.
3.Check "show mirror-session" output

#### Describe the results you received:
mirror session is in inactive state

#### Describe the results you expected:
Mirror should be activated and the monitor port configured for ERSPAN mirror is always Rec port.
#### Output of `show version`:
msft-2205 & master
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
Is this issue handled by #2392? @saksarav-nokia

**Comment by saksarav-nokia** [comment]
@zhangyanzhao , yes. I have few more changes and i will update the PR  by end of this week

**Comment by saksarav-nokia** [comment]
Found few more issues with Everflow mirror

 1) show mirror-session doesn't show correct monitor port when the destination port is in remote asic
 2) When the Acl rule with action as mirror is deleted before mirror is activated by the acl_loader script, then mirror is activated by nexthop update, lot of error messages were seen and orchagent crashes.

**Comment by abdosi** [comment]
should be fix by: https://github.com/sonic-net/sonic-swss/pull/2392

**Comment by abdosi** [comment]
There is another PR on everflow: https://github.com/sonic-net/sonic-swss/pull/2024
