### ISSUE TITLE
[chassis]After sonic-db-cli C++ implementation, database.sh fails to start database-chassis on Supervisor card 

### ISSUE THREAD

**Issue by mlok-nokia** [sonic-net/sonic-buildimage#11473]
#### Description
After sonic-db-cli C++ implementation,  database.sh fails to start database-chassis on the supervisor card. Before the new impelementation,  "sonic-db-cli  [database] PING" return "True".  After the implementation, it return "PONG".  This causes the database.sh  wait forever when it tries to PING the "CHASSIS_APP_DB" since the database.sh expects "True" instead of "PONG"

Before new implementation:
```
admin@supervisor:~$ docker exec -i database-chassis sonic-db-cli CHASSIS_APP_DB PING
True
admin@supervisor:~$ sonic-db-cli STATE_DB PING
True
```
After new implementation:
```
admin@ixre-cpm-chassis14:~$ docker exec -i database-chassis sonic-db-cli CHASSIS_APP_DB PING
PONG
admin@ixre-cpm-chassis14:~$ sonic-db-cli STATE_DB PING
PONG
```

#### Steps to reproduce the issue:
1.  Booting up the latest image on Supervisor card.  database-chassis is in the dead state. 

#### Describe the results you received:
"database-chassis" is in the dead state.  This will cause all containers timeout and in the exited state.

#### Describe the results you expected:
Expected the database-chassis is up and running state in the supervisor card.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:
Issue still exists in the latest code. 
```
(paste your output here or download and attach the file here )
```

**Comment by mlok-nokia** [comment]
@prgeor @judyjoseph  This issue exists in the latest code. Please help to assign to the right person.

**Comment by mlok-nokia** [comment]
@liuh-80 Please take a look this issue which is related to the new sonic-db-cli.  Either fix the return value of the sonic-db-cli  for the case of ping a particular database or fix the database.sh to grep "PONG" instead of "True".  Thanks.

**Comment by liuh-80** [comment]
ACK, I will fix this issue ASAP.

**Comment by liuh-80** [comment]
This is a strange behavior in python, because PING with -s will return PONG, I will check if this is a BUG or feature:

admin@vlab-01:~$ /usr/local/bin/sonic-db-cli -s PING
PONG

admin@vlab-01:~$ /usr/local/bin/sonic-db-cli STATE_DB PING
True

admin@vlab-01:~$ /usr/local/bin/sonic-db-cli CONFIG_DB PING
True

**Comment by liuh-80** [comment]
Please ignore https://github.com/Azure/sonic-swss-common/pull/647, that is a mistake.

Issue fixed with https://github.com/Azure/sonic-swss-common/pull/650

**Comment by mlok-nokia** [comment]
Fixed
