### ISSUE TITLE
[FRR] Submodule was not updated to 8.2

### ISSUE THREAD

**Issue by DavidZagury** [sonic-net/sonic-buildimage#11484]
#### Description

Although SONiC has upgraded FRR to 8.2 the FRR submodule in our code base, on both master and 202205 branches, is still pointing to the same hash c69608a which is part of the FRR branch origin/frr/7.5.

It seems that the PR that updated the FRR version ( https://github.com/Azure/sonic-buildimage/pull/10691 )  has updated the .gitmodules file to the new FRR branch and the makefiles to reflect the new FRR version,  but it kept the FRR submodule pointing to the 7.5 branch – as you can see here: [src/sonic-frr](../tree/master/src/sonic-frr)

#### Describe the results you received:
FRR Submodule is pointing to hash Azure/sonic-frr@c69608a which is part of the FRR branch origin/frr/7.5.

#### Describe the results you expected:
FRR Submodule should point to hash Azure/sonic-frr@79188bf which is part of the FRR branch origin/frr/8.2.

**Comment by liat-grozovik** [comment]
@hasan-brcm could you please self signin this issue on you?

**Comment by zhangyanzhao** [comment]
Fix is provided.

**Comment by yxieca** [comment]
@abdosi please review.
