### ISSUE TITLE
Unable to verify checksum when installing a new image from SONiC environment on Edgecore DCS800.

### ISSUE THREAD

**Issue by sahiltyagi4** [sonic-net/sonic-buildimage#11527]
#### Description
Unable to verify checksum when installing a new image with `sonic_installer` on Edgecore DCS800.
The image was built with PLATFORM barefoot.

#### Steps to reproduce the issue:
1. To build sonic: make configure PLATFORM=barefoot
2. Installation method: installing image from SONiC environment: sudo sonic_installer install sonic-barefoot.bin

#### Describe the results you received:
Verifying image checksum ...
ERROR: Unable to verify archive checksum
Expected: 300a2f7a3b4cc86f2ed516787d2abb4ef06a8bbc
Found   : e244e7591cde92ffff7149cf4f363f9dbe0e7de5

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by jhli-cisco** [comment]
This issue seems to be related with https://github.com/Azure/sonic-buildimage/commit/429254cb2d756e1851050c659d48a718fd7e1973. Use image with 429254c reverse patched, the issue is no longer hit.

**Comment by zhangyanzhao** [comment]
Looks like this issue has been root caused. Any other help from community? Otherwise, can you please close? Thanks.

**Comment by Yuval-Mellanox** [comment]
@zhangyanzhao Why was NVIDIA tag added?

**Comment by dgsudharsan** [comment]
@sahiltyagi4 @jhli-cisco There are some additional fixes that went in following the commit you mentioned. https://github.com/sonic-net/sonic-buildimage/pull/11572
Can you please check if this commit solves your issue?

**Comment by sahiltyagi4** [comment]
@vivekrnv 
[sonic-barefoot.bin.log](https://github.com/sonic-net/sonic-buildimage/files/9278159/sonic-barefoot.bin.log)

**Comment by sahiltyagi4** [comment]
@vivekrnv I just tried with the patch in #11572 and it worked! Earlier I was using an image built prior to the addition of this update. We can close this now. Thanks!
