### ISSUE TITLE
dhcp-relay and macsec dockers are not tagged with the image version

### ISSUE THREAD

**Issue by saiarcot895** [sonic-net/sonic-buildimage#11521]
#### Description

The dhcp-relay and macsec docker containers are not tagged with the image version in `docker images`. They have the `latest` tag, but not the image version tag.

#### Steps to reproduce the issue:
1. Load any master branch or 202205 branch image.
2. Run `docker images` to see what images are available

#### Describe the results you received:

```
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-orchagent              latest                    fe3e64b7e543   478MB
docker-orchagent              master.125402-ba991ab2b   fe3e64b7e543   478MB
docker-macsec                 latest                    dc43ce04e308   462MB
docker-gbsyncd-vs             latest                    6ba40ca23dee   452MB
docker-gbsyncd-vs             master.125402-ba991ab2b   6ba40ca23dee   452MB
docker-dhcp-relay             latest                    56eb71be4440   453MB
docker-sonic-telemetry        latest                    4e801dfe7b2c   524MB
docker-sonic-telemetry        master.125402-ba991ab2b   4e801dfe7b2c   524MB
docker-router-advertiser      latest                    2d779505bd70   444MB
docker-router-advertiser      master.125402-ba991ab2b   2d779505bd70   444MB
docker-platform-monitor       latest                    0389dc544406   566MB
docker-platform-monitor       master.125402-ba991ab2b   0389dc544406   566MB
docker-mux                    latest                    880232ae811e   492MB
docker-mux                    master.125402-ba991ab2b   880232ae811e   492MB
docker-database               latest                    d20792b5f223   444MB
docker-database               master.125402-ba991ab2b   d20792b5f223   444MB
docker-fpm-frr                latest                    f2120bde67bc   458MB
docker-fpm-frr                master.125402-ba991ab2b   f2120bde67bc   458MB
docker-nat                    latest                    6154fa670a3a   431MB
docker-nat                    master.125402-ba991ab2b   6154fa670a3a   431MB
docker-teamd                  latest                    09b5a3bdf40f   429MB
docker-teamd                  master.125402-ba991ab2b   09b5a3bdf40f   429MB
docker-sflow                  latest                    e7343335c5bd   429MB
docker-sflow                  master.125402-ba991ab2b   e7343335c5bd   429MB
docker-syncd-vs               latest                    361573578999   426MB
docker-syncd-vs               master.125402-ba991ab2b   361573578999   426MB
docker-snmp                   latest                    bed1cdc88f51   457MB
docker-snmp                   master.125402-ba991ab2b   bed1cdc88f51   457MB
docker-sonic-mgmt-framework   latest                    7843f3440cec   558MB
docker-sonic-mgmt-framework   master.125402-ba991ab2b   7843f3440cec   558MB
docker-lldp                   latest                    58ce11598f95   454MB
docker-lldp                   master.125402-ba991ab2b   58ce11598f95   454MB
```

`docker-dhcp-relay:latest` is tagged, but not `docker-dhcp-relay:master.125402-ba991ab2b`. `docker-macsec` isn't present in this build, but is also affected.

#### Describe the results you expected:

`docker-dhcp-relay:master.125402-ba991ab2b` should be present.

#### Output of `show version`:

This was taken from the log of the most recent VS image build.

**Comment by stepanblyschak** [comment]
@saiarcot895 Could you please describe the use case where you need to see the docker image tagged also with the image version?

It is by design that the app. ext images have a single tag present in the system, so that it is easy to manage the image. You can find the Tag in the docker image labels.

**Comment by saiarcot895** [comment]
It's more of a visual expectation. All of the other dockers that are packaged with this image are tagged with the image version. Older images (such as those from the 202012 branch) have docker-dhcp-relay tagged with the image version.

**Comment by yxieca** [comment]
@renukamanavalan Can you assess this design change from K8 perspective?

**Comment by renukamanavalan** [comment]
> @renukamanavalan Can you assess this design change from K8 perspective?

Looks good to me.

**Comment by zhangyanzhao** [comment]
Is this issue fix?

**Comment by qiluo-msft** [comment]
> Could you please describe the use case where you need to see the docker image tagged also with the image version?
> 
> It is by design that the app. ext images have a single tag present in the system, so that it is easy to manage the image. You can find the Tag in the docker image labels.

@stepanblyschak We should support multiple tags. I could give a use case. If some docker controller ask SONiC device to pull a latest `docker-macsec:latest` image, the previous image will lose the tag and it is not convenient to refer the previous one. If would be quite meaningful, if we add a label like `master.125402-ba991ab2b` because it comes with this image version.

**Comment by stepanblyschak** [comment]
@qiluo-msft Just to understand is this your use case? Have you tested it?:
1. Load SONiC image in local docker mode
2. Deploy *latest* with kubernetes
3. Switch back to local and observe there's no original docker SONiC was built with?

**Comment by stepanblyschak** [comment]
Discussed online. Will keep SONiC version string instead of *latest*, but will not keep the *latest*, scripts generated by *spm* are using image id to identify image. Medium priority issue.
