### ISSUE TITLE
[master] Errors in docker database supervisord init - flush_unused_database failed

### ISSUE THREAD

**Issue by vaibhavhd** [sonic-net/sonic-buildimage#11597]
#### Description

Database container init has errors in latest master image. Likely due to this error other database dependent services also fail to start.

I think the issue is because of this change: https://github.com/Azure/sonic-buildimage/pull/11215

The change replaced swsssdk.SonicDBConfig with swsscommon.SonicDBConfig, but the function get_instancelist is not in swsscommon. Should that change to getInstanceList?

#### Steps to reproduce the issue:
1. Install latest master image (tested so far on 2700 t0)
2. Cold reboot to it.
3. Check syslog for errors (attached here is an example).

#### Describe the results you received:

Errors seen in `flush_unused_database` script start. This is  part of database container's supervisord conf:

https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-database/supervisord.conf.j2#L39

I think this prevent other database-dependent services from starting, as swss, syncd, bgp did not start after this error in database init.

```
Aug  1 18:37:15.087226 sonic INFO database#supervisord: flushdb Traceback (most recent call last):
Aug  1 18:37:15.087468 sonic INFO database#supervisord: flushdb   File "/usr/local/bin/flush_unused_database", line 14, in <module>
Aug  1 18:37:15.087598 sonic INFO database#supervisord: flushdb     instlists = swsscommon.SonicDBConfig.get_instancelist()
Aug  1 18:37:15.087703 sonic INFO database#supervisord: flushdb AttributeError: type object 'SonicDBConfig' has no attribute 'get_instancelist'
Aug  1 18:37:15.105005 sonic INFO database#supervisord 2022-08-01 18:37:15,104 INFO exited: flushdb (exit status 1; not expected)
Aug  1 18:37:22.607330 str2-msn2700-spy-1 NOTICE systemd[1]: switch state service is not active.
```
#### Describe the results you expected:

Database container init should not throw errors.
Critical services and containers should start.

#### Output of `show version`:

```

SONiC Software Version: SONiC.master.129002-cdd278611
Distribution: Debian 11.4
Kernel: 5.10.0-12-2-amd64
Build commit: cdd278611
Build date: Sun Jul 31 18:51:20 UTC 2022
Built by: AzDevOps@sonic-build-workers-001V01

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: A1
Uptime: 20:31:14 up  1:59,  1 user,  load average: 0.18, 0.17, 0.15
Date: Mon 01 Aug 2022 20:31:14
```

#### Output of `show techsupport`:

```
[syslog.log](https://github.com/Azure/sonic-buildimage/files/9237381/syslog.log)

```

**Comment by liuh-80** [comment]
ACK, will create a fix for this issue soon

**Comment by liuh-80** [comment]
Draft PR created, will request review after all validation passed: https://github.com/Azure/sonic-buildimage/pull/11600

**Comment by liuh-80** [comment]
PR ready for review: https://github.com/sonic-net/sonic-buildimage/pull/11600
Manually verifyed with following command:

admin@vlab-01:~$ sudo docker exec -it database bash
root@vlab-01:/# docker-database-init.sh
/usr/local/lib/python3.9/dist-packages/supervisor/options.py:473: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  self.warnings.warn(
2022-08-02 09:11:55,805 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2022-08-02 09:11:55,806 INFO Set uid to user 0 succeeded
Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.
For help, use /usr/local/bin/supervisord -h
root@vlab-01:/# /usr/local/bin/flush_unused_database
root@vlab-01:/#

**Comment by liuh-80** [comment]
PR merged to master branch.

**Comment by zhangyanzhao** [comment]
@vaibhavhd please close this issue if the fix is verified. Thanks.
