### ISSUE TITLE
[mux] Duplicate binding of port to MUX_ACL_TABLE

### ISSUE THREAD

**Issue by bingwang-ms** [sonic-net/sonic-buildimage#11654]
#### Description

We are seeing below errors on dualtor platform when `MuxCable` was being toggled to `Standby`
```
Aug  8 08:58:29.565883 str2-7050cx3-acs-08 NOTICE swss#orchagent: :- addOperation: Mux State set to standby for port Ethernet80
Aug  8 08:58:29.565883 str2-7050cx3-acs-08 NOTICE swss#orchagent: :- setState: [Ethernet84] Set MUX state from init to standby
Aug  8 08:58:29.565883 str2-7050cx3-acs-08 NOTICE swss#orchagent: :- MuxAclHandler: Binding port 1000000000026
Aug  8 08:58:29.565883 str2-7050cx3-acs-08 ERR swss#orchagent: :- meta_generic_validation_objlist: SAI_ACL_ENTRY_ATTR_FIELD_IN_PORTS:SAI_ATTR_VALUE_TYPE_ACL_FIELD_DATA_OBJECT_LIST object on list [24] oid 0x1000000000026 is duplicated, but not allowed
Aug  8 08:58:29.565883 str2-7050cx3-acs-08 ERR swss#orchagent: :- updateInPorts: Failed to update ACL rule mux_acl_rule, rv:-5
```
The error is because the initial state of `MuxCable` is set to `Standby` in construction function.

https://github.com/sonic-net/sonic-swss/blob/d36c17d62c17b7ae2617868989891bc7bb8c72f8/orchagent/muxorch.cpp#L368

```
MuxCable::MuxCable(string name, IpPrefix& srv_ip4, IpPrefix& srv_ip6, IpAddress peer_ip, std::set<IpAddress> skip_neighbors)
         :mux_name_(name), srv_ip4_(srv_ip4), srv_ip6_(srv_ip6), peer_ip4_(peer_ip), skip_neighbors_(skip_neighbors)
{
    ......

    /* Set initial state to "standby" */
    stateStandby();
}
```
However, the cached state `state_` in `MuxCable` is still `MUX_STATE_INIT`.
It will result in two possible errors
1. From `INIT` to `STANDBY`
The handler `MuxCable::stateStandby` is called. And the port is added to ACL matching field `IN_PORTS` again. Hence we will see the error logs.
3. From 'INIT' to 'ACTIVE`
The handler `MuxCable::stateInitActive` is called. However, the port is not removed from ACL matching field `IN_PORTS`. Packets from server to tor will be dropped unexpectedly.

#### Steps to reproduce the issue:
1. Deploy a dualtor testbed.
2. Check syslog, we will see the error logs

#### Output of `show version`:

```
SONiC Software Version: SONiC.20201231.73
Distribution: Debian 10.12
Kernel: 4.19.0-12-2-amd64
Build commit: 58e0bd5ffe
Build date: Sun Jul 31 22:11:18 UTC 2022
Built by: cloudtest@7a161cc2c000001
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prsunny** [comment]
Fix PR merged
