### ISSUE TITLE
Support preemphasis on Edgecore AS7726-32X

### ISSUE THREAD

**Issue by abhiranjeet** [sonic-net/sonic-buildimage#11678]
#### Description
I am building SONiC 202205 image. I see that media_settings.json file is missing for AS7726-32X platform, but this has been supported for other platforms as mentioned in this PR - https://github.com/sonic-net/sonic-buildimage/pull/10586.

#### Describe the results you expected:
Is the media_settings.json available for AS7726-32X ?

**Comment by yxieca** [comment]
@prgeor  can you give some instructions to @abhiranjeet regarding how to create the media_settings.json? do we have public document?

**Comment by prgeor** [comment]
@abhiranjeet please refer to this document [https://github.com/sonic-net/SONiC/blob/master/doc/media-settings/Media-based-Port-settings.md](https://github.com/sonic-net/SONiC/blob/master/doc/media-settings/Media-based-Port-settings.md)
