### ISSUE TITLE
docker-sonic-vs.gz on master branch is on buster

### ISSUE THREAD

**Issue by Ndancejic** [sonic-net/sonic-buildimage#11706]
#### Description

docker-sonic-vs.gz is buster on the master branch build

#### Steps to reproduce the issue:

Build sonic-buildimage from master branch

#### Describe the results you received:

cannot test swss changes with pytest because swss master is on bullseye and docker-sonic-vs.gz provides a buster image.

#### Describe the results you expected:

docker-sonic-vs.gz should be on bullseye\

**Comment by yxieca** [comment]
@saiarcot895 can you assess the change with @Ndancejic , my concerns are:

- Do we have test depends on buster vs image that will fail after the move?
- The effort of moving to bullseye. Do we need help from the community?

**Comment by saiarcot895** [comment]
sairedis, swss, and swss-common all use the docker-sonic-vs image in pipelines and/or README instructions. The upgrade to Bullseye may need pipeline updates in these submodules as well to build Bullseye artifacts.

As for moving the container itself to Bullseye, it doesn't look to be difficult, just need to remove Python 2 packages.
