### ISSUE TITLE
sonic-net/sonic-buildimage: Build fails with only BULLSEYE enabled

### ISSUE THREAD

**Issue by ashwin-h** [sonic-net/sonic-buildimage#11769]
#### Steps to reproduce the issue:
git clone https://github.com/sonic-net/sonic-buildimage
make init
make configure PLATFORM=broadcom
NOJESSIE=1 NOSTRETCH=1 NOBUSTER=1 NOBULLSEYE=0 make target/sonic-broadcom.bin

#### Describe the results you received:
Build error log below
Make: *** No rule to make target 'target/docker-fpm-frr.gz', needed by 'target/sonic-broadcom.bin'.  Stop.

#### Describe the results you expected:
Build should work fine

**Comment by bgmastermind** [comment]
same here

**Comment by anamehra** [comment]
> 
This looks different from the original issue reported.
This is because rules/snmpd.mk uses hardcoded version 5.9+dfsg-3+b1 but a new version is available to download 5.9+dfsg-4+deb11u1, looks like released two days ago

**Comment by anamehra** [comment]
> same here but since yesterday it fails at a new step sooner than docker-fpm-frr.gz with endless loop
> 
> ```
> [ FAIL LOG START ] [ target/debs/bullseye/libsnmp-dev_5.9+dfsg-3+b1_amd64.deb-install ]
> dpkg: warning: downgrading libsnmp-dev from 5.9+dfsg-4+deb11u1 to 5.9+dfsg-3+b1
> (Reading database ... 214260 files and directories currently installed.)
> Preparing to unpack .../libsnmp-dev_5.9+dfsg-3+b1_amd64.deb ...
> Unpacking libsnmp-dev (5.9+dfsg-3+b1) over (5.9+dfsg-4+deb11u1) ...
> dpkg: dependency problems prevent configuration of libsnmp-dev:
>  libsnmp-dev depends on libnetsnmptrapd40 (= 5.9+dfsg-3+b1); however:
>   Version of libnetsnmptrapd40:amd64 on system is 5.9+dfsg-4+deb11u1.
> 
> dpkg: error processing package libsnmp-dev (--install):
>  dependency problems - leaving unconfigured
> Processing triggers for man-db (2.9.4-2) ...
> Errors were encountered while processing:
>  libsnmp-dev
> [  FAIL LOG END  ] [ target/debs/bullseye/libsnmp-dev_5.9+dfsg-3+b1_amd64.deb-install ]
> [ FAIL LOG START ] [ target/debs/bullseye/libsnmp-dev_5.9+dfsg-3+b1_amd64.deb-install ]
> dpkg: warning: downgrading libsnmp-dev from 5.9+dfsg-4+deb11u1 to 5.9+dfsg-3+b1
> (Reading database ... 214260 files and directories currently installed.)
> Preparing to unpack .../libsnmp-dev_5.9+dfsg-3+b1_amd64.deb ...
> Unpacking libsnmp-dev (5.9+dfsg-3+b1) over (5.9+dfsg-4+deb11u1) ...
> dpkg: dependency problems prevent configuration of libsnmp-dev:
>  libsnmp-dev depends on libnetsnmptrapd40 (= 5.9+dfsg-3+b1); however:
>   Version of libnetsnmptrapd40:amd64 on system is 5.9+dfsg-4+deb11u1.
> ```

This looks different from the original issue reported.
This is because rules/snmpd.mk uses hardcoded version 5.9+dfsg-3+b1 but a new version is available to download 5.9+dfsg-4+deb11u1, looks like released two days ago

**Comment by anamehra** [comment]
@abdosi FYI-

**Comment by adyeung** [comment]
#11777

**Comment by saiarcot895** [comment]
```
NOJESSIE=1 NOSTRETCH=1 NOBUSTER=1 NOBULLSEYE=0 make target/sonic-broadcom.bin
```

This is not a supported build command. As of today, both Buster and Bullseye are needed to build a SONiC image.

Is there a reason you are explicitly setting the `NO*` variables?

**Comment by ashwin-h** [comment]
@saiarcot895 To reduce the buildtime/space i thought we can build only one version of the debian distribution and build the image. Do we reuse the pkgs across debian distributions during build ? We should be able to build one version of the debian and create the image.

**Comment by bgmastermind** [comment]
Well the first time I tried it was the default makefile strech, buster, bulsseye. Which failed.
Then I thought exactly the same as ashwin, to save time I tried only bullseye which again failed. 
Then decided that I can try the others, but always isolated. Just buster, just stretch. Build again failed.
Please update the build readme with that very important information.

**Comment by saiarcot895** [comment]
> @saiarcot895 To reduce the buildtime/space i thought we can build only one version of the debian distribution and build the image. Do we reuse the pkgs across debian distributions during build ? We should be able to build one version of the debian and create the image.

Some containers are currently defined to be on Buster, whereas others are defined to be on Bullseye. For certain platforms, those platforms may have containers that are based on Stretch, and so Stretch will be required as well.

Additionally, it is not that a version of Debian is being built; SONiC builds SONiC-specific/modified packages for a particular Debian distribution, which then get used in one of the Docker containers. Packages built for one version of Debian are not reused across Debian distributions, since those packages may need to be recompiled for newer libraries/dependencies.

> Well the first time I tried it was the default makefile strech, buster, bulsseye. Which failed. Then I thought exactly the same as ashwin, to save time I tried only bullseye which again failed. Then decided that I can try the others, but always isolated. Just buster, just stretch. Build again failed. Please update the build readme with that very important information.

The expectation is that just running `make target/sonic-broadcom.bin` (or the appropriate target for the platform that you're building) should work. If that doesn't work, then that's an error that needs to be fixed.

**Comment by bgmastermind** [comment]
Thank you I get it now. Also with latest fixes it builds successfully.

**Comment by ashwin-h** [comment]
> The expectation is that just running `make target/sonic-broadcom.bin` (or the appropriate target for the platform that you're building) should work. If that doesn't work, then that's an error that needs to be fixed.

Thanks @saiarcot895 for the clarification. I observed that for `make target/sonic-broadcom.bin` works fine with buster and bullseye. In that case we don't need strech/jessie. But what i see is make calls for stretch(by default) as well. Is this configurable per platform so that we can avoid building unnecessary version required for the target ?

**Comment by saiarcot895** [comment]
No, it's not configurable per platform. However, in terms of additional space/time used, it should only be the Stretch slave container that gets uilt

**Comment by ashwin-h** [comment]
Thanks @saiarcot895 .. ```target/sonic-broadcom.bin``` works with buster and bullseye enabled..
