### ISSUE TITLE
[static route] 'STATIC_ROUTE|1.1.1.0/24' and 'STATIC_ROUTE|default|1.1.1.0/24' should not exist at the same time in CONFIG DB

### ISSUE THREAD

**Issue by Junchao-Mellanox** [sonic-net/sonic-buildimage#11803]
#### Description

`config route add prefix vrf default 1.1.1.0/24 ...` adds entry `STATIC_ROUTE|default|1.1.1.0/24` to CONFIG DB; `config route add prefix 1.1.1.0/24 ...` adds entry `STATIC_ROUTE|1.1.1.0/24` to CONFIG DB.

For bgpcfgd,  `STATIC_ROUTE|default|1.1.1.0/24` and `STATIC_ROUTE|1.1.1.0/24` are the same route entry. See https://github.com/sonic-net/sonic-buildimage/blob/2d4ab9e9792c41dd403f4345454bd83db3dfdf36/src/sonic-bgpcfgd/bgpcfgd/managers_static_rt.py#L94:

```python
    @staticmethod
    def split_key(key):
        """
        Split key into vrf name and prefix.
        :param key: key to split
        :return: vrf name extracted from the key, ip prefix extracted from the key
        """
        if '|' not in key:
            return 'default', key
        else:
            return tuple(key.split('|', 1))
```

It causes a few problems:
1. We could have two entries in CONFIG DB which point to the same static route. The two entries may have different next hop which could confuse user
2. `config route del prefix vrf default 1.1.1.0/24`  cannot remove entry `STATIC_ROUTE|1.1.1.0/24`; `config route del prefix 1.1.1.0/24` cannot remove entry `STATIC_ROUTE|default|1.1.1.0/24`

#### Steps to reproduce the issue:
1. config route add prefix vrf default 1.1.1.0/24 ...
2. config route add prefix 1.1.1.0/24 ...

#### Describe the results you received:

See two route entries in CONFIG DB which point to the same static route

#### Describe the results you expected:

Only one route entry should exist in CONFIG DB for the same route

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

Workaround:

1. Don't use `config route add prefix vrf default <ip_prefix>` and `config route add prefix vrf <ip_prefix>`  for the same ip_prefix together
2. Use `config route del prefix vrf default <ip_prefix>` to remove static routes created by `config route add prefix vrf default <ip_prefix>`
3. Use `config route del prefix vrf <ip_prefix>` to remove static routes created by `config route add prefix vrf <ip_prefix>`

**Comment by prsunny** [comment]
I think the 2nd command should also append 'default' as key to the STATIC_ROUTE table. What do you think?

**Comment by Junchao-Mellanox** [comment]
That's true. But we should not allow user configuring same route entry to different redis DB entry.
```
STATIC_ROUTE|default|1.1.1.0/24
STATIC_ROUTE|1.1.1.0/24
```

**Comment by prsunny** [comment]
ETA 9/16
