### ISSUE TITLE
[LAG] Inconsistency in LAG members configuration in config DB

### ISSUE THREAD

**Issue by liorghub** [sonic-net/sonic-buildimage#11873]
#### Description
When adding ports to lag using minigraph, 2 tables contain the lag membership information, PORTCHANNEL and PORTCHANNEL_MEMBER.
But when we adding ports to LAG using CLI, only 1 table contains the lag membership information, PORTCHANNEL_MEMBER.

When I deployed t0 topology (that contains lag) using minigraph, "members@" field is being created in PORTCHANNEL table.
[Link](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliorghub%2Fsonic-buildimage%2Fblob%2Fmaster%2Fsrc%2Fsonic-config-engine%2Fminigraph.py%23L515&data=05%7C01%7Cliora%40nvidia.com%7Cfb2ff84cb555419f024308da89867917%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637973507907184086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VRkkCQMf2KOLbD2tsg%2BKqvtRB64ylhFmJLtpWvIXSUc%3D&reserved=0) to code snippet that adds the “members@” field to PORTCHANNEL table.
```
root@sonic:/home/admin# redis-cli  -n 4 hgetall "PORTCHANNEL|PortChannel102"
1) "admin_status"
2) "up"
3) "members@"
4) "Ethernet58"
5) "min_links"
6) "1"
7) "mtu"
8) "9100"
9) "tpid"
10) "0x8100"

root@sonic:/home/admin# redis-cli  -n 4 hgetall "PORTCHANNEL_MEMBER|PortChannel102|Ethernet58"
1) "NULL"
2) "NULL"

```

When I created lag using the following CLI commands:
#config portchannel add PortChannel200
#config portchannel member add PortChannel200 Ethernet0
Field "members@" field is not created in PORTCHANNEL table.

```
root@sonic:/home/admin# redis-cli  -n 4 hgetall "PORTCHANNEL|PortChannel200"
1) "admin_status"
2) "up"
3) "lacp_key"
4) "auto"
5) "min_links"
6) "1"
7) "mtu"
8) "9100"

root@sonic:/home/admin# redis-cli  -n 4 hgetall "PORTCHANNEL_MEMBER|PortChannel200|Ethernet0"
1) "NULL"
2) "NULL"
```

#### Steps to reproduce the issue:
Install to topology using minigraph:
```
connect to docker-ngts
cd ~/mars/workspace/sonic-mgmt/ansible
./testbed-cli.sh -k ceos add-topo  r-tigris-13-t0 vault -e ptf_imagetag=latest 
./testbed-cli.sh gen-mg r-tigris-13-t0 lab vault 
ansible-playbook -i inventory --limit r-tigris-13 deploy_minigraph.yml -e dut_minigraph=r-tigris-13.t0.xml -b -vvv 
```
Configure LAG using CLI:
```
config portchannel member add PortChannel200 Ethernet0
config portchannel add PortChannel200
```

#### Describe the results you received:
The expectation is to have LAG members configuration saved in a single table. 

#### Output of `show version`:
root@sonic:/home/admin# show version

SONiC Software Version: SONiC.202205.139499-a5171349a
Distribution: Debian 11.4
Kernel: 5.10.0-12-2-amd64
Build commit: a5171349a
Build date: Thu Aug 25 15:52:49 UTC 2022
Built by: AzDevOps@sonic-build-workers-001ZUF

Platform: x86_64-mlnx_msn3800-r0
HwSKU: Mellanox-SN3800-D112C8
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1937X00527
Model Number: MSN3800-CS2FO
Hardware Revision: A2
Uptime: 11:26:29 up 15 min,  1 user,  load average: 1.97, 1.90, 1.26
Date: Mon 29 Aug 2022 11:26:29

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-syncd-mlnx             202205.139499-a5171349a   1e2f53986bf4   844MB
docker-syncd-mlnx             latest                    1e2f53986bf4   844MB
docker-platform-monitor       202205.139499-a5171349a   75c1a9b5c131   847MB
docker-platform-monitor       latest                    75c1a9b5c131   847MB
docker-orchagent              202205.139499-a5171349a   0ecb28e57007   473MB
docker-orchagent              latest                    0ecb28e57007   473MB
docker-teamd                  202205.139499-a5171349a   5037c24fdbdb   454MB
docker-teamd                  latest                    5037c24fdbdb   454MB
docker-macsec                 latest                    42a2666268e9   456MB
docker-dhcp-relay             latest                    aec46c245364   448MB
docker-sonic-telemetry        202205.139499-a5171349a   070635cc1b7c   519MB
docker-sonic-telemetry        latest                    070635cc1b7c   519MB
docker-router-advertiser      202205.139499-a5171349a   c27126ea47e9   438MB
docker-router-advertiser      latest                    c27126ea47e9   438MB
docker-mux                    202205.139499-a5171349a   0c055af258f9   487MB
docker-mux                    latest                    0c055af258f9   487MB
docker-lldp                   202205.139499-a5171349a   9056fe6e98da   481MB
docker-lldp                   latest                    9056fe6e98da   481MB
docker-database               202205.139499-a5171349a   97070b04accb   438MB
docker-database               latest                    97070b04accb   438MB
docker-sflow                  202205.139499-a5171349a   b4ed262d4259   428MB
docker-sflow                  latest                    b4ed262d4259   428MB
docker-fpm-frr                202205.139499-a5171349a   ba3d0ca10044   456MB
docker-fpm-frr                latest                    ba3d0ca10044   456MB
docker-nat                    202205.139499-a5171349a   fad671ccf959   429MB
docker-nat                    latest                    fad671ccf959   429MB
docker-snmp                   202205.139499-a5171349a   f5935674501f   455MB
docker-snmp                   latest                    f5935674501f   455MB
docker-sonic-mgmt-framework   202205.139499-a5171349a   7a28e06406c4   556MB
docker-sonic-mgmt-framework   latest                    7a28e06406c4   556MB

root@sonic:/home/admin# 

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by liorghub** [comment]
[sonic_dump_r-tigris-13_20220829_111839.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/9444089/sonic_dump_r-tigris-13_20220829_111839.tar.gz)
[r-tigris-13-t0-xml.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/9444097/r-tigris-13-t0-xml.tar.gz)

**Comment by zhangyanzhao** [comment]
legacy issue, minigraph LAG member should be deprecated if no component uses it.
