### ISSUE TITLE
[VOQ] syncd and swss didn't come up on sup

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#11892]
#### Description

When testing recent master and also 202205 image, we found that syncd and swss didn't come up on sup.

Our debug indicates syncd and also swss were stuck in asic_status.py https://github.com/sonic-net/sonic-buildimage/blob/master/files/scripts/asic_status.py.  Take asic3 as an example:

$ systemctl status syncd@3
● syncd@3.service - syncd service
     Loaded: loaded (/lib/systemd/system/syncd@.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/syncd@3.service.d
             └─auto_restart.conf
     Active: active (running) since Tue 2022-08-30 04:43:23 UTC; 13min ago
   Main PID: 11848 (syncd.sh)
      Tasks: 2 (limit: 77116)
     Memory: 12.0M
     CGroup: /system.slice/system-syncd.slice/syncd@3.service
             ├─11848 /bin/bash /usr/local/bin/syncd.sh wait 3
             └─11859 python3 /usr/local/bin/asic_status.py syncd 3

We confirmed that asic was already published in chassis_db:

$ sonic-db-cli CHASSIS_STATE_DB hgetall "CHASSIS_ASIC_TABLE|asic3"
{'asic_pci_address': '0000:1a:00.0', 'name': 'FABRIC-CARD1', 'asic_id_in_module': '1'}

syncd3 came up fine after restarting the service (sudo systemctl restart syncd@3)

#### Steps to reproduce the issue:
1. Install master or 202205 image
2. Check if syncd and swss are coming up with 'docker ps'.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ysmanman** [comment]
Add @arlakshm for viz.

**Comment by ysmanman** [comment]
Hi @arlakshm,  should https://github.com/sonic-net/sonic-buildimage/pull/12540 fix this issue too?

**Comment by rlhui** [comment]
@ysmanman  - could you please confirm if issue is now fixed or still there, as #12540 is merged and in 202205.

**Comment by rlhui** [comment]
@ysmanman  - could you please confirm if issue is now fixed or still there, as #12540 is merged and in 202205.

**Comment by anamehra** [comment]
I hit this issue again with 202205 5c7c789

**Comment by ysmanman** [comment]
> I hit this issue again with 202205 [5c7c789](https://github.com/sonic-net/sonic-buildimage/commit/5c7c789b4ac750ac4f32d041201eefe28148321f)

Hi @anamehra https://github.com/sonic-net/sonic-buildimage/pull/12780 and https://github.com/sonic-net/sonic-platform-daemons/pull/311 may fix the issue. Can you try latest 202205 image?

**Comment by anamehra** [comment]
> > I hit this issue again with 202205 [5c7c789](https://github.com/sonic-net/sonic-buildimage/commit/5c7c789b4ac750ac4f32d041201eefe28148321f)
> 
> Hi @anamehra #12780 and [sonic-net/sonic-platform-daemons#311](https://github.com/sonic-net/sonic-platform-daemons/pull/311) may fix the issue. Can you try latest 202205 image?

Thanks!
Looks like the two commits were out of sync. We got the changes for asic_status.py but this came in later.

We also need fix in multi_asic.py script to use FABRIC ASIC table to return get_asic_presence_list()  for sup

@abdosi

**Comment by arlakshm** [comment]
@anamehra this change is done in # 12780
https://github.com/sonic-net/sonic-buildimage/pull/12780/files#diff-d124f90ae4ff343a55a35d310ec376445f5c9d81300bf3a091bbb7bbae995d01

**Comment by anamehra** [comment]
> @anamehra this change is done in # 12780 https://github.com/sonic-net/sonic-buildimage/pull/12780/files#diff-d124f90ae4ff343a55a35d310ec376445f5c9d81300bf3a091bbb7bbae995d01

Thanks! I found that. I looked at the files in master earlier, where it's not present.

**Comment by arlakshm** [comment]
Fixed with PRs https://github.com/sonic-net/sonic-buildimage/pull/12780 and https://github.com/sonic-net/sonic-platform-daemons/pull/311
