### ISSUE TITLE
[sonic-platform-daemons] - chassis daemon does not exit on SIGTERM signal

### ISSUE THREAD

**Issue by amulyan7** [sonic-net/sonic-buildimage#11955]
#### Description
chassis daemon on PMON is not terminating on SIGTERM signal

I see that it receives the signal in signal handler, but does not exit because the child process (ConfigManagerTask) is still running. There was a recent commit that went in removing the stop of config manager on daemon stop. 
[https://github.com/Azure/sonic-platform-daemons/commit/9ac12bfb406416b0fb3b03a084d8179bdc53f3a6](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsonic-platform-daemons%2Fcommit%2F9ac12bfb406416b0fb3b03a084d8179bdc53f3a6&data=05%7C01%7CJudy.Joseph%40microsoft.com%7C0866b3b871a14325260908da8c5c458a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637976625187328657%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5t1ujGjaFmxpYIbLVCEZSo8hGRcGeWEcRhzsa2BAq8I%3D&reserved=0)

#### Steps to reproduce the issue:
1. Enter pmon docker (docker exec -it pmon bash)
2. send SIGTERM to chassisd (kill -15 (chassisd_pid))
3. Notice that chassisd does not exit 

#### Describe the results you received:
chassisd does not exit and remains in running state with same PID

#### Describe the results you expected:
chassisd should exit and start again with a new PID

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by amulyan7** [comment]
@judyjoseph

**Comment by prgeor** [comment]
@judyjoseph please see if this fix is to be ported to 202211 and 202205

**Comment by judyjoseph** [comment]
Fixed via https://github.com/sonic-net/sonic-platform-daemons/pull/328
