### ISSUE TITLE
SNMP is consistent failed after disable the queue flex counter

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-buildimage#11977]
#### Description

When queue flex counter is disabled in config, it results in not
Populating/removal of Counter_QUEUENAME_MAP table in Counter_DB.  As a part of SNMP query, when snmp_subagent process
Triggers MIBupdate, the internal MIB code tries to connect to Redis DB and retrieve the nonexistent COUNTER_QUEUENAME_MAP 
table. This results in Runtime Error and abort without updating any other MIB entities as shown in the following traceback.  The 
problem is happening because  SNMP subagent is not aware of  Queue counter enablement/disablement in the config.  

#### Steps to reproduce the issue:
1. Disable the queue flex counter in flex counter table
2. Run snmpwalk to some oid, such as snmpwalk  -v2c -c public 127.0.0.1 1.3.6.1.2.1.2.2.1.1, it will report error.
iso.3.6.1.2.1.2.2.1.1 = No Such Object available on this agent at this OID

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by qiluo-msft** [comment]
@kevinskwang Could you explain "When queue flex counter is disabled in config, it results in not Populating/removal of Counter_QUEUE_NAME_MAP table in Counter_DB."? I am okay you want to disable some counters, but why remove the map?

**Comment by dorDiogo** [comment]
@qiluo-msft can you add me as assignee? I don't see the button so I probably don't have permission.

**Comment by kevinskwang** [comment]
I think we can close this issue as we have confirmed this is a configuration issue.

**Comment by dorDiogo** [comment]
@kevinskwang, can you close the issue? I don't have permission
