### ISSUE TITLE
Error message during config reload due to by missing `eventd.timer`

### ISSUE THREAD

**Issue by stephenxs** [sonic-net/sonic-buildimage#12008]
#### Steps to reproduce the issue:
1. `config reload` or `systemctl enable eventd.timer` (which is invoked from `config reload`)
2.
3.

#### Describe the results you received:
Error message is observed from the syslog or the output of the command `systemctl enable eventd.timer`
```
admin@sonic:~$ sudo systemctl enable eventd.timer
Failed to enable unit: Unit file eventd.timer does not exist.
```

#### Output of `show version`:

```
admin@r-leopard-01:/usr/lib/systemd/system$ show version

SONiC Software Version: SONiC.master.400-1b5d07f66_Internal
Distribution: Debian 11.4
Kernel: 5.10.0-12-2-amd64
Build commit: 1b5d07f66
Build date: Mon Sep  5 23:35:33 UTC 2022
Built by: sw-r2d2-bot@r-build-sonic02-006

Platform: x86_64-mlnx_msn4700-r0
HwSKU: ACS-MSN4700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2022X08595
Model Number: MSN4700-WS2FO
Hardware Revision: A1
Uptime: 04:06:33 up 36 min,  2 users,  load average: 0.64, 0.72, 0.75
Date: Thu 08 Sep 2022 04:06:33

Docker images:
REPOSITORY                    TAG                             IMAGE ID       SIZE
docker-fpm-frr                latest                          439d47372323   489MB
docker-fpm-frr                master.400-1b5d07f66_Internal   439d47372323   489MB
docker-orchagent              latest                          f7afd7edd043   478MB
docker-orchagent              master.400-1b5d07f66_Internal   f7afd7edd043   478MB
docker-teamd                  latest                          7f969542e247   460MB
docker-teamd                  master.400-1b5d07f66_Internal   7f969542e247   460MB
docker-macsec                 latest                          9e19e6852266   462MB
docker-syncd-mlnx             latest                          ab68922f1558   984MB
docker-syncd-mlnx             master.400-1b5d07f66_Internal   ab68922f1558   984MB
docker-platform-monitor       latest                          242c117df797   991MB
docker-platform-monitor       master.400-1b5d07f66_Internal   242c117df797   991MB
docker-snmp                   latest                          1497192b2f4f   490MB
docker-snmp                   master.400-1b5d07f66_Internal   1497192b2f4f   490MB
docker-dhcp-relay             latest                          0ad3916d1ce0   453MB
docker-sonic-telemetry        latest                          628263dd0aee   737MB
docker-sonic-telemetry        master.400-1b5d07f66_Internal   628263dd0aee   737MB
docker-eventd                 latest                          405747634526   443MB
docker-eventd                 master.400-1b5d07f66_Internal   405747634526   443MB
docker-lldp                   latest                          37d10b44db3d   486MB
docker-lldp                   master.400-1b5d07f66_Internal   37d10b44db3d   486MB
docker-database               latest                          d44766379bb1   444MB
docker-database               master.400-1b5d07f66_Internal   d44766379bb1   444MB
docker-router-advertiser      latest                          d38d16a81c7f   444MB
docker-router-advertiser      master.400-1b5d07f66_Internal   d38d16a81c7f   444MB
docker-mux                    latest                          8b3c3911c42e   492MB
docker-mux                    master.400-1b5d07f66_Internal   8b3c3911c42e   492MB
docker-nat                    latest                          2ec54a0a9b1f   435MB
docker-nat                    master.400-1b5d07f66_Internal   2ec54a0a9b1f   435MB
docker-sflow                  latest                          c119d09e69be   433MB
docker-sflow                  master.400-1b5d07f66_Internal   c119d09e69be   433MB
docker-sonic-mgmt-framework   latest                          c2745f263b12   561MB
docker-sonic-mgmt-framework   master.400-1b5d07f66_Internal   c2745f263b12   561MB
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

The `eventd` service and docker were introduced by PR #11848 but the file `eventd.timer` was missed, which causes the error message.

[sonic_dump_r-anaconda-70_20220906_055706.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/9523488/sonic_dump_r-anaconda-70_20220906_055706.tar.gz)

**Comment by zhangyanzhao** [comment]
@renukamanavalan  can you please help to fix? Thanks.

**Comment by zbud-msft** [comment]
Hi @zhangyanzhao we do not have an eventd.timer file as it is not needed and I am unable to reproduce this issue:

admin@str-msn2700-04:~$ sudo config reload
Clear current config and reload config in config_db format from the default config file(s) ? [y/N]: y
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen  -j /etc/sonic/init_cfg.json  -j /etc/sonic/config_db.json  --write-to-db
Running command: /usr/local/bin/db_migrator.py -o migrate
Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment
Restarting SONiC target ...
Reloading Monit configuration ...
Reinitializing monit daemon

**Comment by stephenxs** [comment]
> sudo systemctl enable eventd.timer

Thanks @zbud-msft 
Can you try running `sudo systemctl enable eventd.timer` or check the syslog?
For `config reload`, the error message is not in CLI output but in the log.
For `sudo systemctl enable eventd.timer`, the error message is printed to the CLI.

**Comment by zbud-msft** [comment]
> > sudo systemctl enable eventd.timer
> 
> Thanks @zbud-msft Can you try running `sudo systemctl enable eventd.timer` or check the syslog? For `config reload`, the error message is not in CLI output but in the log. For `sudo systemctl enable eventd.timer`, the error message is printed to the CLI.

Understand, I see it in the logs. I will look into it.

**Comment by renukamanavalan** [comment]
There is no eventd.timer, so "systemctl <any action> eventd.timer" would indeed fail and the error message says the same.

"`Failed to enable unit: Unit file eventd.timer **does not exist**.`"

@zbud-msft, please check if log has anything related to eventd.timer, when config reload is invoked.
