### ISSUE TITLE
Undefined variables used in ctrmgrd

### ISSUE THREAD

**Issue by xumia** [sonic-net/sonic-buildimage#12022]
#### Description

The variable msg is not defined in method log_error, log_info.
See https://github.com/sonic-net/sonic-buildimage/blob/98d6357ae70d903c04e1ef883887a5e15d7be348/src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py#L107

![image](https://user-images.githubusercontent.com/59720581/189142064-88bede62-5a44-40fd-8a88-35ec4164926b.png)

The LGTM cannot detect such issue, we need to add some static code analysis tools, such as pylint, to catch such kinds of issues.

It can be detected by pylint as below:
```
$ pylint  src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py | grep -i undefined
src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py:107:34: E0602: Undefined variable 'msg' (undefined-variable)
src/sonic-ctrmgrd/ctrmgr/ctrmgrd.py:111:35: E0602: Undefined variable 'msg' (undefined-variable)
```

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@renukamanavalan  can you please help to fix this issue? Thanks.

**Comment by renukamanavalan** [comment]
@lixiaoyuner Can you please fix this?

**Comment by lixiaoyuner** [comment]
@renukamanavalan @zhangyanzhao I will fix this

**Comment by lixiaoyuner** [comment]
Fixed
https://github.com/sonic-net/sonic-buildimage/pull/11946/commits/c19802b1c29b5bf00e582f35d447cf56458d25c7
