### ISSUE TITLE
Update `port_config.ini` for `Arista-720DT-48S`

### ISSUE THREAD

**Issue by lizhijianrd** [sonic-net/sonic-buildimage#12037]
#### Description

`port_config.ini` of `Arista-720DT-48S` is using `Ethernet1`\~`Ethernet52` as alias now. According to [SONiC port naming convention change](https://github.com/sonic-net/SONiC/blob/master/doc/sonic-port-name.md), we need to update it to `etp1`\~`etp52`.

**Comment by andywongarista** [comment]
Hi Zhijian, yes this was something that we had meant to do. We will look into updating it now.
