### ISSUE TITLE
swsscommon Error in docker database supervisord init - flush_unused_database failed

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#12050]
#### Description
Observing following error during database docker start with latest master based image:
Sep 11 23:28:24.601520 sfd-t2-sup INFO database#supervisord: flushdb   File "/usr/local/bin/flush_unused_database", line 14, in <module>
Sep 11 23:28:24.601665 sfd-t2-sup INFO database#supervisord: flushdb     instlists = swsscommon.SonicDBConfig.getInstanceList()
Sep 11 23:28:24.601665 sfd-t2-sup INFO database#supervisord: flushdb NameError: name 'swsscommon' is not defined
Sep 11 23:28:24.613745 sfd-t2-sup INFO database#supervisord 2022-09-11 23:28:24,613 INFO exited: flushdb (exit status 1; not expected)

Looks like introduced by https://github.com/sonic-net/sonic-buildimage/pull/11600

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
Hit this issue on msft/202205 sha 2723c11
https://github.com/azure/sonic-buildimage-msft/commit/2723c1181a69aa14a92ea995e0a866c5f9b941b1
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

<!--
     Also attach debug file produced by `sudo generate_dump`
-->

**Comment by anamehra** [comment]
Hi @abdosi , FYI-

**Comment by zhangyanzhao** [comment]
@anamehra can you please help to add the repro steps and paste the output?

**Comment by anamehra** [comment]
> @anamehra can you please help to add the repro steps and paste the output?

@zhangyanzhao, this is 100% reproducible on the latest image I build. If one enter database docker, and try to run flush_unused_database, it throws error. import swsscommon is missing. But looks like its not just limited to that. I added the import statement and hit a different issue.
```
root@sonic:/home/cisco# docker exec -it database0 bash
root@sonic:/# ps aux | grep flush
root        6327  0.0  0.0   3180   656 pts/1    S+   15:32   0:00 grep flush
root@sonic:/# 

root@sonic:/# /usr/local/bin/flush_unused_database 
Traceback (most recent call last):
  File "/usr/local/bin/flush_unused_database", line 14, in <module>
    instlists = swsscommon.SonicDBConfig.getInstanceList()
NameError: name 'swsscommon' is not defined
root@sonic:/# 

Added import swsscommon:

root@sonic:/# /usr/local/bin/flush_unused_database 
Traceback (most recent call last):
  File "/usr/local/bin/flush_unused_database", line 15, in <module>
    instlists = swsscommon.SonicDBConfig.getInstanceList()
AttributeError: module 'swsscommon' has no attribute 'SonicDBConfig'
root@sonic:/#
```

**Comment by rlhui** [comment]
@anamehra  - is this issue seen in master or 202205 based, or both?  Thanks.

**Comment by anamehra** [comment]
> @anamehra - is this issue seen in master or 202205 based, or both? Thanks. Reminder to put basic info when logging issues. (please see template).

Hi @rlhui , Hit this issue on msft/202205, have not tested master. May be fixed in master and needs double commit to 202205. Update the description with sha1.

**Comment by anamehra** [comment]
Looks like related to this commit missing in 202205 
https://github.com/sonic-net/sonic-buildimage/pull/11215

**Comment by liuh-80** [comment]
I will check and make a list for PRs need cherry-pick to 202205 to fix this issue:
https://github.com/sonic-net/sonic-swss-common/pull/639

**Comment by liuh-80** [comment]
After check all related PR, I found the root cause of this issue is PR https://github.com/sonic-net/sonic-buildimage/pull/11600 been cherry-pick to 202205 branch by mistake, the deprecate swsssdk feature not ready to be cherry pick to 202205.

I create this revert PR to revert change in #11600:
https://github.com/sonic-net/sonic-buildimage/pull/12084
