### ISSUE TITLE
[202205][VOQ] pfcwd failed in SonicDBConfig::validateNamespace

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#12062]
#### Description

With 202205 image, we noticed the following error  when running sonic-mgmt test:

        "  File \\"/usr/local/bin/pfcwd\\", line 8, in <module>",
        "    sys.exit(cli())",
        "  File \\"/usr/local/lib/python3.9/dist-packages/click/core.py\\", line 764, in __call__",
        "    return self.main(*args, **kwargs)",
        "  File \\"/usr/local/lib/python3.9/dist-packages/click/core.py\\", line 717, in main",
        "    rv = self.invoke(ctx)",
        "  File \\"/usr/local/lib/python3.9/dist-packages/click/core.py\\", line 1137, in invoke",
        "    return _process_result(sub_ctx.command.invoke(sub_ctx))",
        "  File \\"/usr/local/lib/python3.9/dist-packages/click/core.py\\", line 956, in invoke",
        "    return ctx.invoke(self.callback, **ctx.params)",
        "  File \\"/usr/local/lib/python3.9/dist-packages/click/core.py\\", line 555, in invoke",
        "    return callback(*args, **kwargs)",
        "  File \\"/usr/local/lib/python3.9/dist-packages/click/decorators.py\\", line 57, in new_func",
        "    obj = ctx.ensure_object(object_type)",
        "  File \\"/usr/local/lib/python3.9/dist-packages/click/core.py\\", line 477, in ensure_object",
        "    self.obj = rv = object_type()",
        "  File \\"/usr/local/lib/python3.9/dist-packages/utilities_common/db.py\\", line 36, in __init__",
        "    multi_asic.connect_config_db_for_ns(ns)",
        "  File \\"/usr/local/lib/python3.9/dist-packages/sonic_py_common/multi_asic.py\\", line 47, in connect_config_db_for_ns",
        "    config_db = swsscommon.ConfigDBConnector(namespace=namespace)",
        "  File \\"/usr/lib/python3/dist-packages/swsscommon/swsscommon.py\\", line 1906, in __init__",
        "    super(ConfigDBConnector, self).__init__(use_unix_socket_path = use_unix_socket_path, namespace = namespace)",
        "  File \\"/usr/lib/python3/dist-packages/swsscommon/swsscommon.py\\", line 1584, in __init__",
        "    for db_name in self.get_db_list():",
        "  File \\"/usr/lib/python3/dist-packages/swsscommon/swsscommon.py\\", line 1520, in get_db_list",
        "    return _swsscommon.SonicV2Connector_Native_get_db_list(self)",
        "RuntimeError: :- validateNamespace: Initialize global DB config using API SonicDBConfig::initializeGlobalConfig"

The cmd caused the above error is: pfcwd start_default 

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ysmanman** [comment]
Add @arlakshm for viz.

**Comment by ysmanman** [comment]
We may need include https://github.com/sonic-net/sonic-utilities/pull/2238 in 202205 branch.

**Comment by liuh-80** [comment]
Can't reproduce this issue with latest 202205 branch build:

admin@vlab-01:~$ pfcwd start_default
Root privileges are required for this operation
admin@vlab-01:~$ sudo  pfcwd start_default
admin@vlab-01:~$

After check the source code of pfcwd, the issue happened when try to validate namespace but not initialize global config.
Issue may caused by some mock in sonic-mgmt, need more information to debug.

@ysmanman , could you please give more detail about:
1. which UT in sonic-mgmt failed?
2. The test environment？
3. please also share the failed UT log.

**Comment by ysmanman** [comment]
> Can't reproduce this issue with latest 202205 branch build:
> 
> admin@vlab-01:~$ pfcwd start_default Root privileges are required for this operation admin@vlab-01:~$ sudo pfcwd start_default admin@vlab-01:~$
> 
> After check the source code of pfcwd, the issue happened when try to validate namespace but not initialize global config. Issue may caused by some mock in sonic-mgmt, need more information to debug.
> 
> @ysmanman , could you please give more detail about:
> 
> 1. which UT in sonic-mgmt failed?
> 2. The test environment？hardware SKU and sonic image version?
> 3. please also share the failed UT log.

Hi Hua,

We first noticed the error because deploy-mg failed. According the traceback, we were able to manually reproduce the error with 'pfcwd start_default'. One thing to notice is the issue was only seen with multi-ASIC. We observed this in both sup and also LC that have 2 ASICs.   

admin@cmp210:/$ show platform summary 
Platform: x86_64-arista_7800_sup
HwSKU: Arista-7804R3-FM
ASIC: broadcom
ASIC Count: 12
Serial Number: SSN20200015
Model Number: DCS-7800A-SUP1A
Hardware Revision: 01.0a
Switch Type: fabric
admin@cmp210:/$ pfcwd start_default
Traceback (most recent call last):
  File "/usr/local/bin/pfcwd", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 57, in new_func
    obj = ctx.ensure_object(object_type)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 477, in ensure_object
    self.obj = rv = object_type()
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/db.py", line 36, in __init__
    multi_asic.connect_config_db_for_ns(ns)
  File "/usr/local/lib/python3.9/dist-packages/sonic_py_common/multi_asic.py", line 47, in connect_config_db_for_ns
    config_db = swsscommon.ConfigDBConnector(namespace=namespace)
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1906, in __init__
    super(ConfigDBConnector, self).__init__(use_unix_socket_path = use_unix_socket_path, namespace = namespace)
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1584, in __init__
    for db_name in self.get_db_list():
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1520, in get_db_list
    return _swsscommon.SonicV2Connector_Native_get_db_list(self)
RuntimeError: :- validateNamespace: Initialize global DB config using API SonicDBConfig::initializeGlobalConfig
admin@cmp210:/$ 

The error was not seen after we patched your change in https://github.com/sonic-net/sonic-utilities/pull/2238.

**Comment by liuh-80** [comment]
@ysmanman  Thanks, I add the request for 202205 label to this PR for cherry pick:
https://github.com/sonic-net/sonic-utilities/pull/2238

**Comment by zhangyanzhao** [comment]
Is this issue fixed? Can we close it? @ysmanman Thanks.

**Comment by rlhui** [comment]
@vmittal-msft - fyi

**Comment by ysmanman** [comment]
> Is this issue fixed? Can we close it? @ysmanman Thanks.

@zhangyanzhao The issue is still in 202205. https://github.com/sonic-net/sonic-utilities/pull/2238 should fix this issue. @liuh-80 will request to cherry pick the PR in 202205.

**Comment by rlhui** [comment]
@ysmanman  - this PR is supposed to fix it.  https://github.com/sonic-net/sonic-utilities/pull/2372  could you please confirm if issue is fixed? Thanks.

**Comment by ysmanman** [comment]
> @ysmanman - this PR is supposed to fix it. [sonic-net/sonic-utilities#2372](https://github.com/sonic-net/sonic-utilities/pull/2372) could you please confirm if issue is fixed? Thanks.

Hi @rlhui yes, https://github.com/sonic-net/sonic-utilities/pull/2372 fixed the issue.
