### ISSUE TITLE
[Ipfwd] Dualtor do not support directed broadcast

### ISSUE THREAD

**Issue by xwjiang-ms** [sonic-net/sonic-buildimage#12167]
#### Description
Dualtor do not support directed broadcast, dualtor will not forward directed broadcast packets

#### Steps to reproduce the issue:
1. Create a DHCP (udp_sport = udp_dport = 67) packet, ip_dst = vlan subnet address
2. Run "show mux status" to get active downstream port in active tor
3. Send this udp packet from a random upstream port
4. Receive packet in active downstream ports in active tor

#### Describe the results you received:
No packets forwarded by downstream ports, "portstat" only shows rx_ok in upstream port, no tx_ok increase in all downstream ports

#### Describe the results you expected:
Packets should be forwarded to all active downstream ports in the packet landing tor

#### Output of `show version`:

```
SONiC Software Version: SONiC.20201231.76
Distribution: Debian 10.12
Kernel: 4.19.0-12-2-amd64
Build commit: dc446d24ae
Build date: Fri Sep  9 23:23:32 UTC 2022
Built by: cloudtest@ff225e64c00000C

Platform: x86_64-arista_7260cx3_64
HwSKU: Arista-7260CX3-D108C8
ASIC: broadcom
ASIC Count: 1
Serial Number: JPE20222159
Uptime: 02:34:35 up  6:54,  1 user,  load average: 0.81, 0.88, 1.01
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by gechiang** [comment]
@prsunny please help triage this one.

**Comment by prsunny** [comment]
Currently this is a limitation and no requirements to support dir_bcast on Dual ToRs. Closing this!
