### ISSUE TITLE
[Sub-If|VRF] Unbind sub-interface from VRF is failed

### ISSUE THREAD

**Issue by Hedgehog-Guru** [sonic-net/sonic-buildimage#12170]
#### Description

Sun-Interface is left in inconsistent state if it was unbinded from VRF

#### Steps to reproduce the issue:
1. Create any VRF `config vrf add Vrf_11`
2. Create any sub-interface `config subinterface add Eth0.11 11`
3. Bind sub-interface to VRF `config interface vrf bind Eth0.11 Vrf_11`
4. Check bind was successful
`show vrf`
`ip link show vrf Vrf_11`
5. Unbind `config interface vrf unbind Eth0.11`
6. Check again
`show vrf`
`ip link show vrf Vrf_11`

#### Describe the results you received:

After unbinding Linux interface is still has master Vrf_11. SONIC output looks OK

```
root@qa-eth-vt01-3-2700a0:/home/admin# ip link show vrf Vrf_11
77: Eth0.11@Ethernet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9100 qdisc noqueue master Vrf_11 state UP mode DEFAULT group default qlen 1000
    link/ether 24:8a:07:80:d1:40 brd ff:ff:ff:ff:ff:ff
root@qa-eth-vt01-3-2700a0:/home/admin# show vrf
VRF     Interfaces
------  ------------
Vrf_11
root@qa-eth-vt01-3-2700a0:/home/admin#
```

#### Describe the results you expected:

Linux interface unbinded too

#### Output of `show version`:

```
SONiC Software Version: SONiC.202205_rc.11-a0e7525cf_Internal
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: a0e7525cf
Build date: Wed Sep 14 14:08:46 UTC 2022
Built by: sw-r2d2-bot@r-build-sonic-ci02-241

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1649X04248
Model Number: MSN2700-CS2F
Hardware Revision: Not Specified
Uptime: 11:24:02 up 14 min,  2 users,  load average: 0.94, 0.90, 0.76
Date: Mon 19 Sep 2022 11:24:02

```
#### Output of `show techsupport`:

[sonic_dump_qa-eth-vt01-3-2700a0_20220919_112341.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/9631881/sonic_dump_qa-eth-vt01-3-2700a0_20220919_112341.tar.gz)

**Comment by dgsudharsan** [comment]
@adyeung @preetham-singh  Can you please investigate?
This is due to unbind not properly handled for subinterface. In unbind call CLI rather than deleting the interface the vlan subinterface table is set with fields other than Vrf which is not properly handled in swss
127.0.0.1:6379[4]> hgetall "VLAN_SUB_INTERFACE|Eth0.11"
1) "admin_status"
2) "up"
3) "vlan"
4) "11"
127.0.0.1:6379> hgetall "INTF_TABLE:Eth0.11"
 1) "vlan"
 2) "11"
 3) "vrf_name"
 4) "Vrf_11"
 5) "mtu"
 6) "0"
 7) ""
 8) ""
 9) "admin_status"
10) "up"
11) "mac_addr"
12) "00:00:00:00:00:00"

**Comment by preetham-singh** [comment]
Please assign the issue to me. I am working on fix.

**Comment by dgsudharsan** [comment]
@preetham-singh @adyeung  Any update on ETA for this issue?

**Comment by preetham-singh** [comment]
ETA: 7th Nov'2022

**Comment by dgsudharsan** [comment]
@preetham-singh  Do we have a PR to fix this issue?
