### ISSUE TITLE
201911 -> 202205 warm-upgrade failure due to "unknown" compression

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#12171]
#### Description

Warm reboot fails due to failure in attempt to mount next image squashfs. This is needed for several things including asic config check, FW upgrade on Nvidia platform, etc. The compression algorithm was changed to ```zstd``` in 202205 but in 201911 this compression is not supported leading to errors and unability to perform warm reboot. Commit that introduced ```zstd```: https://github.com/sonic-net/sonic-buildimage/commit/d5365928d4dc1fa9081cf9fe61ab47e0ef306e9c

#### Steps to reproduce the issue:
1. boot 201911 image
2. install 202205 image
3. sudo warm-reboot -vvvf

#### Describe the results you received:

```
root@str-msn2700-22:~# warm-reboot -vvvf
mount: wrong fs type, bad option, bad superblock on /dev/loop2,
       missing codepage or helper program, or other error
 
       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Wed Sep 21 19:18:33 UTC 2022 Ignoring ASIC config checksum failure...
mount: wrong fs type, bad option, bad superblock on /dev/loop2,
       missing codepage or helper program, or other error
 
       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Failed to mount next SONiC image
SDK upgrade check failued
Warm reboot is not supported
Wed Sep 21 19:18:35 UTC 2022 fastfast-reboot failure (101) cleanup ...
Wed Sep 21 19:18:36 UTC 2022 Cancel warm-reboot: code (0)

```

dmesg output:

```
admin@str-msn2700-22:~$ sudo dmesg | tail
[34260.312537] squashfs: SQUASHFS error: Filesystem uses "unknown" compression. This is not supported
```

#### Describe the results you expected:

Successful warm-reboot operation

#### Output of `show version`:

```
Public hash for base image (201911 image):     69f18cfdbbc67ad12878020da4b506fa6f58306f 
Public hash for target image (202205 image):  6812cf0ccaa302b50e706aaba3416bad90a536c4 
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by saiarcot895** [comment]
Resolved with #12260.
