### ISSUE TITLE
[snmp] Snmp value for cached memory is different from system_info

### ISSUE THREAD

**Issue by AndriiLozovyi** [sonic-net/sonic-buildimage#12192]
#### Description
It looks that starting from sonic image` SONiC.master.137279-dirty-20220820.094848` something changed in output of snmp for CachedMemory, and now output of snmp and info from system have a difference starting from` 6%` and may be up to `12 %`. On previous sonic image `SONiC.master.135201-dirty-20220815.112418` output of snmp for cached memory was in touch with system_info from DUT.

#### Steps to reproduce the issue:
1. Deploy sonic image `SONiC.master.137279-dirty-20220820.094848`
2. Run cmd from sonic-mgmt `snmpwalk -v 2c -c public <DUT_IP> 1.3.6.1.4.1.2021.4.15.0`
3. Check cached memory value on device `cat /proc/meminfo | grep Cached`

#### Describe the results you received:
On `SONiC.master.137279-dirty-20220820.094848`:

```
iso.3.6.1.4.1.2021.4.15.0 = INTEGER: 1045492
Cached:           972064 kB

>>> CALC_DIFF = lambda snmp, sys_data: float(abs(snmp - int(sys_data)) * 100) / float(snmp)
>>> CALC_DIFF(1045492, 972064)
7.023296208866256
```

#### Describe the results you expected:
On `SONiC.master.135201-dirty-20220815.112418`:

```
iso.3.6.1.4.1.2021.4.15.0 = INTEGER: 965504
Cached:           965504 kB
>>> CALC_DIFF(965504, 965504)
0.0
```

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.137279-dirty-20220820.094848
Distribution: Debian 11.4
Kernel: 5.10.0-12-2-amd64
Build commit: 0f50835c1
Build date: Sat Aug 20 16:51:04 UTC 2022
Built by: AzDevOps@sonic-build-workers-001Y2N

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
ASIC: barefoot
ASIC Count: 1
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by gechiang** [comment]
@AndriiLozovyi can you file a bug on snmpd as this is not an issue on the agent.
@qiluo-msft is this been tested and known issue?  If so, can you please help solicit help wanted?

**Comment by AndriiLozovyi** [comment]
Made PR in sonic-mgmt that align **test_snmp_memory** with how cached memory is calculated in snmpd
Closing this issue
