### ISSUE TITLE
[yang-models] Missing constraints in VLAN, VLAN_INTERFACE yang models

### ISSUE THREAD

**Issue by isabelmsft** [sonic-net/sonic-buildimage#12256]
#### Description

VLAN, VLAN_INTERFACE yang models are missing validation criteria. These constraints are missing from the YANG model, but they are checked in sonic-utilities using adhoc validation. Included in the description for each missing constraint is the adhoc validation code in sonic-utilities that we aim to replace with systemized YANG validation.

1. Don't allow write of default vlan (vid = 1)

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        if vid == 1:
            ctx.fail("{} is default VLAN".format(vlan)) # TODO: MISSING CONSTRAINT IN YANG MODEL
```
2. If vlan id already exists, do not allow duplicitous write to ConfigDB

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        if clicommon.check_if_vlanid_exist(db.cfgdb, vlan): # TODO: MISSING CONSTRAINT IN YANG MODEL
            ctx.fail("{} already exists".format(vlan))
```
3. Do not allow removal of vlan interface if vlan has IP address assigned

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        for intf_key in intf_table:
            if ((type(intf_key) is str and intf_key == 'Vlan{}'.format(vid)) or # TODO: MISSING CONSTRAINT IN YANG MODEL
                (type(intf_key) is tuple and intf_key[0] == 'Vlan{}'.format(vid))):
                ctx.fail("{} can not be removed. First remove IP addresses assigned to this VLAN".format(vlan))
```

4. Don't allow removal of vlan if there are members assigned

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        keys = [ (k, v) for k, v in db.cfgdb.get_table('VLAN_MEMBER') if k == 'Vlan{}'.format(vid) ]
    
        if keys: # TODO: MISSING CONSTRAINT IN YANG MODEL
            ctx.fail("VLAN ID {} can not be removed. First remove all members assigned to this VLAN.".format(vid))
```

5. If interface naming mode is alias, make sure corresponding port name exists

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        if clicommon.get_interface_naming_mode() == "alias": # TODO: MISSING CONSTRAINT IN YANG MODEL
            alias = port
            iface_alias_converter = clicommon.InterfaceAliasConverter(db)
            port = iface_alias_converter.alias_to_name(alias)
            if port is None:
                ctx.fail("cannot find port name for alias {}".format(alias))

```

6.  Make sure port is not configured as a mirror destination port

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        if clicommon.is_port_mirror_dst_port(db.cfgdb, port): # TODO: MISSING CONSTRAINT IN YANG MODEL
            ctx.fail("{} is configured as mirror destination port".format(port))
```

7. Make sure port is not already a vlan member

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        if clicommon.is_port_vlan_member(db.cfgdb, port, vlan): # TODO: MISSING CONSTRAINT IN YANG MODEL
            ctx.fail("{} is already a member of {}".format(port, vlan))
```

8. Make sure port is not a router interface

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        if (is_port and clicommon.is_port_router_interface(db.cfgdb, port)) or \
           (not is_port and clicommon.is_pc_router_interface(db.cfgdb, port)): # TODO: MISSING CONSTRAINT IN YANG MODEL
            ctx.fail("{} is a router interface!".format(port))
```

9. Make sure port is not already a portchannel member

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        if (is_port and clicommon.interface_is_in_portchannel(portchannel_member_table, port)): # TODO: MISSING CONSTRAINT IN YANG MODEL
            ctx.fail("{} is part of portchannel!".format(port))
```

10. Make sure port is not already an untagged member

[sonic-utilities config/vlan.py](https://github.com/sonic-net/sonic-utilities/blob/master/config/vlan.py)
```
        if (clicommon.interface_is_untagged_member(db.cfgdb, port) and untagged): # TODO: MISSING CONSTRAINT IN YANG MODEL
            ctx.fail("{} is already untagged member!".format(port))
```
#### Steps to reproduce the issue:
1. Using YANG model as mode of validation, write to ConfigDB with an invalid configuration
2. Write to ConfigDB will go through even though it should be prohibited by YANG model
#### Describe the results you received:
Write to ConfigDB succeeds even though the configuration is invalid

#### Describe the results you expected:
Write to ConfigDB should fail

**Comment by gechiang** [comment]
@zhangyanzhao please help put in correct project.

**Comment by zhangyanzhao** [comment]
This issue has dependency on custom validation YANG.

**Comment by zhangyanzhao** [comment]
@prsunny  can you please help to address this issue? Thanks.

**Comment by prsunny** [comment]
@zhangyanzhao , can we get a help on this from community? I don't have an ETA for this currently

**Comment by matiAlfaro** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/18292 is ready for review, should address all items listed here.
