### ISSUE TITLE
show interfaces neighbor expected returns empty output

### ISSUE THREAD

**Issue by SavchukRomanLv** [sonic-net/sonic-buildimage#12301]
#### Description
Issue has been spotted while running [test_show_interfaces_neighbor_expected](https://github.com/sonic-net/sonic-mgmt/blob/680230f97c9618c2ac4f16abbba771fb903e5bce/tests/iface_namingmode/test_iface_namingmode.py#L777) TC 

Issue started repro from SONiC [147826](https://dev.azure.com/mssonic/build/_build/results?buildId=147826&view=results)
I suspect PR [11894](https://github.com/sonic-net/sonic-buildimage/pull/11894) coused this issue

#### Steps to reproduce the issue:
1. Deploy last successful SONIC master
2. Deploy T1 topo
3. Run TC:  tests/iface_namingmode -k test_show_interfaces_neighbor_expected or execute "show interfaces neighbor expected"

#### Describe the results you received:
TC passed, output is empty 

#### Describe the results you expected:
```    show interfaces neighbor expected
     LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
     Ethernet0    ARISTA01T2  Ethernet1       None                10.232.25.2     SpineRouter
     Ethernet4    ARISTA02T2  Ethernet1       None                10.232.25.3     SpineRouter
     Ethernet8    ARISTA03T2  Ethernet1       None                10.232.25.4     SpineRouter
     Ethernet12   ARISTA04T2  Ethernet1       None                10.232.25.5     SpineRouter
```

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.154150-dirty-20220928.182254
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: f890606d8
Build date: Wed Sep 28 18:29:23 UTC 2022
Built by: AzDevOps@sonic-build-workers-0025UB

Platform: x86_64-accton_as9516_32d-r0
HwSKU: newport
ASIC: barefoot
ASIC Count: 1
```
#### Output of `show techsupport`:

```
```

**Comment by jcaiMR** [comment]
Solution under review with discussion, will merge soon.
