### ISSUE TITLE
[202205] system neighbor was not programmed in remote ASIC

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#12343]
#### Description

We noticed the issue when triaging t2 sonic-mgmt test failure with 202205 image. The issue is that some system neighbors, including inband neighbor, were added in chassis neigh table, but they were missing in kernel and also hw in some asics.  We haven't figured out the exact trigger of the issue.  Our experiment shows config reload may fix this issue. So this seems due to some race condition.  This was seen in both single- or multi-asic LCs.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by rlhui** [comment]
@ysmanman from Arista is working on this issue.
