### ISSUE TITLE
There are some err msg after the installation of 201911 image with ONIE such as "Failed name lookup - disconnected path" 

### ISSUE THREAD

**Issue by nhe-NV** [sonic-net/sonic-buildimage#12346]
#### Description
After the onie installation for the 201911 image, and do the loganalyzer, There are some unexpected err msgs in the syslog:
There is a PR handled this issue in 202012, maybe this need to be backport to the 201911: https://github.com/sonic-net/sonic-buildimage/pull/6040

#### Steps to reproduce the issue:
1. onie install the 201911 image
2. run loganalyzer

#### Describe the results you received:

Oct  8 03:40:47 sonic kernel: [    4.628125] audit: type=1400 audit(1665200447.344:4): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="sbin" pid=549 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:40:47 sonic kernel: [    4.628135] audit: type=1400 audit(1665200447.344:5): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="bin" pid=549 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:40:47 sonic kernel: [    4.628144] audit: type=1400 audit(1665200447.344:6): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="usr/sbin" pid=549 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:40:47 sonic kernel: [    4.628152] audit: type=1400 audit(1665200447.344:7): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="usr/bin" pid=549 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:40:47 sonic kernel: [    4.628125] audit: type=1400 audit(1665200447.344:4): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="sbin" pid=549 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:40:47 sonic kernel: [    4.628135] audit: type=1400 audit(1665200447.344:5): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="bin" pid=549 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:40:47 sonic kernel: [    4.628144] audit: type=1400 audit(1665200447.344:6): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="usr/sbin" pid=549 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:40:47 sonic kernel: [    4.628152] audit: type=1400 audit(1665200447.344:7): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="usr/bin" pid=549 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:41:17.248478 sonic NOTICE kernel: [   34.522081] audit: type=1400 audit(1665200477.240:10): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="bin" pid=5011 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:41:17.248481 sonic NOTICE kernel: [   34.522095] audit: type=1400 audit(1665200477.240:11): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="usr/sbin" pid=5011 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 03:41:17.248483 sonic NOTICE kernel: [   34.522107] audit: type=1400 audit(1665200477.240:12): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="image-detached.203-dirty-20220830.113744/rw/usr/bin" pid=5011 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:42:23.342483 r-lionfish-07 NOTICE kernel: [    4.621027] audit: type=1400 audit(1665200543.334:5): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="bin" pid=493 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:42:23.342484 r-lionfish-07 NOTICE kernel: [    4.621040] audit: type=1400 audit(1665200543.334:6): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="usr/sbin" pid=493 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:42:23.342485 r-lionfish-07 NOTICE kernel: [    4.621051] audit: type=1400 audit(1665200543.334:7): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="image-detached.203-dirty-20220830.113744/rw/usr/bin" pid=493 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:42:27.400347 r-lionfish-07 ERR ntpd[796]: error resolving pool 0.debian.pool.ntp.org: Temporary failure in name resolution (-3)

Oct  8 06:42:27.400992 r-lionfish-07 ERR ntpd[796]: error resolving pool 1.debian.pool.ntp.org: Temporary failure in name resolution (-3)

Oct  8 06:42:27.401643 r-lionfish-07 ERR ntpd[796]: error resolving pool 2.debian.pool.ntp.org: Temporary failure in name resolution (-3)

Oct  8 06:42:27.404151 r-lionfish-07 ERR ntpd[796]: error resolving pool 3.debian.pool.ntp.org: Temporary failure in name resolution (-3)

Oct  8 06:42:32.230208 r-lionfish-07 NOTICE kernel: [   13.509740] audit: type=1400 audit(1665200552.222:10): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="bin" pid=3023 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:42:32.230209 r-lionfish-07 NOTICE kernel: [   13.510031] audit: type=1400 audit(1665200552.222:11): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="usr/sbin" pid=3023 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:42:32.230210 r-lionfish-07 NOTICE kernel: [   13.510232] audit: type=1400 audit(1665200552.222:12): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="image-detached.203-dirty-20220830.113744/rw/usr/bin" pid=3023 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:42:34.597756 r-lionfish-07 NOTICE kernel: [   15.879414] audit: type=1400 audit(1665200554.590:14): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="bin" pid=3396 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:42:34.597758 r-lionfish-07 NOTICE kernel: [   15.879428] audit: type=1400 audit(1665200554.590:15): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="usr/sbin" pid=3396 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:42:34.597760 r-lionfish-07 NOTICE kernel: [   15.879442] audit: type=1400 audit(1665200554.590:16): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="image-detached.203-dirty-20220830.113744/rw/usr/bin" pid=3396 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:44:27.535299 r-lionfish-07 NOTICE kernel: [  128.433160] audit: type=1400 audit(1665200667.527:18): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="bin" pid=7693 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:44:27.535300 r-lionfish-07 NOTICE kernel: [  128.433172] audit: type=1400 audit(1665200667.527:19): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="usr/sbin" pid=7693 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Oct  8 06:44:27.535302 r-lionfish-07 NOTICE kernel: [  128.433183] audit: type=1400 audit(1665200667.527:20): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/ntpd" name="image-detached.203-dirty-20220830.113744/rw/usr/bin" pid=7693 comm="ntpd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

#### Describe the results you expected:
NO such err msgs
#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download
[sysdump_test_check_errors_in_log_during_deploy_sonic_image.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/9750383/sysdump_test_check_errors_in_log_during_deploy_sonic_image.tar.gz)
 and attach the file here )
```

**Comment by dgsudharsan** [comment]
This issue is fixed in 202012+ versions. However it exists in 201911. Should this fix be backported to 201911? https://github.com/sonic-net/sonic-buildimage/pull/6040

**Comment by qiluo-msft** [comment]
I added request label for 201911 branch.
