### ISSUE TITLE
[EVPN][warm-reboot] EVPN vxlan traffic loss during warm-reboot 

### ISSUE THREAD

**Issue by Hedgehog-Guru** [sonic-net/sonic-buildimage#12370]
#### Description

In EVPN vxlan scenario with proper graceful restart config inside FRR, there is traffic loss during warm-reboot

#### Steps to reproduce the issue:
Topology: two switches connected with single port. Each switch has L2 access port to any traffic generator able to send L2 frames. Ixia in my case.
1. Configure split config mode.
2. Configure VTEPs on switches
3. Configure any vlan and add member ports facing traffic generator. Create VNI for that vlan.
4. Configure L3 addresses on interswitch link
5. In FRR configure BGP L2VPN EVPN between switches
6. Add FRR graceful restart options on both switches
```
 bgp graceful-restart restart-time 300
 bgp graceful-restart
 bgp graceful-restart preserve-fw-state
```
7.  Start L2 traffic between switches. Make sure there are no losses
8. Perform warm-reboot and check traffic impact

#### Describe the results you received:
Traffic loss

#### Describe the results you expected:
No any traffic impact

#### Output of `show version`:

```
SONiC Software Version: SONiC.202205_rc.17-12870dde8_Internal
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: 12870dde8
Build date: Tue Oct  4 09:54:37 UTC 2022
Built by: sw-r2d2-bot@r-build-sonic-ci03-242

Platform: x86_64-mlnx_msn4600c-r0
HwSKU: ACS-MSN4600C
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2140X00042
Model Number: MSN4600-CS2FO_QP
Hardware Revision: A1
Uptime: 20:33:11 up 11 min,  1 user,  load average: 0.54, 0.57, 0.39
Date: Fri 07 Oct 2022 20:33:11
```
#### Output of `show techsupport`:

[sonic_dump_qa-eth-vt03-1-4600ca1_20221007_203258.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/9764748/sonic_dump_qa-eth-vt03-1-4600ca1_20221007_203258.tar.gz)
[sonic_dump_qa-eth-vt03-2-3700v_20221007_203257.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/9764751/sonic_dump_qa-eth-vt03-2-3700v_20221007_203257.tar.gz)

#### Additional information you deem important (e.g. issue happens only occasionally):

**Comment by dgsudharsan** [comment]
It appears FRR doesn't support graceful restart for EVPN address family https://github.com/FRRouting/frr/issues/9749

**Comment by dgsudharsan** [comment]
@adyeung Can you please help to assign someone to confirm if warmboot with EVPN will not be supported in SONiC? EVPN HLD mentions that it is supported. Is it tested?

**Comment by arlakshm** [comment]
@yxieca to start the thread with @adyeung on EVPN warmboot issues.

**Comment by adyeung** [comment]
@nkelapur from BRCM will followup

**Comment by nkelapur** [comment]
FRR currently does not support BGP Graceful restart for EVPN address-family. Hence EVPN warm-reboot will not be hitless in Sonic until this support is available in FRR. 
Updated EVPN HLD with this note

**Comment by Yuval-Mellanox** [comment]
@nkelapur could you please point me that note?
could not find it in the HLD:
https://github.com/sonic-net/SONiC/blob/master/doc/vxlan/EVPN/EVPN_VXLAN_HLD.md

**Comment by nkelapur** [comment]
> 

Looks like I missed creating a pull request for the proposed change. I have done it now.
https://github.com/sonic-net/SONiC/pull/1227

**Comment by prgeor** [comment]
Not supported. Closing as hld is now updated
