### ISSUE TITLE
[yang] Need Yang for FG_NHG_MEMBER, FG_NHG table

### ISSUE THREAD

**Issue by ganglyu** [sonic-net/sonic-buildimage#12457]
#### Description

We don't have Yang model for FG_NHG_MEMBER, FG_NHG, NEIGH table.

#### Steps to reproduce the issue:
1. Run build pipeline for below PR:
https://github.com/Azure/sonic-buildimage/pull/10963
2. Check build log:
sonic_yang(6):Note: Below table(s) have no YANG models: TUNNEL, FG_NHG_MEMBER, FG_NHG, NEIGH

#### Describe the results you received:
sonic-config-engine unit test failed.

#### Describe the results you expected:
sonic-config-engine unit test should pass.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ganglyu** [comment]
@anish-n
Did you introduce these tables?

**Comment by zhangyanzhao** [comment]
@anish-n can you please help to create YANG model for these tables? Thanks.
