### ISSUE TITLE
Need Yang for SYSTEM_PORT table

### ISSUE THREAD

**Issue by ganglyu** [sonic-net/sonic-buildimage#12458]
We don't have Yang model for SYSTEM_PORT table.

#### Steps to reproduce the issue:
1. Run build pipeline for below PR:
https://github.com/Azure/sonic-buildimage/pull/10963
2. Check build log:
sonic_yang(6):Note: Below table(s) have no YANG models: SYSTEM_PORT, TUNNEL

#### Describe the results you received:
sonic-config-engine unit test failed.

#### Describe the results you expected:
sonic-config-engine unit test should pass.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ganglyu** [comment]
@mlorrillere
Did you introduce SYSTEM_PORT table?

**Comment by zhangyanzhao** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/12689 merged and close this issue
