### ISSUE TITLE
[yang] sonic-vlan-sub-interface.yang does not align with ConfigDB

### ISSUE THREAD

**Issue by isabelmsft** [sonic-net/sonic-buildimage#12466]
#### Description

VLAN_SUB_INTERFACE ConfigDB table has field: "vlan" but this is not present in yang model

#### Steps to reproduce the issue:
1. `sudo config subinterface add Eth64.100 100` to add subinterface with vlan id 100
2. ` redis-cli -n 4 hgetall "VLAN_SUB_INTERFACE|Eth64.100"` shows 
```
1) "admin_status"
2) "up"
3) "vlan"
4) "100"
```
#### Describe the results you received:
`vlan` field is not represented in `sonic-vlan-sub-interface.yang` , so YANG validation fails when `vlan` field is configured

#### Describe the results you expected:
`vlan` field should be represented in `sonic-vlan-sub-interface.yang`

**Comment by zhangyanzhao** [comment]
@lolyu  can you please help to work on this issue? Thanks.

**Comment by zhangyanzhao** [comment]
@lolyu  kindly ping.

**Comment by zhangyanzhao** [comment]
@lolyu can you please help to pick this issue? Thanks.

**Comment by lolyu** [comment]
@zhangyanzhao  @isabelmsft, the fix is ready for review, please take a look.
