### ISSUE TITLE
Need Yang for RADIUS_SERVER, RADIUS tables

### ISSUE THREAD

**Issue by isabelmsft** [sonic-net/sonic-buildimage#12477]
#### Description
We don't have Yang models for RADIUS_SERVER, RADIUS tables.

#### Steps to reproduce the issue:
1. Attempt to use GCU to apply-patch writing to RADIUS_SERVER or RADIUS tables
Sample JSON patch:
`[{"op": "add", "path": "/RADIUS_SERVER", "value": {}}, {"op": "add", "path": "/RADIUS_SERVER/10.10.10.10", "value": {"auth_port": "1812", "priority": "1"}}]`
#### Describe the results you received:
GCU patch application failed with error:
ValueError: Given patch is not valid because it has changes to tables without YANG models

#### Describe the results you expected:
GCU patch application success with successful write to ConfigDB

#### Output of `show version`:
```
admin@vlab-01:~$ show version

SONiC Software Version: SONiC.master.118843-40cbd3fe8
Distribution: Debian 11.3
Kernel: 5.10.0-12-2-amd64
Build commit: 40cbd3fe8
Build date: Wed Jul  6 14:46:15 UTC 2022
Built by: AzDevOps@sonic-build-workers-001QGK

**Comment by zhangyanzhao** [comment]
@adyeung can you please help to check if BRCM can help to define YANG model for these tables?
