### ISSUE TITLE
Need Yang model for TELEMETRY_CLIENT

### ISSUE THREAD

**Issue by ganglyu** [sonic-net/sonic-buildimage#12483]
#### Description

Dialout client in telemetry container is using TELEMETRY_CLIENT table.
Minigraph and CLI do not cover this table, and we can only use redis CLI to configure this table. So this issue does not block anything.
We should have SONiC Yang model for all the tables in config db.

#### Steps to reproduce the issue:
We don't have any chance to run Yang validation for this table.

#### Describe the results you received:
There's no yang model for TELEMETRY_CLIENT.

#### Describe the results you expected:
We should have yang model for TELEMETRY_CLIENT.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
@adyeung can you please help to find someone in BRCM to help to create YANG model? Thanks.

**Comment by zhangyanzhao** [comment]
bump up this issue and help wanted
