### ISSUE TITLE
Add the debian mirror template to sonic base docker image

### ISSUE THREAD

**Issue by xumia** [sonic-net/sonic-buildimage#12523]
#### Description

Currently, the debian buster and bullseye uses different mirror, we should use the same template to reduce mirror missing issue and make easy to add a new distribution, for example bookworm.
https://github.com/sonic-net/sonic-buildimage/pull/12522

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by xumia** [comment]
PR to fix the issue.
https://github.com/sonic-net/sonic-buildimage/pull/12557

**Comment by prgeor** [comment]
@xumia could you check why issue is open after PR merged?

**Comment by xumia** [comment]
> @xumia could you check why issue is open after PR merged?

The issue was created before the PR https://github.com/sonic-net/sonic-buildimage/pull/12557 merged.
