### ISSUE TITLE
Test failure test_BlockUseSwsssdk()

### ISSUE THREAD

**Issue by EdenGri** [sonic-net/sonic-buildimage#12558]
#### Description

The test test_BlockUseSwsssdk() failed with the error message "AttributeError: 'module' object has no attribute 'run'".
I think that it runs Python 2.7 when the function 'run' of the subprocess (in line 38) is available only in Python 3.5 and newer

The test test_BlockUseSwsssdk() in the sonic-pyswssdk repo failed with the error message "AttributeError: 'module' object has no attribute 'run'".
I think that when we build build_env buster we run Python 2.7 when the function 'run' of the subprocess (in line 38) is available only in Python 3.5 and newer
The commit that adds the test is: e30a1e1e90e6227a771340edcad727255be54b94
The sonic-buildimage not pointing to the commit that adds the tests yet.
This is the submodule update PR with the failure: https://github.com/sonic-net/sonic-buildimage/pull/12559
![image](https://user-images.githubusercontent.com/63317673/199031835-e7092d02-c42c-4d32-8a4f-b562e0d69b18.png)

#### Steps to reproduce the issue:
1. build with the commit e30a1e1e90e6227a771340edcad727255be54b94 of the sonic-py-swssdk repo with buster build env

#### Describe the results you received:
build failure 

#### Describe the results you expected:
build succsses

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prgeor** [comment]
@qiluo-msft could you check why we still using python2.x in test environment?

**Comment by liuh-80** [comment]
This issue fixed by https://github.com/sonic-net/sonic-py-swsssdk/pull/128
