### ISSUE TITLE
[eventd] error in logs "Deserialize failed: input stream errorstr"

### ISSUE THREAD

**Issue by romanvasylys** [sonic-net/sonic-buildimage#12570]
#### Description

Recently we have eventd error in logs after restarting eventd.service:
```
ERR eventd#eventd: :- deserialize: deserialize Failed: input stream errorstr[0:64]:(#001) data type: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&
```

#### Steps to reproduce the issue:
1. docker restart eventd
2. sudo systemctl restart eventd.service
#### Describe the results you received:
Got eventd deserialize fail
#### Describe the results you expected:
No errors during eventd.service restart
#### Output of `show version`:

```
SONiC Software Version: SONiC.master.162651-dirty-20221019.104245
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: ef0559c03
Build date: Wed Oct 19 17:40:59 UTC 2022
Built by: AzDevOps@sonic-build-workers-0029EO

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by liat-grozovik** [comment]
@renukamanavalan any plan to handle this issue as part of 202211?

**Comment by zbud-msft** [comment]
ETA for RCA/fix - 5/10

**Comment by stephenxs** [comment]
@zbud-msft @qiluo-msft 
Is there any update about the issue? It is still observed on 202211 branch.
Thank you.

**Comment by qiluo-msft** [comment]
the fix is in master, pending backport for 202211
