### ISSUE TITLE
[Mellanox] [techsupport] LogAnalyzer report error at teardown of test_techsupport in some Mellanox platforms

### ISSUE THREAD

**Issue by xwjiang-ms** [sonic-net/sonic-buildimage#12621]
#### Description

When we run test script `tests/show_techsupport/test_techsupport.py`, will get below errors at teardown of test_techsupport in some Mellanox platforms.

Error occurred in:

OSVersion | Platform | HardwareSku
-- | -- | --
20191130 | x86_64-mlnx_msn3800-r0 | Mellanox-SN3800-D112C8
20201231, 20220530, master | x86_64-mlnx_msn4600c-r0 | ACS-MSN4600C

Error messages:

E 	Traceback:
E 	Traceback (most recent call last):
E 	  File "/azp/agent/_work/14/s/tests/common/helpers/parallel.py", line 31, in run
E 	    Process.run(self)
E 	  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
E 	    self._target(*self._args, **self._kwargs)
E 	  File "/azp/agent/_work/14/s/tests/common/helpers/parallel.py", line 227, in wrapper
E 	    target(*args, **kwargs)
E 	  File "/azp/agent/_work/14/s/tests/common/plugins/loganalyzer/__init__.py", line 39, in analyze_logs
E 	    dut_analyzer.analyze(markers[node.hostname])
E 	  File "/azp/agent/_work/14/s/tests/common/plugins/loganalyzer/loganalyzer.py", line 371, in analyze
E 	    self._verify_log(analyzer_summary)
E 	  File "/azp/agent/_work/14/s/tests/common/plugins/loganalyzer/loganalyzer.py", line 135, in _verify_log
E 	    raise LogAnalyzerError(result_str)
E 	LogAnalyzerError: expected_match: 0
E 	expected_missing_match: 0
E 	match: 9
E
E 	Match Messages:
E 	Nov  6 19:05:03.022155 str2-msn4600c-acs-04 ERR kernel: [12127.435598] mlxsw_minimal 2-0048: Reg cmd access status failed (status=1(device is busy))
E 	Nov  6 19:05:03.022180 str2-msn4600c-acs-04 ERR kernel: [12127.533693] mlxsw_minimal 2-0048: Reg cmd access failed (reg_id=9014(mcia),type=query)
E 	Nov  6 19:05:03.022192 str2-msn4600c-acs-04 ERR kernel: [12127.628640] mlxsw_minimal 2-0048 sfp17: Eeprom query failed
E 	Nov  6 19:05:03.337161 str2-msn4600c-acs-04 ERR kernel: [12127.750592] mlxsw_minimal 2-0048: Reg cmd access status failed (status=1(device is busy))
E 	Nov  6 19:05:03.337201 str2-msn4600c-acs-04 ERR kernel: [12127.848676] mlxsw_minimal 2-0048: Reg cmd access failed (reg_id=9014(mcia),type=query)
E 	Nov  6 19:05:03.655181 str2-msn4600c-acs-04 ERR kernel: [12128.068628] mlxsw_minimal 2-0048: Reg cmd access status failed (status=1(device is busy))
E 	Nov  6 19:05:03.655210 str2-msn4600c-acs-04 ERR kernel: [12128.166709] mlxsw_minimal 2-0048: Reg cmd access failed (reg_id=9014(mcia),type=query)
E 	Nov  6 19:05:03.987153 str2-msn4600c-acs-04 ERR kernel: [12128.400620] mlxsw_minimal 2-0048: Reg cmd access status failed (status=1(device is busy))
E 	Nov  6 19:05:03.987174 str2-msn4600c-acs-04 ERR kernel: [12128.498687] mlxsw_minimal 2-0048: Reg cmd access failed (reg_id=9014(mcia),type=query)

#### Steps to reproduce the issue:
1. Run test script `tests/show_techsupport/test_techsupport.py`
2. 
3.

#### Describe the results you received:
Error messages in description.

#### Describe the results you expected:
No error messages or these error messages could be ignored.

#### Output of `show version`:

```
OSVersion in ["20191130", "20201231", "20220531", "master"]
```
#### Output of `show techsupport`:

```
[show techsupport in x86_64-mlnx_msn4600c-r0.log](https://github.com/sonic-net/sonic-buildimage/files/9983477/show.techsupport.in.x86_64-mlnx_msn4600c-r0.log)
```

#### Additional information you deem important (e.g. issue happens only occasionally):

```
[syslog.zip](https://github.com/sonic-net/sonic-buildimage/files/9983447/syslog.zip)
```

**Comment by dgsudharsan** [comment]
@xwjiang-ms Can you please attach techsupport to the ticket?

**Comment by xwjiang-ms** [comment]
> @xwjiang-ms Can you please attach techsupport to the ticket?

@dgsudharsan Sure, I have uploaded the output of `show techsupport` in x86_64-mlnx_msn4600c-r0.

**Comment by dgsudharsan** [comment]
@xwjiang-ms I need the tar.gz file generated at the end of techsupport to be attached to the issue. Can you please attach the file?

**Comment by xwjiang-ms** [comment]
> 

Hi @dgsudharsan, the tar.gz file is too big, can you tell me which file you want exactly or give me an email address?

**Comment by dgsudharsan** [comment]
Hi @xwjiang-ms In that case can you please attach the entire syslog file that contains this error message?

**Comment by xwjiang-ms** [comment]
Hi @dgsudharsan, log file uploaded and show techsupport refreshed, please take a look.

**Comment by dgsudharsan** [comment]
@xwjiang-ms This is a known firmware limitation. When techsupport is taken, it invokes fw dump. While taking the fw dump, the fw is busy and doesn't respond to other calls. The access of sfp eeprom happens through firmware and xcvrd gets the DOM fields every 60 seconds which fails during the fw dump. This is a temporary issue and this log can be ignored. Currently there is no fix available for this issue.

**Comment by xwjiang-ms** [comment]
OK, I will add code to ignore this msg, thanks @dgsudharsan

**Comment by dgsudharsan** [comment]
@xwjiang-ms Please let me know if we can close this bug?

**Comment by xwjiang-ms** [comment]
Hi @dgsudharsan, I got more error messages, are they all caused by this reason? If so, please tell me and close this bug, if anything not caused by this reason, please follow up.

E               Nov 12 04:38:42.742174 str2-msn4600c-acs-01 ERR kernel: [ 6447.571772] Fails to access (1) register MCIA (module:5, page:0, device_addr:195, size:1, i2c_addr:0x50, slot:0, status:0), err: -16.
E               
E               Nov 12 04:38:42.802785 str2-msn4600c-acs-01 ERR kernel: [ 6447.715753] Fails to read module eeprom, status: -16.
E               
E               Nov 12 04:38:42.869588 str2-msn4600c-acs-01 ERR kernel: [ 6447.776306] Fails to access (1) module eeprom, status: -16.
E               
E               Nov 12 04:38:42.869853 str2-msn4600c-acs-01 ERR pmon#xcvrd: Failed to read sfp=5 EEPROM page=/sys/module/sx_core/asic0/module5/eeprom/pages/0/i2c-0x50/data, page_offset=195,                     size=1, offset=195, error = [Errno 16] Device or resource busy
E               
E               Nov 12 04:38:42.970443 str2-msn4600c-acs-01 ERR kernel: [ 6447.889636] Fails to get module type, err: -16.
E               
E               Nov 12 04:38:42.970676 str2-msn4600c-acs-01 ERR pmon#xcvrd: Failed to read sfp=5 EEPROM page=/sys/module/sx_core/asic0/module5/eeprom/pages/0/i2c-0x50/data, page_offset=26,                     size=2, offset=26, error = [Errno 16] Device or resource busy
E               
E               Nov 12 04:38:43.166699 str2-msn4600c-acs-01 ERR kernel: [ 6447.996280] Fails to access (1) register MCIA (module:5, page:0, device_addr:220, size:1, i2c_addr:0x50, slot:0, status:0), err: -16.
E               
E               Nov 12 04:38:43.166727 str2-msn4600c-acs-01 ERR kernel: [ 6448.140180] Fails to read module eeprom, status: -16.
E               
E               Nov 12 04:38:43.294019 str2-msn4600c-acs-01 ERR kernel: [ 6448.200729] Fails to access (1) module eeprom, status: -16.
E               
E               Nov 12 04:38:43.294276 str2-msn4600c-acs-01 ERR pmon#xcvrd: Failed to read sfp=5 EEPROM page=/sys/module/sx_core/asic0/module5/eeprom/pages/0/i2c-0x50/data, page_offset=220,                     size=1, offset=220, error = [Errno 16] Device or resource busy
E               
E               Nov 12 04:38:43.487467 str2-msn4600c-acs-01 ERR kernel: [ 6448.319129] Fails to access (1) register MCIA (module:0, page:0, device_addr:0, size:1, i2c_addr:0x50, slot:0, status:0), err: -16.
E               
E               Nov 12 04:38:43.487478 str2-msn4600c-acs-01 ERR kernel: [ 6448.460961] Fails to read module eeprom, status: -16.
E               
E               Nov 12 04:38:43.614826 str2-msn4600c-acs-01 ERR kernel: [ 6448.521520] Fails to access (1) module eeprom, status: -16.
E               
E               Nov 12 04:38:43.698207 str2-msn4600c-acs-01 ERR kernel: [ 6448.617377] Fails to get module type, err: -16.
E               
E               Nov 12 04:38:43.698440 str2-msn4600c-acs-01 ERR pmon#xcvrd: Failed to read sfp=0 EEPROM page=/sys/module/sx_core/asic0/module0/eeprom/pages/0/i2c-0x50/data, page_offset=2,                     size=1, offset=2, error = [Errno 16] Device or resource busy
E               
E               Nov 12 04:38:43.889428 str2-msn4600c-acs-01 ERR kernel: [ 6448.718971] Fails to access (1) register MCIA (module:0, page:3, device_addr:128, size:8, i2c_addr:0x50, slot:0, status:0), err: -16.
E               
E               Nov 12 04:38:43.889441 str2-msn4600c-acs-01 ERR kernel: [ 6448.862920] Fails to read module eeprom, status: -16.
E               
E               Nov 12 04:38:44.016794 str2-msn4600c-acs-01 ERR kernel: [ 6448.923477] Fails to access (1) module eeprom, status: -16.
E

**Comment by xwjiang-ms** [comment]
@dgsudharsan I think you could close this issue, thanks for your help!
