### ISSUE TITLE
[PDDF] sfputil show lpmode will get error message

### ISSUE THREAD

**Issue by jostar-yang** [sonic-net/sonic-buildimage#12634]
#### Description

When cmd "sfputil show lpmode", console will dump error message. 
#### Steps to reproduce the issue:
1. Insert QSFP transceiver to port. 
2. Cmd "sfputil show lpmode" will get error message. 

3.

#### Describe the results you received:
Get below fail message,
File "/usr/local/lib/python3.9/dist-packages/sfputil/main.py", line 1064, in lpmode
    lpmode = platform_chassis.get_sfp(physical_port).get_lpmode()
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform_pddf_base/pddf_sfp.py", line 207, in get_lpmode
    power_set = self.get_power_set()
AttributeError: 'Sfp' object has no attribute 'get_power_set'

#### Describe the results you expected:
Cmd "sfputil show lpmode should get all port lpmode status (on or off). It can't get error message"

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by FuzailBrcm** [comment]
I am working on this issue.
