### ISSUE TITLE
FRR/zebra error messages for routes from kernel default table

### ISSUE THREAD

**Issue by Stephenxf** [sonic-net/sonic-buildimage#12753]
#### Description
With the patch from https://github.com/sonic-net/sonic-buildimage/pull/12018, the routes from kernel default table are ignored in function `netlink_route_info_fill()`. However, this change also introduces unwanted error messages with this sequence of function calls from FRR:

`zfpm_build_route_updates()` -> `zfpm_encode_route()` -> `zfpm_netlink_encode_route()` -> `netlink_route_info_fill()`

As `netlink_route_info_fill()` returns 0 for routes from default table, `zfpm_build_route_updates()` will throw out error messages, for instance, as follows:
```
Nov  9 23:08:05.996495 falco-test-dut01 DEBUG bgp#zebra[29]: FPM: netlink_route_info_fill: Discard default table route
Nov  9 23:08:05.996495 falco-test-dut01 ERR bgp#zebra[29]: zfpm_build_route_updates: Encoding Prefix: 0.0.0.0/0 No valid nexthops
Nov  9 23:08:05.996495 falco-test-dut01 DEBUG bgp#zebra[29]: FPM: netlink_route_info_fill: Discard default table route
Nov  9 23:08:05.996495 falco-test-dut01 ERR bgp#zebra[29]: zfpm_build_route_updates: Encoding Prefix: 172.21.47.0/24 No valid nexthops
Nov  9 23:08:05.997066 falco-test-dut01 DEBUG bgp#zebra[29]: FPM: netlink_route_info_fill: Discard default table route
Nov  9 23:08:05.997066 falco-test-dut01 ERR bgp#zebra[29]: zfpm_build_route_updates: Encoding Prefix: ::/0 No valid nexthops
Nov  9 23:08:05.997066 falco-test-dut01 DEBUG bgp#zebra[29]: FPM: netlink_route_info_fill: Discard default table route
Nov  9 23:08:05.997066 falco-test-dut01 ERR bgp#zebra[29]: zfpm_build_route_updates: Encoding Prefix: fc00:2::/64 No valid nexthops
```

While these error messages are harmless functionally, they may cause one or more test failures. In our sanity, the test case `ipfwd/test_nhop_count.py` fails because the operation from the test case triggers the above call flow and then loganalyzer complains about the errors. 
```
LogAnalyzerError: {'match_messages': {'/tmp/syslog.falco-test-dut01.2022-11-11-17:41:17': ['Nov 11 17:45:29.940308 falco-test-dut01 ERR bgp#zebra[35]: zfpm_build_route_updates: Encoding Prefix: 0.0.0.0/0 No valid nexthops\n', 'Nov 11 17:45:29.940875 falco-test-dut01 ERR bgp#zebra[35]: zfpm_build_route_updates: Encoding Prefix: 172.21.47.0/24 No valid nexthops\n', 'Nov 11 17:45:29.941207 falco-test-dut01 ERR bgp#zebra[35]: zfpm_build_route_updates: Encoding Prefix: ::/0 No valid nexthops\n', 'Nov 11 17:45:29.941535 falco-test-dut01 ERR bgp#zebra[35]: zfpm_build_route_updates: Encoding Prefix: fc00:2::/64 No valid nexthops\n']}, 'total': {'expected_match': 0, 'expected_missing_match': 0, 'match': 4}, 'match_files': {'/tmp/syslog.falco-test-dut01.2022-11-11-17:41:17': {'expected_match': 0, 'match': 4}}, 'expect_messages': {'/tmp/syslog.falco-test-dut01.2022-11-11-17:41:17': []}, 'unused_expected_regexp': []}
```

#### Steps to reproduce the issue:
1. Make sure there are routes in kernel table default, e.g., 0.0.0.0/0 or eth0 prefix.
2. Flap an active interface, which will trigger the above mentioned call flow.
3. Check FRR logs for the error messages.

#### Describe the results you received:
FRR/zebra error messages as shown above.

#### Describe the results you expected:
No FRR/zebra error messages.

#### Additional information you deem important (e.g. issue happens only occasionally):
Our SONiC code is based off 202012, but the FRR code here is same as the latest.

**Comment by theasianpianist** [comment]
Fixed by https://github.com/sonic-net/sonic-buildimage/pull/12912
