### ISSUE TITLE
[eventd] "ERR:The eventd service started" in logs

### ISSUE THREAD

**Issue by romanvasylys** [sonic-net/sonic-buildimage#12787]
#### Description

Recently we have "ERR:The eventd service started" shown in logs when starting/restarting eventd services due to [this message](https://github.com/sonic-net/sonic-buildimage/blob/6a54bc439a980c7fc10e7a74de6472ee7731f8a5/src/sonic-eventd/src/main.cpp#L10)

#### Steps to reproduce the issue:
1. docker restart eventd
2. sudo systemctl restart eventd.service

#### Describe the results you received:
"ERR:The eventd service started" in logs

#### Describe the results you expected:
There should be only one INFO log "The eventd service started"

#### Output of `show version`:

```
SONiC Software Version: SONiC.master.162651-dirty-20221019.104245
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: ef0559c03
Build date: Wed Oct 19 17:40:59 UTC 2022
Built by: AzDevOps@sonic-build-workers-0029EO

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zbud-msft** [comment]
Fixed via https://github.com/sonic-net/sonic-buildimage/pull/16166
