### ISSUE TITLE
[ecmp-fgnhg] ipv6 hash has more then 30% deviation between neighbors

### ISSUE THREAD

**Issue by AntonHryshchuk** [sonic-net/sonic-buildimage#12799]
#### Description

ptf test output: 

15:03:19.550  root      : INFO    : Received packet at 25
15:03:19.550  root      : INFO    : port 41 exp_flows 125 num_flows 108 deviation 0.136
15:03:19.550  root      : INFO    : port 53 exp_flows 125 num_flows 135 deviation 0.08000000000000007
15:03:19.550  root      : INFO    : port 54 exp_flows 125 num_flows 123 deviation 0.016000000000000014
15:03:19.550  root      : INFO    : port 57 exp_flows 125 num_flows 115 deviation 0.07999999999999996
15:03:19.550  root      : INFO    : port 24 exp_flows 125 num_flows 123 deviation 0.016000000000000014
15:03:19.550  root      : INFO    : port 25 exp_flows 125 num_flows 110 deviation 0.12
15:03:19.550  root      : INFO    : port 26 exp_flows 125 num_flows 162 deviation 0.29600000000000004
 

test exception:
 

        "======================================================================", 
        "FAIL: fg_ecmp_test.FgEcmpTest", 
        "----------------------------------------------------------------------", 
        "Traceback (most recent call last):", 
        "  File \"ptftests/py3/fg_ecmp_test.py\", line 557, in runTest", 
        "    self.fg_ecmp()", 
        "  File \"ptftests/py3/fg_ecmp_test.py\", line 421, in fg_ecmp", 
        "    self.test_balancing(hit_count_map)", 
        "  File \"ptftests/py3/fg_ecmp_test.py\", line 198, in test_balancing", 
        "    assert deviation <= self.max_deviation", 
        "AssertionError", 
        "", 
        "----------------------------------------------------------------------", 
        "Ran 1 test in 26.782s", 
        "", 
        "FAILED (failures=1)"
    ], 
    "stdout": "Using packet manipulation module: ptf.packet_scapy\n\n******************************************\nATTENTION: SOME TESTS DID NOT PASS!!!\n\nThe following tests failed:\nFgEcmpTest\n\n******************************************", 
    "stdout_lines": [
        "Using packet manipulation module: ptf.packet_scapy", 
        "", 
        "******************************************", 
        "ATTENTION: SOME TESTS DID NOT PASS!!!", 
        "", 
        "The following tests failed:", 
        "FgEcmpTest",

#### Steps to reproduce the issue:
1. run test_fgnhg test:
/usr/local/bin/py.test /root/mars/workspace/sonic-mgmt/tests/ecmp/test_fgnhg.py::test_fg_ecmp --inventory="../ansible/inventory,../ansible/veos" --host-pattern r-tigon-04 --module-path ../ansible/library/ --testbed r-tigon-04-t0-64 --testbed_file ../ansible/testbed.csv --allow_recover  --junit-xml junit_6162841_0.7.1.1.5.1.1.2.1.1.1.xml --assert plain --log-cli-level info --show-capture=no -ra --showlocals -v --clean-alluredir --alluredir=/tmp/allure-results  --topology t0,any,util --skip_sanity

**Describe the results you received:**
test failed with exception:
assert deviation <= self.max_deviation

**Describe the results you expected:**
test pass

#### Output of `show version`:

```
SONiC-OS-202111_rc_19_22062022.1-ebfccd4d2_Internal
```

#### Additional information you deem important (e.g. issue happens only occasionally):

Reproduced on t0 and t0-64 topology.

**Comment by nazariig** [comment]
@anish-n FYI

**Comment by AntonHryshchuk** [comment]
**Summary of Investigation**
- Investigate all HW Configuration aspects
- Different ECMP Next Hop table structure
- Traffic Parameters
- ECMP Hash Enable Configuration
**No Issues were found** 


Together with Arch team we proposed the following changes to the  test:
- Send 1000 packets randomized source IPv6 Bytes[0-13] (Bytes 14-15 fixed to ‘20d0’)
- Calculate the following
                  - Ei = expected # of packet hits on NHi (Next Hop Index -> shall be 125)
                  - Ai = actual # of packet hits on NHi
                  - deviation = abs(Ei – Ai) / Ei
- Repeat test 10,000 times
- Compare test results to simulation results (Arch Simulation calculates the expected percentage of fail tests allowed according to Max Deviation %)



**Expected Results**
Based on simulation the expected % of error scenario is ~2-2.5%
We performed the test using SDK Verification test and the results were as expected  
We performed the test on the original system and the results were as expected  (~2% of failures)
 


**Conclusion:**
A recommendation is to use the above test scenario to measure ECMP deviation

**Comment by AntonHryshchuk** [comment]
The issue moved to sonic-mgmt project:
https://github.com/sonic-net/sonic-mgmt/issues/7755
