### ISSUE TITLE
SFLOW configuration causes swss docker to exit in Broadcom TD3-X2 platform in 202205 release.

### ISSUE THREAD

**Issue by hari-selvam** [sonic-net/sonic-buildimage#12810]
#### Description:
'config sflow enable' command causes swss docker to exit after sflow feature is enabled by using 'config feature state sflow enabled' command.  Reason is as part of the sflow configuration, Broadcom tries to open the file /proc/bcm/knet_cb/psample/rate and it got failed since the file doesn't exists. psample-cb.o object file is responsible for loading '/proc/bcm/knet-cb/psample/rate' file. And this object file is not included  due to BUILD_PSAMPLE=1 flag is removed in the recent commit.
(https://github.com/sonic-net/sonic-buildimage/commit/8bc8b96c4a69cdb4357131b713bd6a2f916d7833). 

Before this commit, it was working fine. @saiarcot895 I couldn't find this issue is reported in this forum.

#### Steps to reproduce the issue:
1. Load 202205 community SONiC release build into broadcom TD3-X2 chipset device

2. Enable sflow feature by using 'config feature state sflow enabled ' command.

3. Ensure sflow docker is instantiated successfully before executing sflow rleated config commands by using 'docker ps' command.

4. And also check 'psample' module is installed in kernel by using 'lsmod | grep psample' command.

5. Enable sflow globally by using 'config sflow enable'. It invokes '_brcm_sai_port_proc_samplerate_set()' API in which  '/proc/bcm/knet-cb/psample/rate' file is opened for write operation. But it throws 'file not found' error and the swss docker is being stopped.

#### Describe the results you received:
'config sflow enable' command is failed and swss docker is stopped. ''/proc/bcm/knet-cb/' library is not loaded into kernel, since psample-cb.o object file is included only if BUILD_PSAMPLE flag is equal to 1. Hence we couldn't test SFLOW feature in the community SONIC 202205 release build. The same issue is seen in the latest master branch's image as well.

#### Describe the results you expected:
sflow configs should be added in its config_db and expects SFLOW feature works fine. 

#### Output of `show version`:
root@sonic:~# show version

SONiC Software Version: SONiC.last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750
Distribution: Debian 11.5
Kernel: 5.10.0-12-2-amd64
Build commit: 9c305301f
Build date: Tue Nov 22 23:03:04 UTC 2022
Built by: jemston@AZUHPSP08

Platform: x86_64-cel_belgite-r0
HwSKU: CELESTICA-BELGITE
ASIC: broadcom
ASIC Count: 1
Serial Number: E1070F2B071602BY200002
Model Number: R3059-F9010-01
Hardware Revision:
Uptime: 16:28:42 up  1:08,  1 user,  load average: 0.63, 0.55, 0.55
Date: Fri 23 Sep 2022 16:28:42

Docker images:
REPOSITORY                    TAG                                                                  IMAGE ID       SIZE
docker-orchagent              last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   a0abb5f4b4cc   478MB
docker-orchagent              latest                                                               a0abb5f4b4cc   478MB
docker-teamd                  last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   1b03fcbeb1ed   459MB
docker-teamd                  latest                                                               1b03fcbeb1ed   459MB
docker-fpm-frr                last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   c66e22039450   489MB
docker-fpm-frr                latest                                                               c66e22039450   489MB
docker-macsec                 latest                                                               b8d10053751b   461MB
docker-gbsyncd-broncos        last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   9add703b4bd9   490MB
docker-gbsyncd-broncos        latest                                                               9add703b4bd9   490MB
docker-syncd-brcm             last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   91477e30f24a   785MB
docker-syncd-brcm             latest                                                               91477e30f24a   785MB
docker-gbsyncd-credo          last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   925f61cddc07   461MB
docker-gbsyncd-credo          latest                                                               925f61cddc07   461MB
docker-dhcp-relay             latest                                                               8dbf0e3d3bd3   453MB
docker-platform-monitor       last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   c6d54f9d0cdf   568MB
docker-platform-monitor       latest                                                               c6d54f9d0cdf   568MB
docker-snmp                   last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   228550e0123c   488MB
docker-snmp                   latest                                                               228550e0123c   488MB
docker-mux                    last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   be0b40a74b46   492MB
docker-mux                    latest                                                               be0b40a74b46   492MB
docker-lldp                   last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   89d5fd669d5a   486MB
docker-lldp                   latest                                                               89d5fd669d5a   486MB
docker-database               last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   9407dab2faeb   443MB
docker-database               latest                                                               9407dab2faeb   443MB
docker-sonic-telemetry        last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   b9b77922c676   524MB
docker-sonic-telemetry        latest                                                               b9b77922c676   524MB
docker-router-advertiser      last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   b5e8a636eafc   443MB
docker-router-advertiser      latest                                                               b5e8a636eafc   443MB
docker-sflow                  last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   f282b5cf05b2   428MB
docker-sflow                  latest                                                               f282b5cf05b2   428MB
docker-nat                    last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   4efda088a050   430MB
docker-nat                    latest                                                               4efda088a050   430MB
docker-sonic-mgmt-framework   last_good_cls_comm_sonic_vs_staging_202205_0-dirty-20221122.210750   37d53f604c2b   557MB
docker-sonic-mgmt-framework   latest                                                               37d53f604c2b   557MB
root@sonic:~#

#### Additional information you deem important (e.g. issue happens only occasionally):

[sflow_config_202205_branch_issue_commands_dump_logs.txt](https://github.com/sonic-net/sonic-buildimage/files/10074049/sflow_config_202205_branch_issue_commands_dump_logs.txt)

**Comment by saiarcot895** [comment]
@adyeung 

Looks like in [`platform/broadcom/saibcm-modules/sdklt/linux/knetcb/ngknetcb_main.c` line 435](https://github.com/sonic-net/sonic-buildimage/blob/master/platform/broadcom/saibcm-modules/sdklt/linux/knetcb/ngknetcb_main.c#L435), psample initialization is done only when Broadcom's own psample kernel module support is enabled, even if the kernel's psample module is used as a dependency. Can this be changed to check for kernel support for psample (or maybe just unconditionally require it)?

**Comment by adyeung** [comment]
@saiarcot895 BRCM's copy of psample was removed earlier to use the kernel's psample module, I believe the dependency check can be changed/removed
@michaelli10 to help take a look

**Comment by hari-selvam** [comment]
@saiarcot895 @michaelli10 @adyeung : I have removed the PSAMPLE_SUPPORT flag check in this file and verified the SFLOW functionality of both COUNTER and FLOW samples. And also verified polling-interval, interval level sampling-rate configs and the samples' attributes.
Shall I proceed to raise a pull request for the same?   
Kindly advise further course of action.

**Comment by hari-selvam** [comment]
@saiarcot895 @michaelli10 @adyeung : A gentle reminder.

**Comment by michaelli10** [comment]
Hi @hari-selvam
Can you try adding an or condition for CONFIG_PSAMPLE to check for kernel support for psample?

**Comment by hari-selvam** [comment]
@michaelli10 : Thanks for your response. Replaced '#ifdef PSAMPLE_SUPPORT' check with '#if IS_ENABLED(CONFIG_PSAMPLE)' check in this file and its working as expected. 
Shall I proceed to raise a pull request for the same?

**Comment by michaelli10** [comment]
Sounds good.  Yes please raise the PR.

**Comment by hari-selvam** [comment]
@saiarcot895 @adyeung @michaelli10 : When I retested the fix with my fresh build, I have found the compilation itself is failed.  The same fix[Replaced '#ifdef PSAMPLE_SUPPORT' check with '#if IS_ENABLED(CONFIG_PSAMPLE) ] has to be added in "platform/broadcom/saibcm-modules/systems/linux/kernel/modules/knet-cb/knet-cb.c" file in addition to ngknetcb_main.c file and also "ifeq ($(BUILD_PSAMPLE),1)" conditional check should be removed to fix 'psample-cb.o' dependency issue for ngknetcb_main.c file compilation as follows.
```
_**+++ b/platform/broadcom/saibcm-modules/sdklt/linux/knetcb/Kbuild
@@ -17,10 +17,7 @@
 # A copy of the GNU General Public License version 2 (GPLv2) can
 # be found in the LICENSES folder.$
 #
-ifeq ($(BUILD_PSAMPLE),1)
-PSAMPLE_CFLAGS=-DPSAMPLE_SUPPORT
 PSAMPLE_CB_OBJS=psample-cb.o
-endif

 obj-m := linux_ngknetcb.o**_
```

Apologies for my earlier mistake and late findings.

Could you please review and provide me your valuable comments?

**Comment by michaelli10** [comment]
Can you try this in the Kbuild file?  Removing the conditional check for building psample-cb.o will fail if CONFIG_PSAMPLE is not enabled.


ifneq ($(CONFIG_PSAMPLE),)
PSAMPLE_CB_OBJS=psample-cb.o
endif

**Comment by hari-selvam** [comment]
@michaelli10 Yes, psample-cb.o build is failed with "ifneq ($(CONFIG_PSAMPLE),)" check, if  CONFIG_PSAMPLE is not enabled.

PFA for the diff file of this issue's fix. Kindly review the changes.
[sflow-swss-crash-issue-fix-diff.txt](https://github.com/sonic-net/sonic-buildimage/files/10131506/sflow-swss-crash-issue-fix-diff.txt)

If changes are fine, Shall I proceed with PR?

**Comment by michaelli10** [comment]
Looks fine.  Please proceed with the PR.  Thanks for testing it.

**Comment by hari-selvam** [comment]
@michaelli10 : Raised a PR[12918](https://github.com/sonic-net/sonic-buildimage/pull/12918). I couldn't able to add you as a reviewer. Kindly review the code changes. 
If possible, please let me know how to add you as a reviewer.
