### ISSUE TITLE
[CI] azure pipelines build logs are full of the same warning

### ISSUE THREAD

**Issue by guillaumelambert** [sonic-net/sonic-buildimage#13106]
./functions.sh script contains twice the command "git describe --tags". Azure pipelines currently retrieves the repository content by using a "git clone" or "git fetch" command with the option "--depth". When the depth is not enough sized to reach a tag in the "git log" history, "git describe --tags" generates on stderr the warning: "fatal: No names found, cannot describe anything."

https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything

During the build process, the functions.sh script is a lot consumed and this pointless warning appears in CI thousand lines w/o any added value.

This situation can be easily avoided by redirecting related commands stderr output to /dev/null.#### Steps to reproduce the issue:

**Comment by gechiang** [comment]
fix merged. closing...
