### ISSUE TITLE
BGP, teamd, dhcp-relay starts with a delay after an upgrade

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#13117]
#### Steps to reproduce the issue:
1. Upgrade from 202205 to master image
2. Observe that BGP, teamd, dhcp_relay start with a significant delay:

```
admin@anc-ali-t10:~$ docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED         STATUS         PORTS     NAMES
35ef5938740e   b72e99b9f3ee                         "/usr/bin/docker_ini…"   6 seconds ago   Up 4 seconds             dhcp_relay
b531d87c11ae   docker-fpm-frr:latest                "/usr/bin/docker_ini…"   8 seconds ago   Up 7 seconds             bgp
d5750996e280   docker-sonic-telemetry:latest        "/usr/local/bin/supe…"   2 minutes ago   Up 2 minutes             telemetry
bd98f9e3b2db   docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe…"   2 minutes ago   Up 2 minutes             mgmt-framework
464123660ea0   docker-snmp:latest                   "/usr/local/bin/supe…"   2 minutes ago   Up 2 minutes             snmp
1c96288afca9   docker-platform-monitor:latest       "/usr/bin/docker_ini…"   4 minutes ago   Up 4 minutes             pmon
9251d8a262f4   docker-lldp:latest                   "/usr/bin/docker-lld…"   4 minutes ago   Up 4 minutes             lldp
13d9f779720b   docker-router-advertiser:latest      "/usr/bin/docker-ini…"   5 minutes ago   Up 5 minutes             radv
452b305d83d5   docker-syncd-mlnx:latest             "/usr/local/bin/supe…"   5 minutes ago   Up 5 minutes             syncd
98068d56673f   docker-orchagent:latest              "/usr/bin/docker-ini…"   5 minutes ago   Up 5 minutes             swss
046eb3ab63a0   docker-eventd:latest                 "/usr/local/bin/supe…"   5 minutes ago   Up 5 minutes             eventd
08628d47da2f   docker-database:latest               "/usr/local/bin/dock…"   5 minutes ago   Up 5 minutes             database
```

Seems this is the PR that caused additional delay: https://github.com/sonic-net/sonic-buildimage/pull/11796.
#### Describe the results you received:
BGP, teamd start 5 min after swss

#### Describe the results you expected:
BGP, teamd start earlier on boot

#### Output of `show version`:

Version based on 14a5ec79147cfd25ee76031ecbd36332ea11d308

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by stephenxs** [comment]
this also failed warm reboot due to the delay.

**Comment by stephenxs** [comment]
In the PR it updated the logic to enable a feature in the FEATURE table in “init_cfg.json”: it reads some additional tables like “DEVICE_RUNTIME_METADATA” to determine whether bgp, teamd should be enabled or not.
The motivation of the PR, I think, is to determine whether the features should be enabled or not when the image is installed from scratch.
However, there is a building time logic that masks features according to the FEATURE table in “init_cfg.json” in [build_scripts/mask_disabled_services.py](https://github.com/sonic-net/sonic-buildimage/blob/master/files/build_scripts/mask_disabled_services.py) which is called by [sonic_debian_extension.j2](https://github.com/sonic-net/sonic-buildimage/blob/master/files/build_templates/sonic_debian_extension.j2#L958) which is called by build time script [build_debian.sh](https://github.com/sonic-net/sonic-buildimage/blob/master/build_debian.sh#L597)
As a result, the bgp and teamd services are masked from the image.
```
stephens@arc-build-server-2:/builds2/stephens/wip/202205/sonic-buildimage/fsroot-mellanox/etc/systemd/system$ ls {bgp*,teamd*} -l
lrwxrwxrwx 1 root root 9 Dec 15 16:41 bgp.service -> /dev/null
lrwxrwxrwx 1 root root 9 Dec 15 16:41 teamd.service -> /dev/null
```
When the DUT warm rebooted, nobody takes care of trhe services and they keep masked until 5 minutes later when sonic-host-services restarts the services on handling the FEATURE table.

The same syndrome can be observed in warm reboot flow, which causes ~5 minutes traffic drop in warm reboot.
