### ISSUE TITLE
Build test cases failed for the year changed from 2022 to 2023

### ISSUE THREAD

**Issue by xumia** [sonic-net/sonic-buildimage#13222]
#### Description

See https://dev.azure.com/mssonic/build/_build/results?buildId=196912&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=8d99be27-49d0-54d0-99b1-cfc0d47f0318

3 Failed UTs
```
[----------] 1 test from timestampFormatter
[ RUN      ] timestampFormatter.changeTimestampFormat
rsyslog_plugin_tests/rsyslog_plugin_ut.cpp:257: Failure
Expected equality of these values:
  "2022-07-20T10:09:40.230874Z"
  formattedTimestampOne
    Which is: "2023-07-20T10:09:40.230874Z"
rsyslog_plugin_tests/rsyslog_plugin_ut.cpp:262: Failure
Expected equality of these values:
  "2022-01-01T00:00:00.000000Z"
  formattedTimestampTwo
    Which is: "2023-01-01T00:00:00.000000Z"
```

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by xumia** [comment]
@renukamanavalan , could you please help fix it? Thanks.

**Comment by renukamanavalan** [comment]
@xumia  please assign to @zbud-msft

**Comment by xumia** [comment]
The fix is https://github.com/sonic-net/sonic-buildimage/pull/13241
