### ISSUE TITLE
[EVPN][fastboot] Fastboot doesn't work with EVPN

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#13245]
#### Description
Fastboot doesn't work with EVPN. When fastboot is done, the dataplane downtime is 110 sec which exceeds the requirement of 30 seconds for fastboot. The [HLD ](https://github.com/sonic-net/SONiC/blob/master/doc/vxlan/EVPN/EVPN_VXLAN_HLD.md)doesn't contain any details about fastboot interop with EVPN.

#### Steps to reproduce the issue:
1. Configure EVPN
2. Run traffic between the hosts
3. Perform fastboot.

#### Describe the results you received:
If fastboot is supported, EVPN downtime should be less than 30 seconds

#### Describe the results you expected:
Fastboot downtime was 110 seconds

#### Output of `show version`:

Latest 202205 Branch was used to check this functionality
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by adyeung** [comment]
EVPN fastboot is not supported. At the current state BGP GR will not work with ASIC and link reset, control plane, data plane have to be reestablished after fastboot, traffic cannot reconverge in less than 30s without major redesign. Will update the HLD on the limitation.
