### ISSUE TITLE
[logrotate]Logrotate sometimes is started before logrotate-config.service

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#13261]
#### Description
Recently a change was introduced to move logrotate from cronjob to systemd timer (https://github.com/sonic-net/sonic-buildimage/pull/12921) . After this we are noticing logrotate starts sometimes before the logrotate-config service is called.
Jan  3 19:30:11.159249 mtbc-sonic-03-2700 INFO logrotate[391]: error: error running shared postrotate script for '/var/log/mail.info
Jan  3 19:30:11.159326 mtbc-sonic-03-2700 INFO logrotate[391]: /var/log/mail.warn
Jan  3 19:30:11.159374 mtbc-sonic-03-2700 INFO logrotate[391]: /var/log/mail.err
Jan  3 19:30:11.159421 mtbc-sonic-03-2700 INFO logrotate[391]: /var/log/mail.log
Jan  3 19:30:11.159465 mtbc-sonic-03-2700 INFO logrotate[391]: /var/log/daemon.log
Jan  3 19:30:11.159508 mtbc-sonic-03-2700 INFO logrotate[391]: /var/log/kern.log
Jan  3 19:30:11.159552 mtbc-sonic-03-2700 INFO logrotate[391]: /var/log/user.log
Jan  3 19:30:11.159595 mtbc-sonic-03-2700 INFO logrotate[391]: /var/log/lpr.log
Jan  3 19:30:11.159651 mtbc-sonic-03-2700 INFO logrotate[391]: /var/log/debug
Jan  3 19:30:11.159696 mtbc-sonic-03-2700 INFO logrotate[391]: /var/log/messages
Jan  3 19:30:11.159740 mtbc-sonic-03-2700 INFO logrotate[391]: '
Jan  3 19:30:12.228207 mtbc-sonic-03-2700 NOTICE systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAI
Jan  3 19:30:12.228397 mtbc-sonic-03-2700 WARNING systemd[1]: logrotate.service: Failed with result 'exit-code'.
Jan  3 19:30:12.228566 mtbc-sonic-03-2700 ERR systemd[1]: Failed to start Rotate log files.

Jan  3 19:30:27.893673 mtbc-sonic-03-2700 INFO systemd[1]: Starting Update logrotate configuration...
Jan  3 19:30:31.000787 mtbc-sonic-03-2700 INFO systemd[1]: logrotate-config.service: Succeeded.
Jan  3 19:30:31.001746 mtbc-sonic-03-2700 INFO systemd[1]: Finished Update logrotate configuration.

Later when it runs it succeeds.

Jan  3 19:40:11.665245 mtbc-sonic-03-2700 INFO systemd[1]: logrotate.service: Succeeded.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[sysdump_sonic_dump_mtbc-sonic-03-2700_20230103_194622.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/10348229/sysdump_sonic_dump_mtbc-sonic-03-2700_20230103_194622.tar.gz)

**Comment by dgsudharsan** [comment]
@saiarcot895 FYI

**Comment by prgeor** [comment]
> @prgeor Any progress on this issue?

@dgsudharsan sorry, not yet started

**Comment by dgsudharsan** [comment]
@prgeor Any update on this issue?

**Comment by prgeor** [comment]
@dgsudharsan please verify. its fixed.

![image](https://github.com/sonic-net/sonic-buildimage/assets/45705344/c97ab3db-7f29-4c3c-9822-15481fe198b4)
