### ISSUE TITLE
CHASSISD 'SIG_TERM'/'KILL -15' pmon process KILL on supervisor card not working 

### ISSUE THREAD

**Issue by sanjair-git** [sonic-net/sonic-buildimage#13309]
#### Description
On Supervisor card, when '_chassisd_' pmon process is terminated using **SIG_TERM (KILL -15)** signal, chassisd process is never getting killed.

All other pmon process such as _'syseepromd', 'psud', 'pcied', 'thermalctld_' are getting terminated with SIG_TERM (KILL -15) signal on supervisor card but 'chassisd' process is not.

For example, following is the console output when the '_chassisd_' process is terminated on supervisor.

admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status **chassisd**
chassisd RUNNING pid 20, uptime 4 days, **18:36:32**
admin@ixre-cpm-chassis10:$
admin@ixre-cpm-chassis10:$ docker exec pmon bash -c '_kill -15 20_'
admin@ixre-cpm-chassis10:$

admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status _**chassisd**_
chassisd RUNNING pid 20, uptime 4 days, **19:24:14**
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status chassisd
chassisd RUNNING pid 20, uptime 4 days, **19:29:56**
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status chassisd
chassisd RUNNING pid 20, uptime 4 days, **19:29:59**
admin@ixre-cpm-chassis10:$

#### Steps to reproduce the issue:
1. Check the PID of chassisd process using, docker exec pmon supervisorctl status chassisd
2. Terminated the PID of chassisd by, docker exec pmon bash -c 'kill -15 20'
3. Check the new PID of chassisd by checking, docker exec pmon supervisorctl status chassisd

#### Describe the results you received:
- 'chassisd' process is expected to get a new PID after SIG_TERM termination.

#### Describe the results you expected:
- 'chassisd' process even after 60 minutes, not getting a new PID after SIG_TERM KILL.

#### Output of `show version`:

```
admin@ixre-cpm-chassis10:~$ show version

SONiC Software Version: SONiC.HEAD.371319-msft-2205-ndk-next-42251a6bb
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
Build commit: 42251a6bb
Build date: Fri Dec 30 23:36:07 UTC 2022
Built by: gitlab-runner@sonic-bld2

Platform: x86_64-nokia_ixr7250e_sup-r0
HwSKU: Nokia-IXR7250E-SUP-10-r0
ASIC: broadcom
ASIC Count: 16
Serial Number: 01211800009
Model Number: N/A
Hardware Revision: Unknown
Uptime: 19:34:14 up 6 days,  3:19,  1 user,  load average: 6.09, 5.85, 5.10
Date: Mon 09 Jan 2023 19:34:14

```

#### Additional information you deem important (e.g. issue happens only occasionally):

 **SIG_TERM KILL output of other pmon processes:**
_admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status syseepromd
syseepromd                       RUNNING   pid 22, uptime 4 days, 18:45:05
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ docker exec pmon bash -c 'kill -15 22'
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status syseepromd
syseepromd                       STARTING  
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status syseepromd
syseepromd                       STARTING  
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status syseepromd
syseepromd                       STARTING  
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status syseepromd
syseepromd                       STARTING  
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status syseepromd
syseepromd                       RUNNING   pid 1588488, uptime 0:00:10
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status psud
psud                             RUNNING   pid 1247180, uptime 3 days, 1:28:01
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ docker exec pmon bash -c 'kill -15 1247180'
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status psud
psud                             RUNNING   pid 1247180, uptime 3 days, 1:28:22
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status psud
psud                             RUNNING   pid 1247180, uptime 3 days, 1:28:25
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status psud
psud                             STARTING  
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status psud
psud                             STARTING  
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status psud
psud                             RUNNING   pid 1591573, uptime 0:00:10
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ docker exec pmon bash -c 'kill -15 23'
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status thernamctld
thernamctld: ERROR (no such process)
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status thermalctld
thermalctld                      RUNNING   pid 1583074, uptime 0:00:31
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status thermalctld
thermalctld                      RUNNING   pid 1583074, uptime 0:00:36
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status pcied
pcied                            RUNNING   pid 24, uptime 4 days, 18:44:24
admin@ixre-cpm-chassis10:$ docker exec pmon bash -c 'kill -15 24'
admin@ixre-cpm-chassis10:$ 
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status pcied
pcied                            STARTING  
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status pcied
pcied                            STARTING  
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status pcied
pcied                            STARTING  
admin@ixre-cpm-chassis10:$ docker exec pmon supervisorctl status pcied
pcied                            RUNNING   pid 1586686, uptime 0:00:13
admin@ixre-cpm-chassis10:$_

**Comment by judyjoseph** [comment]
@sanjair-git have PR's open for the same, planning to merge it soon https://github.com/sonic-net/sonic-platform-daemons/pull/328

**Comment by sanjair-git** [comment]
> @sanjair-git have PR's open for the same, planning to merge it soon [sonic-net/sonic-platform-daemons#328](https://github.com/sonic-net/sonic-platform-daemons/pull/328)

OK @judyjoseph , thanks.

**Comment by judyjoseph** [comment]
Closed with https://github.com/sonic-net/sonic-platform-daemons/pull/328
