### ISSUE TITLE
[Typo in bgp output] | Typo in "Neighbor" in show ip bgp summary output

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#13330]
#### Steps to reproduce the issue:
1. do "show ip bgp su"

#### Describe the results you received:
```
Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down      State/PfxRcd  NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.2       4  65100       3951       3951         0      0       0  05:28:59                1  10.0.0.2
```

Typo in word ```Neighbhor```

#### Describe the results you expected:
```
Neighbor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down      State/PfxRcd  NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.2       4  65100       3951       3951         0      0       0  05:28:59                1  10.0.0.2
```

#### Output of `show version`:

```
SONiC.202205_1_rc.7-97f441065_Internal
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by Blueve** [comment]
Thanks for pointing out this typo : D
This is the source code: https://github.com/sonic-net/sonic-utilities/blob/49fc3896a0ef907ff337467a3e04d2501ef850fd/utilities_common/bgp_util.py#L259

Since this typo existing for a long time and some automation system might rely on it, I suggest that only fix this issue in master branch.

**Comment by prsunny** [comment]
Agree with @Blueve , since this can break automation and is a legacy output, I suggest not to change it at all.

**Comment by neethajohn** [comment]
closing as per discussion in triage
