### ISSUE TITLE
platform_tests/api/test_sfp.py::test_get_tx_bias return results in dictionary format instead of list

### ISSUE THREAD

**Issue by rajann** [sonic-net/sonic-buildimage#13380]
#### Description

get_tx_bias platform test returns the results in the dictionary format instead of the list format with transceivers like 400GAUI-8 C2M

#### Steps to reproduce the issue:

 Execute platform test on transceiver type 400GAUI-8 C2M

 file="platform_tests/api/test_sfp.py"  name="test_get_tx_bias

#### Describe the results you received:

27/12/2022 14:13:19 sfp.sfp_api                              L0018 INFO   | Executing sfp API: "get_transceiver_info", index: 24, arguments: "[]", result: "{u'active_firmware': u'0.0', u'encoding': u'N/A', u'media_lane_count': 8, u'vendor_rev': u'02', u'host_electrical_interface': u'400GAUI-8 C2M (Annex 120E)', u'serial': u'AJ21190302      ', u'cable_length': 10.0, u'media_interface_technology': u'850 nm VCSEL', u'vendor_oui': u'a8-bc-9c', u'cmis_rev': u'4.0', u'connector': u'No separable connector', u'inactive_firmware': u'1.0', u'ext_identifier': u'Power Class 5 (10.0W Max)', u'media_interface_code': u'Active Cable assembly with BER < 5x10^-5', u'ext_rateselect_compliance': u'N/A', u'hardware_rev': u'1.1', u'type': u'QSFP-DD Double Density 8X Pluggable Transceiver', u'host_lane_count': 8, u'active_apsel_hostlane1': 1, u'nominal_bit_rate': 0, u'active_apsel_hostlane3': 1, u'active_apsel_hostlane2': 1, u'active_apsel_hostlane5': 1, u'active_apsel_hostlane4': 1, u'active_apsel_hostlane7': 1, u'active_apsel_hostlane6': 1, u'active_apsel_hostlane8': 1, u'type_abbrv_name': u'QSFP-DD', u'manufacturer': u'Cloud Light     ', u'application_advertisement': u"{1: {'host_electrical_interface_id': '400GAUI-8 C2M (Annex 120E)', 'module_media_interface_id': 'Active Cable assembly with BER < 5x10^-5', 'media_lane_count': 8, 'host_lane_count': 8, 'host_lane_assignment_options': 1, 'media_lane_assignment_options': 1}, 2: {'host_electrical_interface_id': 'CAUI-4 C2M (Annex 83E)', 'module_media_interface_id': 'Active Cable assembly with BER < 5x10^-5', 'media_lane_count': 8, 'host_lane_count': 8, 'host_lane_assignment_options': 1, 'media_lane_assignment_options': 1}}", u'specification_compliance': u'active_cable_media_interface', u'media_lane_assignment_option': 1, u'cable_type': u'Length Cable Assembly(m)', u'host_lane_assignment_option': 1, u'model': u'7123-G37-10     ', u'vendor_date': u'2021-05-22 '}"
27/12/2022 14:13:19 sfp.sfp_api                              L0018 INFO   | Executing sfp API: "get_tx_bias", index: 24, arguments: "[]", result: "{u'LaserBiasTx5Field': 7.404, u'LaserBiasTx2Field': 6.862, u'LaserBiasTx4Field': 6.926, u'LaserBiasTx6Field': 7.492, u'LaserBiasTx3Field': 6.946, u'LaserBiasTx8Field': 7.448, u'LaserBiasTx1Field': 6.988, u'LaserBiasTx7Field': 7.316}"

#### Describe the results you expected:

 Expected result of TX Bias data should be in the list format. But the results are in dictionary format.

#### Output of `show version`:

```
(SONiC Software Version: SONiC.azure_cisco_202205.2981-dirty-20221220.231152)
```

**Comment by rajann** [comment]
sonic_platform_base/sonic_xcvr/api/public/cmis.py

get_tx_bias() in the above file to be fixed to return the list

**Comment by prgeor** [comment]
@mihirpat1 could you please track this with an ADO

**Comment by mihirpat1** [comment]
> @mihirpat1 could you please track this with an ADO

Sure, have filed ADO for this.
