### ISSUE TITLE
[sflow]ERR sflow#hsflowd: device Loopback0 Get SIOCGIFFLAGS failed : No such device

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#13407]
#### Description

The above error log is seen sometimes when services startup. This happens due to a race condition between intfmgrd and hsflowd.
The intfmgrd removes loopback0 during init during which hsflowd tries to access
Jul 26 15:25:42.648253 r-anaconda-simx-137 NOTICE swss#intfmgrd: :- flushLoopbackIntfs: Remove loopback device Loopback0
Jul 26 15:25:42.884991 r-anaconda-simx-137 ERR sflow#hsflowd: device Loopback0 Get SIOCGIFFLAGS failed : No such device

#### Steps to reproduce the issue:
1. Perform config reload or reboot. 
2. The error is observed few times
3.

#### Describe the results you received:
Errors seen due to race condition

#### Describe the results you expected:
No errors should be seen during the service startup

#### Output of `show version`:

```
SONiC Software Version: SONiC.202205.18-f96f0e464_Internal
Distribution: Debian 11.4
Kernel: 5.10.0-12-2-amd64
Build commit: f96f0e464
Build date: Tue Jul 26 10:26:33 UTC 2022
Built by: sw-r2d2-bot@r-build-sonic-ci03-241

Platform: x86_64-mlnx_msn3700_simx-r0
HwSKU: ACS-MSN3700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1851X02961
Model Number: MSN3700-VS2F
Hardware Revision: N/A
Uptime: 15:27:13 up  1:01,  2 users,  load average: 2.66, 2.08, 1.44
Date: Tue 26 Jul 2022 15:27:13

Docker images:
REPOSITORY                                         TAG                            IMAGE ID       SIZE
docker-platform-monitor                            202205.18-f96f0e464_Internal   fb2691250282   993MB
docker-platform-monitor                            latest                         fb2691250282   993MB
docker-syncd-mlnx                                  202205.18-f96f0e464_Internal   799e1ec9d97f   989MB
docker-syncd-mlnx                                  latest                         799e1ec9d97f   989MB
docker-orchagent                                   202205.18-f96f0e464_Internal   3c02107364ee   474MB
docker-orchagent                                   latest                         3c02107364ee   474MB
docker-macsec                                      latest                         8e618920b78c   458MB
docker-dhcp-relay                                  latest                         a915d8edd99c   449MB
docker-mux                                         202205.18-f96f0e464_Internal   c6f7111d4dc7   489MB
docker-mux                                         latest                         c6f7111d4dc7   489MB
docker-router-advertiser                           202205.18-f96f0e464_Internal   7888a6630ce3   440MB
docker-router-advertiser                           latest                         7888a6630ce3   440MB
docker-database                                    202205.18-f96f0e464_Internal   9d5a94f1601d   440MB
docker-database                                    latest                         9d5a94f1601d   440MB
docker-sonic-telemetry                             202205.18-f96f0e464_Internal   ca982436b36f   520MB
docker-sonic-telemetry                             latest                         ca982436b36f   520MB
docker-sonic-mgmt-framework                        202205.18-f96f0e464_Internal   f1c737701e8d   554MB
docker-sonic-mgmt-framework                        latest                         f1c737701e8d   554MB
docker-snmp                                        202205.18-f96f0e464_Internal   bff1cd70dc83   453MB
docker-snmp                                        latest                         bff1cd70dc83   453MB
docker-fpm-frr                                     202205.18-f96f0e464_Internal   c271254f3761   454MB
docker-fpm-frr                                     latest                         c271254f3761   454MB
docker-sflow                                       202205.18-f96f0e464_Internal   e2bc22db0433   426MB
docker-sflow                                       latest                         e2bc22db0433   426MB
docker-teamd                                       202205.18-f96f0e464_Internal   35e167f3046e   425MB
docker-teamd                                       latest                         35e167f3046e   425MB
docker-nat                                         202205.18-f96f0e464_Internal   6445ad15143d   428MB
docker-nat                                         latest                         6445ad15143d   428MB
docker-lldp                                        202205.18-f96f0e464_Internal   5d0a93dc2688   450MB
docker-lldp                                        latest                         5d0a93dc2688   450MB
urm.nvidia.com/sw-nbu-sws-sonic-docker/sonic-wjh   1.3.0-202205-internal-10       048bc243d78e   492MB
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[sysdump_test_qos_reload_ports.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/10439941/sysdump_test_qos_reload_ports.tar.gz)

**Comment by sflow** [comment]
It's likely that the latest changes to hsflowd will avoid this race  (e.g. the release tagged as v2.0.51-25).  The new start up sequence waits first for the redis connections to come up,  then waits for the redis to indicate SYSTEM_READY|SYSTEM_STATE Status=Up,  and only then does it read the interfaces from Linux.

 I think it would still make sense to use the systemctl dependency tree to ensure that the sflow container is only started after the config has been fully populated in both Linux and redis,  but maybe that is not as easy as it sounds?

**Comment by dgsudharsan** [comment]
> It's likely that the latest changes to hsflowd will avoid this race (e.g. the release tagged as v2.0.51-25). The new start up sequence waits first for the redis connections to come up, then waits for the redis to indicate SYSTEM_READY|SYSTEM_STATE Status=Up, and only then does it read the interfaces from Linux.
> 
> I think it would still make sense to use the systemctl dependency tree to ensure that the sflow container is only started after the config has been fully populated in both Linux and redis, but maybe that is not as easy as it sounds?

What if the system is not ready due to some service like snmp, telemetry not starting or having some issues. This would lead to sflow not working at all even though all ports are created .I recommend having a timeout for system ready and starting sflow if we don't receive within the timeout.

Regarding adding dependency on service level, I think its possible and a simple change. I can make ensure sflow is delayed until ports are initialized.

**Comment by sflow** [comment]
I didn't realize that SYSTEM_READY could be held up so easily.  If sflow is not started until ports are initialized,  then we could probably remove the wait for SYSTEM_READY altogether.  However if you think a timeout is reasonable then we could add that instead as a compromise.  What is a sensible default. 1 minute?

**Comment by dgsudharsan** [comment]
> I didn't realize that SYSTEM_READY could be held up so easily. If sflow is not started until ports are initialized, then we could probably remove the wait for SYSTEM_READY altogether. However if you think a timeout is reasonable then we could add that instead as a compromise. What is a sensible default. 1 minute?

Since this is a negative scenario which may not be common, I suggest having a timeout of 3 minutes which could be the case for all applications to initialize

**Comment by sflow** [comment]
This suggestion has been implemented in hsflowd v2.0.51-26.  The default timeout is 180 seconds,  but it can be overridden in sflow:/etc/hsflowd.conf like this:

**sonic { waitReady=60 }**

**Comment by dgsudharsan** [comment]
@jeff-yin @venkatmahalingam @padmanarayana  Can you please help to update the sflow version so it contains the fix mentioned above?

**Comment by jeff-yin** [comment]
Please help assign the issue to @Gokulnath-Raja , thanks!

**Comment by dgsudharsan** [comment]
@zhangyanzhao can you please assign this issue to @Gokulnath-Raja . I can't find him under assignee list.

@Gokulnath-Raja  Please check the discussion above. We need to upgrade sflow version to get fixes for this issue

**Comment by Gokulnath-Raja** [comment]
@dgsudharsan @jeff-yin i will look into it.
