### ISSUE TITLE
[buildsystem]: Errors are seen during make execution

### ISSUE THREAD

**Issue by nazariig** [sonic-net/sonic-buildimage#13401]
#### Description

**Build system produces errors when building a SONiC target:**
```
user@server: sonic-buildimage$ SONIC_BUILD_JOBS=10 make target/docker-sonic-vs.gz
+++ --- Making target/docker-sonic-vs.gz --- +++
./scripts/run_with_retry make EXTRA_DOCKER_TARGETS=docker-sonic-vs.gz BLDENV=buster -f Makefile.work buster
./scripts/run_with_retry: line 4: [: : integer expression expected
```

#### Steps to reproduce the issue:
1. make `target/docker-sonic-vs.gz`

#### Describe the results you received:
```
./scripts/run_with_retry: line 4: [: : integer expression expected
```

#### Describe the results you expected:
No errors expected

#### Output of `show version`:
* N/A

#### Output of `show techsupport`:
* N/A

#### Additional information you deem important (e.g. issue happens only occasionally):

https://github.com/sonic-net/sonic-buildimage/blob/master/scripts/run_with_retry#L4
```
[ "$SONIC_BUILD_RETRY_COUNT" -gt 0 ] || SONIC_BUILD_RETRY_COUNT=0
```

**Comment by neethajohn** [comment]
@liushilongbuaa, is this issue fixed?
