### ISSUE TITLE
[yang]VRF yang model doesn't contain vni field

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#13456]
#### Description
VRF yang model doesn't contain VNI field. The VNI field is required for  EVPN configuration.
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-vrf.yang 

The VRF table schema as per EVPN HLD is below
https://github.com/sonic-net/SONiC/blob/master/doc/vxlan/EVPN/EVPN_VXLAN_HLD.md

;Existing table
;defines virtual routing forward table. Updated to stores VNI associated with VRF
;
;Status: stable

key = VRF_TABLE:VRF_NAME ;
fallback = "true"/"false"
vni = 1*8DIGIT ; VNI associated with VRF

#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you received:
VRF table doesn't contain vni

#### Describe the results you expected:
VRF table should contain vni field

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by dgsudharsan** [comment]
@srj102 @adyeung @zhangyanzhao FYI

**Comment by adyeung** [comment]
@tapashdas to post VNI support in sonic-vrf.yang

**Comment by tapashdas** [comment]
ETA : 02/17

**Comment by zhangyanzhao** [comment]
PR was merged and close this issue.
