### ISSUE TITLE
chassis: test_container_checker failure for swss/syncd/teamd on multi-asic Supervisor

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#13559]
#### Description

test_container_checker test fails for swss, syncd and teamd on Chassis supervisor.

The testcase calls, 'systemctl stop <service>' adn expects the docker associated with service goes down and container_checker to report 'Expected docker not running'.

container_checker process does not report the 'Expected docker not running' message for swss, syncd and teamd on Supervisor and the test cases fail.

Root cause:
The test case runs for all features and shuts down pmon service before swss/syncd/teamd. When pmon docker goes down, the CHASSIS_FABRIC_ASIC_TABLE entries also gets deleted.
The testcase does not start the pmon before running the test for next service.

When swss, syncd or teamd is tested and the service is stopped. The docker goes down. At this point container_checker script chcks for expected docker state. The container_cheaker depends on CHASSIS_FABRIC_ASIC_TABLE to provide the available asic list to calsulate the expected dockers but as pmon is down and the table is cleared from chassis db, asic information is not present. Due to this, container_checker does not include the swss, syncd, teamd services in the expected docker list and fails to report the error.

#### Steps to reproduce the issue:
1. Run container_checker/test_container_checker.py on Supervisor
2.
3.

#### Describe the results you received:
container_checker failed to report the 'Expected docker not running' error for swss, syncd, and teamd

#### Describe the results you expected:
container_checker should report these containers down after systemctl stop <service>

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
Hi @abdosi , @SuvarnaMeenakshi , FYI-

**Comment by rlhui** [comment]
@mlok-nokia would help address this, thanks.

**Comment by abdosi** [comment]
@mlok-nokia any update on this ? More than test case itself this is generic design issue
