### ISSUE TITLE
saidump on T2 results lua script to take more than 5 sec

### ISSUE THREAD

**Issue by abdosi** [sonic-net/sonic-buildimage#13561]
On T2  with more route scale we see LUA script: https://github.com/sonic-net/sonic-swss-common/blob/master/common/table_dump.lua invoked as part of saidump commands can take more than 5 sec and thus all other process start failing as no/incorrect reply from Redis.

Command
`generate_dump -s yesterday`

```
Jan 30 23:22:32.637122 str2-xxxx-lc1-3 INFO acms#start.py: start: main: Waiting for bootstrap cert
Jan 30 23:23:00.293090 str2-xxxx-lc1-3 DEBUG syncd0#saidump: :> main: enter
Jan 30 23:23:00.307986 str2-xxxx-lc1-3 INFO syncd0#saidump: :- loadRedisScript: lua script local keys = redis.call("KEYS", KEYS[1] .. ":*")#012local res = {}#012#012for i,k in pairs(keys) do#012   local sres={}#012#012   local flat_map = redis.call('HGETALL', k)#012   for j = 1, #flat_map, 2 do#012       sres[flat_map[j]] = flat_map[j + 1]#012   end#012#012   res[k] = sres#012end#012#012return cjson.encode(res)#012 loaded, sha: 654245aafba722f7b601e1fc414c3647058c053c
Jan 30 23:23:05.329309 str2-xxxx-lc1-3 INFO database0#supervisord: redis 39:M 30 Jan 2023 23:23:05.328 # Lua slow script detected: still in execution after 5021 milliseconds. You can try killing the script using the SCRIPT KILL command. Script SHA1 is: 654245aafba722f7b601e1fc414c3647058c053c
Jan 30 23:23:05.329391 str2-xxxxx-lc1-3 ERR gbsyncd0#GBSAI[18]: :- checkReplyType: Expected to get redis type 5 got type 6, err: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.

**Comment by abdosi** [comment]
cc @judyjoseph @arlakshm @anamehra for viz.

**Comment by zhenggen-xu** [comment]
@abdosi do you have a sense how many routes would be too much?  We could hit the issue in other layers too if this is related to route scale.

**Comment by gechiang** [comment]
@kcudnik please help investigate this. Thanks!

**Comment by kcudnik** [comment]
how big is the route table on this? and does it contain ipv6 prefixes ? it could be related to this: https://github.com/redis/redis/issues/8077

**Comment by rlhui** [comment]
> how big is the route table on this? and does it contain ipv6 prefixes ? it could be related to this: [redis/redis#8077](https://github.com/redis/redis/issues/8077), is this during warm reboot ? this is T2 so we don't do worm reboot there ? so this 5 seconds should not impact anything

@kcudnik  - there is no warm boot for T2.  the route table size is 32k ipv4, 32k ipv6.

**Comment by judyjoseph** [comment]
Looks like https://github.com/sonic-net/sonic-swss-common/blob/master/common/table_dump.lua is the lua script getting called -- which inturn go through the ASIC_DB for all routes for eg: and dump it.

So in case of T2 when we have more route entries in ASIC DB, this takes more CPU -- and swss times out 

Can we use the redis-db SAVE option to save the snapshot of DB each time and recover later, instead of looping trough each entry in table and saving it ? @kcudnik I can investigate a bit more in this direction

**Comment by kcudnik** [comment]
yes dump will take all objects including routes, how many of them there are? and why this is a problem if its takes 5sec? this is not T0

**Comment by mlok-nokia** [comment]
@kcudnik @judyjoseph Any progress on this issue?

**Comment by kcudnik** [comment]
please provide dump of all objects i requested

**Comment by rlhui** [comment]
> yes dump will take all objects including routes, how many of them there are? and why this is a problem if its takes 5sec? this is not T0

it takes much longer than 5 sec
