### ISSUE TITLE
201911 -> 202211 fast/warm-upgrade failure due to "unknown" compression

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#13568]
#### Description

Warm reboot fails due to failure in attempt to mount next image squashfs. This is needed for several things including asic config check, FW upgrade on Nvidia platform, etc. The compression algorithm was changed to ```zstd``` in 202211 but in 201911 this compression is not supported leading to errors and unability to perform warm reboot. Commit that introduced ```zstd```: https://github.com/sonic-net/sonic-buildimage/commit/d5365928d4dc1fa9081cf9fe61ab47e0ef306e9c

#### Steps to reproduce the issue:
1. boot 201911 image
2. install 202211 image
3. sudo warm-reboot -vvvf

#### Describe the results you received:

```
root@r-tigris-04:/home/admin# sonic_installer install 202211.bin -y
Image SONiC-OS-202211_RC_2.2-02e5d77ca_Internal is already installed. Setting it as default...
Command: grub-set-default --boot-directory=/host 1

Command: sync;sync;sync

Command: sleep 3

Done
root@r-tigris-04:/home/admin# fast-reboot
mount: wrong fs type, bad option, bad superblock on /dev/loop2,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

ERROR: no such file: /tmp/image-202211_RC_2.2-02e5d77ca_Internal-fs//etc/mlnx/fw-SPC2.mfa

root@r-tigris-04:/home/admin# echo $?
1
root@r-tigris-04:/home/admin# 
```

dmesg output:

```
admin@str-msn2700-22:~$ sudo dmesg | tail
[34260.312537] squashfs: SQUASHFS error: Filesystem uses "unknown" compression. This is not supported
```

#### Describe the results you expected:

Successful warm-reboot operation

#### Output of `show version`:

```
SONiC-OS-202211_RC_2.2-02e5d77ca_Internal
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by stepanblyschak** [comment]
Seems it is the same issue as in https://github.com/sonic-net/sonic-buildimage/issues/12171

**Comment by gechiang** [comment]
@stepanblyschak this is a known issue.  The upgrade path from 201911 to 202211 is not supported currently. it needs to be done step wise by first upgrade to 202012.

@stepanblyschak please consider move the firmware extraction to somewhere else as a resolution for this issue.
