### ISSUE TITLE
[master][Quanta] It can not use SAI mdio to access the PHY on Broadcom Tomahawk3 series

### ISSUE THREAD

**Issue by SLLU77** [sonic-net/sonic-buildimage#13577]
Description
I refer to this document https://github.com/sonic-net/SONiC/blob/master/doc/gearbox/gearbox_mdio-HLD.md.
The switch hardware design that the PHY could be connected to a switch NPU MDIO bus.
Execute the following two methods:
    1. Implement a program that connects to syncd through socket and use SAI mdio to access the PHY.
    2. Use 'socat' simulating the IPC client as an interactive command line shell to access the PHY mdio registers.
The result of both is that the Trident3 can access the PHY mdio registers, but the Tomahawk3 cannot.

Steps to reproduce the issue:
1. Install master branch image on Quanta devices
2. Run these commands in console 
docker exec -it syncd socat - UNIX-CONNECT:/var/run/sswsyncd/mdio-ipc.srv
mdio <address> <reg offset>

Describe the results you received:
Trident3 series:
root@sonic:/home/admin# docker exec -it syncd socat - UNIX-CONNECT:/var/run/sswsyncd/mdio-ipc.srv
mdio 0x81 0x02
0 0x600d
Tomahawk3 series:
root@sonic:/home/admin# docker exec -it syncd socat - UNIX-CONNECT:/var/run/sswsyncd/mdio-ipc.srv
mdio 0x81 0x02
0 0x0

Describe the results you expected:
Tomahawk3 series should get PHY ID like Trident3 series

**Comment by jiahua-wang** [comment]
To eliminate other hardware issue possibility, please compare the output from bcmsh and the output from the syncd ipc server socket. We know that bcmsh works very reliably.
For example, BCM84894 PHY PMA/PMD device identifier part 0 has DEVAD=1 and address=0x0002, part 1 has DEVAD=1 and address=0x0003, to read the both registers on PHY mdio address 0x52 using both bcmsh and ipc socket:
admin@sonic:~$ bcmsh

drivshell>phy raw c45 0x52 0x1 0x2
phy raw c45 0x52 0x1 0x2
	0x02: 0x3590
drivshell>phy raw c45 0x52 0x1 0x3
phy raw c45 0x52 0x1 0x3
	0x03: 0x50b1

admin@sonic:~$ docker exec -it syncd socat - UNIX-CONNECT:/var/run/sswsyncd/mdio-ipc.srv
mdio 0x52 0x10002
0 0x3590
mdio 0x52 0x10003
0 0x50b1

The outputs are the same for the same register. The bcmsh has register DEVAD and address as 2 arguments. The register address used in ipc socket is the concatenation of DEVAD and 16 bit address.

If both bcmsh and ipc socker outputs mismatch the expectation, you need to look into hardware, e.g. PHY mdio address, PHY register address and PHY reset signal.

If bcmsh output mismatch ipc socket output, we can look into TH3 SAI mdio implementation.

**Comment by SLLU77** [comment]
Thank you for the information. 
I really appreciate your help in resolving the problem.
