### ISSUE TITLE
queue counters are not getting populated for voq systems.

### ISSUE THREAD

**Issue by skbarista** [sonic-net/sonic-buildimage#13662]
#### Description

queuestat is returns no counters for both normal egress queue and voq counters.

#### Steps to reproduce the issue:
1. Enable queue counters
2. do a queuestat or queuestat -V and the counters are not populated.

#### Describe the results you received:

The counters were empty for egress queue counter and N/A for voq

#### Describe the results you expected:

Expected non zero counters for ports that were active.

**Comment by arlakshm** [comment]
potential fix in https://github.com/sonic-net/sonic-swss/pull/2653
