### ISSUE TITLE
[Discuss]Why there is little discussion about Netconf?

### ISSUE THREAD

**Issue by ljyfree** [sonic-net/sonic-buildimage#13725]
#### Description

As a universal northbound interface, why the SONiC community rarely discussed Netconf ?
Will Netconf be integrated into SONiC?

**Comment by arlakshm** [comment]
@adyeung , can you confirm in the sonic-mgmt.-framework has support for Netconf.

**Comment by adyeung** [comment]
sonic-mgmt-framework does not support netconf, there is no plan to add netconf in the future

**Comment by ljyfree** [comment]
Understood

**Comment by reisgabrieljoao** [comment]
There are references to netconf on the [Management Framework documentation](https://github.com/sonic-net/SONiC/blob/master/doc/mgmt/Management%20Framework.md):

"All Northbound API services like REST, GNMI, NETCONF invoke this App to read and write data through Translib API calls."

Are they inaccurate? netconf is not supported at all on Sonic?
