### ISSUE TITLE
[Issue/Question]: SONiC iptables & networking configurations for Docker 

### ISSUE THREAD

**Issue by Eric-Zaluzec-Vertiv** [sonic-net/sonic-buildimage#13738]
#### Description

A Docker container service, running on the SONiC OS, that is contacting an external server, is sending it's return address of the `docker_gwbridge` (i.e. 172.16.0.x) interface instead of the host system's address of the machine running the SONiC OS. This results in the external server not being able to respond or make incoming communication back to the machine running the SONiC OS.  (Test script and screenshot on bottom of this comment).

This behavior, on the SONiC OS, is different than what is observed when testing on different Linux distros running the Docker engine. Does the sonic-buildimage have custom Docker networking rules or configurations that are being applied? Are there any iptables rules that are dropped by the SONiC deployment of Docker? I'd like to know why there are missing iptable rules for DOcker on the SONiC OS.

Below are some observations made on the iptables shown on the SONiC OS and on a stock Linux distro. It appears like there are many iptable chains and rules that are not created by default for Docker on the SONiC OS. I was wondering if this was intended or if there was a way to configure these rules in the SONiC OS. Maybe in the sonic_db.json? The closest related issue I could find is, https://github.com/sonic-net/sonic-buildimage/issues/4797. 

**Iptable rules on SONiC OS**
```
~$ sudo iptables -t nat -S
	-P PREROUTING ACCEPT
	-P INPUT ACCEPT
	-P POSTROUTING ACCEPT
	-P OUTPUT ACCEPT

~$ sudo iptables -S
	-P INPUT ACCEPT
	-P FORWARD ACCEPT
	-P OUTPUT ACCEPT
	-N DOCKER-USER
	-A INPUT -s 127.0.0.1/32 -i lo -j ACCEPT
	-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
	...
	-A INPUT -p udp -m udp --dport 67:68 -j ACCEPT
	-A INPUT -p udp -m udp --dport 546:547 -j ACCEPT
	-A INPUT -p udp -m udp --dport 4789 -j ACCEPT
	-A INPUT -p tcp -m tcp --dport 179 -j ACCEPT
	-A INPUT -p tcp -m tcp --sport 179 -j ACCEPT
	...
	-A INPUT -m ttl --ttl-lt 2 -j ACCEPT
	-A FORWARD -j DOCKER-USER
	-A DOCKER-USER -j RETURN
```

**Iptable rules on multiple/different Linux OS**
```
~# iptables -t nat -S
	-P PREROUTING ACCEPT
	-P INPUT ACCEPT
	-P OUTPUT ACCEPT
	-P POSTROUTING ACCEPT
	-N DOCKER
	-N DOCKER-INGRESS
	-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER-INGRESS
	-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
	-A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER-INGRESS
	-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
	-A POSTROUTING -s 172.29.0.0/16 ! -o docker_gwbridge -j MASQUERADE
	-A POSTROUTING -o docker_gwbridge -m addrtype --src-type LOCAL -j MASQUERADE
	-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
	-A POSTROUTING -s 172.29.0.7/32 -d 172.29.0.7/32 -p tcp -m tcp --dport 2222 -j MASQUERADE
	-A POSTROUTING -s 172.29.0.29/32 -d 172.29.0.29/32 -p tcp -m tcp --dport 443 -j MASQUERADE
	-A POSTROUTING -s 172.29.0.30/32 -d 172.29.0.30/32 -p tcp -m tcp --dport 3871 -j MASQUERADE
	-A POSTROUTING -s 172.29.0.3/32 -d 172.29.0.3/32 -p tcp -m tcp --dport 4440 -j MASQUERADE
	-A DOCKER -i docker_gwbridge -j RETURN
	-A DOCKER -i docker0 -j RETURN
	-A DOCKER ! -i docker_gwbridge -p tcp -m tcp --dport 2222 -j DNAT --to-destination 172.29.0.7:2222
	-A DOCKER ! -i docker_gwbridge -p tcp -m tcp --dport 8880 -j DNAT --to-destination 172.29.0.29:443
	-A DOCKER ! -i docker_gwbridge -p tcp -m tcp --dport 3871 -j DNAT --to-destination 172.29.0.30:3871
	-A DOCKER ! -i docker_gwbridge -p tcp -m tcp --dport 4440 -j DNAT --to-destination 172.29.0.3:4440
	-A DOCKER-INGRESS -p tcp -m tcp --dport 4242 -j DNAT --to-destination 172.29.0.2:4242
	-A DOCKER-INGRESS -j RETURN

~# iptables -S
	-P INPUT DROP
	-P FORWARD DROP
	-P OUTPUT DROP
	-N DOCKER
	-N DOCKER-INGRESS
	-N DOCKER-ISOLATION-STAGE-1
	-N DOCKER-ISOLATION-STAGE-2
	-N DOCKER-USER
	...
	-A FORWARD -j DOCKER-USER
	-A FORWARD -j DOCKER-INGRESS
	-A FORWARD -j DOCKER-ISOLATION-STAGE-1
	-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
	-A FORWARD -o docker_gwbridge -j DOCKER
	-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
	-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
	-A FORWARD -o docker0 -j DOCKER
	-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
	-A FORWARD -i docker0 -o docker0 -j ACCEPT
	-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
	...
	-A DOCKER -d 172.29.0.7/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 2222 -j ACCEPT
	-A DOCKER -d 172.29.0.29/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 443 -j ACCEPT
	-A DOCKER -d 172.29.0.30/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 3871 -j ACCEPT
	-A DOCKER -d 172.29.0.3/32 ! -i docker_gwbridge -o docker_gwbridge -p tcp -m tcp --dport 4440 -j ACCEPT
	-A DOCKER-INGRESS -p tcp -m tcp --dport 4242 -j ACCEPT
	-A DOCKER-INGRESS -p tcp -m state --state RELATED,ESTABLISHED -m tcp --sport 4242 -j ACCEPT
	-A DOCKER-INGRESS -j RETURN
	-A DOCKER-ISOLATION-STAGE-1 -i docker_gwbridge ! -o docker_gwbridge -j DOCKER-ISOLATION-STAGE-2
	-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
	-A DOCKER-ISOLATION-STAGE-1 -j RETURN
	-A DOCKER-ISOLATION-STAGE-2 -o docker_gwbridge -j DROP
	-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
	-A DOCKER-ISOLATION-STAGE-2 -j RETURN
	-A DOCKER-USER -j RETURN
```         

If the missing iptable rules are applied to the SONiC OS, then the external server is shown to be given the correct return address of the machine running the SONiC OS, however the ephemeral port of the docker container service, contacting the server, is still lost. 

If this does **NOT** sound like a SONiC OS issue, then please let me know and I will close the issue. I just wanted to make sure that SONiC was not applying any networking configurations that would cause these iptable rules for Docker to be missing.  

#### Steps to reproduce the issue:
1. Deploy SONiC OS to machine
2. Deploy docker container running on the docker networking interface and start up a client tcp/udp communication program.
3. Have client communicate to external server. Have server output the address of the received communication.

#### Describe the results you received:
The iptables rules for Docker are missing. The docker container service contacting teh external server is giving the return address as the internal `docker_gwbridge` instead of the host system's network interface.

#### Describe the results you expected:
The docker container service contacting the external server should be MASQUERADING it's address and port to the host system's network interface address so the external server can contact back. This should be done through iptables.

#### Output of `show version`:

```
SONiC Software Version: SONiC.202006_134-38s
Distribution: Debian 10.12
Kernel: 4.19.0-6-2-amd64
Build commit: e0883b36f
Build date: Mon Jan 30 14:58:35 UTC 2023
Built by: ubuntu

Platform: x86_64-accton_as4630_54pe-r0
HwSKU: Accton-AS4630-54PE
ASIC: broadcom

```
```
Docker Version
Version:          18.09.8
```
#### Output of `show techsupport`:

```
N/A
```

#### Additional information you deem important (e.g. issue happens only occasionally):

![image](https://user-images.githubusercontent.com/65047813/217851913-935c1b01-8b47-49ac-aa1f-64479d1cf4e5.png)

**Test server/client script**
```
import socket
import sys

# udp_test.py server 161
# -- or --
# udp_test.py client 10.207.15.96 161

sock = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)

if sys.argv[1] == 'server':
    port = int(sys.argv[2])
    sock.bind(('', port))
    while True:
        message, address = sock.recvfrom(1024)
        print(f'Got "{message}" from {address}')
        sock.sendto(b'Responding to '+message, address)

else:
    host = sys.argv[2]
    port = int(sys.argv[3])
    sock.sendto(b'Testing 123', (host, port))
    print('Waiting on reply ...')
    message, address = sock.recvfrom(1024)
    print(f'Got "{message}" from {address}')
```

**Comment by Eric-Zaluzec-Vertiv** [comment]
A little more info on this if anyone can help. 
I found that there exists an `/etc/systemd/system/docker.service` file that overrides the `/lib/systemd/system/docker.service` file. In the service file under `/etc/`, it states `ExecStart=/usr/bin/dockerd -H unix:// --storage-driver=overlay2 --bip=240.127.1.1/24  --iptables=false`. 

When the `--iptables=false` is removed, I see that the iptable rules get created **BUT** one of the SONiC docker containers is then clearing the iptables rules before adding it's custom iptables. Any idea who's the culprit and if this behavior is necessary? 
These are the SONiC docker containers that I have running:
```
721e98b1159a        docker-syncd-brcm:latest                   "/usr/bin/supervisord"   3 weeks ago         Up 4 minutes                                            syncd
aea3c0d76b2c        docker-teamd:latest                        "/usr/bin/supervisord"   3 weeks ago         Up 4 minutes                                            teamd
19b5eb84ef5b        docker-orchagent:latest                    "/usr/bin/docker-ini…"   3 weeks ago         Up 4 minutes                                            swss
89ef8543a0c4        docker-platform-monitor:latest             "/usr/bin/docker_ini…"   3 weeks ago         Up 4 minutes                                            pmon
581bdd35c98c        docker-fpm-frr:latest                      "/usr/bin/docker_ini…"   3 weeks ago         Up 4 minutes                                            bgp
5558368928d5        docker-database:latest                     "/usr/local/bin/dock…"   3 months ago        Up 4 minutes                                            database
```

**Comment by arlakshm** [comment]
On sonic devices with single asic device the docker service is running in the host networking. There is no docker bridge configured. How is the docker bridge configured?
