### ISSUE TITLE
[build] libsairedis takes 1.5h to build (used to be 3-4 min in the past)

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#13775]
#### Steps to reproduce the issue:
1. make -f slave.mk target/debs/bullseye/libsairedis_1.0.0_amd64.deb
2.
3.

#### Describe the results you received:

It takes 1.5h to build

#### Describe the results you expected:

202019/202012 libsairedis can be built in 3-4 minutes.

#### Output of `show version`:

14012cfcf600184c69a0954715ae216847cad414 (master)

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by saiarcot895** [comment]
Could you elaborate on where you're seeing the 1.5-hour build time? The most recent commit in sairedis was [built in 25 minutes](https://dev.azure.com/mssonic/build/_build/results?buildId=217898&view=results), which is still high, IMO, but much less than 1.5 hours.

**Comment by saiarcot895** [comment]
Could you also check to see if sonic-net/sonic-sairedis#1194 results in any improvement? Note that testing this PR as part of the full sonic build will require some additional changes (specifically, the build profiles will need to be set instead of build targets).

**Comment by stepanblyschak** [comment]
@saiarcot895 I am not measuring CI build, if I do ```make -f slave.mk target/debs/bullseye/libsairedis_1.0.0_amd64.deb``` once all dependencies of libsairedis are compiled it takes for me almost 1.5 h

**Comment by mikeberesford** [comment]
We are seeing an increase in sairedis build time after migrating to 202211 that may be related here as well - our local builds went from ~25 mins to ~50 mins, which appears to be mostly time spent in SWIG.
