### ISSUE TITLE
[build] Error seen when running make from slave container

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#13773]
#### Steps to reproduce the issue:
1.BLDENV=bullseye make -f Makefile.work sonic-slave-bash
2.stepanb@877418bb93ab:/sonic$ time make -f slave.mk target/debs/bullseye/libsairedis_1.0.0_amd64.deb
SONiC Build System

Build Configuration
"CONFIGURED_PLATFORM"             : "mellanox"
"CONFIGURED_ARCH"                 : "amd64"
"SONIC_CONFIG_PRINT_DEPENDENCIES" : ""
"SONIC_BUILD_JOBS"                : "1"
"SONIC_CONFIG_MAKE_JOBS"          : "12"
"USE_NATIVE_DOCKERD_FOR_BUILD"    : ""
"SONIC_USE_DOCKER_BUILDKIT"       : ""
"USERNAME"                        : "admin"
"PASSWORD"                        : "YourPaSsWoRd"
"ENABLE_DHCP_GRAPH_SERVICE"       : ""
"SHUTDOWN_BGP_ON_START"           : ""
"ENABLE_PFCWD_ON_START"           : ""
"SONIC_BUFFER_MODEL"              : "dynamic"
"INSTALL_DEBUG_TOOLS"             : ""
"ROUTING_STACK"                   : "frr"
"FRR_USER_UID"                    : "300"
"FRR_USER_GID"                    : "300"
"ENABLE_SYNCD_RPC"                : ""
"SAITHRIFT_V2"                    : ""
"ENABLE_ORGANIZATION_EXTENSIONS"  : "y"
"HTTP_PROXY"                      : ""
"HTTPS_PROXY"                     : ""
"NO_PROXY"                        : ""
"ENABLE_ZTP"                      : ""
"INCLUDE_PDE"                     : ""
"SONIC_DEBUGGING_ON"              : ""
"SONIC_PROFILING_ON"              : ""
"KERNEL_PROCURE_METHOD"           : "build"
"BUILD_TIMESTAMP"                 : ""
"BUILD_LOG_TIMESTAMP"             : "none"
"SONIC_IMAGE_VERSION"             : "master.0-3c1c7e23b"
"BLDENV"                          : "bullseye"
"VS_PREPARE_MEM"                  : "yes"
"INCLUDE_MGMT_FRAMEWORK"          : "y"
"INCLUDE_ICCPD"                   : "n"
"INCLUDE_SYSTEM_TELEMETRY"        : "y"
"ENABLE_HOST_SERVICE_ON_START"    : "n"
"INCLUDE_RESTAPI"                 : "n"
"INCLUDE_SFLOW"                   : "y"
"ENABLE_SFLOW_DROPMON"            : "n"
"INCLUDE_NAT"                     : "y"
"INCLUDE_DHCP_RELAY"              : "y"
"INCLUDE_P4RT"                    : "y"
"INCLUDE_KUBERNETES"              : "n"
"INCLUDE_KUBERNETES_MASTER"       : "n"
"INCLUDE_MACSEC"                  : "y"
"INCLUDE_MUX"                     : "y"
"INCLUDE_TEAMD"                   : "y"
"INCLUDE_ROUTER_ADVERTISER"       : "y"
"INCLUDE_BOOTCHART                : "y"
"ENABLE_BOOTCHART                 : "n"
"ENABLE_FIPS_FEATURE"             : "y"
"ENABLE_TRANSLIB_WRITE"           : ""
"ENABLE_NATIVE_WRITE"             : ""
"ENABLE_AUTO_TECH_SUPPORT"        : "y"
"PDDF_SUPPORT"                    : "y"
"MULTIARCH_QEMU_ENVIRON"          : ""
"SONIC_VERSION_CONTROL_COMPONENTS": "none"
"ENABLE_ASAN"                     : "n"
"DEFAULT_CONTAINER_REGISTRY"      : ""
"CROSS_BUILD_ENVIRON"             : ""
"GZ_COMPRESS_PROGRAM"             : ""

**cp: cannot stat 'amd64/buildinfo/*': No such file or directory**
"SONIC_DPKG_CACHE_METHOD"         : "none"

[ 01 ] [ target/debs/bullseye/libnl-3-200_3.5.0-1_amd64.deb ]

#### Describe the results you received:
**cp: cannot stat 'amd64/buildinfo/*': No such file or directory**

#### Describe the results you expected:
Clean output without errors.

#### Output of `show version`:

14012cfcf600184c69a0954715ae216847cad414 (master)

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment]
@xumia Xuhui to take a look, this is with master image.

**Comment by xumia** [comment]
The variable is passed from the Makefile.work, see https://github.com/sonic-net/sonic-buildimage/blob/96817c4357a4b61ee483444984d5a2ebf6768162/Makefile.work#L550
