### ISSUE TITLE
[PDDF] Enhance pddf_eeprom to use cache

### ISSUE THREAD

**Issue by jostar-yang** [sonic-net/sonic-buildimage#13835]
#### Description

1.  sonic_platform_base/sonic_eeprom has provide cache for access eeprom. If pddf can enhance to use cache, performance to access sys-eeprom will better on some machine.
2. Some users find below error message, 
admin@sonic:~$ show interfaces status
Unable to initialize syseeprom - OSError("Failed to read eeprom : [Errno 13] Permission denied: '/sys/bus/i2c/devices/i2c-0/0-0056/eeprom'")  Interface            Lanes    Speed    MTU    FEC          Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  -----  -------------  ------  ------  -------  ------  ----------
  Ethernet0      73,74,75,76     100G   9100    N/A    Eth1(Port1)  routed    down     down     N/A         N/A
  Ethernet8      65,66,67,68     100G   9100    N/A    Eth2(Port2)  routed    down     down     N/A         N/A

When user cmd “show interface” that call sonic_platform and pddf_eeprom __init()__. It will do “read_eeprom”. Then dump error message due to at24/eeprom  need sudo user permission.
If modify eeprom.py to use cache, it will fix the issue. Because admin user will access /var/cache/sonic/decode-syseeprom.

#### Steps to reproduce the issue:
show interfaces status on admin user

Unable to initialize syseeprom - OSError("Failed to read eeprom : [Errno 13] Permission denied: '/sys/bus/i2c/devices/i2c-0/0-0056/eeprom'")  Interface            Lanes    Speed    MTU    FEC          Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  -----  -------------  ------  ------  -------  ------  ----------
  Ethernet0      73,74,75,76     100G   9100    N/A    Eth1(Port1)  routed    down     down     N/A         N/A
#### Describe the results you received:

 Interface            Lanes    Speed    MTU    FEC          Alias    Vlan    Oper    Admin    Type    Asym PFC
-----------  ---------------  -------  -----  -----  -------------  ------  ------  -------  ------  ----------
  Ethernet0      73,74,75,76     100G   9100    N/A    Eth1(Port1)  routed    down     down     N/A         N/A
#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by jostar-yang** [comment]
@FuzailBrcm , please help check. Thanks.

**Comment by FuzailBrcm** [comment]
Please assign this defect to me
