### ISSUE TITLE
[Chassis] container_checker failed on supervisor because lldp7 was not stopped.

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#13941]
#### Description

We encountered the following containter_checker failure on supervisor after deploy minigraph of T2 testing. lldp7 should be stopped since has_per_asic_scope of lldp feature was False.

```
admin@cmp235:~$ container_checker 
Unexpected running containers: lldp7

admin@cmp235:~$ sonic-db-cli CONFIG_DB hgetall "FEATURE|lldp"
{'has_per_asic_scope': 'False', 'has_timer': 'True', 'high_mem_alert': 'disabled', 'has_global_scope': 'True', 'state': 'enabled', 'auto_restart': 'enabled'}
```

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ysmanman** [comment]
Add @arlakshm @wenyiz2021 for visibility.

**Comment by wenyiz2021** [comment]
Hi @ysmanman ,do you still see this issue?
I don't see it from our side:

```
admin@str2-arista-sup-1:~$ docker  ps -a | grep lldp7
38b7b95c5017   docker-lldp:latest                "/usr/bin/docker-lld…"   4 days ago   Exited (0) 4 days ago               lldp7
```

**Comment by ysmanman** [comment]
We hadn't seen the issue anymore in our recent T2 202205 testing.
