### ISSUE TITLE
target/docker-sonic-vs.gz building buster image on master branch

### ISSUE THREAD

**Issue by Ndancejic** [sonic-net/sonic-buildimage#13970]
#### Description

docker-sonic-vs.gz docker image is buster in all of the latest builds:

#### Steps to reproduce the issue:
1. pull latest docker-sonic-vs image from any recent pipeline build
2. docker load < docker-sonic-vs.gz
3. docker run --privileged -v /var/run/redis-vs/sw:/var/run/redis --network container:sw -d --name vs docker-sonic-vs:latest
4. docker exec -it vs bash
5. cat /etc/os-release

#### Describe the results you received:
```
root@ecf0e3fc796c:/# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

#### Describe the results you expected:
VERSION_CODENAME=bullseye

**Comment by saiarcot895** [comment]
This will be covered by #11706.
