### ISSUE TITLE
[yang] Need Yang for NEIGH table

### ISSUE THREAD

**Issue by ganglyu** [sonic-net/sonic-buildimage#13971]
#### Description

We don't have Yang model for NEIGH table.

#### Steps to reproduce the issue:
1. Run build pipeline for below PR:
https://github.com/sonic-net/sonic-buildimage/pull/10963
2. Check build log:
sonic_yang(6):Note: Below table(s) have no YANG models: TUNNEL, FG_NHG_MEMBER, FG_NHG, NEIGH

#### Describe the results you received:
sonic-config-engine unit test failed.

#### Describe the results you expected:
sonic-config-engine unit test should pass.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ganglyu** [comment]
@prsunny

**Comment by zhangyanzhao** [comment]
@prsunny  can you please help to take a look at this PR? This is blocking us to enable the feature to block new features w/o YANG model defined but with Config_DB change. Thanks.

**Comment by prsunny** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/14521
