### ISSUE TITLE
Problem with Interface LEDs on Dell S5248-ON

### ISSUE THREAD

**Issue by ham-xa** [sonic-net/sonic-buildimage#14196]
#### Description
I'm using a Dell S5248-ON switch. I've installed SONiC.master.207726-940e2cd9b on it. 
The problem is that all interface lights are on (green) despite the fact I'm only using 4 Interfaces. 

Only those LEDs should be on whose interfaces are being used.

#### Output of `show version`:
![image](https://user-images.githubusercontent.com/92853499/224230573-296fbbcd-b616-4064-885f-9ef01457082a.png)

#### Additional information you deem important (e.g. issue happens only occasionally):
I've also faced another issue with the warm boot this happens on its own without giving any prompt. 
![image](https://user-images.githubusercontent.com/92853499/224291208-ba71d2ae-f0cc-40cd-9ed9-6879d6b50346.png)

**Comment by ham-xa** [comment]
@zhangyanzhao can you assign someone to this issue?

**Comment by Seitanas** [comment]
Hello, having the same issue with `S5248F-ON`. Any ideas what could be causing this?

**Comment by jeff-yin** [comment]
@aravindmani-1  -- do the LED bin files need to be updated? I believe there may have been BCM SDK changes that may have invalidated the old LED microcode behavior.

**Comment by Seitanas** [comment]
Hello, any updates on this?

**Comment by aravindmani-1** [comment]
@Seitanas @ham-xa Please wait till https://github.com/sonic-net/sonic-buildimage/pull/15790 gets merged.
