### ISSUE TITLE
Chassis: ERR lldp#lldpmgrd[31]: Port init timeout reached (300 seconds), resuming lldpd...

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#14251]
#### Description

Following error is observed after boot or config reload for global lldp docker on multi-asic system:

ERR lldp#lldpmgrd[31]: Port init timeout reached (300 seconds), resuming lldpd...

This does not impact functionality but causes test failures when log analyzer is enabled.

This looks like due to the fact that global config db does not have any ports to initialize. All ports belong to namespaces.

#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you received:
ERR lldp#lldpmgrd[31]: Port init timeout reached (300 seconds), resuming lldpd...

#### Describe the results you expected:
ERR not expected as log analyzer fails the test on ERR.

#### Output of `show version`:
Observed on 202205 but should be present in master as well as code is same. Last tested 202205 sha1 0a354c5

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
Hi @abdosi , raised this for lldp error causing sonic-mgmt autorestart tests failure.

**Comment by rlhui** [comment]
@anamehra can help to add change in sonic-mgmt to ignore this, as it's harmless, but @abdosi will double-check.

**Comment by anamehra** [comment]
> @anamehra can help to add change in sonic-mgmt to ignore this, as it's harmless, but @abdosi will double-check.

Hi @abdosi , any comment on this? Should we add this to ignore list? Thanks!

**Comment by mlok-nokia** [comment]
@abdosi  @anamehra I have a PR for this

**Comment by mlok-nokia** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/14814
