### ISSUE TITLE
[AAA | RADIUS] | root login is done using local even if local is disabled

### ISSUE THREAD

**Issue by Hedgehog-Guru** [sonic-net/sonic-buildimage#14278]
#### Description

root authentication is done against local even if AAA configuration has local auth disabled

#### Steps to reproduce the issue:
1. Set root password to some known value
passwd root
2. Configure any IP as RADIUS server. It must be down or unreachable
config radius add -k test 6.6.6.6
3. Enable authentication using RADIUS only  (local is disabled)
config aaa authentication login radius
4.a. Try to login with root user/pass to switch console  OR
4.b.  Fix sshd config to allow root login via ssh
echo "PermitRootLogin yes" >> sshd_config
systemctl restart sshd
Try to login to switch via ssh with root user/pass
5. If success check local username with "id" or "whoami"

#### Describe the results you received:
Local login is success even if only RADIUS is enabled

#### Describe the results you expected:
Root login is forbidden because it must be done against local which is disabled.

#### Output of `show version`:

```
SONiC Software Version: SONiC.202211_RC7.1-a99614f41_Internal
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
Build commit: a99614f41
Build date: Sun Mar  5 18:03:39 UTC 2023
Built by: sw-r2d2-bot@r-build-sonic-ci03-243

Platform: x86_64-mlnx_msn4600c-r0
HwSKU: ACS-MSN4600C
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2140X00042
Model Number: MSN4600-CS2FO_QP
Hardware Revision: A1
Uptime: 18:53:55 up  2:45,  3 users,  load average: 0.64, 0.74, 0.57
Date: Sun 12 Mar 2023 18:53:55
```

#### Output of `show techsupport`:
[sonic_dump_qa-eth-vt03-1-4600ca1_20230312_185337.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/10994994/sonic_dump_qa-eth-vt03-1-4600ca1_20230312_185337.tar.gz)

**Comment by dgsudharsan** [comment]
@adyeung Any update on this?

**Comment by adyeung** [comment]
Root authentication is designed to be done locally regardless of radius config, see HLD requirement and PAM sections from the HLD PR below 

https://github.com/sonic-net/SONiC/pull/500

By default, root user login is disabled in SONiC, step 4.b enables root login, root login auth will happen locally regardless of device radius settings
