### ISSUE TITLE
chassis-packet: pc_lag_2 test fails due to inclusion of internal portchannels

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#14436]
#### Description

sonic-mgmt test pc/test_lag_2 is failing due to inclusion of back plane port channels in the test.

Looks like this happened after the following change to remove portchannel member array from config db
https://github.com/sonic-net/sonic-mgmt/pull/7660
which was required due to this change:
https://github.com/sonic-net/sonic-buildimage/pull/13660

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
Hi @abdosi , raised this to track portchannel test case issue.

**Comment by rlhui** [comment]
@abdosi  will check more

**Comment by anamehra** [comment]
There is a bug in sonic_py_common/multi_asic.py is_port_channel_internal function.
The function use PORTCHANNEL table to get member port and then test if member ports are internal.
With the new change in portchannel db, members is not an entry in PORTCHANNEL table in config db and thus the function always returns false and all portchannels are included in external list.

The fix is to use PORTCHANNEL_MEMBER table. I am testing a fix.

**Comment by anamehra** [comment]
There is a PR in process for https://github.com/sonic-net/sonic-buildimage/issues/14459 that should fix this issue as well.

**Comment by anamehra** [comment]
Dup of https://github.com/sonic-net/sonic-buildimage/issues/14459
