### ISSUE TITLE
Cannot build sonic on Ubuntu 22, permission denied errors.

### ISSUE THREAD

**Issue by tjarosz-stdair** [sonic-net/sonic-buildimage#14467]
#### Description

I am trying to build sonic with the iccpd option. I am using a fresh install of ubuntu 22 (I also tried 20 but had similar issues). When I run the command `make configure PLATFORM=mellanox` I get numerous errors in the output about cannot create directory permission denied. I attempted to `chmod 777 -R ./` and `umask 002` in the root of the sonic-buildimage directory but I still get the issue every time I run make. I am running ubuntu in a VM on TrueNAS Scale (QEMU). The VM has 2 virtual disks, one for the OS (100GB) and one for the sonic build (800GB). The VM has 8 cores and 32GB RAM.

#### Steps to reproduce the issue:
1. Create a new VM and fresh install of ubuntu 22 on 100GB disk.
2. Partition second disk (800GB) and mount the device using `sudo mount /dev/vdb1 /mnt/sonic`
3. `cd` into `/mnt/sonic`
4. Following sonic-buildimage readme instructions run:
    a. `sudo apt update`
    b. `sudo apt install -y python3-pip`
    c. `pip3 install --user j2cli`
    d. install docker using docker instructions here: https://docs.docker.com/engine/install/ubuntu/
    e. add my user account to docker group `sudo usermod -aG docker tajadmin`. Reboot VM.
    f. remount /mnt/sonic and `cd` into /mnt/sonic.
    g. `git clone --recurse-submodules https://github.com/sonic-net/sonic-buildimage.git`
    h. `sudo modprobe overlay`
    i. `cd sonic-buildimage`
    j. `git checkout master` (output "already on master")
    k. `sudo vi ./rules/config` edit file to make `INCLUDE_ICCPD = y`, save file.
    l. `make init` (seems to run to completion without error in the terminal output)
    m. `make configure PLATFORM=mellanox` (output screen capture below with numerous errors about permission denied).

After getting the permission errors, I tried:
1. from /mnt/sonic, `sudo chmod 777 -R ./`
2. from /mnt/sonic, `sudo chown -R tajadmin ./`
3. from /, `sudo mkdir /vcache`  (thinking that it's making a vcache directory in root directory. so trying this)
4. from /, `sudo chown -R tajadmin /vcache`
5. from both / and /mnt/sonic, `umask 002`
6. re-run `make configure PLATFORM=mellanox` (output still indicates mkdir permission denied errors.)

#### Describe the results you received:

The `make configure` command runs with many separate error sections that indicate permission denied when trying to create a directory `/vcache/sonic-slave-buster`. The error block is much larger than this and spills off the visible terminal:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/62894936/228859779-365fa5af-b3b6-4241-8957-d45461f7af0d.png">

And finally, the make finishes with:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/62894936/228861525-e2975639-a079-48b9-8864-1bf734a7fdf2.png">

#### Describe the results you expected:
The `make configure` would complete without permission errors.

#### Additional information you deem important (e.g. issue happens only occasionally):
Ubuntu version:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/62894936/228862147-79bd9755-2a7e-4b35-bbc2-84a72037d236.png">

Here is the permissions in the ./target directory (presumably where the /vcache is actually created).
<img width="395" alt="image" src="https://user-images.githubusercontent.com/62894936/228867678-83b6407c-f704-4855-8075-50748a2abf68.png">

Also, here is a `ls -l` output from the root so you can see there is a directory /vcache with full permissions in case that is where the make was trying to mkdir:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/62894936/228868126-de34bb5f-17be-43c5-9459-e177e565430f.png">

Linux is a foreign language to me so please let me know if there is any other output I need to include with specific commands. Thanks for your help!

**Comment by ZhaohuiS** [comment]
@tjarosz-stdair 
I encountered before, you can try to delete old docker images and retry "make configure" again.
For me, it may be caused by permission lack when I ran make configure. Even I added permission back, the old docker image has been built already and will not be built again. That's why removing docker images worked for me.

**Comment by tjarosz-stdair** [comment]
@ZhaohuiS  I though I tried a fresh build by deleting the sonic-buildimage directory, the going through the process from the `git clone` command again. Apparently, that didn't help since I had the same issue. From your advice, I decided to re-install ubuntu on the 800GB drive without having a separate OS disk. With the fresh install, all on the same drive, I'm getting a much different result. No permission errors so far. I will update with a final result but it looks like you are correct about previous docker builds causing the issue. I wish the errors were more intuitive so I could have resolved on my own. Thanks!

**Comment by Pterosaur** [comment]
In my experience, Most of the time, the error message `mkdir: cannot create directory '/vcache/sonic-slave-buster': Permission Denied` isn't the root failure caused but it overlaps with the real error message on the terminal. So, you can check logs file in the target folder.
But I believe you are using a fresh build environment, another guess is the partition of docker isn't space enough. So, may you try to mount the partition of docker on the bigger data disk.

**Comment by Pterosaur** [comment]
Maybe you can find the  real failure reason by `make configure PLATFORM=mellanox | grep -v "mkdir"`

**Comment by Pterosaur** [comment]
> In my experience, Most of the time, the error message `mkdir: cannot create directory '/vcache/sonic-slave-buster': Permission Denied` isn't the root failure reason but it overlaps with the real error message on the terminal. So, you can check the log files in the target folder. But I believe you are using a fresh build environment, another guess is the partition of docker isn't space enough. So, may you try to mount the partition of docker on a bigger data disk?

Please follow this guidance: https://www.guguweb.com/2019/02/07/how-to-move-docker-data-directory-to-another-location-on-ubuntu/ to migrate your docker folder to the data disk, it pretty much can help you.

**Comment by devasishsyncmonk** [comment]
@tjarosz-stdair 

can you check the permission for the directory pointing to SONIC_VERSION_CACHE_SOURCE in rules/config. By default it is pointing to /var/cache/sonic/artifacts. Updating the permission to 777 for the vcache (/var/cache/sonic/artifacts/vcache) worked for me.

**Comment by tjarosz-stdair** [comment]
Thank you all for the guidance. I do believe my issue was running out of space on disk. When I installed Ubuntu fresh, I didn't notice that on the partition screen, ubuntu was creating a virtual volume of 100GB. I went back and reinstalled ubuntu 22 again and noticed the partition issue and made sure I created the volume with the full 800GB. I still ran into issues with ubuntu 22 not completing the `make init`. So I went back and reinstalled again with ubuntu 20. This time, on ubuntu 20, I got so much further on the build. I did complete the full build and got a sonic-mellanox.bin file in the target directory. I haven't tested installing it on the hardware yet but will report if there are any issues.

I will note that during the `make init` and the `make configure` on ubuntu 20, I again saw `mkdir: ... /vcache/sonic-slave-buster ...` in various spots during the build. But, this time both make commands continued to build to completion.

**Comment by lllemanet** [comment]
Take a closer look at what SONIC_VERSION_CACHE_SOURCE points to (on host). In my case, I had default /var/cache/sonic/artifacts/vcache and, for some unknown reason, it had the next access (777 is expected):
```
drwxr-xr-x 3 root root 4096 Sep 19 03:30 vcache
```
For me either removing vcache or allowing everyone to write to this dir resolved the problem.
