### ISSUE TITLE
XGS sai-modules 8.4 is needed

### ISSUE THREAD

**Issue by byu343** [sonic-net/sonic-buildimage#14471]
#### Description

We noticed that XGS SAI 8.4 is ready in https://github.com/sonic-net/sonic-buildimage/blob/master/platform/broadcom/sai.mk.
We have a platform with bcm56993 which should be supported starting from XGS SAI 8.4, but the chip cannot be detected on the latest SONiC. The cause looks to be that the XGS sai-modules has not been upgraded to 8.4 yet: https://github.com/sonic-net/sonic-buildimage/blob/master/platform/broadcom/sai-modules.mk.

#### Steps to reproduce the issue:
1. We boot the Arista platform with bcm56993 with the latest SONiC
2.
3.

#### Describe the results you received:
The chip bcm56993 is not detected in /proc/linux_ngbde

#### Describe the results you expected:
The chip bcm56993 is detected in /proc/linux_ngbde

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/14212

**Comment by zhenggen-xu** [comment]
do we need a operate PR to fix this file: https://github.com/sonic-net/sonic-buildimage/blob/master/platform/broadcom/sai-modules.mk ?

**Comment by Gfrom2016** [comment]
@byu343 I have a PR for upgrading saibcm-modules to 8.4. You can download the image to test if it works.

**Comment by byu343** [comment]
> @byu343 I have a PR for upgrading saibcm-modules to 8.4. You can download the image to test if it works.
It is verified that the PR works in terms of detecting bcm56993. Thanks.
