### ISSUE TITLE
Inband ports not being initialized correctly

### ISSUE THREAD

**Issue by cheryls-arista** [sonic-net/sonic-buildimage#14520]
<

#### Description

There is an issue whereby the data for the inband ports is not being initialized correctly. On the Arista modular platforms this is preventing IP connectivity between linecards in the same system. For multi-asic linecards such as Wolverine, it is also preventing IP connectivity between the two asics. Ping fails and also iBGP fails to connect.

The failure cases the CHASSIS_APP_DB 'SYSTEM_NEIGH records to be incorrect. Here is an example of the records with the. failure:
admin@cmp218-3:~$ sonic-db-cli CHASSIS_APP_DB keys \*
SYSTEM_LAG_ID_END
SYSTEM_NEIGH||fc00:3000::1
SYSTEM_LAG_ID_START
SYSTEM_NEIGH||1.1.1.3
SYSTEM_NEIGH||1.1.1.1
SYSTEM_NEIGH||fc00:3000::3
SYSTEM_INTERFACE

This should be the following:
admin@cmp218-3:~$ sonic-db-cli CHASSIS_APP_DB keys \* | grep -i IB0
SYSTEM_INTERFACE|cmp218-3|asic0|Ethernet-IB0
SYSTEM_NEIGH|cmp218-3|asic0|Ethernet-IB0|1.1.1.1
SYSTEM_NEIGH|cmp218-3|asic0|Ethernet-IB0|fc00:3000::1
admin@cmp218-3:~$ sonic-db-cli CHASSIS_APP_DB keys \* | grep -i IB1
SYSTEM_NEIGH|cmp218-3|asic1|Ethernet-IB1|fc00:3000::3
SYSTEM_NEIGH|cmp218-3|asic1|Ethernet-IB1|1.1.1.3
SYSTEM_INTERFACE|cmp218-3|asic1|Ethernet-IB1

Note that the keys are incorrect.

#### Steps to reproduce the issue:
1. Initialize a modular system, optionally with a Wovlerine card.

#### Output of `show version`:
admin@nfc406-7:~$ show version

SONiC Software Version: SONiC.branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
Build commit: 275babb1d
Build date: Tue Apr  4 17:10:52 UTC 2023
Built by: cheryls@us149.sjc.aristanetworks.com

Platform: x86_64-arista_7800r3_48cq2_lc
HwSKU: Arista-7800R3-48CQ2-C48
ASIC: broadcom
ASIC Count: 1
Serial Number: SSN20370041
Model Number: 7800R3-48CQ2-LC
Hardware Revision: 2a.00
Uptime: 19:04:21 up 21 min,  1 user,  load average: 3.02, 2.08, 1.16
Date: Tue 04 Apr 2023 19:04:21

Docker images:
REPOSITORY                 TAG                                                                        IMAGE ID       SIZE
docker-macsec              latest                                                                     cbe16705abdc   377MB
docker-teamd               branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   c9f8f2a79bab   374MB
docker-teamd               latest                                                                     c9f8f2a79bab   374MB
docker-orchagent           branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   7b6f8e4a508e   386MB
docker-orchagent           latest                                                                     7b6f8e4a508e   386MB
docker-fpm-frr             branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   f2c06f80312d   404MB
docker-fpm-frr             latest                                                                     f2c06f80312d   404MB
docker-sflow               branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   d7048ed6b082   351MB
docker-sflow               latest                                                                     d7048ed6b082   351MB
docker-nat                 branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   786885bde647   353MB
docker-nat                 latest                                                                     786885bde647   353MB
docker-syncd-brcm-dnx      branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   3875a87e45da   706MB
docker-syncd-brcm-dnx      latest                                                                     3875a87e45da   706MB
docker-gbsyncd-broncos     branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   04925a9da7b3   406MB
docker-gbsyncd-broncos     latest                                                                     04925a9da7b3   406MB
docker-gbsyncd-credo       branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   3328fee86248   373MB
docker-gbsyncd-credo       latest                                                                     3328fee86248   373MB
docker-dhcp-relay          latest                                                                     49c5fc9d8c16   367MB
docker-sonic-telemetry     branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   5e0ed5dcfab6   656MB
docker-sonic-telemetry     latest                                                                     5e0ed5dcfab6   656MB
docker-snmp                branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   1c2d361c2196   396MB
docker-snmp                latest                                                                     1c2d361c2196   396MB
docker-router-advertiser   branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   000dc8b59849   357MB
docker-router-advertiser   latest                                                                     000dc8b59849   357MB
docker-platform-monitor    branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   84ae79e50b09   478MB
docker-platform-monitor    latest                                                                     84ae79e50b09   478MB
docker-mux                 branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   eb23ce7d4c23   406MB
docker-mux                 latest                                                                     eb23ce7d4c23   406MB
docker-lldp                branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   0774616ed30b   400MB
docker-lldp                latest                                                                     0774616ed30b   400MB
docker-eventd              branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   464f3aa9a76c   357MB
docker-eventd              latest                                                                     464f3aa9a76c   357MB
docker-database            branch.master-ars.7c3549db-buildimage.f80bf7783-nightly-2023.04.04.16.02   437f44df3fb1   357MB
docker-database            latest                                                                     437f44df3fb1   357MB

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

The following patch fixes this issue:
@@ -0,0 +1,30 @@
+From: Cheryl Sanchez <cheryls@arista.com>
+Date: 2023-03-24 14:32:00 -0700
+Subject: Fix bug 782344. This fixes iBGP between ASICs on same linecard.
+
+
+---
+ orchagent/portsorch.cpp |    5 ++---
+ 1 file changed, 2 insertions(+), 3 deletions(-)
+
+diff --git a/orchagent/portsorch.cpp b/orchagent/portsorch.cpp
+index 01234567..89abcdef 100755
+--- a/orchagent/portsorch.cpp
++++ b/orchagent/portsorch.cpp
+@@ -7923,14 +7923,13 @@ bool PortsOrch::addSystemPorts()
+                 }
+ 
+                 //System port for local port. Update the system port info in the existing physical port
+-                Port local_port;
+-                if(!getPort(attr.value.oid, local_port))
++                if(!getPort(attr.value.oid, port))
+                 {
+                     //This is system port for non-front panel local port (CPU or OLP or RCY (Inband)). Not an error
+                     SWSS_LOG_NOTICE("Add port for non-front panel local system port 0x%" PRIx64 "; core: %d, core port: %d",
+                             system_port_oid, core_index, core_port_index);
+                 }
+-                local_port.m_system_port_info.local_port_oid = attr.value.oid;
++                port.m_system_port_info.local_port_oid = attr.value.oid;
+             }
+ 
+             port.m_system_port_oid = system_port_oid;

**Comment by kenneth-arista** [comment]
@arlakshm for viz

**Comment by kenneth-arista** [comment]
The issue has been resolved via https://github.com/sonic-net/sonic-swss/pull/2740 and can be closed.
