### ISSUE TITLE
[database]: Traceback during flush of unused database

### ISSUE THREAD

**Issue by nazariig** [sonic-net/sonic-buildimage#14531]
#### Description

Looks like that database container is missing `python3-redis` package.

**Traceback:**
```
Mar 29 15:39:09.721859 sonic INFO database#supervisord: flushdb Traceback (most recent call last):
Mar 29 15:39:09.721859 sonic INFO database#supervisord: flushdb   File "/usr/local/bin/flush_unused_database", line 3, in <module>
Mar 29 15:39:09.722525 sonic INFO database#supervisord: flushdb     import redis
Mar 29 15:39:09.722525 sonic INFO database#supervisord: flushdb ModuleNotFoundError: No module named 'redis'
Mar 29 15:39:09.731512 sonic INFO database#supervisord 2023-03-29 15:39:09,730 INFO exited: flushdb (exit status 1; not expected)
```

#### Steps to reproduce the issue:
1. docker exec -ti database bash
2. /usr/local/bin/flush_unused_database

#### Describe the results you received:
Script fails with traceback

#### Describe the results you expected:
No traceback is expected

#### Output of `show version`:
* N/A

#### Output of `show techsupport`:
* N/A

#### Additional information you deem important (e.g. issue happens only occasionally):

* N/A

**Comment by liuh-80** [comment]
Create a fix PR: https://github.com/sonic-net/sonic-buildimage/pull/14632
Also will create UT to cover this scenario.

**Comment by liuh-80** [comment]
@nazariig , PR and UT PR merged, please confirm I can close this issue.

**Comment by nazariig** [comment]
@liuh-80 closed. Thanks for the fix!
