### ISSUE TITLE
[Chassis]: PO Member down[PO remains UP] is not handled on remote linecards

### ISSUE THREAD

**Issue by deepak-singhal0408** [sonic-net/sonic-buildimage#14542]
#### Description
In chassis Architecture, Port-channels are synced across linecards/ASICs. 
Assuming we have 2 linecards (LC1 and LC2), and PO is created on LC1(member ports from LC1). This PO will be synced to LC2, so that any incoming traffic landing on LC2 and destined to PO can be forwarded/hashed correctly.

The issue here is that, if one member of PO goes down (but PO remains up), this trigger is not handled on remote linecards (LC2), and thus any traffic landing on LC2 and destined to PO, gets blackholed if its hashed to PO member which is down(same is handled correctly on local Linecard, LC1).

**Before Trigger:**
![image](https://user-images.githubusercontent.com/115033986/230295659-cb349217-6a0d-4c0c-8a9b-c1b3005bb860.png)

**After Trigger:**
![image](https://user-images.githubusercontent.com/115033986/230295387-88792392-f8a9-47c1-998d-03331e9a3478.png)

#### Steps to reproduce the issue:
1. Chassis with atleast 2 Linecards. Create a PO with 2 members(min-link set to 1).
2. Bring down one of the PO member.

#### Describe the results you received:
Upon Disabling Lag Mamber:
**On Local Linecard/Asic:**
![image](https://user-images.githubusercontent.com/115033986/230298233-693d2637-4be9-40b3-99e4-1d021bf79d1c.png)

**On Remote Linecard/Asic:**
![image](https://user-images.githubusercontent.com/115033986/230297703-c0770bf8-c65a-476f-9948-f3ccfd283fb6.png)

#### Describe the results you expected:
On the remote Linecards/Asics the Lag members need to get updated, so that traffic landing on remote linecards gets forwarded correctly.

#### Output of `show version`:
SONiC 202205

**Comment by deepak-singhal0408** [comment]
PR https://github.com/sonic-net/sonic-swss/pull/2730 should fix this issue...

**Comment by rlhui** [comment]
@deepak-singhal0408 can we please confirm if this issue is fixed by this PR? thanks.

**Comment by deepak-singhal0408** [comment]
verified the fix.. closing..
