### ISSUE TITLE
[PDDF] Unable to use desel with CPLDMUX

### ISSUE THREAD

**Issue by bluecmd** [sonic-net/sonic-buildimage#14546]
#### Description

The following code makes it clear that the use case of setting `cpld_desel` is not supported by the standard driver.
https://github.com/sonic-net/sonic-buildimage/blob/9b769244d58bdc76a4074e2ddd7e64901323673f/platform/pddf/i2c/modules/cpldmux/driver/pddf_cpldmux_driver.c#L30-L36

Why is that? With PDDF being close to removing needs for custom drivers it seems odd that such a minor thing would be case for a driver fork.

#### Steps to reproduce the issue:
1. Have a CPLDMUX that requires a deactivation write
2. Try to implement it in PDDF
3. Realize it is implemented but deactivated without possibility to activate

#### Describe the results you received:

The CPLDMUX does not work.

#### Describe the results you expected:

The CPLDMUX can be implemented with PDDF and works.

#### Output of `show version`:

N/A

#### Output of `show techsupport`:

N/A

#### Additional information you deem important (e.g. issue happens only occasionally):

N/A

**Comment by FuzailBrcm** [comment]
@bluecmd 
Thanks for pointing out. Yes the 'deselect' function should be enabled in the PDDF common cpldmux driver code.

As to why it wasn't done in the first place, I think we wanted to test the custom implementation of these functions and we tested it by 'not providing' the deselect function implementation in the common driver. After the whole thing was tested, we should have enabled it back. Looks like that didn't happen. 

If the common implementation is not correct/sufficient for any platform, they can override this in a platform specific custom driver. Below is a sample custom driver for cpldmux.

```
#include <linux/module.h>
#include <linux/i2c.h>
..
..
#include "pddf_cpldmux_defs.h"

extern PDDF_CPLDMUX_OPS pddf_cpldmux_ops;

int cpldmux_byte_write(struct i2c_client *client, u8 regaddr, u8 val)
{
    /* Provide custom implementation here */
}

int pddf_cpldmux_deselect(struct i2c_mux_core *muxc, uint32_t chan)
{
    /* Provide the custom implementation here */
}

static int __init pddf_custom_cpldmux_init(void)
{
    pddf_cpldmux_ops.deselect = pddf_cpldmux_deselect;
    pddf_cpldmux_ops.byte_write = cpldmux_byte_write;
    return 0;
}
..
..
..
..
```
