### ISSUE TITLE
sailibthrift is reading data from port_map.ini instead of config_db.json

### ISSUE THREAD

**Issue by rraghav-cisco** [sonic-net/sonic-buildimage#14706]
We encountered an issue where the sai-thrift library in syncd-rpc container in the SONiC image is reading the port information(lanes, speed) etc from the port_config.ini instead of the /etc/sonic/config_db.json. My understanding is that config_db.json is the place to read this information once it has been created and saved.

When the issue happens, the sai thrift call returns an empty value for port OID. I have attached the packet trace during this call.

Steps done:
We configured the port speeds and lanes for 8 ports  (Ethernet96 to Ethernet152) from 400G to 100G. This was done in config_db.json, and then config-reload or reboot. The port_config.ini was not changed. This caused the following issue:

**The below is the syslog that appears that time:**
Apr 13 03:10:44.818545 chu-dut INFO syncd#/supervisord: message repeated 2 times: [ dshell_client [03:10:44] {/usr/bin/dshell_client.py:1676} INFO - sai_thrift_get_port_id_by_front_port]
Apr 13 03:10:44.818545 chu-dut INFO syncd#/supervisord: dshell_client [03:10:44] {/usr/bin/dshell_client.py:1676} INFO - Didn't find port
Apr 13 03:10:44.819073 chu-dut INFO syncd#/supervisord: dshell_client [03:10:44] {/usr/bin/dshell_client.py:1676} INFO - sai_thrift_get_port_id_by_front_port

This causes **qos/test_qos.py::TestQosSai::testQosSaiSharedReservationSize to fail**. The sai-port-id from the DUT is 0 for Ethernet96(one of the new 100G ports). You can see that **Ethernet0 is returning a valid port ID, but Ethernet96 is returning 0**. This is causing the script to fail.
root@chu-dut:/home/cisco# show int stat | grep "96 "
     Ethernet96  1536,1537,1538,1539     100G   9100     rs    etp12   PortChannel102      up       up                                  QSFP28 or later         off
    Ethernet196      260,261,262,263     100G   9100    N/A   etp24b           routed      up     down  QSFP-DD Double Density 8X Pluggable Transceiver         off

(Pdb) client.sai_thrift_get_port_id_by_front_port("Ethernet96")
0
(Pdb) client.sai_thrift_get_port_id_by_front_port("Ethernet0")
72057594037927956
(Pdb)
This issue is happening in all the new 100G ports:
(Pdb) for i in range(96,153,8): client.sai_thrift_get_port_id_by_front_port("Ethernet"+str(i))
0
0
0
0
0
0
0
0
(Pdb) client.sai_thrift_get_port_id_by_front_port("Ethernet160") **<<< Normal port.**
72057594037927980
(Pdb)

**Comment by rraghav-cisco** [comment]
**Valid port ID for Ethernet0:**
<img width="1792" alt="Screenshot 2023-04-18 at 10 43 35 AM" src="https://user-images.githubusercontent.com/58446052/232860246-50ef537c-265a-4cd1-8509-a9a67583efea.png">
<img width="1792" alt="Screenshot 2023-04-18 at 10 43 58 AM" src="https://user-images.githubusercontent.com/58446052/232860334-db19086a-d15e-47e8-8de9-33542ed0224b.png">
**Invalid port ID for Ethernet96**
<img width="1792" alt="Screenshot 2023-04-18 at 10 44 33 AM" src="https://user-images.githubusercontent.com/58446052/232860450-7e24c3b6-6a6d-4124-8a76-1cf40b6e8c9d.png">
<img width="1792" alt="Screenshot 2023-04-18 at 10 44 48 AM" src="https://user-images.githubusercontent.com/58446052/232860505-b7d60730-392a-45f4-9317-1283c4d54ce8.png">

**Comment by anamehra** [comment]
Hi @abdosi , raised this issue for saithrift lib causing qos test case failure when using minigraph as port_config.ini is used to validate the link.

**Comment by neethajohn** [comment]
@neethajohn to sync with @Gfrom2016 to understand this issue

**Comment by abdosi** [comment]
@Gfrom2016 have fixed this. Please check.  
cc @neethajohn / @vmittal-msft / @anamehra /@rraghav-cisco  for viz.
