### ISSUE TITLE
sonic 202012 and 202111 stretch based builds are failing

### ISSUE THREAD

**Issue by sj-harrish** [sonic-net/sonic-buildimage#14854]
sonic-slave-stretch based builds like SONiC-202012 or SONiC-202111  builds are failing with below error:

```
W: The repository 'http://debian-archive.trafficmanager.net/debian stretch Release' does not have a Release file.
W: The repository 'http://debian-archive.trafficmanager.net/debian stretch-updates Release' does not have a Release file.
W: The repository 'http://debian-archive.trafficmanager.net/debian stretch-backports Release' does not have a Release file.
W: The repository 'http://debian-archive.trafficmanager.net/debian-security stretch/updates Release' does not have a Release file.
E: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/stretch/non-free/source/Sources  404  Not Found
E: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/stretch-updates/non-free/source/Sources  404  Not Found
E: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/stretch-backports/non-free/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://debian-archive.trafficmanager.net/debian-security/dists/stretch/updates/contrib/source/Sources  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

Error: No such container:path: sonic-slave-stretch:/etc/os-release
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/pre-versions
Error: No such container:path: sonic-slave-stretch:/usr/local/share/buildinfo/post-versions
Error: No such container: sonic-slave-stretch
Image sonic-slave-stretch-harrish:b2fc05b0c6d not found. Building...
Sending build context to Docker daemon  223.2kB
Step 1/18 : ARG slave_base_tag_ref=latest
Step 2/18 : FROM sonic-slave-stretch:${slave_base_tag_ref}
pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Unable to find image 'sonic-slave-stretch-harrish:b2fc05b0c6d' locally
docker: Error response from daemon: pull access denied for sonic-slave-stretch-harrish, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

**On further analysis it seems the stretch files are moved to archive from Apr-24. 
Ref : https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html** 

Kindly help in resolving the issue.? Please find the complete build logs attached for reference.

[Community_SONiC_202111_Stretch_Build_Fail_Logs.txt](https://github.com/sonic-net/sonic-buildimage/files/11331378/Community_SONiC_202111_Stretch_Build_Fail_Logs.txt)

**Comment by sj-harrish** [comment]
@neethajohn , Thanks for your inputs. I have checked the pipeline and last executed build seems to be fine - https://sonic-build.azurewebsites.net/ui/sonic/pipelines/138/builds?branchName=202012. 

But Getting the stretch debian error while following the build steps published in sonic-buildimage page as below:
**Error:**
```
E: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/stretch/contrib/source/Sources  404  Not Found
E: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/stretch-updates/non-free/source/Sources  404  Not Found
E: Failed to fetch http://debian-archive.trafficmanager.net/debian/dists/stretch-backports/contrib/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://debian-archive.trafficmanager.net/debian-security/dists/stretch/updates/contrib/source/Sources  404  Not Found

```
**Steps used:**
```
git clone -b 202012 https://github.com/sonic-net/sonic-buildimage.git
sudo modprobe overlay
cd sonic-buildimage
make init
make configure PLATFORM=broadcom
```
Also I could see that stretch debian files are not present in **http://debian-archive.trafficmanager.net/debian/dists/**
Could you please let me know if the SONiC pipeline build fetches the Debian files locally.?
Also could you please share the working steps to build the Broadcom platform image in SONiC-202012.?
Thanks in advance,

**Comment by madhupalu** [comment]
@neethajohn @yxieca @zhangyanzhao as per https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html moved stretch debian files to archieve.debian.org on 04/23/2023, so the build steps failing with 404 with no sources available. Surprisingly, official 202012 builds running fine, does build pipelines pick up from local repos? Could you please let me know if the SONiC pipeline build fetches the Debian files locally.?
Also could you please share the working steps to build the Broadcom platform image in SONiC-202012.?
We are blocking on customer deployment, could you please help us on how to build successful and unblock us!
Thanks - Madhu

**Comment by yxieca** [comment]
> @neethajohn @yxieca @zhangyanzhao as per https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html moved stretch debian files to archieve.debian.org on 04/23/2023, so the build steps failing with 404 with no sources available. Surprisingly, official 202012 builds running fine, does build pipelines pick up from local repos? Could you please let me know if the SONiC pipeline build fetches the Debian files locally.? Also could you please share the working steps to build the Broadcom platform image in SONiC-202012.? We are blocking on customer deployment, could you please help us on how to build successful and unblock us! Thanks - Madhu

@xumia, @liushilongbuaa can you help community with this build question?

**Comment by Yukissss** [comment]
I changed all the source from http://debian-archive.trafficmanager.net/debian to http://archive.debian.org/debian-archive/debian as well as some source like debian-security. It looks good to continue the build process.

**Comment by sj-harrish** [comment]
@Yukissss , Thanks much for your inputs. We are also trying the same in our local. 
Could you please share the changes done to achieve the same.?

**Comment by Yukissss** [comment]
@sj-harrish I am still building the image( actually from a branch based on 201911)  and just finished the process of Dockerfile in sonic-slave-stretch. 
I look for those key words in my VSCode and replace them one by one. Here are some changes where I made.
1. dockers/docker-base
    sources.list
    Dockerfile.j2
2. dockers/docker-base-stretch
    sources.list
3. dockers/docker-ptf
    Dockerfile.j2
4. files/apt
    sources.list.*
5. files/image_config/apt/sources.list.d/amd64
    arm64/debian_mirror_arm64.list & armhf debian_mirror_armhf.list  
6. sonic-slave-jessie
    Dockerfile.j2
7. sonic-slave-stretch
    Dockerfile.j2
8. build_debian.sh

Also, changed (ftp)deb.debian.org to archive.debian.org/debian-archive. Changed security.debian.org to archive.debian.org/debian-archive/debian-security.
And I found that you may need to overwrite(verify needed) the sources.list in Dockerfile.j2 in sonic-slave-jessie and sonic-slave-stretch
`RUN echo "deb [arch=amd64] http://archive.debian.org/debian-archive/debian jessie main contrib non-free" **>** /etc/apt/sources.list && \`


Since we used different version, you may need to find out some differences or anywhere else you have to change. Gook luck!

**Comment by sj-harrish** [comment]
Thanks much @Yukissss for your inputs. We will check and get back on this.

**Comment by sj-harrish** [comment]
@Yukissss , Is it possible for you to share the changes done to fix the build issue.?

BTW We Couldn't trace the error we are getting below even the changes are done to the docker and build files.?
And the "security.debian.org/debian-security stretch" or "deb.debian.org/debian stretch"  is not present in entire build after the changes.

```
Err:4 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
  404  Not Found [IP: 151.101.194.132 80]

Get:44 http://archive.debian.org/debian-archive/debian stretch/non-free amd64 Packages [78.3 kB]
Ign:18 http://deb.debian.org/debian stretch/main amd64 Packages
Ign:22 http://deb.debian.org/debian stretch-updates/main amd64 Packages
Ign:23 http://deb.debian.org/debian stretch-updates/main all Packages
Ign:11 http://deb.debian.org/debian stretch/main all Packages
Err:18 http://deb.debian.org/debian stretch/main amd64 Packages
  404  Not Found
Err:22 http://deb.debian.org/debian stretch-updates/main amd64 Packages
  404  Not Found
```

**Comment by Yukissss** [comment]
@sj-harrish I also got the same error. What I did is deleting **/target** at first, otherwise there may have reference to old sources in your environment.  Now I am fine to build the entire image.

**Comment by sj-harrish** [comment]
@Yukissss , Thanks for your inputs. We are able to get rid of those failures by taking care of /etc/apt/sources.list properly. But we are getting below failures still
```
Unable to find image 'sonic-slave-stretch:9dd14ab0d94' locally
Error response from daemon: pull access denied for sonic-slave-stretch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
But from SONiC build pipeline it seems the stretch is pulled from sonicdev-microsoft.azurecr.io:443/sonic-slave-stretch
https://dev.azure.com/mssonic/build/_build/results?buildId=261789&view=logs&j=88ce9a53-729c-5fa9-7b6e-3d98f2488e3f&t=88f376cf-c35d-5783-0a48-9ad83a873284 

Did you face similar issue and Kindly let us know if you have fixed it already.?
Thanks in advance,

**Comment by sj-harrish** [comment]
@Yukissss , make configure is getting completed now. But we are observing now errors in libhiredis module as below:
Did you get similar error and any inputs on this would be much helpful. Thanks in advance,

```
2023-05-01 09:58:17 (191 MB/s) - 'hiredis_0.14.0-3~bpo9+1.dsc' saved [2072/2072]

dpkg-source: info: extracting hiredis in hiredis-0.14.0
dpkg-source: info: unpacking hiredis_0.14.0.orig.tar.gz
dpkg-source: info: unpacking hiredis_0.14.0-3~bpo9+1.debian.tar.xz
dpkg-source: info: applying 01_use-proper-destdir.patch
dpkg-source: info: applying 02_disable-failing-test.patch
dpkg-source: info: applying 04_disable-network-tests.patch
dpkg-source: info: applying 06_redis-startup.patch
dpkg-source: info: applying 07_cmake.patch
dpkg-source: info: applying 08_cppflags.patch
/sonic/src/hiredis/hiredis-0.14.0 /sonic/src/hiredis
dpkg-buildpackage: info: source package hiredis
dpkg-buildpackage: info: source version 0.14.0-3~bpo9+1
dpkg-buildpackage: info: source distribution stretch-backports
dpkg-buildpackage: info: source changed by Chris Lamb <[lamby@debian.org](mailto:lamby@debian.org)>
dpkg-source --before-build hiredis-0.14.0
dpkg-buildpackage: info: host architecture amd64
fakeroot debian/rules clean
make[2]: Entering directory '/sonic/src/hiredis/hiredis-0.14.0'
dh clean
dh: Compatibility levels before 5 are no longer supported (level 1 requested)
debian/rules:12: recipe for target 'clean' failed
make[2]: *** [clean] Error 25
make[2]: Leaving directory '/sonic/src/hiredis/hiredis-0.14.0'
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
Makefile:9: recipe for target '/sonic/target/debs/stretch/libhiredis0.14_0.14.0-3~bpo9+1_amd64.deb' failed
make[1]: *** [/sonic/target/debs/stretch/libhiredis0.14_0.14.0-3~bpo9+1_amd64.deb] Error 2
make[1]: Leaving directory '/sonic/src/hiredis'
[ FAIL LOG END ] [ target/debs/stretch/libhiredis0.14_0.14.0-3~bpo9+1_amd64.deb ]
slave.mk:472: recipe for target 'target/debs/stretch/libhiredis0.14_0.14.0-3~bpo9+1_amd64.deb' failed
make: *** [target/debs/stretch/libhiredis0.14_0.14.0-3~bpo9+1_amd64.deb] Error 1
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
make[1]: *** [Makefile.work:297: stretch] Error 2
```

**Comment by xumia** [comment]
How about adding the build option MIRROR_SNAPSHOT=y, to use the snapshot mirror?

**Comment by sj-harrish** [comment]
@xumia Thanks much for your inputs. we will check and get back on this.

**Comment by sj-harrish** [comment]
Team, 
Thanks much for your inputs. The issues is not observed after enabling MIRROR_SNAPSHOT=y and SONIC_VERSION_CONTROL_COMPONENTS=all in 202012/202111 stretch based build. Closing the issue.
