### ISSUE TITLE
BGP session not established with following error - nexthop_set failed, resetting connection - intf 0x556658d086f0

### ISSUE THREAD

**Issue by Hedgehog-Guru** [sonic-net/sonic-buildimage#14866]
#### Steps to reproduce the issue:
My setup is DUT + IXIA
1.Create 1k interface VLANs on DUT
2.Configure all needed BGP configurations on DUT and IXIA
3.Start BGP protocols on IXIA side and check that few peers are failed , usually between 1 to 5 peers are failed

#### Describe the results you received:
Not all BGP sessions are established and on IXIA side we see following error:
State Machine error received
On DUT side following error:
nexthop_set failed, resetting connection - intf 0x556658d086f0

#### Describe the results you expected:
Expected to see all sessions are established

#### Output of `show version`:

```
Last time i tested it on SONiC.202211_RC9.3 and SPC3 switch
```
#### Output of `show techsupport`:

```
[sonic_dump_qa-eth-vt02-2-4700a1_20230411_102108.tar.zip.001.zip](https://github.com/sonic-net/sonic-buildimage/files/11340827/sonic_dump_qa-eth-vt02-2-4700a1_20230411_102108.tar.zip.001.zip)
[sonic_dump_qa-eth-vt02-2-4700a1_20230411_102108.tar.zip.002.zip](https://github.com/sonic-net/sonic-buildimage/files/11340839/sonic_dump_qa-eth-vt02-2-4700a1_20230411_102108.tar.zip.002.zip)
[sonic_dump_qa-eth-vt02-2-4700a1_20230411_102108.tar.zip.003.zip](https://github.com/sonic-net/sonic-buildimage/files/11340840/sonic_dump_qa-eth-vt02-2-4700a1_20230411_102108.tar.zip.003.zip)

**Comment by vivekrnv** [comment]
Hi @gechiang , 

We haven't seen any issues with 500 interface vlans.  This PR was supposed to fix this issue. https://github.com/FRRouting/frr/pull/13396
