### ISSUE TITLE
Some of the unit tests on test_system_health.py are not testing anything

### ISSUE THREAD

**Issue by DavidZagury** [sonic-net/sonic-buildimage#14871]
#### Description
The test test_publish_system_status on src/system-health/tests/test_system_health.py will pass no matter what issue are there on the function that it meant to test.
This test is also used by other test, which also make them not reliable.

#### Steps to reproduce the issue:
1. Break the function publish_system_status on sysmonitor.py, for example, change the implantation of this function to:
```
    def publish_system_status(self, astate):
        global system_allsrv_state
        if system_allsrv_state != astate:
            system_allsrv_state = astate
            if astate == "DOWN":
                msg = "System is not ready - one or more services are not up"
            elif astate == "UP":
                msg = "System is ready"
            logger.log_notice(msg)
            self.print_console_message(msg)
            self.post_system_status("FAIL")
```
3. Build target/python-wheels/bullseye/system_health-1.0-py3-none-any.whl

#### Describe the results you received:
The build success

#### Describe the results you expected:
The test test_publish_system_status should fail becuase the publish_system_status function is broken.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):
This happens because the test test_publish_system_status actually mocks the function publish_system_status with an empty MagicMock. We can't mock the very thing we want to test.

**Comment by sg893052** [comment]
I will take a look at it.

**Comment by sg893052** [comment]
ETA: 6/10

**Comment by sg893052** [comment]
@adyeung https://github.com/sonic-net/sonic-buildimage/pull/15433 will address this issue
