### ISSUE TITLE
"show interfaces neighbor expected" returns empty results when neighbor missing loopback address

### ISSUE THREAD

**Issue by veronica-arista** [sonic-net/sonic-buildimage#15348]
#### Description
"show interfaces neighbor expected" returns empty results when run on our clusters after a recent change in minigraph.py:
https://github.com/sonic-net/sonic-buildimage/commit/1496d1d28cff9f6ffbac7eefb2df2fd293d52b7d

Specifically, the device_data now explicitly excludes values that are "None", resulting in the entry being skipped by the "show interfaces neighbor expected" command implementation ( `show/interfaces/__init__.py` )

#### Steps to reproduce the issue:
1. Run "show interfaces neighbor expected" on a DUT for which the neighbor metadata lacks loopback addr
2.
3.

#### Describe the results you received:
The command now returns empty results, though our device has neighbors:

```
root@nfc420-7:~# show interfaces neighbor expected
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------

root@nfc420-7:~# sonic-cfggen -d --var-json "DEVICE_NEIGHBOR"
{
    "Ethernet0": {
        "name": "ARISTA01T3",
        "port": "Ethernet1"
    },
    "Ethernet160": {
        "name": "ARISTA03T3",
        "port": "Ethernet1"
    },
    "Ethernet168": {
        "name": "ARISTA04T3",
        "port": "Ethernet1"
    },
    "Ethernet172": {
        "name": "ARISTA04T3",
        "port": "Ethernet2"
    },
    "Ethernet176": {
        "name": "ARISTA06T3",
        "port": "Ethernet1"
    },
    "Ethernet36": {
        "name": "ARISTA01T3",
        "port": "Ethernet2"
    }
}
```

#### Describe the results you expected:
Prior to the change in minigraph.py the command returned the following on the same device:

```
root@nfc420-7:~$ show interfaces neighbor expected
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet0    ARISTA01T3  Ethernet1       None                10.250.25.2     CoreRouter
Ethernet36   ARISTA01T3  Ethernet2       None                10.250.25.2     CoreRouter
Ethernet160  ARISTA03T3  Ethernet1       None                10.250.25.3     CoreRouter
Ethernet168  ARISTA04T3  Ethernet1       None                10.250.25.4     CoreRouter
Ethernet172  ARISTA04T3  Ethernet2       None                10.250.25.4     CoreRouter
Ethernet176  ARISTA06T3  Ethernet1       None                10.250.25.5     CoreRouter
```

**Comment by judyjoseph** [comment]
@jcaiMR Could you check why it is getting skipped in show command. Thanks.

**Comment by wenyiz2021** [comment]
this issue should be fixed by https://github.com/sonic-net/sonic-utilities/pull/2465
it is already in 202205
it adds safety check if lo_addr etc is emtpy
