### ISSUE TITLE
[chassis][Nokia] When chassis went down due to power lost, show reboot-cause failed to report it.

### ISSUE THREAD

**Issue by gechiang** [sonic-net/sonic-buildimage#15501]
#### Description

While testing how the PSU power source failure is being handled by the Nokia 7250 Chassis, noticed that when I removed all power source the chassis went down but when the power is restored, the reboot-cause was missing...

#### Steps to reproduce the issue:
1.  Remove the power source from the PSU one by one
2.  When last PSU lost power chassis went down as expected.
3.  Restored all power source and ran "show reboot-cause history" shows it failed to capture the "power lost" reboot cause...

#### Describe the results you received:
When I removed the power which is at about this time:
Jun 15 23:15:01.720254

When the chassis came back up issued the show reboot-cause history and observed this:

```
admin@str2-7250-sup-1:~$ show reboot-cause history
Name                 Cause                                              Time                             User     Comment
-------------------  -------------------------------------------------  -------------------------------  -------  ---------
2023_06_13_21_22_31  reboot                                             Tue Jun 13 21:20:11 UTC 2023     admin    N/A
2023_06_10_02_15_47  reboot                                             Sat 10 Jun 2023 02:12:15 AM UTC  admin    N/A
2023_06_10_01_03_30  Power Loss                                         Sun 31 Dec 2000 12:00:02 AM UTC  Unknown  N/A
2023_06_05_20_22_50  Power Loss                                         Sun 31 Dec 2000 12:00:02 AM UTC  Unknown  N/A
2023_06_03_02_28_02  Unknown                                            N/A                              N/A      N/A
2023_06_03_02_10_38  reboot                                             Sat 03 Jun 2023 02:08:24 AM UTC  admin    N/A
2023_06_03_01_03_43  Unknown (First boot of SONiC version 20220531.24)  N/A                              N/A      N/A
2023_06_02_23_01_26  reboot                                             Fri 02 Jun 2023 10:59:00 PM UTC  admin    N/A
2023_06_01_16_49_49  reboot                                             Thu 01 Jun 2023 04:47:33 PM UTC  admin    N/A
2023_06_01_06_27_09  reboot                                             Thu Jun  1 06:24:52 UTC 2023     admin    N/A
admin@str2-7250-sup-1:~$ date
Thu 15 Jun 2023 11:26:17 PM UTC
```
As you can see that the "power Loss" event that should have been captured for 6/15/23 at 23:26 did not happen...
This is reproducible...  Key is to take out all PSUs and just keep one remaining.  and then take out the last PSU...

#### Describe the results you expected:
Reboot-cause should show "power Loss as the reason and NOT missing...

#### Output of `show version`:
This is using the latest image built based on azure/sonic-buildimage-msft 202205 branch.

```
admin@str2-7250-sup-1:~$ show platform sum
Platform: x86_64-nokia_ixr7250e_sup-r0
HwSKU: Nokia-IXR7250E-SUP-10
ASIC: broadcom
ASIC Count: 16
Serial Number: NS214510034
Model Number: 3HE16996AARA01
Hardware Revision: 56
Switch Type: fabric
admin@str2-7250-sup-1:~$
```
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by gechiang** [comment]
[missing_power_loss_reboot-cause_syslog.txt](https://github.com/sonic-net/sonic-buildimage/files/11764155/missing_power_loss_reboot-cause_syslog.txt)

**Comment by prgeor** [comment]
@mlok-nokia can you check this issue on Nokia chassis platform.?

**Comment by gechiang** [comment]
Will work with Nokia team directly.
Closing this issue...
