### ISSUE TITLE
[Routing WG] ASOC Intern project 2: Reduce bgp node memory usage 

### ISSUE THREAD

**Issue by eddieruan-alibaba** [sonic-net/sonic-buildimage#15557]
Currently bgp creates a bgp_node which is the zebra equivalent to route_node + rib_dest_t.  This should be broken up, in BGP, to a route_node and a bgp_dest_t.

Some code has already been written see https://github.com/donaldsharp/frr/tree/pi_rb

Some lock issue was observed before. Need intern to finalize the changes, pass all the bgp test cases and merge them.

**Comment by prgeor** [comment]
@zhangyanzhao can you take care of moving these intern project requests to sonic repo from buildimage repo?

**Comment by eddieruan-alibaba** [comment]
Yunqing's PR is at

[https://github.com/FRRouting/frr/pull/14118](https://github.com/FRRouting/frr/pull/14118)

**Comment by eddieruan-alibaba** [comment]
Changes are merged via https://github.com/FRRouting/frr/commit/e89fd723eeccd0804cb186c67bb891990bd2e059
