### ISSUE TITLE
[202205][syslog]: Log files are disappeared(cleaned) after reboot

### ISSUE THREAD

**Issue by nazariig** [sonic-net/sonic-buildimage#15895]
#### Description

The issue is caused by:
```
commit 365afbb3f031ab3e5e5aa0f4a2104b62ddb9d8c2 (HEAD -> 202205, origin/202205)
Author: mssonicbld <79238446+mssonicbld@users.noreply.github.com>
Date:   Thu Jul 13 05:01:14 2023 +0800

    Move /var/log to RAM for Mellanox SN2700, Nokia 7215 and Dell S6100 (#15077) (#15804)
```
It blocks verification of warm/fast reboot flows, since `loganalyzer` loses it's markers.

Before:
```
root@sonic:/home/admin# df -h /var/log
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop1      3.9G  8.9M  3.7G   1% /var/log
```

After:
```
root@sonic:/home/admin# df -h /var/log
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           790M  2.8M  788M   1% /var/log
```

#### Steps to reproduce the issue:
1. Check `/var/log/syslog` file content
2. Reboot DUT
3. Check `/var/log/syslog` file content (syslog.1, etc.)

#### Describe the results you received:
Logs are removed

#### Describe the results you expected:
Logs should be stored/rotated

#### Output of `show version`:
* N/A

#### Output of `show techsupport`:
* N/A

#### Additional information you deem important (e.g. issue happens only occasionally):

* Culprit PR: https://github.com/sonic-net/sonic-buildimage/pull/15077

**Comment by vaibhavhd** [comment]
This is not an image issue. Moving logs to tmpfs is done to minimize risk to the disk. Disappearing log files is expected after reboot.

As for test issues related to missing logs for LogAnalyzer -- we have a way to detect if logs are in tmpfs and take a backup for loagnalyzer to work - https://github.com/sonic-net/sonic-mgmt/blob/a29ea09e6d707f0dd233a8b0e17d9dbb8c1f7ccf/tests/platform_tests/conftest.py#L489

If there is an issue w/ sonic-mgmt code, then let's raise a bug there, attach failure logs. You can assign that to me.

@nazariig please close this buildimage issue if you agree w/ my analysis.
