### ISSUE TITLE
Unable to set custom ONIE disk partition size for OS

### ISSUE THREAD

**Issue by pbudds** [sonic-net/sonic-buildimage#15949]
#### Description
When building the SONiC image, I'm unable to set the partition size to a custom value that is based on the HW configuration.
I was able to do it using some make file changes, but not sure if that is the way or if there is a already supported method to
customize the Disk partition size. If not supported yet, would be happy to do a pull request with my changes.

#### Steps to reproduce the issue:
1. Try to set the ONIE build parameter ONIE_IMAGE_PART_SIZE to a custom value below.  
2. make USERNAME=test PASSWORD=test123 ONIE_IMAGE_PART_SIZE=130048 all
3. Check partition size on the final image built using "lsblk"

#### Describe the results you received:
After booting the image and checking the OS partition size, It is still 32G

NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0    7:0    0 419.4M  0 loop 
loop1    7:1    0     4G  0 loop /var/log
sda      8:0    0 119.2G  0 disk 
->sda1   8:1    0   256M  0 part 
->sda2   8:2    0   128M  0 part 
->sda3   8:3    0    32G  0 part /host

#### Describe the results you expected:
Expect the  the disk partition size to be 118.8G for sda3

#### Output of `show version`:
This was tried on a 202205 branch, commit hash a66d4699f2ad75442ad146f9237717c01bfc45f3

**Comment by neethajohn** [comment]
@pbudds, please take a look at installer.sh file for options to resize

**Comment by pbudds** [comment]
@neethajohn - Thank you for taking time to triage this.

I did not find installer.sh, Were you referring to "installer/install.sh"? And a platform specific file for example - device/broadcom/x86_64-bcm_xlr-r0/installer.conf
This had some ONIE params to customize for a platform and I added "ONIE_IMAGE_PART_SIZE=130048" to installer.conf and rebuilt. It seems like that should work, but unfortunately it did not. Not sure if I'm missing something. The value got ignored.

Turns out, during build time, the installer.conf isn't being read and build_image.sh calls onie-mk-demo.sh with value read from onie-image.conf which is the default value.

https://github.com/sonic-net/sonic-buildimage/blob/a86eb95005fafd7dabea02849cb4989205d5767f/build_image.sh#L87

onie-mk-demo.sh does a string replace of ONIE_IMAGE_PART_SIZE with the value passed in during build time and modifies install.sh file. During install time, even though install.sh was reading the value, the new value of ONIE_IMAGE_PART_SIZE gets ignored as the string was already replaced. 

https://github.com/sonic-net/sonic-buildimage/blob/a86eb95005fafd7dabea02849cb4989205d5767f/onie-mk-demo.sh#L101

A small change to not do string replace and let install.sh use value read from platform specific installer.conf during install time worked for me. Thoughts appreciated.

**Comment by pbudds** [comment]
Does anyone have any suggestions? Should "ONIE_IMAGE_PART_SIZE=130048" in platform specific installer.conf is the right way to do it and is supposed to work?

**Comment by prgeor** [comment]
@saiarcot895 do you have a suggestion? @pbudds can you share the PR?

**Comment by saiarcot895** [comment]
@pbudds When building an ONIE image, AFAIK, we don't read any platform-specific information, because we don't necessarily know at build time what platform we're building for (besides the ASIC type (broadcom, mellanox, etc.) and architecture). The current code looks at the architecture-specific `onie-image.conf` file (this is either `onie-image.conf`, `onie-image-arm64.conf`, or `onie-image-armhf.conf`). This could, in theory, be extended to look for a ASIC-specific file as well, but I don't think that would be very useful, since devices have vastly different disk sizes.

Can you try building an ONIE image with `ONIE_IMAGE_PART_SIZE=130048 make USERNAME=test PASSWORD=test123 all`? If that works, then it's an issue of the variable not being propagated to the `build_image.sh` script. In that case, in `slave.mk`, where `build_image.sh` gets called, `ONIE_IMAGE_PART_SIZE` needs to be passed down as well.

**Comment by pbudds** [comment]
@saiarcot895 - Appreciate you taking time to take a look. 

Tried "ONIE_IMAGE_PART_SIZE=130048 make USERNAME=test PASSWORD=test123 all" that and it did not work.  

The fix to make above work is in below PRT  and also includes a small change to make platform specific customization  to work. That happens during install time when "installer.conf" file gets read by "install.sh" file and gives a chance of customizing it. Details in below PR.

https://github.com/sonic-net/sonic-buildimage/pull/16691
