### ISSUE TITLE
[Dual-ToR] orchagent timeout responding to linkmgrd 

### ISSUE THREAD

**Issue by ayurkiv-nvda** [sonic-net/sonic-buildimage#15964]
#### Description
Due to orchagent timeout responding to linkmgrd  ToR status is not update that cause traffic losses.
Found during running community test **dualtor_io/test_normal_op.py::test_upper_tor_config_reload_upstream[active-active]** 

#### Steps to reproduce the issue:
Reproduce rate 10-25%

1. Dual-Tor setup UP and Running, both ToRs are Active

2. Traffic sent from the server to T1 via ToR-1

3. Active-ToR go to "config reload" -> traffic switched to ToR-2, ToR-1 becomes standby

4. ToR-1 is restoring, links go UP, and the switch is preparing to become active again

5. while some ports on ToR are still configuring, NIC simulator decides that some ports on ToR-1 are ready and start sending traffic. 
--> it cause traffic losses on some ports for a long period.  (>10 seconds)

#### Describe the results you received:
On some ports, continuous traffic losses were observed.    (>10 seconds)

#### Describe the results you expected:
Traffic losses are minimized or completely absent.

#### Output of `show version`:

```
SONiC.202211.64-cc818fcf0_Internal
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

Explanation:

During ToR-1 UP after ` config reload ` Acive-Active state machine changed state of all mux ports a few times.

1) After `config reload` all ports changed their state from **active** to **standby**.

2) Then, after a few minutes before ports go UP state changes to **active**

3) One second after that - again back to **standby**.

4) And only when routes are established and links are healthy - it will switch to **active**

But in our case, **step#3** (switch back to **standby**) is sometimes skipped due to orchagent timeout responding to linkmgrd.

It means that the port will send gRPC request to the NIC server with info that this port is **active** (**step#2**) and now NIC can choose this port to send traffic (But NIC also may continue using a corresponding identical port on ToR-2).

5) So NIC considers ToR-A that is not ready for traffic forwarding as an Active ToR

**Log:**

**Step#3**
```
Jul 20 13:31:15.044402 switch_tor_1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:1027 switchMuxState: Ethernet40: Switching MUX state to 'Standby' 
\-------> switch to standby Ethernet40 (send message to swss)
Jul 20 13:31:15.044444 switch_tor_1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:1292 handleDefaultRouteStateNotification: Ethernet40: (P: Unknown, M: Standby, L: Up) -> (P: Unknown, M: Standby, L: Up)

Jul 20 13:31:15.045563 switch_tor_1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:1027 switchMuxState: Ethernet72: Switching MUX state to 'Standby' 
\-------> switch to standby Ethernet72 (send message to swss)
Jul 20 13:31:15.045597 switch_tor_1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:1292 handleDefaultRouteStateNotification: Ethernet72: (P: Wait, M: Active, L: Up) -> (P: Wait, M: Standby, L: Up)
===========

Jul 20 13:31:15.056673 switch_tor_1 NOTICE swss#orchagent: :- setState: [Ethernet40] Set MUX state from standby to standby
\ ----> (message for Ethernet40 received)
Jul 20 13:31:15.056912 switch_tor_1 NOTICE swss#orchagent: :- addOperation: Mux State set to standby for port Ethernet40
Jul 20 13:31:15.149933 switch_tor_1 NOTICE pmon#ycabled: calling RPC for hw mux_cable set state ispeer = False port Ethernet40 portid 1 read_side 1 state requested standby  
\-----> send request to gRPC
Jul 20 13:31:15.683428 switch_tor_1 NOTICE swss#orchagent: :- addOperation: Mux setting State DB entry (hw state standby, mux state standby) for port Ethernet40

Jul 20 13:31:15.683719 switch_tor_1 WARNING mux#linkmgrd: MuxManager.cpp:288 addOrUpdateMuxPortMuxState: Ethernet40: state db mux state: standby
Jul 20 13:31:15.683784 switch_tor_1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:179 handleMuxStateNotification: Ethernet40: state db mux state: Standby

Jul 20 13:31:16.275418 switch_tor_1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:485 handleStateChange: Ethernet72: Received link prober event, new state: Unknown
Jul 20 13:31:16.275436 switch_tor_1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:505 handleStateChange: Ethernet72: (P: Wait, M: Standby, L: Up) -> (P: Unknown, M: Standby, L: Up)

(message for Ethernet72 doesn't received)
Jul 20 13:31:18.044658 switch_tor_1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:1224 handleMuxWaitTimeout: Ethernet72: orchagent timed out responding to linkmgrd, current state: (P: Unknown, M: Standby, L: Up)
\----> CONNECTION TIMEOUT!!
```

 
Connectivity problem beetween linkmgrd and orchagent should be fixed
Or maybe Active-Active state machine logic should be updated in order to simplify the number of state swithing

**Comment by keboliu** [comment]
Hi @zjswhhh , do you already have an ETA for fixing this issue?

**Comment by zjswhhh** [comment]
> Hi @zjswhhh , do you already have an ETA for fixing this issue?

Hi @keboliu  - do you still have a full copy of the syslog? If so, can you please share? Thanks!

**Comment by ayurkiv-nvda** [comment]
Hello @zjswhhh 

Here are full **show techsupport**, tcpdump and NIC logs both switches
[sonic_dump_t-A.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/12284361/sonic_dump_t-A.tar.gz)
[sonic_dump_t-B.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/12284362/sonic_dump_t-B.tar.gz)
[tcpdump_capture_and_nic_log.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/12284367/tcpdump_capture_and_nic_log.tar.gz)

Traffic was disrupted  on 2 interfaces (**Ethernet72** - 192.168.0.36, **Ethernet80** - 192.168.0.40) :
```
E       Traffic on server 192.168.0.36 was disrupted for 11.871118068695068s. Maximum allowed disruption: 10s
E       Traffic on server 192.168.0.40 was disrupted for 11.871477127075195s. Maximum allowed disruption: 10s
```

**Comment by zjswhhh** [comment]
> Hello @zjswhhh
> 
> Here are full **show techsupport**, tcpdump and NIC logs both switches [sonic_dump_t-A.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/12284361/sonic_dump_t-A.tar.gz) [sonic_dump_t-B.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/12284362/sonic_dump_t-B.tar.gz) [tcpdump_capture_and_nic_log.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/12284367/tcpdump_capture_and_nic_log.tar.gz)
> 
> Traffic was disrupted on 2 interfaces (**Ethernet72** - 192.168.0.36, **Ethernet80** - 192.168.0.40) :
> 
> ```
> E       Traffic on server 192.168.0.36 was disrupted for 11.871118068695068s. Maximum allowed disruption: 10s
> E       Traffic on server 192.168.0.40 was disrupted for 11.871477127075195s. Maximum allowed disruption: 10s
> ```

Thanks @ayurkiv-nvda - I didn't get a chance to check today. Will provide an update by middle of the week.

**Comment by zjswhhh** [comment]
Hi @ayurkiv-nvda @keboliu - as you probably know when a state change happens, the message passes through:
`linkmgrd -> orchagent -> ycabled -> gRPC server` 

```
// mux state swich triggered by linkmgrd 
Jul 20 13:31:15.045563 r-tigon-20 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:1027 switchMuxState: Ethernet72: Switching MUX state to 'Standby'

// there is a periodically gRPC state checker, it found that state is active
Jul 20 13:31:23.280194 r-tigon-20 NOTICE pmon#ycabled: calling RPC for getting forwarding state port = Ethernet72 portid 1 peer portid 0 read_side 1
Jul 20 13:31:23.282107 r-tigon-20 NOTICE pmon#ycabled: forwarding state RPC received response port = Ethernet72 portids [0, 1] read_side 1
Jul 20 13:31:23.282107 r-tigon-20 NOTICE pmon#ycabled: forwarding state RPC received response port = Ethernet72 state values = [True, True] read_side 1
Jul 20 13:31:23.282808 r-tigon-20 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:274 handleProbeMuxStateNotification: Ethernet72: app db mux state: Active

// so linkmgrd tried change to "standby" again
Jul 20 13:31:23.283064 r-tigon-20 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:1027 switchMuxState: Ethernet72: Switching MUX state to 'Standby'

// but still, orchagent didn't react on the state change 
Jul 20 13:31:26.283113 r-tigon-20 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:1224 handleMuxWaitTimeout: Ethernet72: orchagent timed out responding to linkmgrd, current state: (P: Unknown, M: Standby, L: Up)
```

If you check `swss.rec` log (it has APP DB records that orchagent consumed), you will see for this state change, the message for Ethernet72 and Ethernet80 wasn't consumed. 
![image](https://github.com/sonic-net/sonic-buildimage/assets/26625909/37229620-756a-49dd-b171-909b374157c3)

This looks like a redis db issue and it's actually the 2rd time I saw this. I will be starting an email internally to track this. Will update once I have more!

**Comment by ayurkiv-nvda** [comment]
Thank you, @zjswhhh , great analysis!

**Comment by ayurkiv-nvda** [comment]
Hello @zjswhhh 
Do we have some progress with this bug?

**Comment by zjswhhh** [comment]
> Hello @zjswhhh Do we have some progress with this bug?

Hi @ayurkiv-nvda  - sorry I forgot to update you. 

Turns out `orchagent` did react and consume the DB entry but it was delayed so much. 
```
Jul 20 13:31:29.633725 r-tigon-20 NOTICE swss#orchagent: :- setState: [Ethernet72] Set MUX state from active to standby.
```

The delay was because `orchagent` was busy creating route entries: 
```
Jul 20 13:31:23.343664 r-tigon-20 NOTICE syncd#SDK: [SAI_UTILS.NOTICE] mlnx_sai_utils.c[2315]- mlnx_bulk_statuses_print: [BULK_CREATE] 1000 Routes: 1000 success, 0 not executed, 0 failed
Jul 20 13:31:23.343664 r-tigon-20 NOTICE syncd#SDK: :- inc: 10087 (calls 13) Syncd::processBulkCreateEntry(route_entry) CREATE op took: 5026 ms
Jul 20 13:31:23.353927 r-tigon-20 NOTICE swss#orchagent: :- inc: 10087 (calls 13) RedisRemoteSaiInterface::bulkCreate(route_entry) op took: 6101 ms
Jul 20 13:31:23.446836 r-tigon-20 NOTICE syncd#SDK: :- inc: 10092 (calls 15) Syncd::syncUpdateRedisBulkQuadEvent op took: 587 ms
```

This amount of route entry creation is not expected for the test you ran. Is there any chance you were running any other tasks or tests on the device simultaneously?

**Comment by ayurkiv-nvda** [comment]
Hello @zjswhhh 
Thank you for the explanation and sorry for the delays
We found this bug during the community test run and it was successfully reproduced many times.  There were no other tests at the same time. 
But it is interesting that there was route creation at that moment.
I can try to reproduce this issue a few more times. 
Maybe we will see route creation again and it will help to find a confirm that there is a  correlation and your assumption is correct

**Comment by ayurkiv-nvda** [comment]
I managed to reproduce bug one more time and also tried to run simple  **config reload** few times
Route entries creation logs ( `[BULK_CREATE] 1000 Routes: 1000 success,`)  appeared every time when during config reload.

I have added new techsupport and log (there are might be 2 hours offset between sonic-mgmt log and log from Sonic): 
`Step 3 Active-ToR go to "config reload" -> traffic switched to ToR-2, ToR-1 becomes standby` appeared at 16:42:22 in test_log.log file and 14:22:22 in techsupport

It looks like some kind of timing issue, orchagent  is strongly busy during this period, can we handle it somehow?

[nic_simulator_vm-t1.log](https://github.com/sonic-net/sonic-buildimage/files/13268810/nic_simulator_vm-t1.log)
[t1_.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/13268963/t1_.tar.gz)
[t2.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/13268975/t2.tar.gz)
[test_log.log](https://github.com/sonic-net/sonic-buildimage/files/13268990/test_log.log)

**Comment by zjswhhh** [comment]
> I managed to reproduce bug one more time and also tried to run simple **config reload** few times Route entries creation logs ( `[BULK_CREATE] 1000 Routes: 1000 success,`) appeared every time when during config reload.
> 
> I have added new techsupport and log (there are might be 2 hours offset between sonic-mgmt log and log from Sonic): `Step 3 Active-ToR go to "config reload" -> traffic switched to ToR-2, ToR-1 becomes standby` appeared at 16:42:22 in test_log.log file and 14:22:22 in techsupport
> 
> It looks like some kind of timing issue, orchagent is strongly busy during this period, can we handle it somehow?
> 
> [nic_simulator_vm-t1.log](https://github.com/sonic-net/sonic-buildimage/files/13268810/nic_simulator_vm-t1.log) [t1_.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/13268963/t1_.tar.gz) [t2.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/13268975/t2.tar.gz) [test_log.log](https://github.com/sonic-net/sonic-buildimage/files/13268990/test_log.log)

Hi @Ndancejic - can you please take a look at logs above, is it expected to see orchagent bulk creating route entries after config reload?

**Comment by zjswhhh** [comment]
Discussed with @prsunny offline:
* Orchagent bulk creating route entries after `config reload` can be expected. 
* Agree that there can be a timing issue here, but `config reload` is a `non-production` scenario. Device should already be isolated at this point. 

Hence we consider it as a flaky test instead of image issue. Closing the issue now.
