### ISSUE TITLE
Unable to perform Autogeneration of CLI using Yang model during build with all Yang models

### ISSUE THREAD

**Issue by Purnimayeggina** [sonic-net/sonic-buildimage#16084]
Description:
We encountered an issue while attempting to utilize the Auto Generation tool to extract the CLI  from a Yang model. Our updated the manifest.json file to facilitate this. However, we encountered a roadblock: the automatic enabling of CLI for yang models during the build process did not succeed. Our intention was to obtain autogenerated CLI plugins, specifically for the CONFIG and SHOW functionalities, for all yang models. Unfortunately, despite our efforts, the automated CLI generation only worked for specific yang models which are generated manually for specific yang models.

Expected Behavior:
We expected that after updating the manifest.json file and initiating the build process, the Auto Generation tool would automatically generate CLI plugins for both CONFIG and SHOW functionalities for all yang models present, streamlining the process and removing the need for manual intervention.

Current Behavior:
Contrary to our expectations, the Auto Generation tool only successfully generated CLI plugins for certain yang models, requiring manual initiation for each specific model instead of applying the functionality universally.

Steps to Reproduce:

Update the manifest.json file to include all yang models.
Initiate the build process using the Auto Generation tool.
Observe that the CLI plugins are only generated for specific yang models only when generated manually using
admin@sonic: sonic-cli-gen generate config <yang_model_name>
admin@sonic: sonic-cli-gen generate show <yang_model_name> , but not for all yang models.

**Comment by vadymhlushko-mlnx** [comment]
Hi @Purnimayeggina!

1. As specified in the HLD section [SONiC CLI Auto-generation tool as part of sonic-package-manager](https://github.com/sonic-net/SONiC/blob/master/doc/cli_auto_generation/cli_auto_generation.md#sonic-cli-auto-generation-tool-as-part-of-sonic-package-manager) the CLI autogeneration will only work when you are trying to `install` or `upgrade` the SONiC application extension. So, the CLI autogeneration is not available during the SONiC image build by design.

2. Not every YANG model is suitable for CLI autogeneration. For example, you cannot generate CLI for the: [sonic-types.yang](https://github.com/vadymhlushko-mlnx/sonic-buildimage/blob/master/src/sonic-yang-models/yang-templates/sonic-types.yang.j2), [sonic-extension.yang](https://github.com/vadymhlushko-mlnx/sonic-buildimage/blob/master/src/sonic-yang-models/yang-templates/sonic-extension.yang.j2)

3. If you are trying to autogenerate CLI for the feature in SONiC which already has a manually written CLI (by some developer), you should delete the existing CLI and then generate autogenerated CLI, because they will conflict with each other.

4. I'm not 100% sure that right now, you could autogenerate CLI for every YANG model, because YANG models have been changing over time, and maybe need to enhance the SONiC CLI Autogeneration tool accordingly

5. Please try to autogenerate CLI manually via the `sonic-cli-gen` tool for the YANG models that you're interested in, if there are some errors, send me an error itself, and the tech support dump, and I'll try to help

**Comment by Purnimayeggina** [comment]
Thanks for the comments, Below are the same steps followed for a sample yang model  to generate CLI 
Description:
1. We Intended to autogenerate CLI when uprgaded the SONiC application extension.
2. As part of these we designed a sample yang model for testing the auto generating of CLI 
3.The sample yang model is designed that is located in path: /usr/local/yang-models 
module sonic-allow {

    yang-version 1.1;

    namespace "http://github.com/Azure/sonic-allow";

    prefix sallow;

    description "ALLOW yang Module for SONiC OS";
    revision 2023-01-03 {
        description "First Revision";
    }

    container sonic-allow {
        container ALLOW_SESSION {
            description "Allow_session  for config_db.json";
            list ALLOW_SESSION_LIST {
                key "name";
                leaf name {
                    type string {
                        length 1..64;
                    }
                }
                leaf allow {
                    type string {
                        length 1..64;
                    }
                    default "enable";
                }
            }
        }
    }
}

The changes made are
1.In the manifest.py file changed "False" to "True"
path: sonic-utilities/sonic_package_manager/manifest.py
<img width="518" alt="image" src="https://github.com/sonic-net/sonic-buildimage/assets/131232786/aea11e29-41cb-4a2a-ab8b-ed83ae3ec6cd">
2.for a particular docker image file added the label for yang model
<img width="570" alt="image" src="https://github.com/sonic-net/sonic-buildimage/assets/131232786/e039366b-29b3-405a-9e57-ee8f5bdc2dcc">

3.for the same docker in manifest.json file added  "true" for auto-generation-show and auto-generation-config
"cli": {
        "mandatory": false,
        "show": "",
        "config": "",
        "clear": "",
        "auto-generate-show": "true",
        "auto-generate-config": "true"
    }
with all this changes upgraded the SONiC extension application but we failed to generate CLI for the sample yang model 
Expected Behaviour:
1.After the upgradation of SONiC extension application we expected the auto generated CLI for sonic-allow.yang in model in this path/usr/local/yang-models
path : /usr/local/lib/python3.7/dist-packages/config/plugins/auto/
path : /usr/local/lib/python3.7/dist-packages/show/plugins/auto/
Logs: Attached the syslog file 
[syslog.zip](https://github.com/sonic-net/sonic-buildimage/files/12481496/syslog.zip)

**Comment by vadymhlushko-mlnx** [comment]
> Thanks for the comments, Below are the same steps followed for a sample yang model to generate CLI Description:
> 
> 1. We Intended to autogenerate CLI when uprgaded the SONiC application extension.
> 2. As part of these we designed a sample yang model for testing the auto generating of CLI
>    3.The sample yang model is designed that is located in path: /usr/local/yang-models
>    module sonic-allow {
>    yang-version 1.1;
>    namespace "[http://github.com/Azure/sonic-allow](https://github.com/Azure/sonic-allow)";
>    prefix sallow;
>    description "ALLOW yang Module for SONiC OS";
>    revision 2023-01-03 {
>    description "First Revision";
>    }
>    container sonic-allow {
>    container ALLOW_SESSION {
>    description "Allow_session  for config_db.json";
>    list ALLOW_SESSION_LIST {
>    key "name";
>    leaf name {
>    type string {
>    length 1..64;
>    }
>    }
>    leaf allow {
>    type string {
>    length 1..64;
>    }
>    default "enable";
>    }
>    }
>    }
>    }
>    }
> 
> The changes made are 1.In the manifest.py file changed "False" to "True" path: sonic-utilities/sonic_package_manager/manifest.py <img alt="image" width="518" src="https://private-user-images.githubusercontent.com/131232786/264513712-aea11e29-41cb-4a2a-ab8b-ed83ae3ec6cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjU3ODEsIm5iZiI6MTcxMTQ2NTQ4MSwicGF0aCI6Ii8xMzEyMzI3ODYvMjY0NTEzNzEyLWFlYTExZTI5LTQxY2ItNGEyYS1hYjhiLWVkODNhZTNlYzZjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxNTA0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzVkMjc0MTU2ZDc3NGEyYzY4MmQ3Y2JhZTFlZDllY2EzZDVkM2ZkOTIyMDNmMmRjZDFlODY0MmM4YTJjZTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JwW0r8--dnKD0B5dsAjoJ6PS8JCaGSpsUk_szMPnLfM"> 2.for a particular docker image file added the label for yang model <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/131232786/264514757-e039366b-29b3-405a-9e57-ee8f5bdc2dcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjU3ODEsIm5iZiI6MTcxMTQ2NTQ4MSwicGF0aCI6Ii8xMzEyMzI3ODYvMjY0NTE0NzU3LWUwMzkzNjZiLTI5YjMtNDA1YS05ZTU3LWVlOGY1YmRjMmRjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxNTA0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWE0OWNhNDkwN2MyNzBhZDgxZDhjMzc1OGVmOTE4ZWZlZjJkYjc3ZWUwMjY0MTNlMTU4MjUzOWExNTg4ZGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-cYPcIum6420La4OpMPekTdtUr3ePyAtsH5GR7b3jgs">
> 
> 3.for the same docker in manifest.json file added "true" for auto-generation-show and auto-generation-config "cli": { "mandatory": false, "show": "", "config": "", "clear": "", "auto-generate-show": "true", "auto-generate-config": "true" } with all this changes upgraded the SONiC extension application but we failed to generate CLI for the sample yang model Expected Behaviour: 1.After the upgradation of SONiC extension application we expected the auto generated CLI for sonic-allow.yang in model in this path/usr/local/yang-models path : /usr/local/lib/python3.7/dist-packages/config/plugins/auto/ path : /usr/local/lib/python3.7/dist-packages/show/plugins/auto/ Logs: Attached the syslog file [syslog.zip](https://github.com/sonic-net/sonic-buildimage/files/12481496/syslog.zip)

@Purnimayeggina

1. I've tried to manually generate the `config` and `show` CLI's for this `sonic-allow.yang` - it was successful
2. As far as I understand, you are trying to do a sonic package upgrade from version X to version Y via `sonic-package-manager` or `spm`, could you please send me a 2 files - manifest.json (version X) and manifest.json (version Y), so I will be able to help you.
3. Here you could find an example of [sonic-example-extension](https://github.com/stepanblyschak/sonic-example-extension)

**Comment by volodymyrsamotiy** [comment]
According to comment by @vadymhlushko-mlnx, it is expected behavior: CLI autogeneration is not available during the SONiC image build by design.
