### ISSUE TITLE
"show queue counters" does not show stats for all queues with traffic

### ISSUE THREAD

**Issue by prabhataravind** [sonic-net/sonic-buildimage#16202]
With the introduction of changes via PR https://github.com/sonic-net/sonic-swss/pull/2474, "show queue counters" shows stats only for queues that are configured via config DB. This has created a regression where ports with active traffic do not show up in "show queue counters" if they are missing in config DB. A couple of such examples are:

1. UC7 queue which is used as the default queue for all control traffic
2. Multicast queues with non-zero counters

I have verified with a sonic image without the changes from PR 2474 that these counters show up and they go missing when these changes are added back.

"show queue counters" without the changes from PR 2474:

Port    TxQ    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
-----------  -----  --------------  ---------------  -----------  ------------
  Ethernet124    UC0               0                0            0             0
  Ethernet124    UC1               0                0            0             0
  Ethernet124    UC2               0                0            0             0
  Ethernet124    UC3               0                0            0             0
  Ethernet124    UC4               0                0            0             0
  Ethernet124    UC5               0                0            0             0
  Ethernet124    UC6               0                0            0             0
  Ethernet124    UC7             413           410082            0             0 <<<<<<<<<<
  Ethernet124    UC8               0                0            0             0
  Ethernet124    UC9               0                0            0             0
  Ethernet124   MC10               0                0            0             0
  Ethernet124   MC11            2849           267806            0             0 <<<<<<<<<<
  Ethernet124   MC12               0                0            0             0
  Ethernet124   MC13               0                0            0             0
  Ethernet124   MC14               0                0            0             0
  Ethernet124   MC15               0                0            0             0
  Ethernet124   MC16               0                0            0             0
  Ethernet124   MC17               0                0            0             0
  Ethernet124   MC18               0                0            0             0
  Ethernet124   MC19               0                0            0             0

"show queue counters" with changes from PR 2474:

Port    TxQ    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
-----------  -----  --------------  ---------------  -----------  ------------
Ethernet124    UC0               0                0            0           N/A
Ethernet124    UC1               0                0            0           N/A
Ethernet124    UC2               0                0            0           N/A
Ethernet124    UC3               0                0            0           N/A
Ethernet124    UC4               0                0            0           N/A
Ethernet124    UC5               0                0            0           N/A
Ethernet124    UC6               0                0            0           N/A

**Comment by rlhui** [comment]
@vadymhlushko-mlnx , please provide link to PR for the fix? thanks.

**Comment by rlhui** [comment]
Fixes for 202205 branch: 
https://github.com/sonic-net/sonic-swss/pull/2882
https://github.com/sonic-net/sonic-buildimage/pull/16232

**Comment by rlhui** [comment]
@prabhataravind please help check if this issue can be closed?  Thanks.

**Comment by prabhataravind** [comment]
[like]  Prabhat Aravind reacted to your message:
________________________________
