### ISSUE TITLE
buffer_pool

### ISSUE THREAD

**Issue by GoGSuccOpO** [sonic-net/sonic-buildimage#16315]
In SONIC, configure dynamic headroom. In Redis, there is a table named buffer_pool. What does this buffer_pool refer to and its relationship with headroom?

**Comment by vmittal-msft** [comment]
Please refer https://github.com/sonic-net/sonic-swss/blob/master/doc/swss-schema.md for more details.

;Stores buffer pools

key             = BUFFER_POOL_TABLE:poolname    ; The poolname can be one of ingress_lossless_pool, ingress_lossy_pool, egress_lossless_pool, and egress_lossy_pool or other used-defined pools.
mode            = "dynamic" / "static"          ; Whether the pool uses dynamic threshold or static threshold.
type            = "ingress" / "egress"          ; Whether the pool serves for ingress or egress traffic
size            = 1*10DIGIT                     ; The size of the shared buffer pool
xoff            = 1*10DIGIT                     ; The size of the shared headroom pool. Available only for ingress_lossless_pool.
