### ISSUE TITLE
Master build does not load successfully on the Accton AS4630_54PE

### ISSUE THREAD

**Issue by samitabh** [sonic-net/sonic-buildimage#16436]
#### Description

Master build does not load successfully on the Accton AS4630_54PE

#### Steps to reproduce the issue:
1. Load the latest build from https://sonic-build.azurewebsites.net/ui/sonic/pipelines/138/builds?branchName=master (I loaded Build Id# 353528)
2. The SONiC switch comes up but init fails 

#### Describe the results you received:

**admin@sonic:~$ sudo cat /var/log/syslog | grep "ERR syncd"**
Sep  4 10:35:40.877255 sonic ERR syncd#syncd: [none] SAI_API_SWITCH:platform_process_command:428 Platform command "init bcm" failed, rc = -1.
Sep  4 10:35:40.877836 sonic ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_FAILURE
Sep  4 10:35:40.877989 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_INIT_SWITCH: true
Sep  4 10:35:40.878091 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_FDB_EVENT_NOTIFY: 0x55c1b2545100
Sep  4 10:35:40.878193 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_PORT_STATE_CHANGE_NOTIFY: 0x55c1b2545110
Sep  4 10:35:40.878297 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_SWITCH_SHUTDOWN_REQUEST_NOTIFY: 0x55c1b2545130
Sep  4 10:35:40.878402 sonic ERR syncd#syncd: :- processQuadEvent: attr: SAI_SWITCH_ATTR_SRC_MAC_ADDRESS: 68:21:5F:48:9F:C1
Sep  4 10:36:45.045587 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 50 passed to sai_api_query
Sep  4 10:36:45.045770 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 51 passed to sai_api_query
Sep  4 10:36:45.045971 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 52 passed to sai_api_query
Sep  4 10:36:45.046121 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 53 passed to sai_api_query
Sep  4 10:36:45.046305 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 54 passed to sai_api_query
Sep  4 10:36:45.046475 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 55 passed to sai_api_query
Sep  4 10:36:45.046620 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 56 passed to sai_api_query
Sep  4 10:36:45.046767 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 58 passed to sai_api_query
Sep  4 10:36:45.046920 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 59 passed to sai_api_query
Sep  4 10:36:45.047067 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:441 Invalid sai_api_t 57 passed to sai_api_query
Sep  4 10:36:49.847823 sonic ERR syncd#syncd: [none] SAI_API_SWITCH:platform_process_command:428 Platform command "init bcm" failed, rc = -1.

**Management IP acquire fails:**
admin@sonic:~$ sudo ifconfig eth0
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 68:21:5f:48:9f:c1  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

#### Describe the results you expected:
Switch should come up successfully.

#### Output of `show version`:

admin@sonic:~$ show version

SONiC Software Version: SONiC.master.353528-559151b41
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: 559151b41
Build date: Sun Sep  3 12:59:40 UTC 2023
Built by: AzDevOps@vmss-soni001X3A

Platform: x86_64-accton_as4630_54pe-r0
HwSKU: Accton-AS4630-54PE
ASIC: broadcom
ASIC Count: 1
Serial Number: 463054PE1950031
Model Number: F0PZZ4654037A
Hardware Revision: N/A
Uptime: 10:38:59 up 4 min,  1 user,  load average: 0.98, 1.12, 0.53
Date: Mon 04 Sep 2023 10:38:59

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-gbsyncd-broncos        latest                    087612e54a37   349MB
docker-gbsyncd-broncos        master.353528-559151b41   087612e54a37   349MB
docker-gbsyncd-credo          latest                    24df43750df5   319MB
docker-gbsyncd-credo          master.353528-559151b41   24df43750df5   319MB
docker-syncd-brcm             latest                    53a711b7016f   673MB
docker-syncd-brcm             master.353528-559151b41   53a711b7016f   673MB
docker-macsec                 latest                    4dd1dc665f42   325MB
docker-dhcp-relay             latest                    5850b9cadf8c   306MB
docker-orchagent              latest                    5c6a6af9a8a3   335MB
docker-orchagent              master.353528-559151b41   5c6a6af9a8a3   335MB
docker-eventd                 latest                    a6c493be2add   299MB
docker-eventd                 master.353528-559151b41   a6c493be2add   299MB
docker-fpm-frr                latest                    772b08c86e76   355MB
docker-fpm-frr                master.353528-559151b41   772b08c86e76   355MB
docker-nat                    latest                    c393215b3913   326MB
docker-nat                    master.353528-559151b41   c393215b3913   326MB
docker-sflow                  latest                    8c3cad3867f1   325MB
docker-sflow                  master.353528-559151b41   8c3cad3867f1   325MB
docker-teamd                  latest                    6ba79af1fcb7   323MB
docker-teamd                  master.353528-559151b41   6ba79af1fcb7   323MB
docker-sonic-telemetry        latest                    df67cf638f15   600MB
docker-sonic-telemetry        master.353528-559151b41   df67cf638f15   600MB
docker-snmp                   latest                    16f3ec1e458a   338MB
docker-snmp                   master.353528-559151b41   16f3ec1e458a   338MB
docker-platform-monitor       latest                    93e32887e714   420MB
docker-platform-monitor       master.353528-559151b41   93e32887e714   420MB
docker-router-advertiser      latest                    c76e9cf271e9   299MB
docker-router-advertiser      master.353528-559151b41   c76e9cf271e9   299MB
docker-lldp                   latest                    da58f0eb7bdd   341MB
docker-lldp                   master.353528-559151b41   da58f0eb7bdd   341MB
docker-mux                    latest                    73b04c4fe1a8   348MB
docker-mux                    master.353528-559151b41   73b04c4fe1a8   348MB
docker-database               latest                    41c327b317b9   299MB
docker-database               master.353528-559151b41   41c327b317b9   299MB
docker-sonic-mgmt-framework   latest                    fbba1fc55cd9   416MB
docker-sonic-mgmt-framework   master.353528-559151b41   fbba1fc55cd9   416MB

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by Lewis-Kang** [comment]
Maybe, you can give this [PR](https://github.com/sonic-net/sonic-buildimage/pull/15859) a try to see it helps or not.

**Comment by akenliu** [comment]
There are some PRs that are not merged by community now, these are related to port and switch.
https://github.com/sonic-net/sonic-buildimage/pull/13973
https://github.com/sonic-net/sonic-buildimage/pull/11805
https://github.com/sonic-net/sonic-buildimage/pull/15859

You can try to sync these modification manually.

Note: 
Lewis-Kang help to identify the issue can be fixed by PR-15859.

**Comment by jeffhtgt** [comment]
> Maybe, you can give this [PR](https://github.com/sonic-net/sonic-buildimage/pull/15859) a try to see if it helps.

The above PR should work.  It seems to be stuck in limbo with no reviewers.  You will also want this PR (also stuck in limbo with no review despite all checks passing):

https://github.com/sonic-net/sonic-buildimage/pull/16464

**Comment by samitabh** [comment]
The PR (https://github.com/sonic-net/sonic-buildimage/pull/15859) helped !
The hardware came up fine.
thanks..
