### ISSUE TITLE
"orchagent: :- doTask: Failed to process invalid buffer task" Error messages with system ports

### ISSUE THREAD

**Issue by saksarav-nokia** [sonic-net/sonic-buildimage#16488]
#### Description
Sep  5 14:37:50.241220 ixre-egl-board7 NOTICE swss0#orchagent: :- processQueue: Set buffer queue ixre-egl-board7:asic0:Ethernet104:0-2 to BUFFER_PROFILE_TABLE:egress_lossy_profile
Sep  5 14:37:50.241220 ixre-egl-board7 ERR swss0#orchagent: :- processQueue: Port with alias:ixre-egl-board7|asic0|Ethernet104 not found
Sep  5 14:37:50.241220 ixre-egl-board7 ERR swss0#orchagent: :- doTask: Failed to process invalid buffer task

#### Steps to reproduce the issue:
1.Add the BUFFER_QUEUE config with system ports like following
   "BUFFER_QUEUE": {
        "ixre-egl-board7|asic0|Ethernet0|0-2": {
            "profile": "egress_lossy_profile"
        },
        "ixre-egl-board7|asic0|Ethernet0|3-4": {
            "profile": "egress_lossless_profile"
        },
        "ixre-egl-board7|asic0|Ethernet0|5-6": {
            "profile": "egress_lossy_profile"
        },
        "ixre-egl-board7|asic0|Ethernet8|0-2": {
            "profile": "egress_lossy_profile"
        },

2.   switch reboot or config reload
3. Error messages are seen in syslog

#### Describe the results you received:
Error messages in syslog during switch reboot or config reload

#### Describe the results you expected:

No Error messages
#### Output of `show version`:
202205 latest
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by saksarav-nokia** [comment]
@vmittal-msft for viz

**Comment by prgeor** [comment]
@rlhui could you help take a look for this chassis related failure

**Comment by vmittal-msft** [comment]
@saksarav-nokia Can you please share complete config file you are using ? Does system ports string has different format that the one mentioned above ?

**Comment by vmittal-msft** [comment]
@saksarav-nokia  I checked my system and don't see these messages after reload.

![image](https://github.com/sonic-net/sonic-buildimage/assets/46945843/90d3b915-598d-4016-ac1b-116a81846049)

**Comment by saksarav-nokia** [comment]
Looks like the following code is failing since getPort is failing for system port. The systemport is added to m_portList map in addSystemPort->setPort. I see the  "addSystemPorts: Added system port" logs for all the ports even before the Queue config is processed. So not sure why getPort is failing.
for (string port_name : port_names)
    {
        Port port;
        SWSS_LOG_DEBUG("processing port:%s", port_name.c_str());
        if (!gPortsOrch->getPort(port_name, port))
        {
            SWSS_LOG_ERROR("Port with alias:%s not found", port_name.c_str());
            return task_process_status::task_invalid_entry;
        }

   
bool PortsOrch::getPort(string alias, Port &p)
{
    SWSS_LOG_ENTER();

    if (m_portList.find(alias) == m_portList.end())
    {
        return false;
    }
    else
    {
        p = m_portList[alias];
        return true;
    }
}

**Comment by saksarav-nokia** [comment]
@vmittal-msft , i debugged these errors and here is my finding
1) Orchagent adds the ports of local ports with front panel port names as alias for asic's own ports and as system ports for remote system ports as attached in sys_port_asic0.txt and sys_port_asic1.txt. In other words, the m_portList map doesn't have system ports for the local ports and it has system ports only for remote ports.
2) But the config_db, the BUFFER_PROFILE and QUEUE config are configured with system port for local ports and also for remote system ports. so when BufferOrch::processQueue calls getPort for system ports of local ports, the getPort returns false and error messages are printed and the  buffer profile is not applied.
This needs to be fixed.
[sys_port_asic0.txt](https://github.com/sonic-net/sonic-buildimage/files/12876081/sys_port_asic0.txt)
[sys_port_asic1.txt](https://github.com/sonic-net/sonic-buildimage/files/12876082/sys_port_asic1.txt)
[error.txt](https://github.com/sonic-net/sonic-buildimage/files/12876083/error.txt)

**Comment by saksarav-nokia** [comment]
Not seeing these messages any more. closing it
