### ISSUE TITLE
Chassis: pmon docker fails when DEVICE_METADATA is not available during boot

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#16526]
#### Description

During a fresh image install, it is observed that pmon docker fails to come up when no config has been applied yet. pmon docker is important as it hosts the chassisd daemon to populate chassis db, which may be required in some circumstances to check system state before applying any config.

The root cause for the issue is failure to generate  docker-pmon supervisord.conf file from 
docker-pmon.supervisord.conf

The following check in the file fails due to missing DEVICE_METADATA
```
{% if 'subtype' in DEVICE_METADATA['localhost'] and DEVICE_METADATA['localhost']['subtype'] == 'DualToR' %}
```

https://github.com/sonic-net/sonic-buildimage/blob/202205/dockers/docker-platform-monitor/docker-pmon.supervisord.conf.j2#L115

#### Steps to reproduce the issue:
1. Boot a Chassis after image install without loading any config_db json or minigraph file.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
Hi @abdosi , please assign this to me.

**Comment by prgeor** [comment]
@anamehra assigning as per request.
