### ISSUE TITLE
SONiC ZTP: Credentials doesn't work after upgrading device from ZTP flow

### ISSUE THREAD

**Issue by esapgan** [sonic-net/sonic-buildimage#16565]
#### Steps to reproduce the issue:
1. Send a new image file using ztp.json  and install it as the next boot image
2. The device will be automatically rebooted once the ZTP flow is complete
3. Once the device boots up with the new image, try to login using the default/root creds and it doesn't work.

#### Describe the results you received:
-	Rebooting via ZTP

<img width="779" alt="image" src="https://github.com/sonic-net/sonic-buildimage/assets/22642994/7f9f3abd-8af2-4b2d-8f6b-1f2831f91312">

-	Device boots up on the new image, but creds didn’t work

<img width="685" alt="image" src="https://github.com/sonic-net/sonic-buildimage/assets/22642994/f899eb1e-f556-4a3a-86a2-dc5e350b22ab">

#### Describe the results you expected:

Once the ZTP is finished and the device boots up with the new image, creds should work to login into the device.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by adyeung** [comment]
@rajendra-dendukuri pls help take a look
