### ISSUE TITLE
[202205] [cli] Performance degradation of show/config cli because of swsssdk import 

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#16595]
#### Description

On the latest 202205 image, a diff of 0.2 - 0.3 sec is observed (for slower CPU's) when running show cli's

#### Steps to reproduce the issue:
1. time python3 -c "from sonic_py_common import device_info"
2. run the same command on a 20205 image built before this change https://github.com/sonic-net/sonic-py-swsssdk/pull/138 

#### Describe the results you received:

time diff of 0.2 - 0.3 sec per run.  This is reflected in most of the show cli's since many of them import device_info which is still using swsssdk in 202205. 

Problem is in the redis package used by swsssdk. It was recently bumped to 5.0.0 and the import is taking more time compared to 3.5.3

There was some discussion on moving away from swsssdk for sonic_py_common here but the effort is discontinued, https://github.com/sonic-net/sonic-buildimage/pull/10099#issuecomment-1216022388

That change should fix this.

#### Describe the results you expected:

No perf degradation

**Comment by judyjoseph** [comment]
As mentioned here https://github.com/sonic-net/sonic-buildimage/pull/10099#issuecomment-1216022388, it is tough to move to swsscommon in 202205. @yxieca can we add this to 202205 release notes ?

**Comment by yxieca** [comment]
Release notes updated.
