### ISSUE TITLE
[Bookworm] Update platform-modules-nokia for Bookworm

### ISSUE THREAD

**Issue by saiarcot895** [sonic-net/sonic-buildimage#16734]
#### Description

In the bookworm branch, platform-modules-nokia has been disabled from the Broadcom build as it needs changes for Bookworm. This needs to be updated for Bookworm.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vmittal-msft** [comment]
@saiarcot895 Are you following up with Nokia folks or need help ?
