### ISSUE TITLE
[202205][hostcfgd]: FeatureHandler might override user configuration

### ISSUE THREAD

**Issue by nazariig** [sonic-net/sonic-buildimage#16841]
#### Description

hostcfgd is using a subscribe/listen way to handle configuration data. It handles feature configuration like this:

1. subscribe to CONFIG DB FEATURE table
2. read initial data from CONFIG DB FEATURE table and call FeatureHandler.sync_state_field to process the initial data
3. As FEATURE table "state" field might be a template, FeatureHandler is responsible for rendering it
4. FeatureHandler will "resync" the rendered "state" back to CONFIG DB

However, if there is a user configuration occurs between step 2 and step 3, user configuration will be silently ignored and override. 

Here is an example:
1. subscribe to CONFIG DB FEATURE table
2. read initial FEATURE data, say sflow.state = disabled. FeatureHandler.sync_state_field get an input that "sflow.state = disabled"
3. user issued command "config feature state sflow enabled". Now sflow.state is enabled in FEATURE table.
4. FeatureHandler.sync_state_field continues running and resync "sflow.state = disabled" back to FEATURE table

In this case, user configuration in step#3 will be override.

#### Steps to reproduce the issue:
1. ONIE install `202012` image
2. Login into the switch, then `sonic-installer` upgrade to `202205` image
3. Enable `sflow` feature 
```bash
sudo config feature state sflow enabled
```
4. Enable `sflow`
```bash
sudo config sflow enable
```
5. Do basic `sflow` config
```bash
sudo config sflow collector add collector0 50.0.0.2 --port 6343 --vrf default
sudo config sflow interface disable all
sudo config sflow interface enable Ethernet0
sudo config sflow interface enable Ethernet120
```
6. Observe `sflow` feature is disabled
```
show feature status
Feature             State            AutoRestart     SetOwner
------------------  ---------------  --------------  ----------
bgp                 enabled          enabled
database            always_enabled   always_enabled
dhcp_relay          enabled          enabled         local
lldp                enabled          enabled
macsec              disabled         enabled         local
mgmt-framework      enabled          enabled
mux                 always_disabled  enabled
nat                 disabled         enabled
pmon                enabled          enabled
radv                enabled          enabled
sflow               disabled         enabled
snmp                enabled          enabled
swss                enabled          enabled
syncd               enabled          enabled
teamd               enabled          enabled
telemetry           enabled          enabled
what-just-happened  enabled          enabled         local
```

#### Describe the results you received:
```
2023-09-20 11:54:02 [    INFO] (proxy_ssh_engine.py:444) Player: 10.210.24.97, Running cmd: sudo config feature state sflow enabled
2023-09-20 11:54:05 [    INFO] (proxy_ssh_engine.py:444) Player: 10.210.24.97, Running cmd: sudo config sflow enable
2023-09-20 11:54:07 [    INFO] (proxy_ssh_engine.py:622) Failed to enable unit: Unit file /etc/systemd/system/sflow.service is masked.
2023-09-20 11:54:07 [    INFO] (proxy_ssh_engine.py:444) Player: 10.210.24.97, Running cmd: sudo config sflow collector add collector0 50.0.0.2 --port 6343 --vrf default
2023-09-20 11:54:08 [    INFO] (proxy_ssh_engine.py:444) Player: 10.210.24.97, Running cmd: echo "$?"
2023-09-20 11:54:09 [    INFO] (proxy_ssh_engine.py:444) Player: 10.210.24.97, Running cmd: sudo config sflow interface disable all
2023-09-20 11:54:11 [    INFO] (proxy_ssh_engine.py:444) Player: 10.210.24.97, Running cmd: sudo config sflow interface enable Ethernet0
2023-09-20 11:54:12 [    INFO] (proxy_ssh_engine.py:444) Player: 10.210.24.97, Running cmd: sudo config sflow interface enable Ethernet120
```

#### Describe the results you expected:
Feature is enabled and `sflow` interface configuration could be checked by command `show sflow interface`

#### Output of `show version`:
* N/A

#### Output of `show techsupport`:
* N/A

#### Additional information you deem important (e.g. issue happens only occasionally):

* N/A

**Comment by nazariig** [comment]
@yxieca FYI

**Comment by yxieca** [comment]
Merged fix.
