### ISSUE TITLE
[Bookworm] Paramiko can't connect to DUT

### ISSUE THREAD

**Issue by saiarcot895** [sonic-net/sonic-buildimage#16851]
#### Description

In the Bookworm upgrade, looks like Paramiko has some trouble connecting to the DUT, in `tacacs/test_accounting.py`

Test log: https://elastictest.org/scheduler/testplan/652625b1f773ca326e14c0fd?testcase=tacacs%2Ftest_accounting.py&type=console

#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you expected:

Snippet of log:

```
        if len(agreed_keys) == 0:
>           raise SSHException(
                "Incompatible ssh peer (no acceptable host key)"
            )  # noqa
E           paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable host key)

agreed_kex = ['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group16-sha512', 'diffie-hellman-group-exchange-sha256', ...]
agreed_keys = []
client_compress_algo_list = ['none', 'zlib@openssh.com']
client_encrypt_algo_list = ['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com']
client_lang_list = ['']
client_mac_algo_list = ['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', ...]
```

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by dgsudharsan** [comment]
@saiarcot895  Is this fix not into bookworm branch?

**Comment by saiarcot895** [comment]
@dgsudharsan , no, this particular fix needs to be in the master branch, because this is a change in the sonic-mgmt docker itself,  and updates to that docker are currently coming from master branch.

Pulling the latest sonic-mgmt docker should bring in the fix.
