### ISSUE TITLE
[Bookworm] Update fullcone NAT kernel patch for Linux 6.1

### ISSUE THREAD

**Issue by saiarcot895** [sonic-net/sonic-buildimage#16867]
#### Description

The fullcone NAT patch in sonic-linux-kernel needs to be updated for Linux 6.1.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by saiarcot895** [comment]
@kirankella would you be able to work on this?

**Comment by adyeung** [comment]
https://github.com/sonic-net/sonic-linux-kernel/pull/357

**Comment by skg-net** [comment]
@saiarcot895 Can you please update the Quality Metric (Alpha/Beta/GA) for the feature either in this PR comments or in HLD itself based on https://github.com/sonic-net/SONiC/blob/master/doc/SONiC%20feature%20quality%20definition.md
Thanks
