### ISSUE TITLE
[Chassis] : CLI command "show queue counters --voq" not working

### ISSUE THREAD

**Issue by vmittal-msft** [sonic-net/sonic-buildimage#16895]
This command is broken as it is showing NA for all entries. It used to work fine before.

![image](https://github.com/sonic-net/sonic-buildimage/assets/46945843/72bad66a-ac20-4e36-bf62-4d76a8c615e6)

**Comment by kenneth-arista** [comment]
This is seen with the latest DNX SAI 7.1.60.4.

**Comment by kenneth-arista** [comment]
DNX SAI fix forthcoming from Broadcom.

**Comment by arlakshm** [comment]
SAI pr merged. Closing this
