### ISSUE TITLE
Failed to start Docker SONiC Virtual Switch 

### ISSUE THREAD

**Issue by thovikeerthi** [sonic-net/sonic-buildimage#16972]
Hi,
I am trying to run Docker Virtual Switch image following references from community GIThub link https://github.com/sonic-net/sonic-buildimage/blob/master/platform/vs/README.vsdocker.md . Then facing an error as below. Please suggest.

**Steps:**
1. Clone 202305 branch source code

2. Run command 
      $ cd sonic-buildimage/plaform/vs/

3. Using the above shared link, created the docker name space by running following commands:
      $ docker run -id --name sw debian bash
      $ sudo ./create_vnet.sh -n 2 sw
      $ ip netns list

4. Whenever I attempt to start the VS Docker using command, then error is shown as detailed below.
      $ docker run --privileged --network container:sw --name vs -d docker-sonic-vs 

**Error Message:**
sonic@sfsintel:/sonic-path$ docker run --privileged --network container:sw --name vs -d docker-sonic-vs
Unable to find image 'docker-sonic-vs:latest' locally
**docker: Error response from daemon: pull access denied for docker-sonic-vs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.**
See 'docker run --help'.

Please help what is the error in my approach.

**Comment by msosyak** [comment]
I bealive you need to get docker-sonic-vs  image archive and import it to local images.
Thare are two options:
1. Built from sources. Here are the steps off the top of my head
```
# clone repo and checkout needed revision.
cd sonic-buildimage
make init
make configure PLATFORM-vs
make target/docker-sonic-vs.gz
```
2. Download prebuild `docker-sonic-vs.gz` from community builds https://sonic-build.azurewebsites.net/ui/sonic/Pipelines. Use build for vs platfrom and suiteble realese branch. For example here is the link to `docker-sonic-vs.gz` from the lates vs master build 
```
 wget 'https://sonic-build.azurewebsites.net/api/sonic/artifacts?branchName=master&platform=vs&target=target%2Fdocker-sonic-vs.gz' -O docker-sonic-vs.gz
```

Then load it to docker images:
```
docker load -i docker-sonic-vs.gz
```
Then try to start container again:
```
docker run --privileged --network container:sw --name vs -d docker-sonic-vs
```

**Comment by dgsudharsan** [comment]
@thovikeerthi Please try the steps mentioned by @msosyak and update here if you still see the issue. @prsunny FYI

**Comment by thovikeerthi** [comment]
Hi Team, Thank you all. I am able to launch and start the docker VS instance successfully, by following above instructions. 

But, I noticed that all options available in SONiC VS VM, are not available/part of this Docker instance i.e.
- $'docker ps' command doesn't work i.e. 'docker' command not available 
- $'show version' command throws an exception

My understanding was 'SONiC VS Docker Instance' is similar to 'SONiC VS VM Instance', with only difference that it runs as Docker service instead of KVM instance. 
Please suggest, is my understanding correct ? or I am missing any basics here ?

**Comment by msosyak** [comment]
docker-sonic-vs is not the same as VM. It is kind of all-in-one docker. All services installed in SONiC host, no separate containers for services. Not sure in which state the docker-sonic-vs is right know.  Unfortunetly I do not see any document which desribe that. All i know that docker-sonic-vs is used for for CI in sonic-swss submodule https://github.com/sonic-net/sonic-swss/blob/master/tests/README.md

**Comment by thovikeerthi** [comment]
Hi @msosyak , Thank you for the update. Closing the issue as my doubts are clarified and able to proceed from my earlier reported issue cause.

JFYI: Raised a pull-request to update the VS Docker README document with the details of information gained from this experience. Please suggest if this can be taken forward. Thanks. 
PR ID: https://github.com/sonic-net/sonic-buildimage/pull/16783
