### ISSUE TITLE
[Eventd] Eventd Unit test fails frequently

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#16996]
#### Description
Eventd unit tests are flaky and the build fails frequently. Attached are the list of build failures. One observation is frequency of failures increased after https://github.com/sonic-net/sonic-buildimage/pull/16598

[eventd_fail_log_1.txt](https://github.com/sonic-net/sonic-buildimage/files/13146400/eventd_fail_log_1.txt)
[eventd_fail_log_2.txt](https://github.com/sonic-net/sonic-buildimage/files/13146403/eventd_fail_log_2.txt)
[eventd_fail_log_3.txt](https://github.com/sonic-net/sonic-buildimage/files/13146405/eventd_fail_log_3.txt)
[eventd_fail_log_4.txt](https://github.com/sonic-net/sonic-buildimage/files/13146407/eventd_fail_log_4.txt)

#### Steps to reproduce the issue:
1. Build sonic.
2.
3.

#### Describe the results you received:
Eventd tests fail frequently

#### Describe the results you expected:
Eventd tests shouldn't fail

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zbud-msft** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/17055

**Comment by liushilongbuaa** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/17152
Hi @dgsudharsan , Maybe this PR can fix eventd.proxy. I'm not sure about my test environment.
Can you help review the code?

**Comment by dgsudharsan** [comment]
@liushilongbuaa There is also another PR raised by @zbud-msft . Can you both please co-ordinate? https://github.com/sonic-net/sonic-buildimage/pull/17055

**Comment by liushilongbuaa** [comment]
They are not the same issue.
I find that zmq_setsockopt need to be called before amq_connect according to doc. Maybe it is a code bug.
@zbud-msft try to fix from the UT scenario side. @zbud-msft can you help review PR#17152?

**Comment by zbud-msft** [comment]
Fixed
