### ISSUE TITLE
[chassis]: determine/process-reboot-cause services fail to start if database service fails in first run during boot

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#16990]
#### Description
1. This is observed on a Chassis system when a new image is installed on Supervisor only while LC boots with image previously installed.

During the first boot after sonic-installer, Supervisor boot goes through lazy install which takes a few mins more than the normal boot due to multiple debian package installations and platform service enablement.

As LCs also reboot as part of supervisor reboot and LCs are no going through the Lazy install, LCs boot faster and reach database start point. database service does a sonic-db-cli PING in systemd pre check before activating the service. As Supervisor is still in boot, the chassis_redis server sometimes take a little more time to start before LC could reach it.

On LC, as database service wait for redis chassis server, systemd hits 90 sec default timeout and kills the service which gets restarted after 30 sec. By that time as redis chassis service is available, databse and all other dependent services like bgp, swss, syncd etc also starts.

determine-reboot-cause and process-reboot-cause services are also dependent on database service. When database service fails in first attempt, that marks depedency failure for these services. These services are not setup as restartable, so these do not get restarted when database service restarts and retries redis chassis server.
This causes 'show reboot-cause history' display empty on the LC.

2. If database service restarts on Chassis or pizza box, reboot-cause history also gets deleted from db. As process-reboot-cause and determine-reboot-cause services do not restart, it cause 'show reboot-cause- history' output to be empty post database restart.

This github issue is to analyze and find a solution for declaring a better dependency for these services to be able to restart and run when the dependency is resolved.

#### Steps to reproduce the issue:
1.
2.
4.

#### Output of `show version`:
Issue seen with 202205  8e945fb2117e1cbef0b8a28732871afec36fe57b
but should be same on master and other branches as the service Unit files are same.

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
@abdosi , @vperumal , @bmridul , for your viz

**Comment by gechiang** [comment]
> @anamehra Please discuss in chassis subgroup and triage

@anamehra , please be ready to discuss this at tomorrow's chassis subgroup meeting at 10AM DST. Thanks!
