### ISSUE TITLE
redis memory increased more than expected

### ISSUE THREAD

**Issue by wenyiz2021** [sonic-net/sonic-buildimage#17026]
#### Description
This is recently seen with chassis image 202205.45:

```Failed: Redis Memory Increase more than expected: 5.65371024735```

it occasionally fail test_cont_link_flap on different chassis platform.

error issued from test_continouse_link_flap because that with 3 iterations of links flapping, redis memery, output of `redis-cli info memory | grep used_memory_human` has increase more than `5%` compared to the same output when test starts. in this example it is `5.65371024735%`
https://github.com/sonic-net/sonic-mgmt/blob/635d4b15979195de92f149319570e17ad27dca14/tests/platform_tests/link_flap/test_cont_link_flap.py#L152

#### Steps to reproduce the issue:
1. run test_cont_link_flap on any chassis dut
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by gechiang** [comment]
@wenyiz2021 can you describe more info such as which branch you see this and any further details on what potential component may have caused this?

**Comment by gechiang** [comment]
is this from MNONIT?  or some receiver not consuming the published events?  maybe follow some of the known memory related TSG...  any special steps involved?  maybe collect techsupport?

**Comment by wenyiz2021** [comment]
@gechiang updated

**Comment by kenneth-arista** [comment]
This problem is not specific to chassis as we have seen hits on other topologies such as T0, T1, and Mx.

**Comment by wenyiz2021** [comment]
removing chassis label as it is not only seen in chassis and it needs testcase fix

**Comment by tirupatihemanth** [comment]
@wenyiz2021 Just wanted to check if the issue is closed because we have a fix elsewhere? We see a large redis RSS when there are a lot of link flaps.

**Comment by tirupatihemanth** [comment]
@vmittal-msft to help triage/tag relevant folks

**Comment by wenyiz2021** [comment]
@tirupatihemanth 
If I remember correctly, the issue was not platform specific, and not topology specific at all. the final action was increasing redis mem threshold at that time, right now I can see the threshold is 15% for redis mem for non M0/Mx topologies.
If you see any sku exceed this threshold with continouse link flap, there should be real issue 

`incr_redis_memory_threshold = 20 if tbinfo["topo"]["type"] in ["m0", "mx"] else 15`

**Comment by saravanan-nexthop** [comment]
> [@tirupatihemanth](https://github.com/tirupatihemanth) If I remember correctly, the issue was not platform specific, and not topology specific at all. the final action was increasing redis mem threshold at that time, right now I can see the threshold is 15% for redis mem for non M0/Mx topologies. If you see any sku exceed this threshold with continouse link flap, there should be real issue
> 
> `incr_redis_memory_threshold = 20 if tbinfo["topo"]["type"] in ["m0", "mx"] else 15`

@wenyiz2021 do you know if increasing the threshold is right approach or wait longer for the mem usage to go down ? 
for ut2 max topo (topo_t2_single_node_max_64p*.yml) the timeouts were increased to 350s or more it was fine. 
cc @yifan-nexthop
