### ISSUE TITLE
[Bookworm] [ntpd] Error logs seen during config reload

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#17034]
#### Steps to reproduce the issue:
1. Load bookworm image
2. Run config reload -y -f

#### Describe the results you received:

```
Oct 28 04:57:11.748425 arc-switch1025 NOTICE ntpd[11546]: ERR: ntpd exiting on signal 15 (Terminated)
Oct 28 04:58:42.744484 sonic ERR ntpd[46252]: statistics directory /var/log/ntpsec/ does not exist or is unwriteable, error No such file or directory
Oct 28 04:58:45.727232 sonic NOTICE ntpd[46252]: ERR: ntpd exiting on signal 15 (Terminated)
Oct 28 04:58:51.578765 sonic ERR ntpd[47271]: statistics directory /var/log/ntpsec/ does not exist or is unwriteable, error No such file or directory
```

**Comment by saiarcot895** [comment]
The statistics directory error message is known and added to the loganalyzer ignore list in sonic-net/sonic-mgmt#10502.

**Comment by dgsudharsan** [comment]
@saiarcot895 Looks like the loganalyzer is catching the below log as error due to presence of ERR eventhough log level is NOTICE. Can you please add this to ignore list as well?
Oct 28 04:58:45.727232 sonic NOTICE ntpd[46252]: ERR: ntpd exiting on signal 15 (Terminated)
