### ISSUE TITLE
Need a way to trigger CMIS manager after resetting a CMIS cable

### ISSUE THREAD

**Issue by Junchao-Mellanox** [sonic-net/sonic-buildimage#17058]
#### Description

CMIS manager task running in xcvrd is responsible for applying SI parameters and initialize data path for CMIS cable. It seems that we missed one feature for SFP reset. By resetting a CMIS cable, CMIS EEPROM will be reset and CMIS cable will be set to low power according to the standard. In that case, sonic needs a way to re-trigger CMIS manager as well as applying SI parameters to re-initialize CMIS cable.

#### Steps to reproduce the issue:
1. sfputil reset Ethernet0
2. module of Ethernet0 goes to low power
3. CMIS manager knows nothing of it and Ethernet0 cannot go to oper up again

#### Describe the results you received:

Module keeps in low power after reset

#### Describe the results you expected:

Need a way to trigger CMIS manager after resetting a CMIS cable and do the initialization again

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by mihirpat1** [comment]
The following sequence can be followed to restore the link after issuing "sfputil reset"

1.	config interface shutdown <port>
2.	sfputil reset <port>
3.	config interface startup <port>
 
The above sequence has been verified to be working and has also been confirmed by @Junchao-Mellanox. Hence, closing this issue.

@prgeor for viz
