### ISSUE TITLE
[Bookworm] [techsupport] test_techsupport_commands failed due to no "/proc/sched_debug" in the cp commands

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#17064]
#### Description

/proc/sched_debug is missing in bookworm

#### Steps to reproduce the issue:
1. Run the  `show_techsupport/test_techsupport.py::test_techsupport_commands` test 
2. Or run techsupport and check the `/proc/sched_debug` file

#### Describe the results you received:
```
cat dump.proc/sched_debug
/proc/sched_debug not found
```

**Comment by gechiang** [comment]
fix is in sonic-utilities that @vivekrnv is aware of and will retest to confirm before closing.

**Comment by saiarcot895** [comment]
`/proc/sched_debug` collection removed in sonic-net/sonic-utilities@fe11c2ea8801995ea4cdd15837df83ec365679cc. sonic-net/sonic-mgmt#10718 will remove the test code that checks for this.
