### ISSUE TITLE
Tests test_non_secure_boot_upgrade_failure fails to run on device with Secure Boot enabled

### ISSUE THREAD

**Issue by DavidZagury** [sonic-net/sonic-buildimage#17153]
#### Steps to reproduce the issue:
1. Have a Secure switch with secured image installed
2. Run the test using a path to non secure image,

#### Describe the results you received:
Test is meant to validate non successful upgrade to non secure image.
The tests fails.

#### Describe the results you expected:
Test should pass.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):
The test is trying to find the error output in _err.results._check_key("module_stdout")_ while it is located in _err.results._check_key("msg")_

**Comment by arlakshm** [comment]
@DavidZagury will create a PR to modify the test
