### ISSUE TITLE
[warm-reboot] natsort import is taking more time with python 3.11 in bookworm

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#17246]
#### Description

import natsort is adding 0.5 - 0.6 sec to the CLI runtime in bookworm. 

This is affecting WR LACP Session down time because every call to sonic-cfggen is taking 0.5 sec more and there is degradation in CLI. Average lacp_session_wait time in around 93-94 sec. 

Tested on a following system on the following CPU. 
```
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Celeron(R) CPU 1047UE @ 1.40GHz
    CPU family:          6
    Model:               58
    Thread(s) per core:  1
    Core(s) per socket:  2
```

#### Steps to reproduce the issue:

```
admin@arc-switch1025:~$ docker exec -it syncd bash 
root@arc-switch1025:/# time python3 -c "import natsort" <bullseye>
real    0m0.105s
user    0m0.074s
sys     0m0.028s

root@arc-switch1025:/# exit
exit

admin@arc-switch1025:~$ time python3 -c "import natsort"
real    0m0.695s
user    0m0.549s
sys     0m0.122s
```

#### Triage:

This is fixed by updating the natsort to latest bookworm version. Run the following steps on the host and containers to upgrade the version.

```
 pip3 uninstall --yes natsort
Found existing installation: natsort 6.2.1
Uninstalling natsort-6.2.1:
  Successfully uninstalled natsort-6.2.1

 pip3 install natsort
Collecting natsort
  Downloading natsort-8.4.0-py3-none-any.whl.metadata (21 kB)
Downloading natsort-8.4.0-py3-none-any.whl (38 kB)
Installing collected packages: natsort
```

After updating to latest version, downtime fell to 84 sec.

**Comment by arlakshm** [comment]
to be discussed in the platform subgroup.

**Comment by saiarcot895** [comment]
Likely cause is because of `/usr/lib/python3/dist-packages/_distutils_hack/__init__.py`, related to pypa/setuptools#417.

**Comment by dgsudharsan** [comment]
@saiarcot895  Any updates on this bug?
