### ISSUE TITLE
[202305][chssis-packet]: minigraph.py does not generate correct STATIC_ROUTE entry

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#17402]
#### Description
https://github.com/sonic-net/sonic-buildimage/pull/14951 is breaking STATIC_ROUTE generation on 202305 branch.

Looks like minigraph attribute changes expected by this PR are not in 202305.

#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you received:
static route block format generated in config db
```
"STATIC_ROUTE": {
        "20.0.6.2,20.0.5.2,20.0.2.2,20.0.1.2,20.0.14.2,20.0.11.2,20.0.16.2,20.0.12.2,20.0.15.2,20.0.13.2/32": {
            "advertise": "false",
            "ifname": "PortChannel06",
            "nexthop": "PortChannel05"
        },
        "20.0.6.3,20.0.5.3,20.0.2.3,20.0.1.3,20.0.14.3,20.0.11.3,20.0.16.3,20.0.12.3,20.0.15.3,20.0.13.3/32": {
```

#### Describe the results you expected:
static route block format expected in config db

```
        "3.3.3.10/32": {
            "advertise": "false",
            "ifname": "PortChannel06,PortChannel05,PortChannel02,PortChannel01",
            "nexthop": "20.0.6.8,20.0.5.8,20.0.2.8,20.0.1.8"
        },
```

#### Output of `show version`:

```
sha1 from 202305 build:
d814cc41d [eventd]: Disabling eventd tests (#17053) (#17061)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
Hi @abdosi , @gechiang , @rlhui , for your viz. Thanks

**Comment by rlhui** [comment]
@abdosi will check more.

**Comment by prabhataravind** [comment]
@abdosi, could you please check?

**Comment by abdosi** [comment]
> @abdosi, could you please check?

Fix by: https://github.com/sonic-net/sonic-mgmt/pull/11161 @anamehra for viz.
