### ISSUE TITLE
[202305] [multi-asic]: cacl test case failure due to missing ip6table rule in namspace

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#17431]
#### Description

Observed the cacl test case failure due to missing ip6table rule on multi-asic Line card on 202305 image.

<failure message="Failed: Missing expected ip6tables rules: {'-A INPUT -s fd00::1/128 -d fd00::242:f07f:102/128 -j ACCEPT'}">

The rule is created for namespace.

ip6tables v1.8.7 (nf_tables): host/network `self.namespace_docker_mgmt_ipv6[namespace]' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.7 (nf_tables): host/network `self.namespace_docker_mgmt_ipv6[namespace]' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.7 (nf_tables): host/network `self.namespace_docker_mgmt_ipv6[namespace]' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.7 (nf_tables): host/network `self.namespace_docker_mgmt_ipv6[namespace]' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.7 (nf_tables): host/network `self.namespace_docker_mgmt_ipv6[namespace]' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.7 (nf_tables): host/network `self.namespace_docker_mgmt_ipv6[namespace]' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by gechiang** [comment]
@anamehra Do we have this same problem for 202205 branch?
