### ISSUE TITLE
Regarding MTU 

### ISSUE THREAD

**Issue by guichuan2018** [sonic-net/sonic-buildimage#17445]
#### Description
The definition of MTU is not clear: 

I see quite a number of vendors implement it as L2MTU, but there's a vendor that implements it as L3MTU, which creates confusion and incompatibility. We need a clear definition.

#### Steps to reproduce the issue:
Does the following MTU mean L2MTU or L3MTU?
by L2MTU, it includes all ethernet headers.
by L3MTU, it excludes all ethernet headers.

        "Ethernet80": {
            "admin_status": "down",
            "alias": "Eth11",
            "fec": "rs",
            "index": "10",
            "lanes": "137,138,139,140",
            "mtu": "9100",
            "speed": "100000"
        },
#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prsunny** [comment]
This is L3 MTU. While programming ASIC, L2 size is added to this MTU [here]( https://github.com/sonic-net/sonic-swss/blob/master/orchagent/portsorch.cpp#L1501)

**Comment by guichuan2018** [comment]
Cool, thank you @prsunny for the quick clarification

**Comment by prabhataravind** [comment]
Closing the issue as concern is addressed.
