### ISSUE TITLE
[VOQ] PFCWD didn't drop IPv6 traffic in storm condition with drop action being configured.

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#17446]
#### Description

We noticed this in PFCWD testing with 202205 image on VOQ chassis. Drop action was configured for PFCWD.
IPv6 traffic was not dropped in storm condition. This issue was not seen with IPv4 traffic.

BRCM SAI ver: [7.1.64.4], OCP SAI ver: [1.10.2], SDK ver: [sdk-6.5.24]

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by kenneth-arista** [comment]
https://github.com/sonic-net/sonic-mgmt/issues/10959 tracks the missing sonic-mgmt test coverage

**Comment by rlhui** [comment]
Brcm SAI fix needed

**Comment by rlhui** [comment]
Brcm provided patch and was validated by Arista working. To get fix in SAI

**Comment by kenneth-arista** [comment]
Fix is available in DNX SAI 7.1.72.4 and 9.3.x

**Comment by abdosi** [comment]
@alpeshspatel : for viz.

**Comment by vmittal-msft** [comment]
This issue is fixed with latest SAI for branch 202205.
