### ISSUE TITLE
[dualtor] Mux toggle failure with fallback due to the removal of still referenced neighbor

### ISSUE THREAD

**Issue by lolyu** [sonic-net/sonic-buildimage#17504]
#### Steps to reproduce the issue:
1. issue observed during nightly

#### Describe the results you received:
![image](https://github.com/sonic-net/sonic-buildimage/assets/35479537/f85dbd63-0735-4409-b3ac-c44b2d05c589)
#### Describe the results you expected:
success toggle without fallback

#### Output of `show version`:
20230531.10

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by lolyu** [comment]
Hi @prsunny, I'm creating this as this is observed once during nightly. Could you please help check?

**Comment by prsunny** [comment]
@lolyu , this should be fixed by https://github.com/sonic-net/sonic-swss/pull/2982
