### ISSUE TITLE
[YANG] keyword "choicenot work in YANG file except sonic-acl.yang

### ISSUE THREAD

**Issue by wen587** [sonic-net/sonic-buildimage#17517]
#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prabhataravind** [comment]
@wen587 please provide more details on the issue to triage further.

**Comment by wen587** [comment]
@prabhataravind This is opened by mistake. Please check this one: https://github.com/sonic-net/sonic-buildimage/issues/17518
