### ISSUE TITLE
Ipv6 /64 route not getting advertised to Peer

### ISSUE THREAD

**Issue by abdosi** [sonic-net/sonic-buildimage#17638]
on master and 202305

For 202205 behavior is fine where Static Route is not marked as `queued` by FRR .
 
On 202305 and master route is maeked as queued. This is because of fib suppression feature enable from 202305 onwards.
 
str3-xxxx-lc3-1# show ipv6 route fc00:12::/64
Routing entry for fc00:12::/64
  Known via "static", distance 1, metric 0, best
  Last update 01w1d19h ago
  * directly connected, Loopback0, weight 1
 
str3-xxxx-lc3-1# show ipv6 route static
S>* fc00:12::/64 [1/0] is directly connected, Loopback0, weight 1, 01w1d19h

**Comment by abdosi** [comment]
Solution for 202305: Fib suppression feature is going to disable so we should not see this isse. PR will be open bu @stepanblyschak / @dgsudharsan for viz.

Solution for master is being looked into by @prsunny

**Comment by stepanblyschak** [comment]
@abdosi Isn't it the same as https://github.com/sonic-net/sonic-buildimage/issues/15709?

**Comment by rlhui** [comment]
> @abdosi Isn't it the same as #15709?

@stepanblyschak don't think it's the same issue as #15709 was closed in July. nonetheless, can we use this new one to track the current issue?
