### ISSUE TITLE
[BookWorm Image] NTP Not working

### ISSUE THREAD

**Issue by kaushiksrivatsav** [sonic-net/sonic-buildimage#17657]
#### Description

     NTP is not working because /etc/default/ntp file is missing and because of that ntp community test cases are failing

**LOG:**

if (res.is_failed or 'exception' in res) and not module_ignore_errors:>           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)E           tests.common.errors.RunAnsibleModuleFail: run module command failed, Ansible Results =>E           {"changed": true, "cmd": ["sed", "-i", "s/NTPD_OPTS=-x/NTPD_OPTS=-g/", "/etc/default/ntp"], "delta": "0:00:00.010112", "end": "2023-09-21 19:05:09.524571", "failed": true, "msg": "non-zero return code", "rc": 2, "start": "2023-09-21 19:05:09.514459", "stderr": "sed: can't read /etc/default/ntp: No such file or directory", "stderr_lines": ["sed: can't read /etc/default/ntp: No such file or directory"], "stdout": "", "stdout_lines": [], "warnings": ["Consider using the replace, lineinfile or template module rather than running 'sed'.  If you need to use command because replace, lineinfile or template is insufficient you can add 'warn: false' to this command task or set 'command_warnings=False' in ansible.cfg to get rid of this message."]} complex_args = {}filename   = '/var/AzDevOps/sonic-mgmt/tests/common/devices/multi_asic.py'function_name = '_run_on_asics'index      = 0line_number = 118lines      = ['            return getattr(self.sonichost, self.multi_asic_attr)(*module_args, **complex_args)\n']module_args = ["sed -i s/NTPD_OPTS='-x'/NTPD_OPTS='-g'/ /etc/default/ntp"]module_async = Falsemodule_ignore_errors = Falseprevious_frame = <frame at 0x7f8ec1326420, file '/var/AzDevOps/sonic-mgmt/tests/common/devices/multi_asic.py', line 118, code _run_on_asics>res        = {'failed': True, 'msg': 'non-zero return code', 'cmd': ['sed', '-i', 's/NTPD_OPTS=-x/NTPD_OPTS=-g/', '/etc/default/ntp..._lines': [], 'stderr_lines': ["sed: can't read /etc/default/ntp: No such file or directory"], '_ansible_no_log': False}self       = <SonicHost str-marvell-acs-1>verbose    = True common/devices/base.py:127: RunAnsibleModuleFail====================================================== warnings summary 

#### Image:-

```
/home/admin# show version

SONiC Software Version: SONiC.bookworm.0-dirty-20231122.094720
SONiC OS Version: 12
Distribution: Debian 12.2
Kernel: 6.1.0-11-2-arm64
Build commit: 2a86d1118
Build date: Wed Nov 22 09:48:03 UTC 2023
```

**Comment by saiarcot895** [comment]
What branch/hash of sonic-mgmt are you using? This testcase has been already updated for the new file paths.

**Comment by kaushiksrivatsav** [comment]
hi we are using 202305 branch and commit id is the following:

commit 63be4fa68dac05270560e95f7b3d4690eaf52aa4 (HEAD -> 202305_branch, origin/202305, 202305)
Author: Hua Liu <[58683130+liuh-80@users.noreply.github.com](mailto:58683130+liuh-80@users.noreply.github.com)>

**Comment by saiarcot895** [comment]
@kaushiksrivatsav You'll need to use the master branch. 202305 branch of sonic-mgmt doesn't have support for Bookworm.

**Comment by kaushiksrivatsav** [comment]
issue resolved after sonic-mgmt upgrade test cases are passing
