### ISSUE TITLE
SonicMgmt master branch build failure with fetching submodule link with  https://raw.githubusercontent.com

### ISSUE THREAD

**Issue by davidm-arista** [sonic-net/sonic-buildimage#17707]
Our sonic-mgmt master builds are failing with

get_url_version https://raw.githubusercontent.com/sonic-net/sonic-buildimage/master/src/sonic-dash-api/pypkg/__init__.py failed

It seems this link now fails with a 404 error. Browsing around, it appears to happen for all other files that are in a git submodule. Is this a temporary issue with github? or is this something that needs to fixed in sonic-mgmt?

**Comment by liushilongbuaa** [comment]
It is caused by src/sonic-dash-api changed from folder to submodule.
@Pterosaur Please help check.

**Comment by Pterosaur** [comment]
Hi @davidm-arista , Could you please try to update your downstream to the latest upstream? The reason is as @liushilongbuaa 's comment.

**Comment by davidm-arista** [comment]
Updated.  Closing bug
