### ISSUE TITLE
[VOQ][PFC] Orchagent crashed because of SAI_STATUS_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#17839]
#### Description

We observed the following orchagent crash in PFC testing on DNX VOQ chassis with 202205 image:

```
Jan 15 22:30:51.026194 cmp329-6 ERR syncd0#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_ACL_BIND_POINT_TYPE_LIST: 1:SAI_ACL_BIND_POINT_TYPE_PORT
Jan 15 22:30:51.026194 cmp329-6 ERR syncd0#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_FIELD_TC: true
Jan 15 22:30:51.026194 cmp329-6 ERR syncd0#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_ACL_ACTION_TYPE_LIST: 2:SAI_ACL_ACTION_TYPE_PACKET_ACTION,SAI_ACL_ACTION_TYPE_COUNTER
Jan 15 22:30:51.026194 cmp329-6 ERR syncd0#syncd: :- processQuadEvent: attr: SAI_ACL_TABLE_ATTR_ACL_STAGE: SAI_ACL_STAGE_EGRESS
Jan 15 22:30:51.026342 cmp329-6 ERR swss0#orchagent: :- create: create status: SAI_STATUS_INSUFFICIENT_RESOURCES
Jan 15 22:30:51.026391 cmp329-6 ERR swss0#orchagent: :- addAclTable: Failed to create ACL table EgressTable_PfcWdAclHandler_3
Jan 15 22:30:51.026431 cmp329-6 ERR swss0#orchagent: :- AclRule: Failed to find ACL table EgressTable_PfcWdAclHandler_3. ACL table must exist at the time of creating AclRule
Jan 15 22:30:51.031253 cmp329-6 INFO swss0#supervisord: message repeated 2 times: [ nbrmgrd RTNETLINK answers: File exists]
Jan 15 22:30:51.031253 cmp329-6 INFO swss0#supervisord: orchagent terminate called after throwing an instance of 'std::runtime_error'
Jan 15 22:30:51.031354 cmp329-6 INFO swss0#supervisord: orchagent   what():  :- AclRule: Failed to find ACL table EgressTable_PfcWdAclHandler_3. ACL table must exist at the time
```

In our testbed, PFCWD was configured on a port with drop action, and bidirectional IPV4 traffic was flowing through the port.  The majority of the traffic were tc3 & tc4. 

The above crash was seen with the following steps:
- Inject tc3 pause frame to the port. 
- tc3 is stormed and pfcwd starts to drop tc3 traffic.  pfcwd status may flap between `storm` and `operational` for tc3.
- Now inject tc4 pause frame to the port to also storm tc4.

We observed the crash after the last step.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ysmanman** [comment]
@arlakshm @vmittal-msft @kenneth-arista

**Comment by vmittal-msft** [comment]
There is sonic-mgmt test to verify PFC storm on multiple priority/port which is not running on T2 chassis now. Will work on enabling this to see if it catches this issue.

**Comment by ysmanman** [comment]
When macsec is eanbled,  orchagent also created an egress acl table in ipv4 acl context. We were not able to reproduce the issue after disabling macsec. So the resource overflow was caused by macsec + pfcwd.

**Comment by judyjoseph** [comment]
@ysmanman, I see your update that this issue happens on a macsec enabled port. In macsec we have acl enties created under this table **SAI_ACL_ENTRY_ATTR_TABLE_ID** eg: https://github.com/sonic-net/sonic-swss/blob/9c995f0c83892ae9a4f6657c1c4673164e803169/orchagent/macsecorch.cpp#L2930C40-L2930C56

Did you sync with Broadcom on fixing this above error, or we are looking to put the fix in sonic for PFC in egress stage? Let us know, as we are looking to include this fix also in next image we build internally

+@kenneth-arista

**Comment by ysmanman** [comment]
We ran into SAI issue ( failing to add egress acl entry) with using shared egress acl table. Opened CSP CS00012340180 to track.

**Comment by abdosi** [comment]
@sdszhang

**Comment by ysmanman** [comment]
Close the issue since the fix https://github.com/sonic-net/sonic-swss/pull/3136 was merged into master.
