### ISSUE TITLE
sonic-db-cli  -n <asic-ns> CHASSIS_APP_DB EVAL  fails intermittently after config reload or load-minigraph 

### ISSUE THREAD

**Issue by saksarav-nokia** [sonic-net/sonic-buildimage#17945]
#### Description
When the config reload or load-minigraph is done , swss dockers are restarted and when swss comes back up, swss.sh script cleans the SYSYTEM_NEIGH, SYSTEM_INTERFACE, SYSTEM_LAG_MEMBER_TABLE and SYSTEM_LAG_ID_TABLE entries added by this LC+asic from the CHASSIS_APP_DB table using sonic-db-cli -n <asic-ns> CHASSIS_APP_DB EVAL command.

Even though the EVAL command is called after  sonic-db-cli -n <asic-ns> CHASSIS_APP_DB PING is successful, the EVAL command fails sometimes.  

When we replaced the "sonic-db-cli -n <asic-ns> CHASSIS_APP_DB EVAL" with "redis-cli -h 10.6.0.100 -p 6380 -n 12 EVAL",  the issues are not seen.

#### Steps to reproduce the issue:
1. Run full OC test or write a  simple bash script which just does config reload or load-minigraph 100 times with 7 mins sleep between each config reload or load-migraph.
2. Check the syslog for "Invalid database name input : 'CHASSIS_APP_DB'  error
3. Check for orchagent crash in the remote LC's

#### Describe the results you received:
 1) Error in syslog with "Invalid database name input : 'CHASSIS_APP_DB' , with  Unable to connect to redis: Cannot assign requested address
 2) The orchagent crash in the remote LC's

#### Describe the results you expected:
No errors in syslog and no crash

#### Output of `show version`:
SONiC Software Version: SONiC.20220532.54
SONiC OS Version: 11
Distribution: Debian 11.8
Kernel: 5.10.0-23-2-amd64
Build commit: b9e6caad98
Build date: Tue Jan  9 00:13:06 UTC 2024
Built by: cloudtest@95bebd0dc000000

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by saksarav-nokia** [comment]
@arlakshm @judyjoseph @abdosi @deepak-singhal0408  @mlok-nokia  for viz

**Comment by judyjoseph** [comment]
@qiluo-msft, below is the question from Shakthi 

```
When we replaced the "sonic-db-cli -n CHASSIS_APP_DB EVAL" with "redis-cli -h 10.6.0.100 -p 6380 -n 12 EVAL", the issues are not seen.
```

Is there any difference between these two calls ?  This is the place where we refer to : https://github.com/sonic-net/sonic-buildimage/blob/4af43dc63b49f29b2b9e1c6d304d738a18ecf693/files/scripts/swss.sh#L143

**Comment by judyjoseph** [comment]
@saksarav-nokia  just noticed you see this error "Unable to connect to redis: Cannot assign requested address" -- which means some issue in local connectivity, local interface not available at this time

Can you check if the network-config service is still setting up local interface ? 
In case of namespace we have macvlan -- is it taking time to configure that locally ?

**Comment by saksarav-nokia** [comment]
@judyjoseph , if it is connectivity issue, how come the redis-cli command does not fail. It worked fine with 300 config reload.

**Comment by saksarav-nokia** [comment]
@judyjoseph , We realized hostname-config.service is restarted every time the config reload or load-minigraph is done and this service updates the /etc/hosts and this is conflicting with the swss service chassis-db-cleanup. We didn't see the issue with adding "After=hostname-config.service" in swss@.service  and we will run full OC this weekend with the change and update the PR if everything goes fine.
 
# Swap file: hosts.new and hosts
mv -f /etc/hosts     /etc/hosts.old
mv -f /etc/hosts.new /etc/hosts

**Comment by saksarav-nokia** [comment]
admin@lc4:~$ sudo mv /etc/hosts /etc/hosts.old
admin@lc4:~$ sonic-db-cli -n asic0 CHASSIS_APP_DB PING
Invalid database name input : 'CHASSIS_APP_DB'
Unable to connect to redis: Cannot assign requested address
admin@lc4:~$ sonic-db-cli  CHASSIS_APP_DB PING
Invalid database name input : 'CHASSIS_APP_DB'
Unable to connect to redis: Cannot assign requested address
admin@lc4:~$ sudo mv /etc/hosts.old /etc/hosts
admin@lc4:~$ sonic-db-cli  CHASSIS_APP_DB PING
True
admin@lc4:~$ sonic-db-cli -n asic0 CHASSIS_APP_DB PING
True
