### ISSUE TITLE
build_debain.sh fails to install latest version libgrcp++1 for bookworm

### ISSUE THREAD

**Issue by mlok-nokia** [sonic-net/sonic-buildimage#18033]
#### Description
Building sonic image in bookworm on the latest master branch, the related the version of libgrpc++1 is not installed. 

#### Steps to reproduce the issue:
1. Build the latest image 
2. check if libgrpc++.so.1.51 is installed in fsroot-broadcom-dnx/lib/x86_64-linux-gnu directory

#### Describe the results you received:
After the image is built in the workspace, cannot find libgrpc++.so.1.51 in fsroot-broadcom-dnx/lib/x86_64-linux-gnu directory

#### Describe the results you expected:
libgrpc++.so.1.51 should be founded in fsroot-broadcom-dnx/lib/x86_64-linux-gnu directory in workspace

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by gechiang** [comment]
@mlok-nokia , assigned this to you since you have raised the PR to fix it.
