### ISSUE TITLE
Packages are Missing on Sonicstorage for FIPs with Bookworm Build 

### ISSUE THREAD

**Issue by wumiaont** [sonic-net/sonic-buildimage#18133]
#### Description
Turned on FIPS support for bookworm build (macsec container for now). Build failed on following places as the images are not there. 

https://sonicstorage.blob.core.windows.net/public/fips/bookworm/0.10/amd64/symcrypt-openssl_0.10_amd64.deb
https://sonicstorage.blob.core.windows.net/public/fips/bookworm/0.1/amd64/golang-1.15-go_1.15.15-1~deb11u4%2Bfips_amd64.deb
https://sonicstorage.blob.core.windows.net/public/fips/bookworm/0.1/amd64/golang-1.15-src_1.15.15-1~deb11u4%2Bfips_amd64.deb
Openssh may also needs to be there.

These is a whole list of FIPs related packages needs to be there with proper version and release numbers. Following are for bullseye. For example, openssl should be openssl_3.0.11-1~deb12u2+fips_amd64.deb.

for target in symcrypt-openssl_0.10_amd64.deb openssl_1.1.1n-0+deb11u5+fips_amd64.deb libssl1.1_1.1.1n-0+deb11u5+fips_amd64.deb libssl-dev_1.1.1n-0+deb11u5+fips_amd64.deb libssl-doc_1.1.1n-0+deb11u5+fips_all.deb  openssh-client_8.4p1-5+deb11u2+fips_amd64.deb openssh-sftp-server_8.4p1-5+deb11u2+fips_amd64.deb openssh-server_8.4p1-5+deb11u2+fips_amd64.deb golang-1.15_1.15.15-1~deb11u4+fips_all.deb golang-1.15-go_1.15.15-1~deb11u4+fips_amd64.deb golang-1.15-src_1.15.15-1~deb11u4+fips_amd64.deb golang-1.15-doc_1.15.15-1~deb11u4+fips_all.deb python3.9_3.9.2-1+fips_amd64.deb python3.9-minimal_3.9.2-1+fips_amd64.deb libpython3.9_3.9.2-1+fips_amd64.deb libpython3.9-minimal_3.9.2-1+fips_amd64.deb libpython3.9-stdlib_3.9.2-1+fips_amd64.deb libk5crypto3_1.18.3-6+deb11u4+fips_amd64.deb libkrb5support0_1.18.3-6+deb11u4+fips_amd64.deb libkrb5-3_1.18.3-6+deb11u4+fips_amd64.deb libgssapi-krb5-2_1.18.3-6+deb11u4+fips_amd64.deb libkadm5clnt-mit12_1.18.3-6+deb11u4+fips_amd64.deb libkadm5srv-mit12_1.18.3-6+deb11u4+fips_amd64.deb libgssrpc4_1.18.3-6+deb11u4+fips_amd64.deb krb5-multidev_1.18.3-6+deb11u4+fips_amd64.deb libkrb5-dev_1.18.3-6+deb11u4+fips_amd64.deb; do

Corresponding mk files is in rules/sonic-fips.mk.

Currently this is blocking us for testing FIPs related work against macsec on bookworm which Nokia is working on now.

#### Steps to reproduce the issue:
1. 
2.
3.

#### Describe the results you received:
get_url_version https://sonicstorage.blob.core.windows.net/public/fips/bookworm/0.10/amd64/symcrypt-openssl_0.10_amd64.deb failed
make[1]: *** [Makefile:12: /sonic/target/debs/bookworm/symcrypt-openssl_0.10_amd64.deb] Error 1

**Comment by arlakshm** [comment]
@saiarcot895 can you please confirm if FIPs is enabled in bookworm

**Comment by xumia** [comment]
For OpenSSL 3.0.11, see the PR: https://github.com/sonic-net/sonic-buildimage/pull/18088/files
```
https://sonicstorage.blob.core.windows.net/public/fips/bookworm/1.1-preview/amd64/symcrypt-openssl_1.1-preview_amd64.deb
https://sonicstorage.blob.core.windows.net/public/fips/bookworm/1.1-preview/amd64/golang-1.19-go_1.19.8-2+fips_amd64.deb
https://sonicstorage.blob.core.windows.net/public/fips/bookworm/1.1-preview/amd64/golang-1.19-src_1.19.8-2+fips_all.deb
```

**Comment by rlhui** [comment]
Nokia confirmed it's working, closing.
