### ISSUE TITLE
EAPOL COPP rules are not getting installed when other features also try to use same trap group. Working only with MACSEC.

### ISSUE THREAD

**Issue by vijaya-ops** [sonic-net/sonic-buildimage#18226]
We are trying to place PAC functionality in the Sonic community.

As part of this, we edited the copp_json.j2 file as below
      "ip2me": {
            "trap_ids": "ip2me",
            "trap_group": "queue1_group1",
            "always_enabled": "true"
        },
        "macsec": {
            "trap_ids": "eapol",
            "trap_group": "queue4_group1"
        },
        "nat": {
            "trap_ids": "src_nat_miss,dest_nat_miss",
            "trap_group": "queue1_group2"
        },
        "sflow": {
            "trap_group": "queue2_group1",
            "trap_ids": "sample_packet"
        },
        "pac": {
            "trap_ids": "eapol",
            "trap_group": "queue4_group1"
        }

The issue currently we are facing is that if macsec is enabled , then only eapol frames are coming up. Same is the case with feature disable.

We would like to have the eapol frames to come up even if any one of the features is enabled. Similarly only when the both features get disabled, then only the eapol copp functionality should get disabled.

Also as an experiment, when macsec entry is removed from the above copp_cfg.j2 and enable pac feature, then we were able to see  the eapol rule in the respective trap group.

Below are the logs collected regarding the same.

========
root@sonic:/home/admin#
root@sonic:/home/admin# show feature status
Feature         State            AutoRestart     SetOwner
--------------  ---------------  --------------  ----------
bgp             enabled          enabled
database        always_enabled   always_enabled
dhcp_relay      disabled         enabled         local
eventd          enabled          enabled
gnmi            enabled          enabled
lldp            enabled          enabled
macsec          disabled         enabled         local
mgmt-framework  enabled          enabled
mux             always_disabled  enabled
nat             disabled         enabled
pac             disabled         enabled
pmon            enabled          enabled
radv            enabled          enabled
sflow           disabled         enabled
snmp            enabled          enabled
swss            enabled          enabled
syncd           enabled          enabled
teamd           enabled          enabled
root@sonic:/home/admin# sonic-db-cli APPL_DB hgetall COPP_TABLE:queue4_group1
{'cbs': '6000', 'cir': '6000', 'meter_type': 'packets', 'mode': 'sr_tcm', 'queue': '4', 'red_action': 'drop', 'trap_action': 'trap', 'trap_priority': '4', 'trap_ids': 'bgp,bgpv6,lacp'}
root@sonic:/home/admin#
root@sonic:/home/admin# config feature state pac enabled
root@sonic:/home/admin# docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS     NAMES
651119d7959e   docker-pac:latest                    "/usr/local/bin/supe??"   2 seconds ago    Up 1 second               pac
22e9199473ce   docker-snmp:latest                   "/usr/local/bin/supe??"   17 minutes ago   Up 10 minutes             snmp
e44a9e18f0ef   docker-platform-monitor:latest       "/usr/bin/docker_ini??"   17 minutes ago   Up 10 minutes             pmon
ff767e39f79d   docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe??"   17 minutes ago   Up 10 minutes             mgmt-framework
1fa668875abe   docker-lldp:latest                   "/usr/bin/docker-lld??"   17 minutes ago   Up 10 minutes             lldp
906c38129901   docker-sonic-gnmi:latest             "/usr/local/bin/supe??"   17 minutes ago   Up 10 minutes             gnmi
128973531f17   docker-fpm-frr:latest                "/usr/bin/docker_ini??"   18 minutes ago   Up 11 minutes             bgp
87f6567b859f   docker-router-advertiser:latest      "/usr/bin/docker-ini??"   18 minutes ago   Up 12 minutes             radv
5785199a834e   docker-syncd-brcm:latest             "/usr/local/bin/supe??"   18 minutes ago   Up 12 minutes             syncd
e853b47800a5   docker-teamd:latest                  "/usr/local/bin/supe??"   18 minutes ago   Up 12 minutes             teamd
3567151fb93a   docker-orchagent:latest              "/usr/bin/docker-ini??"   18 minutes ago   Up 12 minutes             swss
829be10654cb   docker-eventd:latest                 "/usr/local/bin/supe??"   18 minutes ago   Up 12 minutes             eventd
7f762096d55d   docker-database:latest               "/usr/local/bin/dock??"   18 minutes ago   Up 12 minutes             database
root@sonic:/home/admin# sonic-db-cli APPL_DB hgetall COPP_TABLE:queue4_group1
{'cbs': '6000', 'cir': '6000', 'meter_type': 'packets', 'mode': 'sr_tcm', 'queue': '4', 'red_action': 'drop', 'trap_action': 'trap', 'trap_priority': '4', 'trap_ids': 'bgp,bgpv6,lacp'}
root@sonic:/home/admin#
root@sonic:/home/admin#

root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin# config feature state macsec enabled
root@sonic:/home/admin# docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED              STATUS              PORTS     NAMES
20367bfd3913   51dae8a385bc                         "/usr/local/bin/supe??"   11 seconds ago       Up 10 seconds                 macsec
651119d7959e   docker-pac:latest                    "/usr/local/bin/supe??"   About a minute ago   Up About a minute             pac
22e9199473ce   docker-snmp:latest                   "/usr/local/bin/supe??"   18 minutes ago       Up 12 minutes                 snmp
e44a9e18f0ef   docker-platform-monitor:latest       "/usr/bin/docker_ini??"   18 minutes ago       Up 12 minutes                 pmon
ff767e39f79d   docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe??"   18 minutes ago       Up 12 minutes                 mgmt-framework
1fa668875abe   docker-lldp:latest                   "/usr/bin/docker-lld??"   18 minutes ago       Up 12 minutes                 lldp
906c38129901   docker-sonic-gnmi:latest             "/usr/local/bin/supe??"   18 minutes ago       Up 12 minutes                 gnmi
128973531f17   docker-fpm-frr:latest                "/usr/bin/docker_ini??"   20 minutes ago       Up 12 minutes                 bgp
87f6567b859f   docker-router-advertiser:latest      "/usr/bin/docker-ini??"   20 minutes ago       Up 13 minutes                 radv
5785199a834e   docker-syncd-brcm:latest             "/usr/local/bin/supe??"   20 minutes ago       Up 13 minutes                 syncd
e853b47800a5   docker-teamd:latest                  "/usr/local/bin/supe??"   20 minutes ago       Up 13 minutes                 teamd
3567151fb93a   docker-orchagent:latest              "/usr/bin/docker-ini??"   20 minutes ago       Up 13 minutes                 swss
829be10654cb   docker-eventd:latest                 "/usr/local/bin/supe??"   20 minutes ago       Up 13 minutes                 eventd
7f762096d55d   docker-database:latest               "/usr/local/bin/dock??"   20 minutes ago       Up 13 minutes                 database
root@sonic:/home/admin# sonic-db-cli APPL_DB hgetall COPP_TABLE:queue4_group1
{'cbs': '6000', 'cir': '6000', 'meter_type': 'packets', 'mode': 'sr_tcm', 'queue': '4', 'red_action': 'drop', 'trap_action': 'trap', 'trap_priority': '4', 'trap_ids': 'bgp,bgpv6,eapol,lacp'}
root@sonic:/home/admin#

root@sonic:/home/admin#
root@sonic:/home/admin# config feature state pac disabled
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin# docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED              STATUS              PORTS     NAMES
20367bfd3913   51dae8a385bc                         "/usr/local/bin/supe??"   About a minute ago   Up About a minute             macsec
22e9199473ce   docker-snmp:latest                   "/usr/local/bin/supe??"   19 minutes ago       Up 12 minutes                 snmp
e44a9e18f0ef   docker-platform-monitor:latest       "/usr/bin/docker_ini??"   19 minutes ago       Up 12 minutes                 pmon
ff767e39f79d   docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe??"   19 minutes ago       Up 12 minutes                 mgmt-framework
1fa668875abe   docker-lldp:latest                   "/usr/bin/docker-lld??"   19 minutes ago       Up 12 minutes                 lldp
906c38129901   docker-sonic-gnmi:latest             "/usr/local/bin/supe??"   19 minutes ago       Up 13 minutes                 gnmi
128973531f17   docker-fpm-frr:latest                "/usr/bin/docker_ini??"   21 minutes ago       Up 13 minutes                 bgp
87f6567b859f   docker-router-advertiser:latest      "/usr/bin/docker-ini??"   21 minutes ago       Up 14 minutes                 radv
5785199a834e   docker-syncd-brcm:latest             "/usr/local/bin/supe??"   21 minutes ago       Up 14 minutes                 syncd
e853b47800a5   docker-teamd:latest                  "/usr/local/bin/supe??"   21 minutes ago       Up 14 minutes                 teamd
3567151fb93a   docker-orchagent:latest              "/usr/bin/docker-ini??"   21 minutes ago       Up 14 minutes                 swss
829be10654cb   docker-eventd:latest                 "/usr/local/bin/supe??"   21 minutes ago       Up 14 minutes                 eventd
7f762096d55d   docker-database:latest               "/usr/local/bin/dock??"   21 minutes ago       Up 14 minutes                 database
root@sonic:/home/admin# sonic-db-cli APPL_DB hgetall COPP_TABLE:queue4_group1
{'cbs': '6000', 'cir': '6000', 'meter_type': 'packets', 'mode': 'sr_tcm', 'queue': '4', 'red_action': 'drop', 'trap_action': 'trap', 'trap_priority': '4', 'trap_ids': 'bgp,bgpv6,eapol,lacp'}
root@sonic:/home/admin#

root@sonic:/home/admin# config feature state macsec disabled
root@sonic:/home/admin# docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS     NAMES
22e9199473ce   docker-snmp:latest                   "/usr/local/bin/supe??"   20 minutes ago   Up 13 minutes             snmp
e44a9e18f0ef   docker-platform-monitor:latest       "/usr/bin/docker_ini??"   20 minutes ago   Up 13 minutes             pmon
ff767e39f79d   docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe??"   20 minutes ago   Up 13 minutes             mgmt-framework
1fa668875abe   docker-lldp:latest                   "/usr/bin/docker-lld??"   20 minutes ago   Up 13 minutes             lldp
906c38129901   docker-sonic-gnmi:latest             "/usr/local/bin/supe??"   20 minutes ago   Up 13 minutes             gnmi
128973531f17   docker-fpm-frr:latest                "/usr/bin/docker_ini??"   21 minutes ago   Up 14 minutes             bgp
87f6567b859f   docker-router-advertiser:latest      "/usr/bin/docker-ini??"   21 minutes ago   Up 15 minutes             radv
5785199a834e   docker-syncd-brcm:latest             "/usr/local/bin/supe??"   21 minutes ago   Up 15 minutes             syncd
e853b47800a5   docker-teamd:latest                  "/usr/local/bin/supe??"   21 minutes ago   Up 15 minutes             teamd
3567151fb93a   docker-orchagent:latest              "/usr/bin/docker-ini??"   21 minutes ago   Up 15 minutes             swss
829be10654cb   docker-eventd:latest                 "/usr/local/bin/supe??"   21 minutes ago   Up 15 minutes             eventd
7f762096d55d   docker-database:latest               "/usr/local/bin/dock??"   22 minutes ago   Up 15 minutes             database
root@sonic:/home/admin#
root@sonic:/home/admin#
root@sonic:/home/admin# sonic-db-cli APPL_DB hgetall COPP_TABLE:queue4_group1
{'cbs': '6000', 'cir': '6000', 'meter_type': 'packets', 'mode': 'sr_tcm', 'queue': '4', 'red_action': 'drop', 'trap_action': 'trap', 'trap_priority': '4', 'trap_ids': 'bgp,bgpv6,lacp'}
root@sonic:/home/admin#

**Comment by prabhataravind** [comment]
@vijaya-ops Please provide ASIC_DB entries as well when the problem is observed or attach techsupport dump. Thanks!

**Comment by dgsudharsan** [comment]
@vijaya-ops  Please add techsupport

Workaround: Set the following entry in config_db when macsec or pac is enabled through feature command.

```
    "COPP_TRAP": {
        "eapol": {
            "always_enabled": "true"
        }
    }
```

By default the copp_cfg.j2 should contain the following entry

```
	    "eapol": {
		    "trap_ids": "eapol",
		    "trap_group": "queue4_group1"
	    },
```

**Comment by vijaya-ops** [comment]
Attached the tech support as suggested. Thanks.

[sonic_dump_sonic_20240314_085614.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/14599740/sonic_dump_sonic_20240314_085614.tar.gz)

**Comment by dgsudharsan** [comment]
@vijaya-ops I think the techsupport is not taken in problem state since the macsec is enabled. Can you please take in problem state where macsec is not enabled but pac is enabled and copp not installed?

  "FEATURE|macsec": {
    "expireat": 1710406621.3164713,
    "ttl": -0.001,
    "type": "hash",
    "value": {
      "auto_restart": "enabled",
      "check_up_status": "False",
      "delayed": "False",
      "has_global_scope": "False",
      "has_per_asic_scope": "True",
      "high_mem_alert": "disabled",
      "set_owner": "local",
      "state": "enabled",
      "support_syslog_rate_limit": "True"
    }
  },

**Comment by vijaya-ops** [comment]
The new techsupport is uploaded with only pac enabled. Please do take a look.  Thank you.

**Comment by vijaya-ops** [comment]
Please find the tech support in a state with only PAC enabled.  Thank you.

[sonic_dump_sonic_20240417_061600.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15007170/sonic_dump_sonic_20240417_061600.tar.gz)
