### ISSUE TITLE
[Yang] Port table for multi-asic device does not match yang definition

### ISSUE THREAD

**Issue by ganglyu** [sonic-net/sonic-buildimage#18417]
#### Description

Port table for multi-asic device is:
admin@vlab-08:~$ sudo sonic-cfggen -d -v PORT
{'Ethernet1/1': {'admin_status': 'up', 'description': 'ASIC0:Eth0-ASIC0', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/2': {'admin_status': 'up', 'd
escription': 'ASIC0:Eth1-ASIC0', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/3': {'admin_status': 'up', 'description': 'ASIC0:Eth2-ASIC0', 'mtu': '
9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/4': {'admin_status': 'up', 'description': 'ASIC0:Eth3-ASIC0', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000
', 'tpid': '0x8100'}, 'Ethernet1/5': {'admin_status': 'up', 'description': 'ASIC1:Eth0-ASIC1', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/6': {'ad
min_status': 'up', 'description': 'ASIC1:Eth1-ASIC1', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/7': {'admin_status': 'up', 'description': 'ASIC1:
Eth2-ASIC1', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/8': {'admin_status': 'up', 'description': 'ASIC1:Eth3-ASIC1', 'mtu': '9100', 'pfc_asym': '
off', 'speed': '40000', 'tpid': '0x8100'}}

Above ports do not have lanes, but "lanes" is a mandatory field:
https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-yang-models/yang-models/sonic-port.yang#L49

#### Steps to reproduce the issue:
1. Create virtual testbed: kvm-four-asic-t1-lag
2. check port table

#### Describe the results you received:
Yang validation failed.

#### Describe the results you expected:
Port table should have "lanes", or "lanes" should not be mandatory.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ganglyu** [comment]
https://stackoverflow.com/questions/65582700/yang-model-mandatory-node-only-when-condition-is-true

**Comment by ganglyu** [comment]
@xincunli-sonic 
Can you provide ETA?

**Comment by abdosi** [comment]
@SuvarnaMeenakshi please help check this.

**Comment by ganglyu** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/19968

**Comment by ganglyu** [comment]
admin@vlab-08:~$ sonic-cfggen -d -v DEVICE_METADATA
{'localhost': {'bgp_asn': '65100', 'buffer_model': 'traditional', 'cloudtype': 'Public', 'default_bgp_status': 'up', 'default_pfcwd_status': 'disable', 'deployment_id': '1', 'docker_routing
_config_mode': 'separated', 'hostname': 'vlab-08', 'hwsku': 'msft_four_asic_vs', 'mac': '52:54:00:11:fa:22', 'platform': 'x86_64-kvm_x86_64_4_asic-r0', 'region': 'None', 'suppress-fib-pendi
ng': 'enabled', 'synchronous_mode': 'enable', 'timezone': 'UTC', 'type': 'LeafRouter', 'yang_config_validation': 'disable'}}
admin@vlab-08:~$ sonic-cfggen -d -v PORT
{'Ethernet1/1': {'admin_status': 'up', 'description': 'ASIC0:Eth0-ASIC0', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/2': {'admin_status': 'up', 'descr
iption': 'ASIC0:Eth1-ASIC0', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/3': {'admin_status': 'up', 'description': 'ASIC0:Eth2-ASIC0', 'mtu': '9100', '
pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/4': {'admin_status': 'up', 'description': 'ASIC0:Eth3-ASIC0', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '
0x8100'}, 'Ethernet1/5': {'admin_status': 'up', 'description': 'ASIC1:Eth0-ASIC1', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/6': {'admin_status': 'up
', 'description': 'ASIC1:Eth1-ASIC1', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/7': {'admin_status': 'up', 'description': 'ASIC1:Eth2-ASIC1', 'mtu': 
'9100', 'pfc_asym': 'off', 'speed': '40000', 'tpid': '0x8100'}, 'Ethernet1/8': {'admin_status': 'up', 'description': 'ASIC1:Eth3-ASIC1', 'mtu': '9100', 'pfc_asym': 'off', 'speed': '40000', 
'tpid': '0x8100'}}
