### ISSUE TITLE
[multi-asic][202305]: 'config reload -l <>' option  loads incorrect config

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#18431]
#### Description
On multi-asic system, I see that when we run config reload with -l, it creates additional ports with alias as interface names.

root@sfd-vt2-lc0:/home/cisco# show int st -d all -n asic0
      Interface                Lanes    Speed    MTU    FEC         Alias             Vlan    Oper    Admin    Type    Asym PFC
---------------  -------------------  -------  -----  -----  ------------  ---------------  ------  -------  ------  ----------
     Eth0/0/0/0                  N/A     400G   9100    N/A           N/A           routed     N/A       up     N/A         off
     Eth0/0/0/1                  N/A     400G   9100    N/A           N/A           routed     N/A       up     N/A         off
     Eth0/0/0/2                  N/A     400G   9100    N/A           N/A           routed     N/A       up     N/A         off
     Eth0/0/0/3                  N/A     400G   9100    N/A           N/A           routed     N/A       up     N/A         off
     Eth0/0/0/4                  N/A     400G   9100    N/A           N/A           routed     N/A       up     N/A         off
     Eth0/0/0/5                  N/A     400G   9100    N/A           N/A           routed     N/A       up     N/A         off
     Eth0/0/0/6                  N/A     400G   9100    N/A           N/A           routed     N/A       up     N/A         off
 
This affects the sonic-mgmt recovery and other test cases which use config reload with  running_golden_config option.

Root Cause:
sonic-cfggen misses handling for namespace at couple of locations. Due to which when port config is fetched, it returns data from global config and not the namespace.

The function calls at https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-config-engine/sonic-cfggen#L361C1-L364C84

get_path_to_port_config_file
get_port_config

needs to be fixed to handle namespace

it should be
```
        if args.port_config is None:
            args.port_config = device_info.get_path_to_port_config_file(hwsku, **asic_id**)
        load_namespace_config(asic_name)
        (ports, _, _) = get_port_config(hwsku, platform, args.port_config, hwsku_config_file=args.hwsku_config, asic_name=asic_name)
```
#### Steps to reproduce the issue:
1. Run 'config reload -l'
2.
3.

#### Describe the results you received:
Additional ports were created with 'alias' as interface names.

#### Describe the results you expected:
Duplicate port entries with alias names should not be created

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
Hi @abdosi , @vperumal , @rajendrat  for your viz

**Comment by prgeor** [comment]
@qiluo-msft would you check why the host has populated port data from other namespace? @mlok-nokia can you create a separate git issue for chassis community and point to this?

**Comment by mlok-nokia** [comment]
This issue has been reported by https://github.com/sonic-net/sonic-buildimage/issues/18286

**Comment by wen587** [comment]
Hi @judyjoseph , the issue was introduced in your PR https://github.com/sonic-net/sonic-utilities/pull/877
I will assign it to you for triage.

**Comment by anamehra** [comment]
I have a PR to fix this, https://github.com/sonic-net/sonic-buildimage/pull/18452
please help with review.
