### ISSUE TITLE
[multi-asic][202305]: system_health/test_watchdog  test fails due to missing multi-asic support

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#18471]
#### Description
system_health/test_watchdog.py script uses 'docker exec -i swss ' to access swss docker and run commands for the test execution and validation. This works for single asic but causes test to fail for multi asic as swss with namespace id is not used.

This also affects further test cases as this test stops orchagent due to failure, does not recover the orchagent process.

#### Steps to reproduce the issue:
1. Run system_health/test_watchdog.py on multi-asic router
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
hi @abdosi , for your vix. Please add chassis label. Thanks

**Comment by anamehra** [comment]
@abdosi , please assign this to me.

**Comment by prgeor** [comment]
@anamehra assigning to you as you requested. please improve the test case for mulit-asic platform

**Comment by anamehra** [comment]
Duplicate.
