### ISSUE TITLE
[master][voq]  fabric switch id is not read from configDb 

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#18558]
#### Description

https://github.com/sonic-net/sonic-swss/pull/2908  added switch_id in create_switch call for fabric switch.  But swss only read switch_id from configDb for voq switch. 

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ysmanman** [comment]
We need to fix this following check to allow reading switch_id for fabric swtich from configDb.

https://github.com/sonic-net/sonic-swss/blob/9c995f0c83892ae9a4f6657c1c4673164e803169/orchagent/main.cpp#L190

    if (gMySwitchType != "voq")
    {
        //Non VOQ switch. Nothing to read
        return true;
    }

**Comment by ysmanman** [comment]
Add @arlakshm @vmittal-msft @kenneth-arista @arista-nwolfe for viz.

**Comment by rlhui** [comment]
this PR is needed for brcm SAI 10.1.15
