### ISSUE TITLE
[Chassis][multi-asic] Stopping swss services on SFMs should remove the related fabric reachability links but it does not

### ISSUE THREAD

**Issue by mannytaheri** [sonic-net/sonic-buildimage#18554]
#### Description
When stopping swss services on SFMs,  the related fabric reachability information do not get remove from the database. 

#### Steps to reproduce the issue:
1.Ensure the related swss a syncd are up and running.

```
admin@ixre-cpm-chassis11:~$ docker ps -a
CONTAINER ID   IMAGE                                COMMAND                             CREATED      STATUS    PORTS     NAMES
1c6ac7cd1594   docker-syncd-brcm-dnx:latest     "/usr/local/bin/supeâ¦"   5 days ago   Up 27 hours            syncd15
2a0675724b5a   docker-orchagent:latest              "/usr/bin/docker-iniâ¦"   5 days ago   Up 27 hours             swss14
9f06a06e5907   docker-orchagent:latest               "/usr/bin/docker-iniâ¦"   5 days ago   Up 27 hours             swss15
7b6bde1b5460   docker-syncd-brcm-dnx:latest   "/usr/local/bin/supeâ¦"   5 days ago   Up 27 hours             syncd14
```
2.show fabric reachability information for acic14 and asic15

admin@ixre-cpm-chassis11:~$ show fabric reachability -n asic14 | grep up | wc
     72     288    3960
admin@ixre-cpm-chassis11:~$ show fabric reachability -n asic15 | grep up | wc
     72     288    3960
 
3.Stop swss services

admin@ixre-cpm-chassis11:~$ sudo systemctl stop swss@14
admin@ixre-cpm-chassis11:~$ sudo systemctl stop swss@15

4. Check swss and syncd dockers. Ensure they have exited.

```
admin@ixre-cpm-chassis11:~$ docker ps -a
1c6ac7cd1594   docker-syncd-brcm-dnx:latest     "/usr/local/bin/supeâ¦"   5 days ago   Exited (0) 5 seconds ago     syncd15
2a0675724b5a   docker-orchagent:latest              "/usr/bin/docker-iniâ¦"   5 days ago   Exited (0) 26 seconds ago    swss14
9f06a06e5907   docker-orchagent:latest               "/usr/bin/docker-iniâ¦"   5 days ago   Exited (0) 11 seconds ago    swss15
7b6bde1b5460   docker-syncd-brcm-dnx:latest   "/usr/local/bin/supeâ¦"   5 days ago   Exited (0) 18 seconds ago    syncd14
```

5. Show fabric reachibilty information on each related asics.   These entries should have been removed but they are not.

admin@ixre-cpm-chassis11:~$ show fabric reachability -n asic15 | grep up | wc
     72     288    3960
admin@ixre-cpm-chassis11:~$ show fabric reachability -n asic14 | grep up | wc
     72     288    3960

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by wumiaont** [comment]
@deepak-singhal0408 @Aravind-Subbaroyan @mlok-nokia The information is in STATE_DB. such as key of FABRIC_PORT_TABLE|PORT100. Symptom is that of stop swss docker. The FABRIC_PORT_TABLE| corresponding ports STATUS are still up. 
Should some routine do update of tables in STATE_DB? Or can I add code in swss.sh in stop() case to cleanup the FABRIC_PORT_TABLE entries?

**Comment by deepak-singhal0408** [comment]
+ @arlakshm @abdosi

**Comment by wumiaont** [comment]
Currently I made a fix to add clean FABRIC_PORT_TABLE from STATE_DB when stopping swss docker. It seems to be working fine.  Not sure if there's any other generic place to monitor this.
