### ISSUE TITLE
[Query] Regarding the PDDF framework

### ISSUE THREAD

**Issue by chiranjeevi-u** [sonic-net/sonic-buildimage#18697]
#### Description

I have a query regarding the PDDF framework. I can see that the framework is developed by Broadcom and is submitted to the community.

"_Platform Driver Development Framework (PDDF) is part of SONiC Platform Development Kit (PDK), which enables rapid development of platform drivers and APIs for SONiC platforms_"
- Can PDDF only be developed for Broadcom devices, or can it be used for devices from other vendors like Intel, Marvell, and Nvidia?

#### Steps to reproduce the issue:
NA

#### Describe the results you received:
NA

#### Describe the results you expected:
NA

#### Output of `show version`:

```
NA
```
#### Output of `show techsupport`:

```
NA
```

**Comment by adyeung** [comment]
PDDF is a generic design, it's agnostic to silicon vendors. It'll be good to see other silicon vendors come on board with the framework.
