### ISSUE TITLE
g++: fatal error: Killed signal terminated program cc1plus compilation terminated.

### ISSUE THREAD

**Issue by Prajwal027** [sonic-net/sonic-buildimage#18759]
#### Description
Hi,
I was trying to build sonic using Jenkinsfile and am facing the above error when make cmd is used.

#### Steps to reproduce the issue:
1. make SONIC_CONFIG_BUILD_JOBS=1 $CACHE_OPTIONS INSTALL_DEBUG_TOOLS=y target/sonic-broadcom.bin
2.
3.

#### Describe the results you received:
This is want error I am facing in sonic-swss
<img width="406" alt="image" src="https://github.com/sonic-net/sonic-buildimage/assets/90600292/9ae46a65-9d3d-4193-8ab1-17c9b4e226f5">

#### Output of `show version`:
using Ubuntu 22.04 
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

Please Help me on resolving this error.

**Comment by bingwang-ms** [comment]
@xumia Can you help to check this issue?

**Comment by bingwang-ms** [comment]
@Prajwal027 Does retry workaround the build failure?

**Comment by Prajwal027** [comment]
Hi @bingwang-ms ,
The build for Make all is working fine, but failing 1 test case out of 7.
![image](https://github.com/sonic-net/sonic-buildimage/assets/90600292/452088fe-8cb3-4da7-bd67-418a9e13f540)

**Comment by Prajwal027** [comment]
The initial build attempts failed due to insufficient memory. To resolve this, I increased the available RAM and am now able to build SONiC successfully.
