### ISSUE TITLE
[202311] Celestica DX010 'show platform fan' fails

### ISSUE THREAD

**Issue by mbze430** [sonic-net/sonic-buildimage#18767]
brand new reload of 202311 build
SONiC Software Version: SONiC.202311.528790-c609af64d
SONiC OS Version: 11
Distribution: Debian 11.9
Kernel: 5.10.0-23-2-amd64
Build commit: c609af64d
Build date: Mon Apr 22 12:07:23 UTC 2024
Built by: AzDevOps@vmss-soni003IGZ

Platform: x86_64-cel_seastone-r0
HwSKU: Seastone-DX010
ASIC: broadcom
ASIC Count: 1
Serial Number: DX010B2F108423LK100045
Model Number: R0872-F0010-01
Hardware Revision: N/A
Uptime: 20:40:27 up  8:51,  1 user,  load average: 1.01, 1.06, 1.08
Date: Mon 22 Apr 2024 20:40:27

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-gbsyncd-broncos        202311.528790-c609af64d   be55fb422477   351MB
docker-gbsyncd-broncos        latest                    be55fb422477   351MB
docker-gbsyncd-credo          202311.528790-c609af64d   713306b97976   324MB
docker-gbsyncd-credo          latest                    713306b97976   324MB
docker-syncd-brcm             202311.528790-c609af64d   f3b99cf12dc4   715MB
docker-syncd-brcm             latest                    f3b99cf12dc4   715MB
docker-macsec                 latest                    b37676abd39d   329MB
docker-dhcp-relay             latest                    068f197d5ecc   310MB
docker-orchagent              202311.528790-c609af64d   702e43f636f4   339MB
docker-orchagent              latest                    702e43f636f4   339MB
docker-fpm-frr                202311.528790-c609af64d   5bd2419e6b39   359MB
docker-fpm-frr                latest                    5bd2419e6b39   359MB
docker-nat                    202311.528790-c609af64d   3443e92151e2   330MB
docker-nat                    latest                    3443e92151e2   330MB
docker-sflow                  202311.528790-c609af64d   d943b74b78eb   328MB
docker-sflow                  latest                    d943b74b78eb   328MB
docker-eventd                 202311.528790-c609af64d   9bd71979d03b   301MB
docker-eventd                 latest                    9bd71979d03b   301MB
docker-teamd                  202311.528790-c609af64d   64a4d7a505e4   327MB
docker-teamd                  latest                    64a4d7a505e4   327MB
docker-platform-monitor       202311.528790-c609af64d   96826cb44a62   421MB
docker-platform-monitor       latest                    96826cb44a62   421MB
docker-snmp                   202311.528790-c609af64d   dc64cfffbc28   340MB
docker-snmp                   latest                    dc64cfffbc28   340MB
docker-router-advertiser      202311.528790-c609af64d   b66f8434740e   301MB
docker-router-advertiser      latest                    b66f8434740e   301MB
docker-lldp                   202311.528790-c609af64d   b09c9845f8d3   343MB
docker-lldp                   latest                    b09c9845f8d3   343MB
docker-mux                    202311.528790-c609af64d   03e58e4a52e3   349MB
docker-mux                    latest                    03e58e4a52e3   349MB
docker-sonic-gnmi             202311.528790-c609af64d   f90899c4f877   389MB
docker-sonic-gnmi             latest                    f90899c4f877   389MB
docker-database               202311.528790-c609af64d   bc13e3a04fd0   301MB
docker-database               latest                    bc13e3a04fd0   301MB
docker-sonic-mgmt-framework   202311.528790-c609af64d   12a5ea22d4f8   416MB
docker-sonic-mgmt-framework   latest                    12a5ea22d4f8   416MB

getting this error:
```
admin@sonic:~$ show platform fan
Traceback (most recent call last):
  File "/usr/local/bin/fanshow", line 85, in <module>
    fanShow.show()
  File "/usr/local/bin/fanshow", line 75, in show
    table.append((data_dict[DRAWER_FIELD_NAME], data_dict[LED_STATUS_FIELD_NAME], name, speed, data_dict[DIRECTION_FIELD_NAME], presence, status,
KeyError: 'drawer_name'
```

**Comment by mbze430** [comment]
not sure how long it takes to get merged but as of 5/04/24 it is still not working

admin@sonic:~$ show ver

SONiC Software Version: SONiC.202311.537841-1d8111206
SONiC OS Version: 11
Distribution: Debian 11.9
Kernel: 5.10.0-23-2-amd64
Build commit: 1d8111206
Build date: Fri May  3 12:22:51 UTC 2024
Built by: AzDevOps@vmss-soni003LFS

Platform: x86_64-cel_seastone-r0
HwSKU: Seastone-DX010
ASIC: broadcom
ASIC Count: 1
Serial Number: DX010B2F108423LK100045
Model Number: R0872-F0010-01
Hardware Revision: N/A
Uptime: 22:19:26 up  8:48,  1 user,  load average: 1.19, 1.09, 1.08
Date: Sat 04 May 2024 22:19:26

**Comment by mbze430** [comment]
Even though this has been marked closed, but 'Semgrep' failed.  should it be a concern?

**Comment by mbze430** [comment]
@qnos 
according to this:
https://dev.azure.com/mssonic/build/_build/results?buildId=541868&view=results
it failed?

**Comment by qnos** [comment]
> @qnos according to this: https://dev.azure.com/mssonic/build/_build/results?buildId=541868&view=results it failed?

It's not committed code issue, it was testbed timeout.
Another PR at similar date encountered the same issue.

**Comment by mbze430** [comment]
@lguohan 
as of 6/6/24 version SONiC.202311.564467-43bcca75f
this PR still have not been merged to 202311.

**Comment by lhw365** [comment]
still no go with SONiC.202311-buildId-1089277-20260415.3
202405 202411 202505, all Bookworm based works.
