### ISSUE TITLE
python3-protobuf not present inside swss container after swss upgrade to bookworm

### ISSUE THREAD

**Issue by shanshri** [sonic-net/sonic-buildimage#18765]
google/protobuf is missing from python packages after swss upgrade to bookworm.

We are not building protobuf as it is present in bullseye environment.
```
# protobuf package
# Protobuf 3.21.12 has been released in bookworm, So we only need to build it
# in the bullseye environment.
ifeq ($(BLDENV),bullseye)
```
Can someone please help?

**Comment by vivekrnv** [comment]
Will raise a fix to install this in SwSS container
