### ISSUE TITLE
[master][voq][chassis] swss.sh "systemctl start" dhcp_relay failed and log error which causes logAnalyze failure in OC test

### ISSUE THREAD

**Issue by mlok-nokia** [sonic-net/sonic-buildimage#18822]
#### Description
on Master branch, dhcp_relay is not supported in VOQ chassis.  It is disabled in the FEATURE table.   But based on the dependency,  swss.sh always call "systemctl start" it although it's service file has been masked/disabled.  The following error is logged in syslog which causes the logAnalyze failed on some of the OC tests. 
```
Apr 27 23:15:14.472425 ixre-egl-board7 ERR systemctl[7299]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
Apr 27 23:15:14.476897 ixre-egl-board7 ERR systemctl[7298]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
``` 
These logs show as ERR in the master branch which is use the newer version of kernel while they are shown as "INFO" in the 202205 branch.

#### Steps to reproduce the issue:
1. Using Master branch image, reboot the system or config reload. Check syslog.  The following logs exist.
```
Apr 27 23:15:14.472425 ixre-egl-board7 ERR systemctl[7299]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
Apr 27 23:15:14.476897 ixre-egl-board7 ERR systemctl[7298]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
```

#### Describe the results you received:
The syslog contain the error log as below when system bootup or execute the config reload.
```
Apr 27 23:15:14.472425 ixre-egl-board7 ERR systemctl[7299]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
Apr 27 23:15:14.476897 ixre-egl-board7 ERR systemctl[7298]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
```

#### Describe the results you expected:
There should not be such error log in syslog.

#### Output of `show version`:
Latest image.
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by rlhui** [comment]
@kellyyeh would you please check this?

**Comment by rlhui** [comment]
was this syslog INFO in 202205 but now it's ERR, and it triggered sonic-mgmt errors?

**Comment by mlok-nokia** [comment]
> was this syslog INFO in 202205 but now it's ERR, and it triggered sonic-mgmt errors?

Yes. This message is shown as INFO in 202205 branch as below:
```
May  7 23:10:38.902883 ixre-egl-board4 INFO swss.sh[6407]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
May  7 23:10:38.907071 ixre-egl-board4 INFO swss.sh[6406]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
```
But they are shown as ERR in the master branch.  This triggers the LogAnalyze fails OC test in sonic-mgmt run

**Comment by wenyiz2021** [comment]
@mlok-nokia your PR https://github.com/sonic-net/sonic-buildimage/pull/18829#pullrequestreview-2092712267 should fix this issue, is that correct?

**Comment by mlok-nokia** [comment]
> @mlok-nokia your PR [#18829 (review)](https://github.com/sonic-net/sonic-buildimage/pull/18829#pullrequestreview-2092712267) should fix this issue, is that correct?

Yes. correct.

**Comment by abdosi** [comment]
@StormLiangMS : Do we see this issue on T1 platforms ?

**Comment by mlok-nokia** [comment]
Fixed
