### ISSUE TITLE
Building issue for VS platform, Undetermined Error [IP: 151.101.2.132 80] for  http://archive.debian.org/debian buster/main amd64 debian-keyring all 2019.02.25and also libpython2.7-dev_2.7.16-2+deb10u4_amd64.deb

### ISSUE THREAD

**Issue by DennyAgussy** [sonic-net/sonic-buildimage#18860]
Hi Community,

I'm facing the issue while building the OS for platform VS, the error im facing is raising when the host is building a docker image for buster. I'll mention the error details below(Branch 202311):

#12 108.9 Get:519 http://archive.debian.org/debian buster/main amd64 debian-keyring all 2019.02.25 [32.4 MB]
#12 109.6 Err:519 http://archive.debian.org/debian buster/main amd64 debian-keyring all 2019.02.25
#12 1806.1 E: Failed to fetch http://archive.debian.org/debian/pool/main/d/debian-keyring/debian-keyring_2019.02.25_all.deb  Undetermined Error [IP: 151.101.2.132 80]
1806.1 E: Failed to fetch http://archive.debian.org/debian/pool/main/d/debian-keyring/debian-keyring_2019.02.25_all.deb  Undetermined Error [IP: 151.101.2.132 80]

Failed to fetch http://archive.debian.org/debian/pool/main/d/debian-keyring/debian-keyring_2019.02.25_all.deb  Undetermined Error [IP: 151.101.2.132 80]
1806.1 E: Failed to fetch http://debian-archive.trafficmanager.net/debian-security/pool/updates/main/p/python2.7/libpython2.7-dev_2.7.16-2+deb10u4_amd64.deb  Undetermined Error [IP: 52.139.235.206 80]
1806.1 E: Sub-process /usr/bin/dpkg returned an error code (1).

If you need any furthur information I can help you with that.

Thanks
Denny Agussy

**Comment by neethajohn** [comment]
@DennyAgussy , please provide more info on which branch the issue is seen and check the landing page for the build status

**Comment by DennyAgussy** [comment]
Hey @neethajohn Thanks for the reply.

The branch I'm using is 202305 and the build is successed for VS platform.
