### ISSUE TITLE
[DX010] Console/SSH super slow then after a few hours normal

### ISSUE THREAD

**Issue by mbze430** [sonic-net/sonic-buildimage#18871]
#### Description

I don't know if there is a memory leak or bug.  But every few days (usually overnight) the next morning the console or the ssh is super slow.  Hence, I am not able to do a dump or techsupport while in that state.  I am hoping a longer techsupport dump will show up, but I am doubtful.  But this is super annoying.

I really hope someone will actually take a look at the log.

#### Steps to reproduce the issue:
it just happens randomly or overnight

#### Describe the results you received:
the SSH or console is super slow.  It takes up to 10mins to respond and most of time it just times out and quits

#### Describe the results you expected:
normal behavior

#### Output of `show version`:

admin@sonic:~$ show ver

SONiC Software Version: SONiC.202311.537841-1d8111206
SONiC OS Version: 11
Distribution: Debian 11.9
Kernel: 5.10.0-23-2-amd64
Build commit: 1d8111206
Build date: Fri May  3 12:22:51 UTC 2024
Built by: AzDevOps@vmss-soni003LFS

Platform: x86_64-cel_seastone-r0
HwSKU: Seastone-DX010
ASIC: broadcom
ASIC Count: 1
Serial Number: DX010B2F108423LK100045
Model Number: R0872-F0010-01
Hardware Revision: N/A
Uptime: 11:29:55 up 18 min,  1 user,  load average: 1.29, 1.07, 0.96
Date: Sun 05 May 2024 11:29:55

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-gbsyncd-broncos        202311.537841-1d8111206   0b33b5395ac8   351MB
docker-gbsyncd-broncos        latest                    0b33b5395ac8   351MB
docker-gbsyncd-credo          202311.537841-1d8111206   58237914ace2   324MB
docker-gbsyncd-credo          latest                    58237914ace2   324MB
docker-syncd-brcm             202311.537841-1d8111206   514b8888cdfe   715MB
docker-syncd-brcm             latest                    514b8888cdfe   715MB
docker-macsec                 latest                    41da2d3f8dae   329MB
docker-dhcp-relay             latest                    3671e2b3167c   310MB
docker-orchagent              202311.537841-1d8111206   177f5267aae0   339MB
docker-orchagent              latest                    177f5267aae0   339MB
docker-fpm-frr                202311.537841-1d8111206   5b73f1d3b550   359MB
docker-fpm-frr                latest                    5b73f1d3b550   359MB
docker-eventd                 202311.537841-1d8111206   6eeff2f1cc30   301MB
docker-eventd                 latest                    6eeff2f1cc30   301MB
docker-nat                    202311.537841-1d8111206   0c7ebfdf485a   330MB
docker-nat                    latest                    0c7ebfdf485a   330MB
docker-sflow                  202311.537841-1d8111206   0fa4a48b1334   328MB
docker-sflow                  latest                    0fa4a48b1334   328MB
docker-teamd                  202311.537841-1d8111206   f00b63addfe7   327MB
docker-teamd                  latest                    f00b63addfe7   327MB
docker-platform-monitor       202311.537841-1d8111206   0b57c7f05462   421MB
docker-platform-monitor       latest                    0b57c7f05462   421MB
docker-snmp                   202311.537841-1d8111206   55ba11023b0a   340MB
docker-snmp                   latest                    55ba11023b0a   340MB
docker-router-advertiser      202311.537841-1d8111206   d5dd84231b8c   301MB
docker-router-advertiser      latest                    d5dd84231b8c   301MB
docker-lldp                   202311.537841-1d8111206   acec19f65787   343MB
docker-lldp                   latest                    acec19f65787   343MB
docker-sonic-gnmi             202311.537841-1d8111206   6a49929fdb2d   389MB
docker-sonic-gnmi             latest                    6a49929fdb2d   389MB
docker-database               202311.537841-1d8111206   f753761666aa   301MB
docker-database               latest                    f753761666aa   301MB
docker-mux                    202311.537841-1d8111206   28175c8e8560   349MB
docker-mux                    latest                    28175c8e8560   349MB
docker-sonic-mgmt-framework   202311.537841-1d8111206   6c7222bfa1a3   416MB
docker-sonic-mgmt-framework   latest                    6c7222bfa1a3   416MB
#### Output of `show techsupport`:

[sonic_dump_sonic_20240505_110552.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15213707/sonic_dump_sonic_20240505_110552.tar.gz)
[sonic_dump_sonic_20240505_073046.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15213708/sonic_dump_sonic_20240505_073046.tar.gz)

#### Additional information you deem important (e.g. issue happens only occasionally):

this is the 'sudo generate_dump' file:

[sonic_dump_sonic_20240505_113106.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15213729/sonic_dump_sonic_20240505_113106.tar.gz)

**Comment by mbze430** [comment]
since last night, it created two more dump files by itself... here they are

[sonic_dump_sonic_20240506_045957.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15222603/sonic_dump_sonic_20240506_045957.tar.gz)
[sonic_dump_sonic_20240506_052059.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15222604/sonic_dump_sonic_20240506_052059.tar.gz)

**Comment by mbze430** [comment]
This morning there is another two more dump file just there (I previously cleared out all the dump file)

[sonic_dump_sonic_20240507_040703.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15236323/sonic_dump_sonic_20240507_040703.tar.gz)
[sonic_dump_sonic_20240507_034401.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15236324/sonic_dump_sonic_20240507_034401.tar.gz)

**Comment by mbze430** [comment]
I am currently in an ssh session where it is super slow now, trying to do a 'show techsupport'.  Will post the dump if I can get one

```
Last login: Tue May  7 09:55:49 2024 from 10.0.253.254
admin@sonic:~$ ls /var/dump
admin@sonic:~$ sudo show system-memory

Failed to get routing stack: Command 'sudo docker ps | grep bgp | awk '{print$2}' | cut -d'-' -f3 | cut -d':' -f1 | head -n 1' timed out after 300 seconds
               total        used        free      shared  buff/cache   available
Mem:            3896        3582         103          93         209          40
Swap:              0           0           0
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$
admin@sonic:~$ ls /var/dump
admin@sonic:~$ show techsupport
```

**Comment by amazor** [comment]
As far as I am aware, SSH itself is not managed by SONiC NOS, but rather the debian OS. Try taking a look at SSH specific logs. Since it is managed by systemd, try using the `journalctl` command. For example `journalctl -t sshd` or `journalctl -u ssh`.

You might need to change some settings, or possibly update the ssh daemon.

Does this occur after being connected (with keep-alive) for long periods of time? Or is the connection slow right as you start a new connection?

**Comment by mbze430** [comment]
this only happens when I log in the first time.  I have had left my console session open for days and never.

What I have noticed though is that when this happens the 'sudo show system-memory' the available is almost exhausted

if you look at my previous post the 'sudo show system-memory' is down to 40.
right now a good session:
admin@sonic:~$ sudo show system-memory
               total        used        free      shared  buff/cache   available
Mem:            3896        3039         179          86         676         548
Swap:              0           0           0

this has 548.  But since yesterday I had a crash, I had to reboot from a cold start, so this problem won't come back for a few days.

**Comment by amazor** [comment]
Scanning through the logs, the most common syslogs i see are related to the lldp-syncd container.
It seems LLDP is failing to get info for multiple Ethernet Ports and keeps retrying:

```May  6 10:07:04.740276 sonic INFO lldp#lldp-syncd [lldp_syncd] INFO: Failed to get system capabilities on Ethernet104 (50:eb:1a:f7:3b:94)
May  6 10:07:04.741254 sonic INFO lldp#lldp-syncd [lldp_syncd] INFO: Failed to get system capabilities on Ethernet108 (50:eb:1a:f7:3b:94)
May  6 10:07:04.742253 sonic INFO lldp#lldp-syncd [lldp_syncd] INFO: Failed to get system capabilities on Ethernet116 (48:df:37:e0:24:e0)
May  6 10:07:04.743257 sonic INFO lldp#lldp-syncd [lldp_syncd] INFO: Failed to get system capabilities on Ethernet117 (48:df:37:e0:24:e1)
May  6 10:07:04.744224 sonic INFO lldp#lldp-syncd [lldp_syncd] INFO: Failed to get system capabilities on Ethernet118 (48:df:37:e0:24:e2)
May  6 10:07:04.745174 sonic INFO lldp#lldp-syncd [lldp_syncd] INFO: Failed to get system capabilities on Ethernet119 (48:df:37:e0:24:e3)
May  6 10:07:04.746094 sonic INFO lldp#lldp-syncd [lldp_syncd] INFO: Failed to get system capabilities on Ethernet125 (d0:67:e5:d0:51:47)
```

Since this keeps happening, there could possibly be a memory leak when the application fails to get system capabilities.
Even if it is small, since it keeps retrying, even a small memory leak could cause a problem.

Could be a broadcom specific issue as well. In the meantime I would try and figure out what is causing the problem on the Ethernet's mentioned in the log (are the shutdown?).

**Comment by mbze430** [comment]
```
admin@sonic:~$ show lldp table
Capability codes: (R) Router, (B) Bridge, (O) Other
LocalPort    RemoteDevice    RemotePortID                 Capability    RemotePortDescr
-----------  --------------  ---------------------------  ------------  -----------------
Ethernet104  sw0             FortyGigabitEthernet 1/0/49
Ethernet108  sw0             FortyGigabitEthernet 1/0/50
Ethernet116                  48:df:37:e0:24:e0
Ethernet117                  48:df:37:e0:24:e1
Ethernet118                  48:df:37:e0:24:e2
Ethernet119                  48:df:37:e0:24:e3
Ethernet125                  te1/0/2
--------------------------------------------------
Total entries displayed:  7
admin@sonic:~$ show lldp neighbors
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    Ethernet104, via: LLDP, RID: 6, Time: 0 day, 17:03:57
  Chassis:
    ChassisID:    mac 50:eb:1a:f7:3b:94
    SysName:      sw0
  Port:
    PortID:       ifname FortyGigabitEthernet 1/0/49
    TTL:          120
-------------------------------------------------------------------------------
Interface:    Ethernet108, via: LLDP, RID: 6, Time: 0 day, 17:03:57
  Chassis:
    ChassisID:    mac 50:eb:1a:f7:3b:94
    SysName:      sw0
  Port:
    PortID:       ifname FortyGigabitEthernet 1/0/50
    TTL:          120
-------------------------------------------------------------------------------
Interface:    Ethernet116, via: LLDP, RID: 1, Time: 0 day, 17:04:01
  Chassis:
    ChassisID:    mac 48:df:37:e0:24:e0
  Port:
    PortID:       mac 48:df:37:e0:24:e0
    TTL:          121
-------------------------------------------------------------------------------
Interface:    Ethernet117, via: LLDP, RID: 2, Time: 0 day, 17:04:01
  Chassis:
    ChassisID:    mac 48:df:37:e0:24:e1
  Port:
    PortID:       mac 48:df:37:e0:24:e1
    TTL:          121
-------------------------------------------------------------------------------
Interface:    Ethernet118, via: LLDP, RID: 3, Time: 0 day, 17:04:01
  Chassis:
    ChassisID:    mac 48:df:37:e0:24:e2
  Port:
    PortID:       mac 48:df:37:e0:24:e2
    TTL:          121
-------------------------------------------------------------------------------
Interface:    Ethernet119, via: LLDP, RID: 4, Time: 0 day, 17:04:01
  Chassis:
    ChassisID:    mac 48:df:37:e0:24:e3
  Port:
    PortID:       mac 48:df:37:e0:24:e3
    TTL:          121
-------------------------------------------------------------------------------
Interface:    Ethernet125, via: LLDP, RID: 7, Time: 0 day, 00:03:32
  Chassis:
    ChassisID:    mac d0:67:e5:d0:51:47
  Port:
    PortID:       ifname te1/0/2
    TTL:          120
-------------------------------------------------------------------------------

```

Ethernet104/108 is in a portchannel01 that's goes to a Brocade/Extreme Network switch
Ethernet116-119 is actually going to a HP host running VMware, so there is vSwitch
Ethernet125 is going to a Dell switch

Is SONiC expecting TLV data?  I couldn't find anything about it in https://github.com/sonic-net/sonic-utilities/blob/master/doc/Command-Reference.md#lldp-show-commands

**Comment by mbze430** [comment]
just went to console and did a 'sudo show system-health detail'
System services and devices monitor list

```
Name                   Status    Type
---------------------  --------  ----------
sonic                  Not OK    System
memory_check           Not OK    Program
rsyslog                OK        Process
root-overlay           OK        Filesystem
var-log                OK        Filesystem
routeCheck             OK        Program
dualtorNeighborCheck   OK        Program
diskCheck              OK        Program
container_checker      OK        Program
vnetRouteCheck         OK        Program
container_memory_snmp  OK        Program
container_memory_gnmi  OK        Program
container_eventd       OK        Program
database:redis         OK        Process
bgp:zebra              OK        Process
bgp:staticd            OK        Process
bgp:bgpd               OK        Process
bgp:fpmsyncd           OK        Process
bgp:bgpcfgd            OK        Process
syncd:syncd            OK        Process
teamd:teammgrd         OK        Process
teamd:teamsyncd        OK        Process
teamd:tlm_teamd        OK        Process
swss:orchagent         OK        Process
swss:portsyncd         OK        Process
swss:neighsyncd        OK        Process
swss:fdbsyncd          OK        Process
swss:vlanmgrd          OK        Process
swss:intfmgrd          OK        Process
swss:portmgrd          OK        Process
swss:buffermgrd        OK        Process
swss:vrfmgrd           OK        Process
swss:nbrmgrd           OK        Process
swss:vxlanmgrd         OK        Process
swss:coppmgrd          OK        Process
swss:tunnelmgrd        OK        Process
eventd:eventd          OK        Process
snmp:snmpd             OK        Process
snmp:snmp-subagent     OK        Process
lldp:lldpd             OK        Process
lldp:lldp-syncd        OK        Process
lldp:lldpmgrd          OK        Process
gnmi:gnmi-native       OK        Process
PSU 2                  Not OK    PSU
ASIC temp sensor       OK        ASIC
FAN-1F                 OK        Fan
FAN-1R                 OK        Fan
FAN-2F                 OK        Fan
FAN-2R                 OK        Fan
FAN-3F                 OK        Fan
FAN-3R                 OK        Fan
FAN-4F                 OK        Fan
FAN-4R                 OK        Fan
FAN-5F                 OK        Fan
FAN-5R                 OK        Fan
PSU 1                  OK        PSU

System services and devices ignore list

Name         Status    Type
-----------  --------  ------
PSU-1 FAN-1  Ignored   Device
PSU-2 FAN-1  Ignored   Device
```
didn't change any config.  but I did enable TLV information from the other switches (except from VMWare, this might be a bit difficult to do with vSwitch.

**Comment by mbze430** [comment]
more dump files...

[sonic_dump_sonic_20240508_140942.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15256905/sonic_dump_sonic_20240508_140942.tar.gz)
[sonic_dump_sonic_20240508_112110.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15256906/sonic_dump_sonic_20240508_112110.tar.gz)
[sonic_dump_sonic_20240508_111009.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15256909/sonic_dump_sonic_20240508_111009.tar.gz)
[sonic_dump_sonic_20240508_105607.tar.gz](https://github.com/sonic-net/sonic-buildimage/files/15256910/sonic_dump_sonic_20240508_105607.tar.gz)

**Comment by mbze430** [comment]
just to give an update.  I got the 8GB module.  From the looks of things, it's taking longer to to run out of memory, but it is inevitable.  I've been doing a 'sudo show system-memory' and it is slowly running out of memory.

**Comment by mbze430** [comment]
For record keeping
```
admin@sonic:~$ sudo show system-memory
               total        used        free      shared  buff/cache   available
Mem:            7922        6401         187         124        1332        1158
Swap:              0           0           0
```

**Comment by mbze430** [comment]
it looks like it reboot this morning
```
admin@sonic:~$ sudo show system-memory
               total        used        free      shared  buff/cache   available
Mem:            7922        2592        4019          80        1309        5016
Swap:              0           0           0
admin@sonic:~$ sudo show reboot-cause history
Name                 Cause                        Time    User    Comment
-------------------  ---------------------------  ------  ------  -------------------------------------------------------------
2024_05_15_08_28_54  Power Loss (Power on reset)  N/A     N/A     Unknown
```

**Comment by mbze430** [comment]
I am starting to feel that the issue I am having is related to #17025 

```
2024-05-10 23:05:50,312 INFO exited: dependent-startup (exit status 0; expected)
sonic-platform package not installed, attempting to install...
Error: Unable to locate /usr/share/sonic/platform/sonic_platform-1.0-py2-none-any.whl
/usr/local/lib/python3.9/dist-packages/supervisor/options.py:473: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  self.warnings.warn(
2024-05-15 08:30:59,802 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2024-05-15 08:30:59,802 INFO Set uid to user 0 succeeded
Unlinking stale socket /var/run/supervisor.sock
2024-05-15 08:31:00,117 INFO RPC interface 'supervisor' initialized
2024-05-15 08:31:00,117 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-05-15 08:31:00,118 INFO supervisord started with pid 1
2024-05-15 08:31:01,123 INFO spawned: 'dependent-startup' with pid 21
2024-05-15 08:31:01,128 INFO spawned: 'supervisor-proc-exit-listener' with pid 22
2024-05-15 08:31:02,495 INFO success: dependent-startup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-05-15 08:31:02,495 INFO success: supervisor-proc-exit-listener entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-05-15 08:31:02,598 INFO spawned: 'rsyslogd' with pid 25
2024-05-15 08:31:03,810 INFO success: rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-05-15 08:31:04,883 INFO spawned: 'chassis_db_init' with pid 29
2024-05-15 08:31:04,885 INFO success: chassis_db_init entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-05-15 08:31:04,897 INFO spawned: 'lm-sensors' with pid 30
2024-05-15 08:31:04,898 INFO success: lm-sensors entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-05-15 08:31:04,913 INFO spawned: 'fancontrol' with pid 31
2024-05-15 08:31:04,942 INFO spawned: 'xcvrd' with pid 33
2024-05-15 08:31:04,970 INFO spawned: 'psud' with pid 37
2024-05-15 08:31:05,001 INFO spawned: 'syseepromd' with pid 41
2024-05-15 08:31:05,040 INFO spawned: 'thermalctld' with pid 46
2024-05-15 08:31:05,078 INFO spawned: 'pcied' with pid 51
2024-05-15 08:31:07,155 INFO exited: chassis_db_init (exit status 0; expected)
2024-05-15 08:31:07,215 INFO exited: lm-sensors (exit status 0; expected)
2024-05-15 08:31:15,260 INFO success: fancontrol entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2024-05-15 08:31:15,260 INFO success: xcvrd entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2024-05-15 08:31:15,261 INFO success: psud entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2024-05-15 08:31:15,261 INFO success: syseepromd entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2024-05-15 08:31:15,261 INFO success: thermalctld entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2024-05-15 08:31:15,262 INFO success: pcied entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2024-05-15 08:31:16,730 INFO exited: dependent-startup (exit status 0; expected)
```

**Comment by mbze430** [comment]
```
admin@sonic:~$ sudo show system-memory
               total        used        free      shared  buff/cache   available
Mem:            7922        3509        2929          86        1482        4088
```
```
admin@sonic:~$ docker container stats --no-stream
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
c774224056c8   dhcp_relay       0.09%     73.49MiB / 7.736GiB   0.93%     0B / 0B   10.2MB / 217kB    69
8623ab159769   snmp             12.57%    66.16MiB / 7.736GiB   0.84%     0B / 0B   12.6MB / 131kB    11
268b2ad842c7   pmon             14.51%    1.317GiB / 7.736GiB   17.03%    0B / 0B   19.3MB / 147kB    20
5b05efd6d4f0   mgmt-framework   0.04%     60.5MiB / 7.736GiB    0.76%     0B / 0B   65.9MB / 69.6kB   16
8261ca44f473   lldp             0.05%     59.62MiB / 7.736GiB   0.75%     0B / 0B   10.3MB / 115kB    13
f28dfff8d7fd   gnmi             1.45%     99.05MiB / 7.736GiB   1.25%     0B / 0B   43.8MB / 86kB     28
ca106ae11b65   bgp              0.08%     171.9MiB / 7.736GiB   2.17%     0B / 0B   22.2MB / 140MB    30
c933aa6d838b   radv             0.07%     33.27MiB / 7.736GiB   0.42%     0B / 0B   5.7MB / 77.8kB    8
419bf92d9d39   syncd            19.19%    531.6MiB / 7.736GiB   6.71%     0B / 0B   286MB / 274kB     49
ad8352bc6290   teamd            0.16%     39.14MiB / 7.736GiB   0.49%     0B / 0B   5.26MB / 90.1kB   15
5cf4f2acfda6   swss             0.41%     76.62MiB / 7.736GiB   0.97%     0B / 0B   33.8MB / 303kB    48
f57b759b15de   eventd           0.43%     43.98MiB / 7.736GiB   0.56%     0B / 0B   4.16MB / 77.8kB   19
1d53abbaf1e7   database         6.70%     132.9MiB / 7.736GiB   1.68%     0B / 0B   48.1MB / 86kB     13
```

**Comment by mbze430** [comment]
@amazor I don't think it's lldp has a memory leak, rather it's PMON.  There is another report of it #17025.

@neethajohn can we get a dev to really look at the PMON docker?

**Comment by mbze430** [comment]
```
admin@sonic:~$ sudo show system-memory
               total        used        free      shared  buff/cache   available
Mem:            7922        4741        1614          99        1565        2839
Swap:              0           0           0
admin@sonic:~$ docker container stats --no-stream
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
c774224056c8   dhcp_relay       0.07%     73.51MiB / 7.736GiB   0.93%     0B / 0B   10.2MB / 217kB    69
8623ab159769   snmp             70.15%    66.16MiB / 7.736GiB   0.84%     0B / 0B   12.6MB / 131kB    11
268b2ad842c7   pmon             6.67%     2.507GiB / 7.736GiB   32.41%    0B / 0B   19.3MB / 147kB    20
5b05efd6d4f0   mgmt-framework   0.03%     60.5MiB / 7.736GiB    0.76%     0B / 0B   65.9MB / 69.6kB   16
8261ca44f473   lldp             0.09%     59.73MiB / 7.736GiB   0.75%     0B / 0B   10.3MB / 115kB    13
f28dfff8d7fd   gnmi             1.05%     99.13MiB / 7.736GiB   1.25%     0B / 0B   43.9MB / 86kB     28
ca106ae11b65   bgp              0.14%     174.1MiB / 7.736GiB   2.20%     0B / 0B   22.2MB / 281MB    30
c933aa6d838b   radv             0.04%     33.27MiB / 7.736GiB   0.42%     0B / 0B   5.7MB / 77.8kB    8
419bf92d9d39   syncd            17.24%    531.6MiB / 7.736GiB   6.71%     0B / 0B   286MB / 274kB     49
ad8352bc6290   teamd            0.20%     39MiB / 7.736GiB      0.49%     0B / 0B   5.26MB / 90.1kB   15
5cf4f2acfda6   swss             0.48%     76.69MiB / 7.736GiB   0.97%     0B / 0B   33.8MB / 303kB    48
f57b759b15de   eventd           0.45%     44.63MiB / 7.736GiB   0.56%     0B / 0B   4.16MB / 77.8kB   19
1d53abbaf1e7   database         5.34%     133.2MiB / 7.736GiB   1.68%     0B / 0B   48.1MB / 86kB     13
admin@sonic:~$
```

**Comment by mbze430** [comment]
as of ver: SONiC Software Version: SONiC.202311.564467-43bcca75f
per #17025 
there are no longer any memory leak in PMON.
