### ISSUE TITLE
system-pstore is not running - Dumps do not move to /var/lib/systemd/pstore/ 

### ISSUE THREAD

**Issue by DavidZagury** [sonic-net/sonic-buildimage#18895]
#### Description

The service systemd-pstore should moves dumps regarding kernel panics/oops from the UEFI storage onto the disk.
If this does not happen, carry a risk of filling up the UEFI storage space.
The service is not running at the moment - https://github.com/systemd/systemd/issues/18540

#### Steps to reproduce the issue:
1. Run (on UEFI enabled system) systemctl status systemd-pstore.service

Also can be shown that after simulating of a kernel panic/oops files are stored in /sys/firmware/efi/efivars/dump*

#### Describe the results you received:
```
● systemd-pstore.service - Platform Persistent Storage Archival
     Loaded: loaded (/lib/systemd/system/systemd-pstore.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
  Condition: start condition failed at Tue 2024-05-07 08:00:10 UTC; 1min 23s ago
       Docs: man:systemd-pstore(8)
```

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by neethajohn** [comment]
@saiarcot895 , please take a look at this issue
