### ISSUE TITLE
Breakout error on SN2700 

### ISSUE THREAD

**Issue by aprrodrigues** [sonic-net/sonic-buildimage#18913]
admin@sonic:~$ sudo config interface breakout Ethernet0 4x25G[10G] -y -f
[ERROR] Target mode 4x25G[10G] is not available for the port Ethernet0
Aborted!

Any interface that i use i have this error.

SONiC Software Version: SONiC.master.541012-a268da38c
SONiC OS Version: 12
Distribution: Debian 12.5
Kernel: 6.1.0-11-2-amd64
Build commit: a268da38c
Build date: Tue May  7 12:26:21 UTC 2024
Built by: AzDevOps@vmss-soni003MHY

Platform: x86_64-mlnx_msn2700-r0
HwSKU: ACS-MSN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2026J35294
Model Number: MSN2700-CS2ROS
Hardware Revision: A2
Uptime: 19:06:00 up 53 min,  1 user,  load average: 0.56, 0.53, 0.63
Date: Wed 08 May 2024 19:06:00

Docker images:
REPOSITORY                    TAG                       IMAGE ID       SIZE
docker-syncd-mlnx             latest                    4fcf603470da   779MB
docker-syncd-mlnx             master.541012-a268da38c   4fcf603470da   779MB
docker-orchagent              latest                    cd612e355e32   343MB
docker-orchagent              master.541012-a268da38c   cd612e355e32   343MB
docker-macsec                 latest                    e62cdeb9625c   332MB
docker-nat                    latest                    c56311863e0e   332MB
docker-nat                    master.541012-a268da38c   c56311863e0e   332MB
docker-teamd                  latest                    6a6585234744   330MB
docker-teamd                  master.541012-a268da38c   6a6585234744   330MB
docker-dhcp-relay             latest                    0c379ebc0dfa   311MB
docker-snmp                   latest                    88dd3287e96b   341MB
docker-snmp                   master.541012-a268da38c   88dd3287e96b   341MB
docker-platform-monitor       latest                    4c82d3c7525c   590MB
docker-platform-monitor       master.541012-a268da38c   4c82d3c7525c   590MB
docker-lldp                   latest                    b36202d6b503   348MB
docker-lldp                   master.541012-a268da38c   b36202d6b503   348MB
docker-router-advertiser      latest                    511be2cabc5c   302MB
docker-router-advertiser      master.541012-a268da38c   511be2cabc5c   302MB
docker-database               latest                    da0acafb4e88   310MB
docker-database               master.541012-a268da38c   da0acafb4e88   310MB
docker-mux                    latest                    5404373b8570   354MB
docker-mux                    master.541012-a268da38c   5404373b8570   354MB
docker-eventd                 latest                    e1cfc0f7a7d8   302MB
docker-eventd                 master.541012-a268da38c   e1cfc0f7a7d8   302MB
docker-fpm-frr                latest                    d8e960958a82   362MB
docker-fpm-frr                master.541012-a268da38c   d8e960958a82   362MB
docker-sflow                  latest                    d3912025d2ca   332MB
docker-sflow                  master.541012-a268da38c   d3912025d2ca   332MB
docker-sonic-gnmi             latest                    54cbb49c2169   391MB
docker-sonic-gnmi             master.541012-a268da38c   54cbb49c2169   391MB
docker-sonic-mgmt-framework   latest                    35ee18ba482b   382MB
docker-sonic-mgmt-framework   master.541012-a268da38c   35ee18ba482b   382MB

**Comment by amazor** [comment]
Hi, 

In order to use breakout, you must have the specific breakout mode applied to your hwsku.json and platform.json.

Your Platform is: x86_64-mlnx_msn2700-r0
Your hwsku is: ACS-MSN2700

These files can be found (or created) in:
 /usr/share/sonic/device/<PLATFORM>/platform.json
/usr/share/sonic/device/<>PLATFORM>/<HWSKU>/hwsku.json

You can find an example of hwsku.json [here](https://github.com/sonic-net/sonic-buildimage/blob/master/platform/vs/docker-sonic-vs/hwsku.json)

You can find an example of platform.json [here](https://github.com/sonic-net/sonic-buildimage/blob/master/platform/vs/docker-sonic-vs/platform.json)

For the specific syntax specification you can check out the high-level design document [here](https://github.com/sonic-net/SONiC/blob/ada7fd063c31c075a2482abe7a9a168b8d7a6240/doc/dynamic-port-breakout/sonic-dynamic-port-breakout-HLD.md)

Hope this helps, let me know if you have any more issues with port breakout after adding Target mode 4x25G[10G] for Ethernet0 to your json files.

**Comment by aprrodrigues** [comment]
I change the file platform.json.

then when i apply mode 4x25[10G] on the interface he accept but makes the switch reboot many times and all interfaces dissapear.

**Comment by amazor** [comment]
Can you attach your json files as well as your log?

**Comment by aprrodrigues** [comment]
Here is my files
[hwsku.json](https://github.com/sonic-net/sonic-buildimage/files/15265507/hwsku.json)
[platform.json](https://github.com/sonic-net/sonic-buildimage/files/15265508/platform.json)

**Comment by aprrodrigues** [comment]
Hi,

I found where the error was, the SN2700 has a limitation on the ports, when it breakout (4 ports) I have to remove the next port.

Example: 4x25G on port Ethernet0 i have to remove the Ethernet4.

**Comment by gechiang** [comment]
@aprrodrigues , if you no longer having issue other than the limitation on number of breakpouts, please go ahead close this isue.
Thanks!
