### ISSUE TITLE
[ssdutil] [Vitrium] Can't read ssd temperature on Vitrium nvme disks

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#19020]
#### Steps to reproduce the issue:
```
root@r-hw-sonic-01:/home/admin# show platform ssdhealth
```

#### Describe the results you received:

```
[Error] Cannot read SMART information on device /dev/nvme0n1
Device Model : Virtium VTPM24CEXI080-BM110006
Health       : 100.0%
Temperature  : N/A
```

#### Describe the results you expected:
Should read temperature correctly.

**Comment by volodymyrsamotiy** [comment]
@saiarcot895, could you please help to check?

**Comment by gechiang** [comment]
Why you believe this is generic issue and not platform specific issue?  please provide more info. also which HW platform...
@vivekrnv

**Comment by vivekrnv** [comment]
It is seen on Vitrium disks on our platform. It is seen on our new platform (smartswitch) which uses nvme. According to the ticket opened on smartmontools it is seen on KINGSTON SFYRS1000G, Corsair MP600 PRO NH 8TB. So, i think there's enough evidence to assume it is a generic issue related to smartmontools and NVMe disks

**Comment by gechiang** [comment]
@prgeor Can you help take a look to see who should own the NVME support?  Sounds like a new platform specific support needed.  Should we ask community to help on this?
