### ISSUE TITLE
[xcvrd] typo "log_notifce" results in port oper down

### ISSUE THREAD

**Issue by Junchao-Mellanox** [sonic-net/sonic-buildimage#19116]
#### Description

PR https://github.com/sonic-net/sonic-platform-daemons/pull/459 introduces a typo "log_notifce". Check line: https://github.com/sonic-net/sonic-platform-daemons/blob/9ffce2036d53571bd23b4a630ac285039e383c4f/sonic-xcvrd/xcvrd/xcvrd.py#L1482.

It causes an exception in cmis task manager which results in port down:

```
May 27 20:38:17.489639 sonic ERR pmon#xcvrd: CMIS: Ethernet96: internal errors due to 'CmisManagerTask' object has no attribute 'log_notifce'
```

#### Steps to reproduce the issue:
no need

#### Describe the results you received:
typo and port not up

#### Describe the results you expected:
No typo and port should up

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by arlakshm** [comment]
This issue is fixed. Closing it
