### ISSUE TITLE
ERR swss#orchagent: :- doDecapTunnelTask: unknown decap tunnel table attribute 'dst_ip'.

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#19145]
#### Description

The following error is seen when IP address is assigned to an interface and config reload/reboot is performed

```
ERR swss#orchagent: :- doDecapTunnelTask: unknown decap tunnel table attribute 'dst_ip'.
```

The IPINIP tunnel that is implicitly created contains dst_ip.
```
  "TUNNEL_DECAP_TABLE:IPINIP_TUNNEL": {
    "expireat": 1717084665.954929,
    "ttl": -0.001,
    "type": "hash",
    "value": {
      "dscp_mode": "uniform",
      "dst_ip": "10.0.1.1,10.1.0.32,100.0.0.1,101.0.0.1,20.0.0.1,30.0.0.1,40.0.0.1,50.0.0.1,69.0.0.1,69.0.1.1",
      "ecn_mode": "standard",
      "ttl_mode": "pipe",
      "tunnel_type": "IPINIP"
    }
  },
```

However the recent code changes made in this PR https://github.com/sonic-net/sonic-swss/pull/3117 doesn't parse dst_ip and error log is seen.

#### Steps to reproduce the issue:
1. Add IP address to any interface
2. Perform reboot or config reload
3.

#### Describe the results you received:
Error in the syslog

#### Describe the results you expected:
No error in syslog

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by dgsudharsan** [comment]
@prsunny @lolyu  Can you please investigate this?

**Comment by prsunny** [comment]
@bingwang-ms for viz

**Comment by bingwang-ms** [comment]
Acked. Will check.

**Comment by lolyu** [comment]
PR https://github.com/sonic-net/sonic-buildimage/pull/18752 will fix this.

**Comment by prsunny** [comment]
Closing this as PR is merged
