### ISSUE TITLE
Build Error in SONiC 202305 branch - Marvell ARM64 on amd64 build server

### ISSUE THREAD

**Issue by samaity** [sonic-net/sonic-buildimage#19146]
#### Description

I am trying to build a Marvell-ARM64 image  (based on 202305 source code) on amd64 build server

I am facing the below compilation/build error. 
```

ERROR: failed to solve: process "/bin/sh -c apt-get update || apt-get install -y gnupg" did not complete successfully: exit code: 100
Unable to find image 'sonic-slave-bullseye-march-arm64:5f789a86c41' locally
Error response from daemon: pull access denied for sonic-slave-bullseye-march-arm64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error response from daemon: No such container: sonic-slave-bullseye-march-arm64-5f789a86c41
Error response from daemon: No such container: sonic-slave-bullseye-march-arm64-5f789a86c41
Error response from daemon: No such container: sonic-slave-bullseye-march-arm64-5f789a86c41
Error response from daemon: No such image: sonic-slave-bullseye-march-arm64:5f789a86c41
[+] Building 1.4s (3/3) FINISHED                                                                                                 docker:default
 => [internal] load .dockerignore                                                                                                          0.4s
 => => transferring context: 2B                                                                                                            0.0s
 => [internal] load build definition from Dockerfile.cleanup                                                                               0.3s
 => => transferring dockerfile: 354B                                                                                                       0.0s
 => ERROR [internal] load metadata for docker.io/library/sonic-slave-bullseye-march-arm64:5f789a86c41                                      0.6s
------
 > [internal] load metadata for docker.io/library/sonic-slave-bullseye-march-arm64:5f789a86c41:
------
Dockerfile.cleanup:6
--------------------
   4 |     # Copy the cache data to host
   5 |     From scratch as output
   6 | >>> COPY --from=sonic-slave-bullseye-march-arm64:5f789a86c41 /cache.tgz cache.tgz
   7 |
   8 |     # Clean up the cache data
--------------------
ERROR: failed to solve: sonic-slave-bullseye-march-arm64:5f789a86c41: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
[+] Building 1.3s (3/3) FINISHED                                                                                                 docker:default
 => [internal] load build definition from Dockerfile.cleanup                                                                               0.4s
 => => transferring dockerfile: 354B                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                          0.3s
 => => transferring context: 2B                                                                                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/sonic-slave-bullseye-march-arm64:5f789a86c41                                      0.4s
------
 > [internal] load metadata for docker.io/library/sonic-slave-bullseye-march-arm64:5f789a86c41:
------
Dockerfile.cleanup:9
--------------------
   7 |
   8 |     # Clean up the cache data
   9 | >>> FROM sonic-slave-bullseye-march-arm64:5f789a86c41 as final
  10 |     RUN rm /cache.tgz
  11 |
--------------------
```

Steps followed:
Step 1: git clone -b 202305 https://github.com/sonic-net/sonic-buildimage.git
Step 2: cd sonic-buildimage
Step 3: make init
Step 5: make configure PLATFORM=marvell-arm64 PLATFORM_ARCH=arm64

#### Describe the results you received:

I noticed the azure pipeline is using the arm64 server, did cross compilation ever work for the 202305 branch?

**Comment by arlakshm** [comment]
@xumia, can you help with this issue?

**Comment by xumia** [comment]
@liushilongbuaa , could you please help on it? Thanks.

**Comment by liushilongbuaa** [comment]
The following packages have unmet dependencies:
 dirmngr : Depends: gpgconf (= 2.2.27-2+deb11u2) but it is not going to be installed
           Depends: libassuan0 (>= 2.5.0) but it is not installable
           Depends: libgnutls30 (>= 3.7.0) but 3.6.15-4 is to be installed
           Depends: libldap-2.4-2 (>= 2.4.7) but it is not going to be installed
           Depends: libnpth0 (>= 0.90) but it is not installable
 gnupg-utils : Depends: libassuan0 (>= 2.5.0) but it is not installable
               Depends: libreadline8 (>= 6.0) but it is not installable
               Recommends: gpgconf but it is not going to be installed
 gpg : Depends: gpgconf (= 2.2.27-2+deb11u2) but it is not going to be installed
       Depends: libassuan0 (>= 2.5.0) but it is not installable
       Depends: libreadline8 (>= 6.0) but it is not installable
       Depends: libsqlite3-0 (>= 3.7.15) but it is not installable
 gpg-agent : Depends: gpgconf (= 2.2.27-2+deb11u2) but it is not going to be installed
             Depends: pinentry-curses but it is not installable or
                      pinentry but it is not installable
             Depends: libassuan0 (>= 2.5.1) but it is not installable
             Depends: libnpth0 (>= 0.90) but it is not installable
 gpg-wks-client : Depends: libassuan0 (>= 2.5.0) but it is not installable
 gpgsm : Depends: gpgconf (= 2.2.27-2+deb11u2) but it is not going to be installed
         Depends: libassuan0 (>= 2.5.0) but it is not installable
         Depends: libreadline8 (>= 6.0) but it is not installable

Here is the detailed error message.

**Comment by liushilongbuaa** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/19226
A workaround PR.

**Comment by zhiqqqq** [comment]
I came across the same error when I built bookworm user image. When building `sonic-slave-bookworm-march-arm64-<username>` image, an error called `cannot find sonic-slave-bookworm-march-arm64:<tag> locally` was prompted, even though I had that local image.
Seems that `--platform=linux/arm64` should be added when arm64 images are imported by `FROM` cmd at amd64 machines.
So it looks like:
```
lang=dockerfile
ARG slave_base_tag_ref=latest
FROM --platform=linux/arm64 sonic-slave-bookworm-march-arm64:${slave_base_tag_ref}
```
@samaity

**Comment by Prsahs** [comment]
> I came across the same error when I built bookworm user image. When building `sonic-slave-bookworm-march-arm64-<username>` image, an error called `cannot find sonic-slave-bookworm-march-arm64:<tag> locally` was prompted, even though I had that local image. Seems that `--platform=linux/arm64` should be added when arm64 images are imported by `FROM` cmd at amd64 machines. So it looks like:
> 
> ```
> ARG slave_base_tag_ref=latest
> FROM --platform=linux/arm64 sonic-slave-bookworm-march-arm64:${slave_base_tag_ref}
> ```
> 
> @samaity

I have the same problem, is it solved now?

**Comment by zhiqqqq** [comment]
> > I came across the same error when I built bookworm user image. When building `sonic-slave-bookworm-march-arm64-<username>` image, an error called `cannot find sonic-slave-bookworm-march-arm64:<tag> locally` was prompted, even though I had that local image. Seems that `--platform=linux/arm64` should be added when arm64 images are imported by `FROM` cmd at amd64 machines. So it looks like:
> > ```
> > ARG slave_base_tag_ref=latest
> > FROM --platform=linux/arm64 sonic-slave-bookworm-march-arm64:${slave_base_tag_ref}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @samaity
> 
> I have the same problem, is it solved now?

@Prsahs Adding `--platform=linux/arm64` works for me, you can have a try.
