### ISSUE TITLE
[chassis][master] : sonic-mgmt precheck fails on missing lldp serive on LCs

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#19174]
#### Description
Afer https://github.com/sonic-net/sonic-host-services/pull/120, global lldp service is disabled on LCs.
This requires sonic-mgmt change to handle this in pre-checks.

WARNING  root:recover.py:169 Restoring {'failed': True, 'check_item': 'processes', 'host': 'sfd-lt2-lc0', 'processes_status': {'pmon': {'status': True, 'exited_critical_process': [], 'running_critical_process': []}, 'snmp': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['snmp-subagent', 'snmpd']}, **'lldp': {'status': False, 'exited_critical_process': [], 'running_critical_process': []},** 'database': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['redis']}, 'bgp0': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['bgpcfgd', 'bgpd', 'fpmsyncd', 'staticd', 'zebra']}, 'database0': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['redis']}, 'lldp0': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['lldp-syncd', 'lldpd', 'lldpmgrd']}, 'swss0': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['buffermgrd', 'coppmgrd', 'fabricmgrd', 'fdbsyncd', 'intfmgrd', 'nbrmgrd', 'neighsyncd', 'orchagent', 'portmgrd', 'portsyncd', 'tunnelmgrd', 'vlanmgrd', 'vrfmgrd', 'vxlanmgrd']}, 'syncd0': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['syncd']}, 'teamd0': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['teammgrd', 'teamsyncd', 'tlm_teamd']}, 'macsec0': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['macsecmgrd']}, 'gbsyncd0': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['syncd']}, 'bgp1': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['bgpcfgd', 'bgpd', 'fpmsyncd', 'staticd', 'zebra']}, 'database1': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['redis']}, 'lldp1': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['lldp-syncd', 'lldpd', 'lldpmgrd']}, 'swss1': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['buffermgrd', 'coppmgrd', 'fabricmgrd', 'fdbsyncd', 'intfmgrd', 'nbrmgrd', 'neighsyncd', 'orchagent', 'portmgrd', 'portsyncd', 'tunnelmgrd', 'vlanmgrd', 'vrfmgrd', 'vxlanmgrd']}, 'syncd1': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['syncd']}, 'teamd1': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['teammgrd', 'teamsyncd', 'tlm_teamd']}, 'macsec1': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['macsecmgrd']}, 'gbsyncd1': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['syncd']}, 'bgp2': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['bgpcfgd', 'bgpd', 'fpmsyncd', 'staticd', 'zebra']}, 'database2': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['redis']}, 'lldp2': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['lldp-syncd', 'lldpd', 'lldpmgrd']}, 'swss2': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['buffermgrd', 'coppmgrd', 'fabricmgrd', 'fdbsyncd', 'intfmgrd', 'nbrmgrd', 'neighsyncd', 'orchagent', 'portmgrd', 'portsyncd', 'tunnelmgrd', 'vlanmgrd', 'vrfmgrd', 'vxlanmgrd']}, 'syncd2': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['syncd']}, 'teamd2': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['teammgrd', 'teamsyncd', 'tlm_teamd']}, 'macsec2': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['macsecmgrd']}, 'gbsyncd2': {'status': True, 'exited_critical_process': [], 'running_critical_process': ['syncd']}}, 'services_status': {'pmon': True, 'snmp': True, 'lldp': False, 'database': True, 'bgp0': True, 'database0': True, 'lldp0': True, 'swss0': True, 'syncd0': True, 'teamd0': True, 'macsec0': True, 'gbsyncd0': True, 'bgp1': True, 'database1': True, 'lldp1': True, 'swss1': True, 'syncd1': True, 'teamd1': True, 'macsec1': True, 'gbsyncd1': True, 'bgp2': True, 'database2': True, 'lldp2': True, 'swss2': True, 'syncd2': True, 'teamd2': True, 'macsec2': True, 'gbsyncd2': True}} with proposed action: config_reload, final action: config_reload

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
Hi @abdosi , @vperumal  for you viz

**Comment by abdosi** [comment]
working on this
