### ISSUE TITLE
[Chassis] Master: Fabric monitor feature isolates the fabric ports in SUP when the config reload is done in LC

### ISSUE THREAD

**Issue by saksarav-nokia** [sonic-net/sonic-buildimage#19288]
#### Description
In Nokia chassis, the SUP isolates the fabric ports in Ramon when we issue "config reload" in IMM.  This causes iBGP not coming up in some scenarios when all the fabric ports are isolated. We have the following fabric_monitor json config 

  "FABRIC_MONITOR_DATA": {
      "monErrThreshCrcCells": 1,
      "monErrThreshRxCells": 61035156,
      "monPollThreshRecovery": 8,
      "monPollThreshIsolation": 1,
      "monCapacityThreshWarn": 10,
      "monState": "enable"

When the  Ramon/J2C+ is initialized, we always see some CRC errors which is expected according to BCM. Does the fabric monitor code considers this?.

damin@ixre-cpm-chassis15:$ fabricstat | grep 54
     6      54       up        808     130,205         743      112,929  1,170                  4                    0             4
     6      56       up        801     128,098         714      106,911    954                  1                    0             1
     6      99       up        912     148,154         843      124,388  1,953                 57                    0            57
     6     154     down          0           0           0            0      0                  0                    0             0
     6     161       up        781     108,543         820      127,607      0                  2                    0             2
     7      54     down          0           0           0            0      0                  0                    0             0
     7     122       up        906     145,369         854      126,993    983                 10                    0            10
     7     154     down          0           0           0            0      0                  0                    0             0

yslog.1:2024 Jun 12 17:19:26.230943 ixre-cpm-chassis15 NOTICE swss6#orchagent: :- updateFabricDebugCounters: port PORT54 set AUTO_ISOLATED 1
syslog.1:2024 Jun 12 17:19:26.230943 ixre-cpm-chassis15 NOTICE swss6#orchagent: :- updateFabricDebugCounters: Set fabric port 54 with isolate 1 
syslog.1:2024 Jun 12 17:19:26.243328 ixre-cpm-chassis15 NOTICE swss6#orchagent: :- updateFabricDebugCounters: Set fabric port 54 state done 1 
syslog.1:2024 Jun 12 17:27:26.263980 ixre-cpm-chassis15 NOTICE swss6#orchagent: :- updateFabricDebugCounters: Set fabric port 54 with isolate 0 
syslog.1:2024 Jun 12 17:27:26.265382 ixre-cpm-chassis15 NOTICE swss6#orchagent: :- updateFabricDebugCounters: Set fabric port 54 state done 0 

#### Steps to reproduce the issue:
1. Load latest master code in chassis
2. sudo config reload in IMM
3. check the syslog

#### Describe the results you received:
Fabric ports are isolated in SUP

#### Describe the results you expected:
The fabric ports should not be isolated during config reload or IMM reboot.

#### Output of `show version`:
latest master code
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by saksarav-nokia** [comment]
@arlakshm for viz

**Comment by saksarav-nokia** [comment]
@jfeng-arista  for viz

In the function FabricPortsOrch::updateFabricDebugCounters, where is skipCrcErrorsOnLinkupCount reset when the fabric ports go down?
 if (skipCrcErrorsOnLinkupCount < maxSkipCrcCnt)
        {
            skipCrcErrorsOnLinkupCount += 1;
            valuePt = to_string(skipCrcErrorsOnLinkupCount);
            m_stateTable->hset(key, "SKIP_CRC_ERR_ON_LNKUP_CNT", valuePt.c_str());
            SWSS_LOG_INFO("port %s updates SKIP_CRC_ERR_ON_LNKUP_CNT to %s %d",
                          key.c_str(), valuePt.c_str(), skipCrcErrorsOnLinkupCount);
            // update error counters.
            prevCrcErrors = crcErrors;
        }
        else
        {
            uint64_t diffRxCells = 0;
            uint64_t diffCrcCells = 0;

            diffRxCells = rxCells - prevRxCells;
            if (testState == "TEST"){
                diffCrcCells = testCrcErrors - prevCrcErrors;
                prevCrcErrors = 0;
                isolationPollsCfg = isolationPollsCfg + 1;
            }
            else
            {
                diffCrcCells = crcErrors - prevCrcErrors;
                prevCrcErrors = crcErrors;
            }
            bool isErrorRateMore =
               ((diffCrcCells * errorRateRxCellsCfg) >
                (diffRxCells * errorRateCrcCellsCfg));
            if (isErrorRateMore)
            {
                if (consecutivePollsWithErrors < isolationPollsCfg)
                {
                    consecutivePollsWithErrors += 1;
                    consecutivePollsWithNoErrors = 0;
                }
            } else {
                if (consecutivePollsWithNoErrors < recoveryPollsCfg)
                {
                    consecutivePollsWithNoErrors += 1;
                    consecutivePollsWithErrors = 0;
                }
            }
            SWSS_LOG_INFO("port %s diffCrcCells %lld", key.c_str(), (long long)diffCrcCells);
            SWSS_LOG_INFO("consecutivePollsWithCRCErrs %d consecutivePollsWithNoCRCErrs %d",
                           consecutivePollsWithErrors, consecutivePollsWithNoErrors);
        }

**Comment by saksarav-nokia** [comment]
Here is some more info about this issue.
The fabricportsorch polls the fabric port status every FABRIC_POLLING_INTERVAL_DEFAULT (30secs) and the fabric port monitor interval is FABRIC_DEBUG_POLLING_INTERVAL_DEFAULT (60secs).
When the config reload is issued in IMM, the fabric ports in SUP goes down and stays down when the asic is reset in J2C+ and till the fabric ports are enabled in J2C+. 
This duration is less than 60secs and not detected by fabric monitor even though fabric port status down is detected by fabricportsorch and updated in STATE_DB and it is reflected in "show fabric reachability" output.  Also the skipCrcErrorsOnLinkupCount is not reset anywhere. So after couple of config reload or reboot of IMM, the SUP isolates the fabric ports.

**Comment by rlhui** [comment]
not nokia platfrom specific

**Comment by kenneth-arista** [comment]
@jfeng-arista for awareness

**Comment by saksarav-nokia** [comment]
@kenneth-arista , When can we expect the fix for this?

**Comment by kenneth-arista** [comment]
> @kenneth-arista , When can we expect the fix for this?

See https://github.com/sonic-net/sonic-swss/pull/3247

**Comment by kenneth-arista** [comment]
https://github.com/sonic-net/sonic-swss/pull/3247 merged to master. Please close this issue.
