### ISSUE TITLE
[MCLAG] iccpd cannot execute "ebtables" command.

### ISSUE THREAD

**Issue by puffc** [sonic-net/sonic-buildimage#19323]
#### Description

According to the description excerpted from the MCLAG HLD, ICCPd must use ebtables rules to isolate the peer link port and the MCLAG port channel, preventing trapped BUM packets from looping back to the MCLAG port channel through the peer link:

"In Linux kernel, ebtable is used to isolate peer link port from MC-LAG port. The Linux command is like ‘ebtables –A FORWARD -i PortChannel0002 -o PortChannel0001 -j DROP’. PortChannel0002 is the peer-link input interface, and PortChannel0001 is the output interface."

However, the ICCPd Docker still uses the legacy ebtables utilities, preventing ICCPd from adding ebtables rules to the kernel nftables.

#### Steps to reproduce the issue:
1. execute "docker exec -it iccpd bash
2. execute "ebtables -L"

#### Describe the results you received:
ebtables command returns "The kernel doesn't support the ebtables 'filter' table." error.

#### Describe the results you expected:
<pre>
admin@sonic:~$ sudo ebtables -L
Bridge table: filter

Bridge chain: INPUT, entries: 0, policy: ACCEPT

Bridge chain: FORWARD, entries: 4, policy: ACCEPT
-i PortChannel2 -o PortChannel1 -j DROP
-d BGA -j DROP
-p ARP -j DROP
-p 802_1Q --vlan-encap 0806 -j DROP

</pre>

#### Output of `show version`:

```
202305
202211
```

**Comment by TafkaMax** [comment]
Same issue here. I am running the master branch.
