### ISSUE TITLE
Reg: Sequential IDF isolation skipping condition is based on switch type and not type leading to skipping of the feature

### ISSUE THREAD

**Issue by vikshaw-Nokia** [sonic-net/sonic-buildimage#19379]
#### Description
While executing the feature IDF Isolation.
The Feature is getting skipped as per syslog, even though the type is SpineRouter because the code checks for "switch type" being "SpineRouter" and not just "type" in the code 
Please see the reference below  
For the PR: https://github.com/sonic-net/sonic-buildimage/pull/19136/files
The File name src/sonic-bgpcfgd/bgpcfgd/managers_bgp.py
The Code uses the switch type for deciding the skipping condition.
![image](https://github.com/sonic-net/sonic-buildimage/assets/135994174/851f3d51-a683-439b-906f-a1d769303fbb)

Whereas in the the code file dockers/docker-fpm-frr/base_image_files/idf_isolation.
The Condition for checking the type uses the just the type and not the switch type.
![image](https://github.com/sonic-net/sonic-buildimage/assets/135994174/c7178070-74dd-40e2-9a74-15e5354527f3)

#### Steps to reproduce the issue:
1. Use the latest Master Image 
2. After installation check the "sonic-cfggen -d -v DEVICE_METADATA.localhost.type"
3. If the output is Spine Router then the feature is supported
4. Execution the IDF Isolation to any other state i.e. withdrawall or no export
5. Observe the logs if the Feature policy gets skipped

#### Describe the results you received:
1. "sonic-cfggen -d -v DEVICE_METADATA.localhost.type" is SpineRouter
2. "sonic-cfggen -d -v DEVICE_METADATA.localhost.switch_type" is voq
3.  Execute "sudo idf_isolation isolated_withdraw_all"
4. Observe the syslog for skipping the use_case

#### Describe the results you expected:
1. The Policy is applied

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prgeor** [comment]
@tjchadaga can you check why not checking switch type for idf isolation
