### ISSUE TITLE
[202205] 'show techsupport' not working properly from SUP. Fine on LC.

### ISSUE THREAD

**Issue by vmittal-msft** [sonic-net/sonic-buildimage#19405]
'show techsupport' is not collecting all the data from SUP and missing information. It is working fine from the LC.

**Comment by vmittal-msft** [comment]
[sonic_dump_str3-7808-sup-1_20240627_060038.tar.log](https://github.com/user-attachments/files/16008810/sonic_dump_str3-7808-sup-1_20240627_060038.tar.log)

**Comment by prgeor** [comment]
@judyjoseph needs to be discussed in chassis group

**Comment by arlakshm** [comment]
check to see if the sonic-mgmt `show techsupport` testcase passes on superivisor. we need to create a testgap if this test does not run on supervisior

**Comment by deepak-singhal0408** [comment]
Nokia will be helping on this issue. @vmittal-msft/@Deepak to provide more logs from Prod/Lab Device,

**Comment by vmittal-msft** [comment]
I am not seeing this issue on lab device but happening on production.

**Comment by vmittal-msft** [comment]
[sonic_dump_MIL01-0101-0100-01T2-sup00_20240729_234135.tar.gz](https://github.com/user-attachments/files/16420501/sonic_dump_MIL01-0101-0100-01T2-sup00_20240729_234135.tar.gz)

**Comment by vmittal-msft** [comment]
Lab device -
https://nokianam.sharepoint.com/:u:/r/sites/MSFTNOKIASONiCChassisTeamChannel/Shared%20Documents/General/Nokia_logs/[sonic_dump_str2-7250-sup-1_20240730_003522.tar.gz](https://nokianam.sharepoint.com/:u:/r/sites/MSFTNOKIASONiCChassisTeamChannel/Shared%20Documents/General/Nokia_logs/sonic_dump_str2-7250-sup-1_20240730_003522.tar.gz?csf=1&web=1&e=6UhlP1)?csf=1&web=1&e=6UhlP1

**Comment by vmittal-msft** [comment]
Closing this issue.
