### ISSUE TITLE
[202205] Multicast replication error on sonic T2 chassis

### ISSUE THREAD

**Issue by vmittal-msft** [sonic-net/sonic-buildimage#19404]
It is observed that packet loss happens due to multicast replication error on sonic T2 chassis although no multicast traffic. The possibility is that LLDP traffic could be going to recycle port and getting dropped. Need to investigate further.

![image](https://github.com/sonic-net/sonic-buildimage/assets/46945843/a387257e-0d46-4f99-92cd-711e27dea06d)

**Comment by prgeor** [comment]
@abdosi seems like you have a fix for this @judyjoseph FYI

**Comment by abdosi** [comment]
Closed via https://github.com/sonic-net/sonic-buildimage/pull/15440
