### ISSUE TITLE
[syncd] syncd should handle SAI_REDIS_NOTIFY_SYNCD_INVOKE_DUMP even if temp view is not enabled

### ISSUE THREAD

**Issue by Junchao-Mellanox** [sonic-net/sonic-buildimage#19411]
#### Description

At line https://github.com/sonic-net/sonic-sairedis/blob/a988dd1b7b9044fd7ca859ecdfa1eb858cc3ea08/syncd/Syncd.cpp#L3759, the function`processNotifySyncd` will exit early if temp view is not enabled. It will even ignore SAI_REDIS_NOTIFY_SYNCD_INVOKE_DUMP notification. This is not reasonable.

#### Steps to reproduce the issue:
1. Do a fast-reboot which will set m_commandLineOptions->m_enableTempView to false
2. Trigger a dump from orchagent

#### Describe the results you received:

syncd will not collect sai dump

#### Describe the results you expected:

syncd should collect sai dump

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prgeor** [comment]
@liat-grozovik @dgsudharsan could you help check if this feature is fully supported to collet sai redis dump in fast reboot fail scenario
