### ISSUE TITLE
NTP configuration no longer has iburst enabled by default

### ISSUE THREAD

**Issue by saiarcot895** [sonic-net/sonic-buildimage#19425]
#### Description

On 202305 and older images, NTP servers that were configured in config_db.json had iburst enabled by default. However, with #15058, because iburst was split into a separate configurable option (along with other options being added), and iburst needed to be enabled by default, the iburst option was removed from `ntp.conf`. While there's a way to restore this option when loading a config_db.json file, there's no easy way to do this when loading from minigraph (except for manually adding the option into the generated config_db.json file and either doing a `config reload` or restarting ntp-config and ntp services).

#### Steps to reproduce the issue:
1. Load a 202311, 202405, or master branch image, and load a minigraph.xml file that has an NTP server specified. (The one generated from sonic-mgmt works for this purpose)

#### Describe the results you received:

In `/etc/ntpsec/ntp.conf`, on master branch (only the relevant lines pasted here):

```
server 10.0.0.1
restrict 10.0.0.1 kod limited nomodify noquery

server 10.0.0.2
restrict 10.0.0.2 kod limited nomodify noquery
```

#### Describe the results you expected:

The `server` lines above should have `iburst` at the end.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

Relevant section of `config_db.json`:

```
    "NTP_SERVER": {
        "10.0.0.1": {},
        "10.0.0.2": {}
    },
```

**Comment by prgeor** [comment]
@saiarcot895 seems you have the PR for enabling iburst. can you tag that in this issue
