### ISSUE TITLE
[202405] ORDERED_ECMP_CAPABLE is missing in  SWITCH_CAPABILITY|switch in Config_DB

### ISSUE THREAD

**Issue by vikshaw-Nokia** [sonic-net/sonic-buildimage#19455]
#### Description
In Database  Config DB the KEY "SWITCH_CAPABILITY|switch" is missing the entry for ORDERED_ECMP_CAPABLE..

#### Steps to reproduce the issue:
1. Login to the database container on 202405
2. Execute the command redis-cli -n 6 HGETALL "SWITCH_CAPABILITY|switch"
3. Observe the Use Case as below

#### Describe the results you received:
Missing Data ORDERED_ECMP_CAPABLE 
![image](https://github.com/sonic-net/sonic-buildimage/assets/135994174/d4ec3698-bac4-44ea-b131-427d8a263a8a)

#### Describe the results you expected:
Working in master branch
![image](https://github.com/sonic-net/sonic-buildimage/assets/135994174/be2846a3-94b8-448c-b04d-c0110d265290)

#### Output of `show version`:
![image](https://github.com/sonic-net/sonic-buildimage/assets/135994174/519a41eb-7b7b-43b9-82e5-baffc68becc3)

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prgeor** [comment]
@mlok-nokia seems this is under discussion in chassis

**Comment by abdosi** [comment]
@mlok-nokia : do we need this for chassis ?

**Comment by arlakshm** [comment]
This cause sonic-mgmt test failures because the capability is missing.

**Comment by arlakshm** [comment]
@abdosi, can you check on this?

**Comment by saksarav-nokia** [comment]
@vikshaw-Nokia , can you test with latest 202405?. When i tried today, i see the ORDERED_ECMP_CAPABLE field in the STATE_DB in both asic0 and asic1
![image](https://github.com/user-attachments/assets/568bc1f6-4d0c-4d4c-9d18-60f8fe36e3b9)

**Comment by vikshaw-Nokia** [comment]
This was Fixed.
