### ISSUE TITLE
T2 Chassis - SNMP Queue counters value is not as expected after buffer queue deletion

### ISSUE THREAD

**Issue by sanjair-git** [sonic-net/sonic-buildimage#19542]
#### Description

As part of the test '_test_snmp_queue_counters_', it is expected that after enabling counters optimization by setting _create_only_config_db_buffers_ entry to '_true_' under DEVICE_METADATA, and when device config reload is done (_with modified config)_ after certain buffer queue deletion, the value of the SNMP queue counters should be as expected. (_lesser than the counter value before deletion_).

But actually, the SNMP queue counters are same as before deletion and config reload.

#### Steps to reproduce the issue:
1. Run 'test_snmp_queue_counters.py' test on a T2 chassis. (_Use_ #(https://github.com/sonic-net/sonic-mgmt/pull/13637 _PR for multi-asic support for the test case_)

For manual test,

1. Add '_create_only_config_db_buffers_ ' field as true, under DEVICE_METADATA section of config_db.json of the dut.
2. Save the file and load the new config.
3. Collect the snmp stats by running '_docker exec snmp snmpwalk -v2c -c public <dut_ip> 1.3.6.1.4.1.9.9.580.1.5.5.1.4.1_' 
4. Delete the buffer queue for port _Ethernet0|3-4_ for asic0 under config_db.json
5. Save the config and load the config again.
6. Collect the snmp stats by running '_docker exec snmp snmpwalk -v2c -c public <dut_ip> 1.3.6.1.4.1.9.9.580.1.5.5.1.4.1_' 

#### Describe the results you received:
```
>       pytest_assert((queue_counters_cnt_pre - queue_counters_cnt_post)
                      in [unicast_expected_diff, multicast_expected_diff],
                      "Queue counters actual count {} differs from expected values {}, {}".
                      format(queue_counters_cnt_post, (queue_counters_cnt_pre - unicast_expected_diff),
                             (queue_counters_cnt_pre - multicast_expected_diff)))
E       Failed: Queue counters actual count 64 differs from expected values 56, 48

Ethernet0_queue_cntrs_oid = '1.3.6.1.4.1.9.9.580.1.5.5.1.4.1'
```
#### Describe the results you expected:

- The expected value after buffer queue deletion is either **48** or **56**, but the total snmp queue counters value is 64 irrespective of the buffer queue deletion and also config reload with modified config.

#### Output of `show version`:

```
SONiC Software Version: SONiC.HEAD.764760-nokia-master-ce6cd4227
SONiC OS Version: 12
Distribution: Debian 12.6
Kernel: 6.1.0-11-2-amd64
Build commit: ce6cd4227
Build date: Tue Jul  9 19:42:23 UTC 2024
Built by: gitlab-runner@sonic-build-server03

Platform: x86_64-nokia_ixr7250e_36x400g-r0
HwSKU: Nokia-IXR7250E-36x400G
ASIC: broadcom
ASIC Count: 2
Serial Number: EAG2-02-052
Model Number: N/A
Hardware Revision: 56
Uptime: 19:30:11 up  9:36,  2 users,  load average: 1.77, 1.79, 1.65
Date: Thu 11 Jul 2024 19:30:11

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vmittal-msft** [comment]
@SuvarnaMeenakshi Can you please help check this ?

**Comment by SuvarnaMeenakshi** [comment]
> @SuvarnaMeenakshi Can you please help check this ?

I have reviewed the PR and provided some comments.
It seems like the test is not saving the configuration change to per-asic namespace config file and that might be causing the config to go back to initial config upon reload.

**Comment by sanjair-git** [comment]
> > @SuvarnaMeenakshi Can you please help check this ?
> 
> I have reviewed the PR and provided some comments. It seems like the test is not saving the configuration change to per-asic namespace config file and that might be causing the config to go back to initial config upon reload.

Thanks for the PR review comments, and I have taken care of them. Please take a look.

And it has been understood that, for '_Broadcom DNX_' multi-asic voq chassis, the number of voq is fixed (static). The queues are created during switch create itself and it cannot be modified dynamically. That is the reason, we don't see any snmp counters value change. Test verification modified accordingly.

We can close this bug if it's okay.
