### ISSUE TITLE
/lib/systemd/systemd-networkd-wait-online command fails on host

### ISSUE THREAD

**Issue by mannytaheri** [sonic-net/sonic-buildimage#19620]
#### Description
/lib/systemd/systemd-networkd-wait-online fails with the message "Timeout occurred while waiting for network connectivity".

admin@ixre-egl-board3:~$  /lib/systemd/systemd-networkd-wait-online
Timeout occurred while waiting for network connectivity.

Restarted the service but it did not help:
 
admin@ixre-egl-board3:~$ sudo systemctl restart systemd-networkd-wait-online.service
Job for systemd-networkd-wait-online.service failed because the control process exited with error code.
See "systemctl status systemd-networkd-wait-online.service" and "journalctl -xeu systemd-networkd-wait-online.service" for details.
 
Checked the status.  Active is in failed state
 
admin@ixre-egl-board3:~$ sudo systemctl status systemd-networkd-wait-online.service
Ã systemd-networkd-wait-online.service - Wait for Network to be Configured
     Loaded: loaded (/lib/systemd/system/systemd-networkd-wait-online.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Tue 2024-07-16 21:53:06 UTC; 37s ago
       Docs: man:systemd-networkd-wait-online.service(8)
    Process: 2838062 ExecStart=/lib/systemd/systemd-networkd-wait-online (code=exited, status=1/FAILURE)
   Main PID: 2838062 (code=exited, status=1/FAILURE)
 
Jul 16 21:51:05 ixre-egl-board3 systemd[1]: Starting systemd-networkd-wait-online.service - Wait for Network to be Configured...
Jul 16 21:53:06 ixre-egl-board3 systemd-networkd-wait-online[2838062]: Timeout occurred while waiting for network connectivity.
Jul 16 21:53:06 ixre-egl-board3 systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
Jul 16 21:53:06 ixre-egl-board3 systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
Jul 16 21:53:06 ixre-egl-board3 systemd[1]: Failed to start systemd-networkd-wait-online.service - Wait for Network to be Configured

#### Steps to reproduce the issue:
1.  Execute  /lib/systemd/systemd-networkd-wait-online
2. Restart the service with command  "sudo systemctl restart systemd-networkd-wait-online.service"
3. Check the status with command "sudo systemctl status systemd-networkd-wait-online.service"  

#### Describe the results you received:
Received "Timeout occurred while waiting for network connectivity"

#### Output of `show version`:
```
admin@ixre-egl-board3:~$ show ver

SONiC Software Version: SONiC.HEAD.767184-202405-483b96735
SONiC OS Version: 12
Distribution: Debian 12.6
Kernel: 6.1.0-11-2-amd64
Build commit: 483b96735
Build date: Thu Jul 11 20:42:30 UTC 2024
Built by: gitlab-runner@sonic-build-server04

```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment]
@kperumalbfn f.y.i

**Comment by mlok-nokia** [comment]
> As per @dgsudharsan this PR should be fixing it : #19107. @mlok-nokia find that this issuse is not seen in lastest master. To check further

I just checked the latest image. The issue is still seen.

**Comment by dgsudharsan** [comment]
@mlok-nokia This PR is not yet merged. So you may have to check after this is merged

**Comment by arlakshm** [comment]
@mannytaheri, the PR https://github.com/sonic-net/sonic-buildimage/pull/19107 merged and cherry-picked to 202405. Can please retest on the latest image

**Comment by mannytaheri** [comment]
This issue has not been seen anymore.
