### ISSUE TITLE
[202405] Missing YANG model for new added attribute related to fabric link monitoring 

### ISSUE THREAD

**Issue by jfeng-arista** [sonic-net/sonic-buildimage#19660]
#### Description

Missing YANG model for new added attribute related to fabric link monitoring . we should add them . 

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by jfeng-arista** [comment]
@jfeng-arista will fix it . 

@arlakshm @vmittal-msft @kenneth-arista

**Comment by arlakshm** [comment]
PR merged in 202405. Closing this issue
