### ISSUE TITLE
Ethernet RIF counters being reported as ifInErrors in SNMP 

### ISSUE THREAD

**Issue by SuvarnaMeenakshi** [sonic-net/sonic-buildimage#19715]
#### Description

ifInErrors for Ethernet interfaces are expected to have L2 CRC errors. With a change that went into SNMP, the RIF counters are being aggregated into ifInErrors/ifOutErrors, this is misleading while monitoring the link for CRC errors.

This is becuase there was a change added in SONiC SNMP to support VLAN and RIF counters. 

As a part of this change, the ifInErrors(1.3.6.1.2.1.2.2.1.14) and ifOutErrors(1.3.6.1.2.1.2.2.1.20) OIDs will start seeing sum of L2 and L3 (RIF) counters for each interface. 

[Restored snmp vlan support per RFC1213 and added the missing support for RFC2863 by raphaelt-nvidia · Pull Request #218 · sonic-net/sonic-snmpagent (github.com)](https://github.com/sonic-net/sonic-snmpagent/pull/218) 

https://github.com/sonic-net/sonic-snmpagent/blame/a281f9ab771adaa438f01fd5394d7a73ed6bc1d6/src/sonic_ax_impl/mibs/ietf/rfc1213.py#L361

#### Steps to reproduce the issue:
Issue seen in 202205 image onwards.
Boot up image on platform with RIF counter support with Ethernet RIF interface.
From CLI below, can see that there are are no L2 errors on Ethernet112 but there are RIF errors:
```
show int counters
      IFACE    STATE    RX_OK     RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK     TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
-----------  -------  -------  ---------  ---------  --------  --------  --------  -------  ---------  ---------  --------  --------  --------
..
Ethernet112        U      839  34.17 B/s      0.00%         0         0         0      631  12.97 B/s      0.00%         0         0         0
..

show int counter rif
         IFACE    RX_OK     RX_BPS    RX_PPS    RX_ERR    TX_OK    TX_BPS    TX_PPS    TX_ERR
--------------  -------  ---------  --------  --------  -------  --------  --------  --------
   Ethernet112      658  12.11 B/s    0.13/s        16        0  0.00 B/s    0.00/s         0
PortChannel102      511   1.93 B/s    0.03/s        17        0  0.00 B/s    0.00/s         0
PortChannel103      514   2.35 B/s    0.03/s        17        0  0.00 B/s    0.00/s         0
PortChannel104      508   2.35 B/s    0.03/s        17        0  0.00 B/s    0.00/s         0
      Vlan1000      837   0.93 B/s    0.02/s       220        0  0.00 B/s    0.00/s         0

 docker exec -it snmp snmpwalk -v2c -c <comm> <IP> 1.3.6.1.2.1.2.2.1.14
iso.3.6.1.2.1.2.2.1.14.1 = Counter32: 0
..
iso.3.6.1.2.1.2.2.1.14.113 = Counter32: 16 --- Ethernet112
..
iso.3.6.1.2.1.2.2.1.14.1102 = Counter32: 17
iso.3.6.1.2.1.2.2.1.14.1103 = Counter32: 17
iso.3.6.1.2.1.2.2.1.14.1104 = Counter32: 17
iso.3.6.1.2.1.2.2.1.14.3000 = Counter32: 220
iso.3.6.1.2.1.2.2.1.14.10000 = Counter32: 0

      ```

#### Describe the results you expected:
RIF counters should not be part of ifInErrors/ifOutErrors in SNMP.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by bingwang-ms** [comment]
@volodymyrsamotiy As discussed in the meeting, please create an internal ticket and have it triaged.
