### ISSUE TITLE
Interfaces in portchannel show duplicate drops in case of congestion.

### ISSUE THREAD

**Issue by amitpawar12** [sonic-net/sonic-buildimage#19730]
#### Description
**Setup:**
Test is done with Broadcom DNX multi-ASIC Nokia chassis with different ingress and egress line card. Chassis is running 2205 image.

Setup has ingress port-channel with 2x400Gbps links and egress port-channel with 1x400Gbps link.
Ingress port-channel:
```
admin@ixre-egl-board73:~$ show interfaces portchannel 
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
  No.  Team Dev        Protocol     Ports
-----  --------------  -----------  -------------------------
  104  PortChannel104  LACP(A)(Up)  Ethernet8(S) Ethernet0(S)
```

Egress port-channel:
```
admin@ixre-egl-board74:~$ show interfaces portchannel 
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
  No.  Team Dev        Protocol     Ports
-----  --------------  -----------  ------------
  105  PortChannel105  LACP(A)(Up)  Ethernet0(S)
```

**Traffic:**
Traffic on each ingress interface consists of 12% of priority 0, 2, 3, 4 and 5 traffic (overall 60% traffic on each ingress link).

When 60% (240Gbps per ingress link) is sent to the box, overall traffic towards egress link( of 400Gbps) is around 480Gbps and hence over-subscribed.

**Issue:**
The DUT ingress port-channel starts dropping the lossy traffic and sends PFCs for priority 3 and 4 traffic. On calculations, we see that 'show interface counter' has ingress interfaces reporting identical amount of drop and cumulative **this drop is twice as drop actually expected**. Interfaces configured in port-channel mode show duplicate drops in case of congestion. 

#### Steps to reproduce the issue:
1. Configure MACSEC on ingress and egress ports.
2. Configure ingress port-channel with 2 interfaces
3. Configure egress port-channel with single interface.
4. Send traffic to over-subscribe the egress link.
5. To ensure lossy priority traffic is dropped, send all priorities are sent in equal ratio.
6. Monitor the ingress port-channel interface statistics.
7. Capture the actual loss reported on IXIA or traffic generator.

#### Describe the results you received:
1. Loss reported by IXIA is half as much as reported by 'show interface counters' on ingress interfaces.
2. Output as seen on the DUT:
```
admin@ixre-egl-board73:~$ date;show interface counter | grep -E "STATE|Ethernet0 |Ethernet8 "
Mon 29 Jul 2024 12:37:41 PM UTC
      IFACE    STATE          RX_OK     RX_BPS    RX_UTIL    RX_ERR       RX_DRP    RX_OVR    TX_OK     TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
  Ethernet0        U    902,359,061  91.19 B/s      0.00%         0  222,372,605         0      485  91.19 B/s      0.00%         0         0         0
  Ethernet8        U  1,096,168,558  91.83 B/s      0.00%         0  222,372,605         0      513  91.90 B/s      0.00%         0         0         0

```
3. Loss per ingress interface is shown as 222,372, 605 packets.
4. Checking the output of show queue counter on the egress DUT:
```
Ethernet0 Last cached time was 2024-07-29 12:24:59.548714
     Port    TxQ    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
---------  -----  --------------  ---------------  -----------  ------------
Ethernet0    UC0     364,549,684  368,924,280,208            0             0
Ethernet0    UC2     364,534,010  368,908,418,120            0             0
Ethernet0    UC3     341,269,431  345,364,664,172            0             0
Ethernet0    UC4     341,266,878  345,362,080,536            0             0
Ethernet0    UC5     364,534,021  368,908,429,252            0             0
Ethernet0    UC7             531           86,940            0             0

```
5. Packet statistics as seen on the IXIA:
![image](https://github.com/user-attachments/assets/29c75781-c079-49a5-a3d0-e301e4d1fe36)

6. Total lossy drop packets on IXIA = 74113756+74129430+74129419 = 222372605
7. However, show interface counter - output in step(2) shows each interface dropping that much amount of traffic.

#### Describe the results you expected:
1. The packet drops should be identical on both traffic generator and DUT.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by saksarav-nokia** [comment]
@judyjoseph , i can debug this further.

**Comment by judyjoseph** [comment]
@vmittal-msft to check on this, does the voq counters gets added in RX_DRP.

**Comment by saksarav-nokia** [comment]
The BCM SAI uses the CRPS counters for the IF_IN_DISCARDS stats using the keys as pp_port and core_id. If the ports are members of portchannel, then the pp_port is same for all port members of a given port channel as shown below and in this specific test, the interface Ethernet0 (eth1) and Ethernet8 (eth2) are in the same core 1. So SAI reads the same stats from crps database and passes to sonic counter_db for both ports (Ethernet0 and Ethernet8). This works as per BCM DNX design and can't be fixed.
========================================================================================
| Name          | PP   | PP  | Type       | Core | Ingress | Ingress | Egress | Egress |
|               | Port | DSP |            |      | Enable  | Force   | Enable | Force  |
========================================================================================
| cpu0          | 0    | 0   | CPU        | 0    | 1       | 1       | 1      | 1      |
| eth1          | 35   | 1   | NIF_ETH    | 1    | 1       | 1       | 1      | 1      |
| eth2          | 35   | 2   | NIF_ETH    | 1    | 1       | 1       | 1      | 1      |

**Comment by amitpawar12** [comment]
@vmittal-msft  - FYI

**Comment by abdosi** [comment]
Known design of BRCM SAI/SDK.
