### ISSUE TITLE
[BFD] [ACL] Unexpected BFD state change (up->down) after applying ACL

### ISSUE THREAD

**Issue by volodymyrsamotiy** [sonic-net/sonic-buildimage#19762]
#### Description

Applying ACL triggers state change for the existing BFD sessions.

If there is BFD session configured which is up and then user applies some ACL rule then BFD session is going down.
After some time BFD session will go back to up state.

Looks like this issue is happening due to the design of caclmgrd.
BFD feature is using control plane ACLs in order to route BFD packets.
And in caclmgrd it is mentioned that it will take Control Plane ACTION for any ACL Table Event: [caclmgrd#L1087](https://github.com/sonic-net/sonic-host-services/blob/ca6b3cdb9a56604765ada4ac67234c117f0fb5ad/scripts/caclmgrd#L1087
).

So each time we add some ACL it causes caclmgrd to reconfigure all control plane ACLs.
Which means that control plane ACLs are first removed and then added again.
So there is some period of time when BFD control plane ACL was removed but not added yet.
As a result  BFD session goes down.

#### Steps to reproduce the issue:
1. Connect 2 SONiC switches via 1 physical link (DUT 1 <-> DUT 2)
2. Configure IP connection (1.1.1.1/30 <-> 1.1.1.2/30)
3. Configure 2 loopback interfaces on both sides
4. Configure static route on both devices to reach each other loopbacks
5. On both switches configure 2 BFD sessions
6. Verify that all BFD sessions are up
7. Config ACL on DUT 2 switch to block all ingress traffic except one subnet on which 2nd BFD session is cofigured
8. Verify that 1st BFD session is "down" on DUT 2 and "init" DUT 1, which is expected according to applied ACL
9. Observe that 2nd BFD session changed state to "down" and then back to "up" which is not expected according to applied ACL

Topology and BFD configuration (steps 1-6):
```
+--------------------------+                       +--------------------------+
| DUT 1                    |                       | DUT 2                    |
|                          |                       |                          | 
|                          |                       |                          | 
|      [Ethernet0|1.1.1.1/30]---------------------[Ethernet0||1.1.1.2/30]     |
|                          |                       |                          |
|                          |          BFD          |                          |
|   [Loopback0|10.10.0.1/32]- - - - - - - - - - - -[Loopback0|20.20.0.1/32]   |
|   [Loopback1|10.10.1.1/32]- - - - - - - - - - - -[Loopback1|20.20.1.1/32]   |
|                          |                       |                          |
|                          |                       |                          |
| Route:                   |                       | Route:                   |
| 20.20.0.0/16 via 1.1.1.2 |                       | 10.10.0.0/16 via 1.1.1.1 |
|                          |                       |                          |
+--------------------------+                       +--------------------------+
```

ACL Rule that is applied (step 7):
```
{
    "ACL_RULE": {
        "DATAACL|ALLOW_RULE": {
            "DST_IP": "20.20.1.0/24",
            "ETHER_TYPE": "2048",
            "PACKET_ACTION": "FORWARD",
            "PRIORITY": "999"
        },
        "DATAACL|DEFAULT_RULE": {
            "ETHER_TYPE": "2048",
            "PACKET_ACTION": "DROP",
            "PRIORITY": "1"
        }
    }
}
```

#### Describe the results you received:

Applying ACL triggers state change for the existing BFD sessions.

If there is BFD session configured which is up and then user applies some ACL rule then BFD session is going down.
After some time BFD session will go back to up state.

#### Describe the results you expected:

Applying ACL should not trigger any state change for the existing BFD sessions.
BFD sessions of the subnet that is not affected by ACL should not change state and should stay in Up state after applying ACL.

#### Output of `show version`:
All versions (caclmgrd didn't change implementation recently)

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zjswhhh** [comment]
This scenario should be discussed between @dgsudharsan and @prsunny. Can any update to control plane ACLs effect BFD?

**Comment by bingwang-ms** [comment]
@ZhaohuiS FYI.
