### ISSUE TITLE
[Micas]platform M2-W6510 standardization by using native Linux kernel drivers

### ISSUE THREAD

**Issue by philo-micas** [sonic-net/sonic-buildimage#19901]
#19599 This PR has not been reviewed for over 6 weeks, please help to push it forward,
#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by gechiang** [comment]
prs reviewer assigned already. closing this...
