### ISSUE TITLE
test_events.py is flaky in PR test

### ISSUE THREAD

**Issue by xwjiang-ms** [sonic-net/sonic-buildimage#19943]
#### Steps to reproduce the issue:
1. Run `test_events.py` in PR test
2.
3.

#### Describe the results you received:
There is a chance test would fail for `AssertionError: No output from PTF docker, thread timed out after 30 seconds`
or `Failed: events_monit_test has not published`

#### Describe the results you expected:
No error or failure

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zbud-msft** [comment]
Fixed with
