### ISSUE TITLE
Add rack test failed for PortChannel missing after patch

### ISSUE THREAD

**Issue by xwjiang-ms** [sonic-net/sonic-buildimage#19942]
#### Steps to reproduce the issue:
1. Run test_add_rack.py test in KVM platform
2.
3.

#### Describe the results you received:
Example: The PortChannel1011 is missing after patch.
ROUTE_TABLE:20c0:aad0::/64 {'ifname': 'PortChannel102,PortChannel105,PortChannel108,PortChannel1014,PortChannel1017,PortChannel1020,PortChannel1023', 'nexthop': 'fc00::2,fc00::a,fc00::12,fc00::22,fc00::2a,fc00::32,fc00::3a', 'protocol': 'bgp'} != {'ifname': 'PortChannel102,PortChannel105,PortChannel108,PortChannel1011,PortChannel1014,PortChannel1017,PortChannel1020,PortChannel1023', 'nexthop': 'fc00::2,fc00::a,fc00::12,fc00::1a,fc00::22,fc00::2a,fc00::32,fc00::3a', 'protocol': 'bgp'}

#### Describe the results you expected:
No error reported

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by wen587** [comment]
TestPlanId	TestbedName	ModulePath	OSVersion	TestCase	Result	Summary	UploadTime
66c3807af93ad6e0b1725012	vms-kvm-t1-lag	configlet.test_add_rack	SONiC.master.622951-fdc6fb608	test_add_rack	xfail_success		2024-08-19T18:52:57.816Z
66c3127ef93ad6e0b1724fc0	vms-kvm-t1-lag	configlet.test_add_rack	SONiC.master.622258-7e063f791	test_add_rack	xfail_success		2024-08-19T11:02:43.915Z
