### ISSUE TITLE
[202405][BRCM]  SAI RPC server failed to disable credit watchdog

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#19972]
#### Description

After https://github.com/sonic-net/sonic-mgmt/pull/13041 was merged in 202405, sonic-mgmt test started to disable/enable credit watchdog by using SAI RPC call.  However, the corresponding SAI RPC server PR https://github.com/opencomputeproject/SAI/pull/2010 is still missing in 202405.   202405 SAI submodule needs to be updated to pick up this PR.

#### Steps to reproduce the issue:
1. Run `qos/test_qos_sai.py` on BRCM modular box with 202405 image.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ysmanman** [comment]
Add @kenneth-arista @arlakshm @vmittal-msft for viz.

**Comment by abdosi** [comment]
@saksarav-nokia : Will look into this.

**Comment by arlakshm** [comment]
Sai is updated.
