### ISSUE TITLE
[Broadcom][DNX]  SAI does not support SAI_PORT_STAT_IN_DROPPED_PKTS

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#19998]
#### Description

We encountered the issue in recent 202405 testing on DNX.  Created the issue to track the following impact/following-up:

- Looked at SONiC source code and portsorch does poll this counters from SAI.  According to BRCM, this counter was not supported in old SAI 7.x neither.  Given there was no related issue/bug uncovered in 202205 testing, it's not clear if SONiC require to support this counter on DNX. 

- The handling of this unsupported counter was changed in new SAI, e.g. 11.x. This change unfortunately breaks the SAI thrift APIs, like `sai_thrift_read_port_counters`. For example, the SAI thrift API  does not return the correct PFC counter.  This breaks  sonic-mgmt qos tests.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ysmanman** [comment]
Add @arlakshm @vmittal-msft @kenneth-arista for viz.

**Comment by ysmanman** [comment]
FYI, CSP CS00012365714 was created for this issue and BRCM confirmed SAI_PORT_STAT_IN_DROPPED_PKTS is not supported by SAI.

**Comment by rlhui** [comment]
adding @tjchadaga as well.

**Comment by rlhui** [comment]
Fix in test.
