### ISSUE TITLE
Leverage ssg platform services.conf support for startup_tsa_tsb service

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#20049]
#### Description

Startup_tsa_tsb service is only used in x86_64-nokia_ixr7250e_36x400g-r0 platform (https://github.com/sonic-net/sonic-buildimage/pull/18496). However, it starts in other platforms as well.

For services like this, a recent enhancement to systemd-sonic-generator is added here https://github.com/sonic-net/sonic-buildimage/pull/18730 which enables platforms to enables custom services during runtime. 

IMO startup_tsa_tsb can leverage this infrastructure. 

#### Why

This service which starts very early during init is using valuable CPU share and combined with other daemons like banner-config, hostname-config etc is causing a 1-2 delay in the start of swss.service in devices with weaker CPU'

```
root@sn2700:/home/admin# systemctl status startup_tsa_tsb
● startup_tsa_tsb.service - STARTUP TSA-TSB SERVICE
     Loaded: loaded (/lib/systemd/system/startup_tsa_tsb.service; enabled-runtime; preset: enabled)
     Active: active (exited) since Wed 2024-08-28 05:09:14 UTC; 35min ago
   Main PID: 2338 (code=exited, status=0/SUCCESS)

Aug 28 05:09:14 sn2700 systemd[1]: Started startup_tsa_tsb.service - STARTUP TSA-TSB SERVICE.
Aug 28 05:09:15 sn2700 startup_tsa_tsb[2338]: /usr/share/sonic/device/x86_64-mlnx_msn2700-r0/startup-tsa-tsb.conf does not exist, exiting the service
```

**Comment by saksarav-nokia** [comment]
Nokia will fix it.

**Comment by saksarav-nokia** [comment]
> @saksarav-nokia any update? thanks.

@rlhui , I have already raised https://github.com/sonic-net/sonic-buildimage/pull/20315 for this. Please approve and merge it
