### ISSUE TITLE
[master][202405] Warning "Failed to get image 'docker-sonic-telemetry' is logged to the syslog every minute although it is not supported

### ISSUE THREAD

**Issue by mlok-nokia** [sonic-net/sonic-buildimage#20056]
#### Description
When upgrade platform from 202205 image to master [or 202405], the following Warning is logged to the syslog every minute. Since telemetry has been converted to "gnmi".  The db_migrate should migrate this feature by removing this feature from the feature table to avoid this message is logged to the syslog every minute.
```
2024 Aug 28 15:35:12.219750 Linecard WARNING Chassis: Failed to get image 'docker-sonic-telemetry'. Error: '404 Client Error for http+docker://localhost/v1.43/images/docker-sonic-telemetry/json: Not Found ("No such image: docker-sonic-telemetry:latest")'
"
```
.

#### Steps to reproduce the issue:
1. Upgrade the existing chassis which is running 202205 image to the latest master or 202405 image
2. Check the syslog, the following line is shown in every minute
```
2024 Aug 28 15:35:12.219750 Linecard WARNING Chassis: Failed to get image 'docker-sonic-telemetry'. Error: '404 Client Error for http+docker://localhost/v1.43/images/docker-sonic-telemetry/json: Not Found ("No such image: docker-sonic-telemetry:latest")'
"
```
4.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by zhangyanzhao** [comment]
db-migrator should have better handling (remove) the unused legacy component to avoid such log info. @mlok-nokia will take a look.

**Comment by zhangyanzhao** [comment]
@qiluo-msft  will review the change later.
