### ISSUE TITLE
[FDB]SONiC sairedis FDB callback handling is not efficient to handle bulk notifications

### ISSUE THREAD

**Issue by dgsudharsan** [sonic-net/sonic-buildimage#20212]
#### Description

SONiC FDB callback handling is not efficient to handle bulk notifications. In case of a bulk aging events, it does lot of processing and then updating redis which can consume lot of cycles holding the underlying SAI library from handling any other events or notifications.

https://github.com/sonic-net/sonic-sairedis/blob/dbcba69b04e774a442cccda642d9bddbe82b9ee9/syncd/NotificationProcessor.cpp#L306

Doing some benchmarking I found that for 10K Aging through 300 notifications, the call back spends nearly 1.5 seconds during which we face some timeouts in our SAI library due to SAI being unavailable to handle these events.

```
2024 Sep  4 20:48:35.503119 r-tigon-20 ERR syncd#SDK: [SAI_OBJECT.ERR] ./src/mlnx_sai_object.c[860]- mlnx_wait_for_bulk_read_event: Failed to wait for an event: Connection timed out, status: -1.
2024 Sep  4 20:48:35.503119 r-tigon-20 ERR syncd#SDK: [SAI_PORT.ERR] ./src/mlnx_sai_port.c[14502]- mlnx_sai_bulk_port_stats_get: Failed to prepare bulk counter for shared buffer stats.
```

Ideally the callback handler in SONiC should get notification from SAI, enqueue them and return immediately and process the notification in a different context.

#### Steps to reproduce the issue:
1. Learn 10K MACs in such a way that aging of them happens at same time
2.  Wait for aging. Observe errors in SAI.
3.

#### Describe the results you received:

Timeout events happen in SAI since the callback handler is held up.

#### Describe the results you expected:

No timeout events

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by dgsudharsan** [comment]
@kcudnik FYI. Can we improve the handling of callback handlers in Sairedis so that it doesn't overwhelm underlying SAI library?

**Comment by zhangyanzhao** [comment]
Feature improvement suggestion.

**Comment by zhangyanzhao** [comment]
SAI Redis bug, move to that repo. @dgsudharsan

**Comment by zhangyanzhao** [comment]
BRCM will help to take a look firstly.

**Comment by anilkpan** [comment]
@dgsudharsan, from SAI context, it calls NotificationQueue::enqueue to enqueue the FDB events and then returns. NotificationProcessor::process_on_fdb_event is called by a different thread. It should not block SAI processing.

**Comment by dgsudharsan** [comment]
@anilkpan Thanks for the clarification. Indeed I see that's the behavior. I am closing this ticket
