### ISSUE TITLE
ERR eventd#eventd: :- deserialize: deserialize Failed: input stream error

### ISSUE THREAD

**Issue by saksarav-nokia** [sonic-net/sonic-buildimage#20246]
#### Description
The following errors are seen during sonic-mgmt PC and VOQ suites in 202405.  We have not seen this before.

  ERR eventd#eventd: :- deserialize: deserialize Failed: input stream errorstr[0:64]:(#001) data type: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&
 ERR eventd#eventd: :- deserialize: deserialize Failed: input stream errorstr[0:64]:(#001) data type: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&
             

#### Steps to reproduce the issue:
1. Run full sonic-mgmt oc tests
2.
3.

#### Describe the results you received:
The eventd errors are logged in syslog file

#### Describe the results you expected:
No errors

#### Output of `show version`:
202405
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by arista-hpandya** [comment]
Arista also noticed this error. We saw this when we were running the `test_reboot_supervisor` in `test_voq_disrupts.py`. This narrows it down to a reboot issue. Will update if we get more details on this.

**Comment by arista-hpandya** [comment]
The case 4 described in PR #20024 aligns with the error we are seeing. I assume that the follow up PR mentioned in the description would be addressing this error @zbud-msft ?

**Comment by zbud-msft** [comment]
PR already exists: https://github.com/sonic-net/sonic-swss-common/pull/906

**Comment by arista-hpandya** [comment]
Thank you for the update @zbud-msft . Can you please link the PR with this issue.

**Comment by saksarav-nokia** [comment]
Closed it since it is fixed
