### ISSUE TITLE
DASH smartswitch DPU orchagent zmq listens to wrong midplane IP

### ISSUE THREAD

**Issue by mukeshmv** [sonic-net/sonic-buildimage#20295]
#### Description

On the DASH Smartswitch, the orchagent is started on DPU with -q option to enable zmq listen. With midplane IP support it is set to listen to a specific IP rather than wildcard. But the DPU midplane IP is obtained by DHCP and changes after init. Hence the zmq channel configurations are not received by DPU orchagent.

#### Steps to reproduce the issue:
1. Boot the switch and DPU with midplane IP support
2. Push configurations
3. Configurations do not show up in DPU swss.rec

#### Workaround
Edit `/usr/bin/orchagent.sh` in the `swss` container to start listen on wildcard and restart DPU
        ORCHAGENT_ARGS+=" -q tcp://0.0.0.0:8100"

**Comment by prsunny** [comment]
@prabhataravind , @qiluo-msft , @theasianpianist , @Pterosaur for viz

**Comment by liuh-80** [comment]
According to design doc, the midplane IP is pre-configured in config_db:

'''
The DHCP_SERVER_IPV4_PORT table includes the following:

For each DPU available in the system the IP address that should be assigned to the DPU.
'''

So, after push the config, the swss container should restart after reload config. and should load correct midplane IP during reboot.

**Comment by liuh-80** [comment]
Close because fix PR merged: https://github.com/sonic-net/sonic-buildimage/pull/20352
