### ISSUE TITLE
[202405][Broadcom-DNX]  ebgp session kepts flapping when macsec is enabled

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-buildimage#20342]
#### Description

In our testbed,  we config ebgp with the peer connecting to macsec enabled 400G port. We observed the bgp session kept flapping. After investigation, we found SONiC was not able to tx large size bgp packet to peer because of the following tx error:

`TX FIFO Underrun frame` 
`TX Error frame`

The issue was not seen after we configured very small MTU like 256.

#### Steps to reproduce the issue:
1.
2.
3.

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by ysmanman** [comment]
Add @kenneth-arista @arlakshm @judyjoseph for viz.

**Comment by ysmanman** [comment]
CSP CS00012369949 was created to track the issue.

**Comment by arlakshm** [comment]
Fix is available. Closing this issue
