### ISSUE TITLE
[Mellanox] syncd container has Python development packages installed

### ISSUE THREAD

**Issue by saiarcot895** [sonic-net/sonic-buildimage#20419]
#### Steps to reproduce the issue:

In the syncd container for Mellanox images, on master and 202405 branches, there are Python development packages and setuptools installed. These should be removed.

#### Describe the results you received:

```
root@str-msn2700-01:/# dpkg -l | grep python | grep dev
ii  libpython3-dev:amd64               3.11.2-1+b1                    amd64        header files and a static library for Python (default)
ii  libpython3.11-dev:amd64            3.11.2-6+deb12u2               amd64        Header files and a static library for Python (v3.11)
ii  python-sdk-api                     1.mlnx.4.6.4072                amd64        SX SDK API python wrapper module for SX devices.
ii  python3-dev                        3.11.2-1+b1                    amd64        header files and a static library for Python (default)
ii  python3.11-dev                     3.11.2-6+deb12u2               amd64        Header files and a static library for Python (v3.11)
root@str-msn2700-01:/# dpkg -l | grep python | grep setuptools
ii  python3-setuptools                 66.1.1-1                       all          Python3 Distutils Enhancements
```

#### Describe the results you expected:

Development packages shouldn't be installed at runtime.

**Comment by bingwang-ms** [comment]
@volodymyrsamotiy , @dgsudharsan Can you please help assign the issue?

**Comment by bingwang-ms** [comment]
The file is https://github.com/sonic-net/sonic-buildimage/blob/master/platform/mellanox/docker-syncd-mlnx/Dockerfile.j2

**Comment by nazariig** [comment]
@saiarcot895 from the code i can see that `python3-setuptools` is not a part of Mellanox specific `syncd` docker

**Sample:**
https://github.com/sonic-net/sonic-buildimage/blob/master/dockers/docker-base-bookworm/Dockerfile.j2#L36
```docker
# Update apt cache and
# pre-install fundamental packages
RUN apt update &&            \
    apt -y install           \
        curl                 \
        less                 \
        perl                 \
        procps               \
        python3              \
        python3-distutils    \
        python3-pip          \
        python3-setuptools   \
        python3-wheel        \
        python-is-python3    \
        vim-tiny             \
        rsyslog              \
```

Are you still considering it as the item which we need to do a clean up?
If yes, than i would suggest MSFT to take care of it, as this is a common piece of code

**Comment by bingwang-ms** [comment]
Discussed in issue triage meeting, having Python3 is fine, but Python3-dev needs to be removed.
MSFT will remove python3-setuptools and python3-pip from docker base image, and Nvidia will remove it from mlnx syncd image.
