### ISSUE TITLE
Remove runtime config update for FEATURE table 

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#20462]
#### Description

Issue related to https://github.com/sonic-net/sonic-buildimage/issues/20302

FEATURE config will be updated some time later after load_minigraph. This will result in the FEATURE is inconsistent between the desired config and running config.
The ask it to make it consistent and not more run time update. The fix should also consider the backward compatibility.

#### Steps to reproduce the issue:
1.Run config load_minigraph -y
2. Record the config right after the command finish.
The FEATURE  are the same as the [init_cfg.json](https://github.com/sonic-net/sonic-buildimage/blob/master/files/build_templates/init_cfg.json.j2#L24-L30)
```
admin@sonic:~$ redis-cli -n 4 hgetall "FEATURE|bgp"
 1) "auto_restart"
 2) "enabled"
 3) "check_up_status"
 4) "false"
 5) "support_syslog_rate_limit"
 6) "true"
 7) "delayed"
 8) "False"
 9) "has_per_asic_scope"
10) "True"
11) "high_mem_alert"
12) "disabled"
13) "state"
14) "{% if not DEVICE_RUNTIME_METADATA['ETHERNET_PORTS_PRESENT'] or ('CHASSIS_METADATA' in DEVICE_RUNTIME_METADATA and DEVICE_RUNTIME_METADATA['CHASSIS_METADATA']['module_type'] in ['supervisor']) %}disabled{% else %}enabled{% endif %}"
15) "has_global_scope"
16) "False"
```

3. Run command again:

```
admin@sonic:~$ redis-cli -n 4 hgetall "FEATURE|bgp"
 1) "auto_restart"
 2) "enabled"
 3) "check_up_status"
 4) "false"
 5) "support_syslog_rate_limit"
 6) "true"
 7) "delayed"
 8) "False"
 9) "has_per_asic_scope"
10) "True"
11) "high_mem_alert"
12) "disabled"
13) "state"
14) "enabled"
15) "has_global_scope"
16) "False"
```

#### Describe the results you received:

FEATURE field was updated.

#### Describe the results you expected:

We expect the FEATURE to be consitent and no longer have run time update. This will help us manage the running config of the device.
Currently if we refer the init_cfg.json as the source of truth, it will be wrong.

#### Output of `show version`:

```
SONiC Software Version: SONiC.20231110.21
SONiC OS Version: 11
Distribution: Debian 11.10
Kernel: 5.10.0-23-2-amd64
Build commit: e868b9ca70
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by stepanblyschak** [comment]
These issues are related to CONFIG_DB writeback:
  - https://github.com/sonic-net/sonic-buildimage/issues/15102
  - https://github.com/sonic-net/sonic-buildimage/issues/19878

**Comment by stepanblyschak** [comment]
@qiluo-msft mentioned a potential solution for this issue offline, @qiluo-msft could you please share it here?

**Comment by stepanblyschak** [comment]
@qiluo-msft PR that introduced config db write back for FEATURE table - https://github.com/sonic-net/sonic-buildimage/pull/6700

**Comment by wen587** [comment]
Hi @stepanblyschak , this one is different.
If we have static value in config_db, it will not update. For example, we have put a static value in FEATURE state with either `enable` or `disable` in  golden config during override, it will not change with static value after service start.
FLEX_COUNTER_TABLE is different, if we put below static config like below, it will still be upadted after service start. such as `PORT`, `PFC_WD`
```
 "FLEX_COUNTER_TABLE": {
        "ACL": {
            "FLEX_COUNTER_STATUS": "enable",
            "FLEX_COUNTER_DELAY_STATUS": "true",
            "POLL_INTERVAL": "10000"
        },
```
