### ISSUE TITLE
Dell S5248F-ON port definitions wrong?

### ISSUE THREAD

**Issue by bradh352** [sonic-net/sonic-buildimage#20480]
#### Description

Dell S5248F-ON port definitions appear to not match the hardware.  

In particular, there are 2x 200G QSFP28-DD ports on the switch.  They can be used as a 200G ports, or can be broken out in various ways like 2x100G, or 8x25G.

Front panel numbering on these ports is a little strange, as each port gets 2 numbers, 49&50 is the first, 51&52 is the second.

https://github.com/sonic-net/sonic-buildimage/blob/64cd07c1ffcc5fa00d615be4c63ff3b8f2cf7487/device/dell/x86_64-dellemc_s5248f_c3538-r0/platform.json#L822C1-L865C11

So I think that section of the configuration should be more like:
```
        "Ethernet48": {
            "index":"49,49,49,49,50,50,50,50",
            "lanes":"121,122,123,124,125,126,127,128",
            "breakout_modes": {
                "1x200G": ["Eth49"],
                "2x100G[40G]": ["Eth49", "Eth50"],
                "4x50G": ["Eth49/1", "Eth49/2", "Eth50/1", "Eth50/2"],
                "8x25G[10G]": ["Eth49/1", "Eth49/2", "Eth49/3", "Eth49/4", "Eth50/1", "Eth50/2", "Eth50/3", "Eth50/4"],
            }
        },
        "Ethernet56": {
            "index":"51,51,51,51,52,52,52,52",
            "lanes":"65,66,67,68,69,70,71,72",
            "breakout_modes": {
                "1x200G": ["Eth51"],
                "2x100G[40G]": ["Eth51", "Eth52"],
                "4x50G": ["Eth51/1", "Eth51/2", "Eth52/1", "Eth52/2"],
                "8x25G[10G]": ["Eth51/1", "Eth51/2", "Eth51/3", "Eth51/4", "Eth52/1", "Eth52/2", "Eth52/3", "Eth52/4"],
            }
        },
```
Granted, I've not played with it so i could be wrong.

Also, I'd think this would need to change too:
https://github.com/sonic-net/sonic-buildimage/blob/64cd07c1ffcc5fa00d615be4c63ff3b8f2cf7487/device/dell/x86_64-dellemc_s5248f_c3538-r0/platform.json#L459C1-L470C15

Obviously the port type is really QSFP28-DD, but I'm not entirely sure how that listing gets modified.

**Comment by bradh352** [comment]
@arunlk-dell looks like you were the last to commit a change for this switch model, mind looking at this?

**Comment by arunlk-dell** [comment]
The switch S5248F-ON is built on Broadcom TD3 which only supports upto 100G.
With QSFP-DD port, only achieved mode is 2x100G (with the limitation of TD3) and hardware wise DD ports is numbered as two (100G) ports.
In the similar sense 1x200G is not supported on this switch. Hope this clears your query.

**Comment by bradh352** [comment]
thanks for the info.
