### ISSUE TITLE
Route can not be set to APPDB when zebra switch to dplane_fpm_nl in SONIC-202311

### ISSUE THREAD

**Issue by AlanYoush** [sonic-net/sonic-buildimage#20529]
#### Description
When I change zebra to dplane_fpm_nl from fpm, and I find route cannot be set into ASIC and no route in APPDB. Whether dplane_fpm_nl is not supported for 202311 ? Or need I merge some patches for dplane_fpm_nl.

#### Steps to reproduce the issue:
1.  Just configure dockers/docker-fpm-frr/frr/supervisord/supervisord.conf.j2 like this " command=/usr/lib/frr/zebra -A 127.0.0.1 -s 90000000 -M dplane_fpm_sonic -M snmp"
2.
3.

#### Describe the results you received:
N/A

#### Describe the results you expected:
N/A

#### Output of `show version`:
SONiC-202311
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vdahiya12** [comment]
@AlanYoush we are supporting this in 202411, not in this version
