### ISSUE TITLE
https://packages.trafficmanager.net/snapshot/debian/latest/timestamp not accessible

### ISSUE THREAD

**Issue by koutlaws** [sonic-net/sonic-buildimage#20547]
UPDATE 12/9/2024:
The issue has expanded, previously accessible urls are broken as well, e.g.
https://packages.trafficmanager.net/public/packages/socat_1.7.4.1.orig.tar.gz-780d14908dc1a6aa2790de376ab56b7a

Error Msg:
<img width="574" alt="Screenshot 2024-12-09 at 2 53 55 PM" src="https://github.com/user-attachments/assets/df87d6b1-b3be-4206-81b2-a9d565b1a68a">

This is breaking all builds on our CICD, please help take a look.

----------------

#### Description

During SONiC Build, if MIRROR_SNAPSHOT is enabled, it will try to access https://packages.trafficmanager.net/snapshot/debian/latest/timestamp to get the latest timestamp for debian mirrors. This url is returning 404, causing the url generated to download to be broken, e.g.

```
#12 0.332 Ign:1 http://packages.trafficmanager.net/snapshot/debian/<!DOCTYPE html><html><head><title>WebContentNotFound</title></head><body><h1>The InRelease
#12 0.362 Ign:2 http://packages.trafficmanager.net/snapshot/debian-security/<!DOCTYPE html><html><head><title>WebContentNotFound</title></head><body><h1>The InRelease   
```

#### Steps to reproduce the issue:
1. Access https://packages.trafficmanager.net/snapshot/debian/latest/timestamp

#### Describe the results you received:
404 HTTP Error

#### Describe the results you expected:
A file containing the latest timestamp

#### Output of `show version`:
n/a

```
(paste your output here)
```
#### Output of `show techsupport`:
n/a

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

https://packages.trafficmanager.net/snapshot/debian/latest/ is accessible, it is only the timestamp file causing issues
Also, acessing https://packages.trafficmanager.net/snapshot/debian/latest will redirect you to http://sonic-build.westus2.cloudapp.azure.com/snapshot/debian/latest/
From this url, timestamp file is accessible. Not sure why it does not work when directly accessing https://packages.trafficmanager.net/snapshot/debian/latest/timestamp

Reference PR https://github.com/sonic-net/sonic-buildimage/pull/13097
Was hoping if I can get some more info on this from @xumia or @qiluo-msft

**Comment by jusherma** [comment]
@xumia @qiluo-msft looks like the packages.trafficmanager.net site is still down. The main directory listing works, but trying to reach `timestamp` or `dist` fails with 404. Any update on when this will be resolved?

**Comment by jusherma** [comment]
@xumia @qiluo-msft any update on this?

**Comment by koutlaws** [comment]
Looks like the issue has expanded, we cannot access other locations in trafficmanager now.

```
--2024-12-09 20:26:28--  https://packages.trafficmanager.net/public/packages/socat_1.7.4.1.orig.tar.gz-780d14908dc1a6aa2790de376ab56b7a
...
Proxy request sent, awaiting response... 404 The requested website is not configured.
2024-12-09 20:26:28 ERROR 404: The requested website is not configured..
```

**Comment by koutlaws** [comment]
@xumia @qiluo-msft, could you help take a look?

**Comment by nmoray** [comment]
@koutlaws Try downloading the package from "https://sonicstorage.blob.core.windows.net/public/debian" URL.

Ref: https://github.com/sonic-net/sonic-buildimage/blob/master/src/socat/Makefile

**Comment by liushilongbuaa** [comment]
https://packages.trafficmanager.net/snapshot/debian/latest/timestamp
https://packages.trafficmanager.net/public/packages/socat_1.7.4.1.orig.tar.gz-780d14908dc1a6aa2790de376ab56b7a
These kinds of url are fixed.

**Comment by koutlaws** [comment]
> @koutlaws Try downloading the package from "https://sonicstorage.blob.core.windows.net/public/debian" URL.
> 
> Ref: https://github.com/sonic-net/sonic-buildimage/blob/master/src/socat/Makefile

Thank you @nmoray for the suggestion. Will keep this in mind if the packages.trafficmanager.net experiences failure in the future

**Comment by koutlaws** [comment]
> https://packages.trafficmanager.net/snapshot/debian/latest/timestamp https://packages.trafficmanager.net/public/packages/socat_1.7.4.1.orig.tar.gz-780d14908dc1a6aa2790de376ab56b7a These kinds of url are fixed.

Thank you @liushilongbuaa for the quick fix. The builds are working now, appreciate the help!
