### ISSUE TITLE
[macsec] clear counters clears XPN

### ISSUE THREAD

**Issue by liamkearney-msft** [sonic-net/sonic-buildimage#20653]
#### Description
Clearing macsec counters also clears the XPN counter

#### Steps to reproduce the issue:
1. Run some macsec traffic
2. run sonic-clear macsec
3. run show macsec

#### Describe the results you received:
Stats cleared, but also XPN counter cleared

#### Describe the results you expected:
Stats cleared, but XPN counter not cleared

#### Output of `show version`:
202205

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by rlhui** [comment]
PR for this is merged, closing
