### ISSUE TITLE
vstest is failing in sonic-swss repo in recent runs due to "generate coverage" step failing

### ISSUE THREAD

**Issue by anilkpan** [sonic-net/sonic-buildimage#20787]
#### Description

vstest is failing in sonic-swss repo in recent runs for several PRs due to "Generate coverage" step failing. Here is the error log:

##[debug] /agent/_work/_temp/b5d76725-58f5-4bb8-838f-a57eb555625e.sh
/usr/bin/bash --noprofile --norc /agent/_work/_temp/b5d76725-58f5-4bb8-838f-a57eb555625e.sh

reportgenerator -reporttypes:Cobertura '-reports:tests/*coverage.xml' -targetdir:.
/agent/_work/_temp/b5d76725-58f5-4bb8-838f-a57eb555625e.sh: line 2: reportgenerator: command not found
##[debug]Exit code 127 received from tool '/usr/bin/bash'
##[debug]STDIO streams have closed for tool '/usr/bin/bash'
##[error]Bash exited with code '127'.
##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]Bash exited with code '127'.
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]
Finishing: Generate coverage.xml

For example, the following PRs have this failure:
https://github.com/sonic-net/sonic-swss/pull/3313
https://github.com/sonic-net/sonic-swss/pull/3143
https://github.com/sonic-net/sonic-swss/pull/3329

#### Steps to reproduce the issue:
1.
2.
3.

#### Describe the results you received:

vstest failed

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by adyeung** [comment]
@yxieca @qiluo-msft any idea how to fix this?

**Comment by liushilongbuaa** [comment]
Fix PR:  https://github.com/sonic-net/sonic-swss/pull/3369

**Comment by adyeung** [comment]
Problem not fixed, same reportgenerator not found error seen in another code PR on Nov19

https://github.com/sonic-net/sonic-swss/pull/3313

https://dev.azure.com/mssonic/build/_build/results?buildId=699831&view=logs&j=3f6395b2-1619-5ebe-f305-2aedcf353cb5&t=459b0051-ec95-53f6-5459-a8151fc73505&l=64
