### ISSUE TITLE
[sonic-cfggen] sonic-cfggen should consider DPU ports when generating L2 mode configuration

### ISSUE THREAD

**Issue by echuawu** [sonic-net/sonic-buildimage#20937]
#### Description
When running L2 mode test on bobcat switch, the sonic-cfggen should consider the DPU ports.
Currently, when using command "sonic-cfggen -H -k Mellanox-SN4280-O28 -p --preset l2 > /tmp/init_l2_config.json", it would generate DPU ports with admin status UP, but the operation status would be DOWN.
The DPU ports configuration should be admin status DOWN, in order to make the L2 tests pass.

#### Steps to reproduce the issue:
1. On bobcat switch, run command "sonic-cfggen -H -k Mellanox-SN4280-O28 -p --preset l2 > /tmp/init_l2_config.json" to generate L2 mode port configuration. 
2. Besides normal ports, the DPU ports would be admin status UP, and operation status DOWN.

#### Describe the results you received:
Ethernet224  224,225,226,227,228,229,230,231     400G   9100    N/A    etp29   trunk    down       up                                DPU-NPU Data Port         N/A
Ethernet232  232,233,234,235,236,237,238,239     400G   9100    N/A    etp30   trunk    down       up                                DPU-NPU Data Port         N/A
Ethernet240  240,241,242,243,244,245,246,247     400G   9100    N/A    etp31   trunk    down       up                                DPU-NPU Data Port         N/A
Ethernet248  248,249,250,251,252,253,254,255     400G   9100    N/A    etp32   trunk    down       up                                DPU-NPU Data Port         N/A

#### Describe the results you expected:
All the DPU ports configuration should be admin status DOWN.
Command "sonic-cfggen -H -k Mellanox-SN4280-O28 -p --preset l2" should handle the bobcat switch automatically.

#### Output of `show version`:
202405 image
```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by prabhataravind** [comment]
@dgsudharsan to follow up with @echuawu on exact failure and expected results.

**Comment by dgsudharsan** [comment]
202405 is in dark mode and hence DPUs are down. So the oper status down is expected.
