### ISSUE TITLE
docker-sonic-vs build is failing in sonic-swss repo

### ISSUE THREAD

**Issue by anilkpan** [sonic-net/sonic-buildimage#21031]
#### Description

With latest master rebase, docker-sonic-vs build is failing in sonic-swss repo. Here is the error log:

#8 1.092 Unpacking swss (1.0.0) ...
#8 4.176 Setting up libdashapi (1.0.0) ...
#8 4.181 Setting up libswsscommon (1.0.0) ...
#8 4.184 dpkg: dependency problems prevent configuration of python3-swsscommon:
#8 4.184  python3-swsscommon depends on libpython3.9 (>= 3.9.1); however:
#8 4.184   Package libpython3.9 is not installed.
#8 4.184 
#8 4.184 dpkg: error processing package python3-swsscommon (--install):
#8 4.184  dependency problems - leaving unconfigured
#8 4.184 Setting up sonic-db-cli (1.0.0) ...
#8 4.188 Setting up libsaimetadata (1.0.0) ...
#8 4.191 Setting up libsairedis (1.0.0) ...
#8 4.194 Setting up libsaivs (1.0.0) ...
#8 4.197 Setting up syncd-vs (1.0.0) ...
#8 4.198 
#8 4.198 Configuration file '/etc/init.d/syncd', does not exist on system.
#8 4.198 Installing new config file as you requested.
#8 4.210 invoke-rc.d: could not determine current runlevel
#8 4.214 invoke-rc.d: policy-rc.d denied execution of start.
#8 4.216 Setting up swss (1.0.0) ...
#8 4.217 
#8 4.217 Configuration file '/etc/swss/config.d/netbouncer.json', does not exist on system.
#8 4.217 Installing new config file as you requested.
#8 4.220 Processing triggers for libc-bin (2.36-9+deb12u7) ...
#8 4.240 Errors were encountered while processing:

ERROR: failed to solve: process "/bin/sh -c dpkg -i /debs/libdashapi_1.0.0_amd64.deb             /debs/libswsscommon_1.0.0_amd64.deb             /debs/python3-swsscommon_1.0.0_amd64.deb             /debs/sonic-db-cli_1.0.0_amd64.deb             /debs/libsaimetadata_1.0.0_amd64.deb             /debs/libsairedis_1.0.0_amd64.deb             /debs/libsaivs_1.0.0_amd64.deb             /debs/syncd-vs_1.0.0_amd64.deb             /debs/swss_1.0.0_amd64.deb" did not complete successfully: exit code: 1

##[debug]Exit code 1 received from tool '/usr/bin/bash'
##[debug]STDIO streams have closed for tool '/usr/bin/bash'
##[error]Bash exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;correlationId=1f4258d4-0bd7-4928-85d1-ea18079682b3;]Bash exited with code '1'.
##[debug]task result: Failed

#### Steps to reproduce the issue:
Issue is seen during build process

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by adyeung** [comment]
Build test failing for all code PRs on sonic-swss, this is blocking 202411

https://github.com/sonic-net/sonic-swss/pull/3316 
https://github.com/sonic-net/sonic-swss/pull/3143
https://github.com/sonic-net/sonic-swss/pull/3313

FYI @prsunny @zhangyanzhao @yuezhoujk

**Comment by adyeung** [comment]
https://github.com/sonic-net/sonic-swss/pull/3413
