### ISSUE TITLE
[eventd] eventd unit test is not stable

### ISSUE THREAD

**Issue by Junchao-Mellanox** [sonic-net/sonic-buildimage#21140]
#### Description

There is statistical failure in eventd unit test:

```
16:10:15  [ RUN      ] eventd.proxy
16:10:15  Proxy TEST started
16:10:15  tests/eventd_ut.cpp:170: Failure
16:10:15  Expected equality of these values:
16:10:15    1
16:10:15    rc
16:10:15      Which is: 36
16:10:15  tests/eventd_ut.cpp:279: Failure
16:10:15  Expected equality of these values:
16:10:15    rd_cevts_sz
16:10:15      Which is: 6
16:10:15    wr_evts.size()
16:10:15      Which is: 5
16:10:15  eventd_proxy is tested GOOD
16:10:15  [  FAILED  ] eventd.proxy (1603 ms)
```

#### Steps to reproduce the issue:
1. build eventd

#### Describe the results you received:

eventd.proxy failed

#### Describe the results you expected:

no faillure

#### Output of `show version`:

```
commit hash: 7bdf8d4bb26709001cf95397c6a8e617986dd7fd
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by anamehra** [comment]
We have also observed this error intermittently recently causing multiple build failures. It works with retyr most of the time but sometime requires multiple retires.

@abdosi , @yejianquan , for you viz

**Comment by zbud-msft** [comment]
PR fix: https://github.com/sonic-net/sonic-buildimage/pull/21200

**Comment by zbud-msft** [comment]
Hi @Junchao-Mellanox, is it possible for you take changes in #21200 and see if there is any flakiness in eventd builds on your side? I have ran ~25 image builds and have not seen any flakiness with these changes.

**Comment by Junchao-Mellanox** [comment]
sure, will try

**Comment by zbud-msft** [comment]
@Junchao-Mellanox Any update on testing?

**Comment by Junchao-Mellanox** [comment]
i ran a few times, looks good
