### ISSUE TITLE
ARM arch support for SONIC

### ISSUE THREAD

**Issue by antony-rheneus** [sonic-net/sonic-buildimage#3271]
Support for ARM architecture
>> Sonic buildimage
             Platform arch armhf and arm64 changes
Submodule support for ARM
>> Sonic swss
>> SAI
>> sairedis
>> sonic linux kernel
>> kdump

**Comment by antony-rheneus** [comment]
@lguohan , please assign this issue on my name (@antony-rheneus ) as enhancement

**Comment by antony-rheneus** [comment]
Support for ARM architecture
>> Sonic buildimage
             https://github.com/Azure/sonic-buildimage/pull/2980 - DONE
            https://github.com/Azure/sonic-buildimage/pull/3237 - DONE
           https://github.com/Azure/sonic-buildimage/pull/3263 - DONE

>> Platform/hwsku
            https://github.com/Azure/sonic-buildimage/pull/3221 - DONE
Submodule support for ARM
>> Sonic swss
       https://github.com/Azure/sonic-swss/pull/989   - DONE
       https://github.com/Azure/sonic-swss/pull/1015 - OPEN
>> sonci swss-common       
     https://github.com/Azure/sonic-swss-common/pull/298 - DONE

>> SAI
     https://github.com/opencomputeproject/SAI/pull/993  - OPEN
     https://github.com/opencomputeproject/SAI/pull/969 -DONE

>> sairedis
     https://github.com/Azure/sonic-sairedis/pull/468 - DONE
     https://github.com/Azure/sonic-sairedis/pull/490 - OPEN

>> sonic linux kernel

**Comment by stcheng** [comment]
@antony-rheneus anything left to do?

**Comment by antony-rheneus** [comment]
> @antony-rheneus anything left to do?
These are the pending items.
#1 sonic linux kernel
kernel has to be built as part of sonic build process instead of using pre-built kernel for ARM

#2 x86 grub to uboot in all scripts and utilities
Most of the script like /usr/bin/reboot, sonic-utilities uses grub.cfg to check the installed image.
Need to change it to uboot env for ARM

**Comment by antony-rheneus** [comment]
> > @antony-rheneus anything left to do?
> 
> These are the pending items.
> #1 sonic linux kernel
> kernel has to be built as part of sonic build process instead of using pre-built kernel for ARM
> 
> #2 x86 grub to uboot in all scripts and utilities
> Most of the script like /usr/bin/reboot, sonic-utilities uses grub.cfg to check the installed image.
> Need to change it to uboot env for ARM

Raised PR for sonic-linux-kernel changes
https://github.com/Azure/sonic-buildimage/pull/3556
