### ISSUE TITLE
PFC test failing on Mellanox platforms

### ISSUE THREAD

**Issue by prsunny** [sonic-net/sonic-buildimage#5014]
**Description**
pfc_functional and pfc_all_port_storm is failing on Mellanox platforms running 201911 image

**Steps to reproduce the issue:**
1. ansible-playbook test_sonic.yml -i str --limit str-sn3800-01 --vault-password-file password.txt -e testcase_name=pfc_wd -e testbed_name=vms12-t0-3800 -e restore_time=3000 -e allow_recover=true -e subtest=pfc_functional
2. ansible-playbook test_sonic.yml -i str --limit str-sn3800-01 --vault-password-file password.txt -e testcase_name=pfc_wd -e testbed_name=vms12-t0-3800 -e restore_time=3000 -e allow_recover=true -e subtest=pfc_all_port_storm

**Describe the results you received:**
```
TASK [test : Fail due to errors in logs] ***************************************
Tuesday 21 July 2020  05:09:14 +0000 (0:00:02.057)       0:05:57.232 ********** 
fatal: [str-sn3800-01]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

**Describe the results you expected:**
```

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of show version:**

```
        "SONiC Software Version: SONiC.20191130.42", 
        "Distribution: Debian 9.12", 
        "Kernel: 4.9.0-11-2-amd64", 
        "Build commit: 911270941", 
        "Build date: Wed Jul 15 15:13:00 UTC 2020", 
        "Built by: sonicbld@jenkins-slave-phx-2", 
```

    **Attach debug file `sudo generate_dump`:**

**Comment by sumukhatv** [comment]
pfc_all_port_storm is seen passing at occasionally. I believe the issue is with the log-analyzer.
