### ISSUE TITLE
show lldp does not show any data for BackEnd asics

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#6098]
**Description**
On a multi asic system, show lldp table/neighbor is empty for BackEnd asics.
lldp protocol does work on the interfaces on BackEnd asics but show output is empty.

**Steps to reproduce the issue:**
1. Configure multi-asic chassis system
2. run show lldp table on card with BackEnd asics
3.

**Describe the results you received:**
Empty list

root@sonic:/# show lldp table 
Capability codes: (R) Router, (B) Bridge, (O) Other
LocalPort    RemoteDevice    RemotePortID    Capability    RemotePortDescr
-----------  --------------  --------------  ------------  -----------------
--------------------------------------------------
Total entries displayed:  0
root@sonic:/# show lldp neighbors 
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------

root@sonic:/# 

**Describe the results you expected:**
show lldp should list port data for BackEnd asics

root@sonic:/# show lldp table
Capability codes: (R) Router, (B) Bridge, (O) Other
LocalPort     RemoteDevice    RemotePortID    Capability    RemotePortDescr
------------  --------------  --------------  ------------  -----------------
Ethernet0068  LC4.0           Eth4/0/2250     BR            Ethernet2250
Ethernet0070  LC4.0           Eth4/0/2254     BR            Ethernet2254
Ethernet0094  sonic           Eth3/0/2254     BR            Ethernet2254
Ethernet0096  sonic           Eth3/0/2250     BR            Ethernet2250
Ethernet0106  sonic           Eth3/1/2508     BR            Ethernet2508
Ethernet0124  sonic           Eth3/1/2510     BR            Ethernet2510
--------------------------------------------------
Total entries displayed:  6

**Additional information you deem important (e.g. issue happens only occasionally):**
sonic-buildimage/src/sonic-utilities% git status
HEAD detached at c2c4c0d

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by abdosi** [comment]
@anamehra we are supporting only front-end asic o/p as part of show commands. To get backend we can individual docker and execute lldpcli.

As of now there is no plan to enhance CLI command. One reason is in future we can move away from running lldp for backend asic/docker.

**Comment by anamehra** [comment]
Thanks for the update @abdosi !
LLDP helps determine the peer connectivity between frontend and backend asics. If comes handy debugging link/connectivity issues and validating configuration between these asics. In absence of LLDP, is there any other plan to fill that gap?

**Comment by abdosi** [comment]
Closing based on above comment.
