### ISSUE TITLE
show ip bgp summary fail when configured neighbor through frr

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#6135]
**Description**

show ip bgp summary throws error 'Error: peerGroupCount missing in the bgp_summary' when neighbor is configured through frr.

FC0.0# show run
Building configuration...

Current configuration:
!
frr version 7.2.1-sonic
frr defaults traditional
hostname FC0.0
log syslog informational
log facility local4
agentx
no service integrated-vtysh-config
!
enable password zebra
password zebra
!
router bgp 65100
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 bgp graceful-restart restart-time 240
 bgp graceful-restart
 bgp graceful-restart preserve-fw-state
 bgp bestpath as-path multipath-relax
 !
 address-family ipv4 unicast
  maximum-paths 64
 exit-address-family
 !
 address-family ipv6 unicast
  maximum-paths 64
 exit-address-family
!
ip nht resolve-via-default
!
line vty
!
end
FC0.0# config t
FC0.0(config)# router bgp 65100 
FC0.0(config-router)# neighbor 10.10.10.1 remote-as 65500
FC0.0(config-router)# address-family ipv4 unicast 
FC0.0(config-router-af)# neighbor 10.10.10.1 activate 
FC0.0(config-router-af)# end
FC0.0# exit
root@FC0:/home/cisco# show ip bgp sum
Usage: show ip bgp sum [OPTIONS]

Error: peerGroupCount missing in the bgp_summary

**Steps to reproduce the issue:**
1. configure bgo neighbor through vtysh
2. show ip bgp summary
3.

**Describe the results you received:**
root@FC0:/home/cisco# show ip bgp su
Usage: show ip bgp su [OPTIONS]

Error: peerGroupCount missing in the bgp_summary

**Describe the results you expected:**
bgp summary table

**Additional information you deem important (e.g. issue happens only occasionally):**
I am using a ws pulled from 201911, Nov 19 commit 7045d4a5ef4c04892812ebcd8b134bf1225136ba

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anshuv-mfst** [comment]
Configuration by vtysh is not currently supported, known issue. 
Could you please confirm if reason for using vtysh for bgp configuration?

**Comment by anamehra** [comment]
What is the planned way for configuring bgp on multi-asic? I see some configuration like neighbor data could be entered through config_db.json but some configurations like update-source, policy etc, are not supported in config_db.json.
Is there plan to support all the configuration via config_db.json?

**Comment by richawil** [comment]
In the sonic-mgmt/spytest/tests/routing/BGP/test_bgp_fast_reboot.py file, the vtysh is used to configure BGP neighbors. If such configuration is not supported, why is it being used in this file?

**Comment by richawil** [comment]
FRR is also used to configure BGP neighbors in sonic-mgmt/spytest/tests/routing/test_ip.py

**Comment by abdosi** [comment]
SONiC command has assumption to interact with DB so if we add Neighbor via FRR directly command is not design to display that. So closing this.
