### ISSUE TITLE
show ip interface CLI support for multi asic

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-buildimage#6171]
**Description**
show ip interface CLIs needs multi asic support.

**Steps to reproduce the issue:**
1. configure multi asic router
2. configure asic interfaces with ip
3. run show ip interface -n asic<id>

**Describe the results you received:**
root@sonic:/home/cisco# ip netns
asic0 (id: 1)
asic1 (id: 0)

root@sonic# show ip interfaces 
Interface    Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  -------------------  ------------  --------------  -------------
docker0                240.127.1.1/24       up/up         N/A             N/A
eth0                   1.0.0.101/24         up/up         N/A             N/A
lo                     127.0.0.1/8          up/up         N/A             N/A

root@sonic# show ip interfaces -n asic0
Error: no such option: -n
root@sonic:/home/cisco# show ip interfaces -d all
Error: no such option: -d

**Describe the results you expected:**

The CLI should list the ip interface table.

root@sonic# ip netns exec asic0 show ip inter
Interface     Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
------------  --------  -------------------  ------------  --------------  -------------
Ethernet0               10.0.0.0/31          up/up         N/A             N/A
Ethernet1               10.0.0.2/31          up/up         N/A             N/A
Ethernet2               10.0.0.4/31          up/up         N/A             N/A
Ethernet3               10.0.0.6/31          up/up         N/A             N/A
Ethernet4               10.0.0.8/31          up/up         N/A             N/A
Ethernet5               10.0.0.10/31         up/up         N/A             N/A
Ethernet6               10.0.0.12/31         up/up         N/A             N/A
Ethernet7               10.0.0.14/31         up/up         N/A             N/A
Ethernet8               10.0.0.16/31         up/up         N/A             N/A
Ethernet9               10.0.0.18/31         up/up         N/A             N/A
Ethernet10              10.0.0.20/31         up/up         N/A             N/A
Ethernet11              10.0.0.22/31         up/up         N/A             N/A
Ethernet12              10.0.0.24/31         up/up         N/A             N/A
Ethernet15              10.0.0.26/31         up/up         N/A             N/A
Ethernet18              10.0.0.28/31         up/up         N/A             N/A
Ethernet21              10.0.0.30/31         up/up         N/A             N/A
Ethernet24              10.0.0.32/31         up/up         N/A             N/A
Ethernet27              10.0.0.34/31         up/up         N/A             N/A
Ethernet30              10.0.0.36/31         up/up         N/A             N/A
Ethernet33              10.0.0.38/31         up/up         N/A             N/A
Ethernet36              10.0.0.40/31         up/up         N/A             N/A
Ethernet39              10.0.0.42/31         up/up         N/A             N/A
Ethernet42              10.0.0.44/31         up/up         N/A             N/A
Ethernet45              10.0.0.46/31         up/up         N/A             N/A
Ethernet2064            10.0.0.48/31         up/up         N/A             N/A
Ethernet2246            10.0.0.50/31         up/up         N/A             N/A
Ethernet2248            10.0.0.52/31         up/up         N/A             N/A
Ethernet2250            10.0.0.54/31         up/up         N/A             N/A
Ethernet2252            10.0.0.56/31         up/up         N/A             N/A
Ethernet2254            10.0.0.58/31         up/up         N/A             N/A
Ethernet2262            10.0.0.60/31         up/up         ARISTA01T0      11.1.0.61
Loopback0               10.1.0.1/32          up/up         N/A             N/A
eth0                    240.127.1.2/24       up/up         N/A             N/A
lo                      127.0.0.1/8          up/up         N/A             N/A

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by gechiang** [comment]
Already Fixed by https://github.com/Azure/sonic-utilities/pull/1396

**Comment by anshuv-mfst** [comment]
@anamehra - please re-test and close this issue.

**Comment by anamehra** [comment]
The CLI works for multi asics. -n, -d options work

The interfaces from host are printed in output of each asic:

Loopback0              10.1.0.1/32          up/up         N/A             N/A
docker0                240.127.1.1/24       up/up         N/A             N/A
eth0                   1.2.32.3/16          up/up         N/A             N/A
eth1                   1.0.0.31/24          up/up         N/A             N/A
                       1.0.0.33/24                        N/A             N/A
lo                     127.0.0.1/8          up/up         N/A             N/A
                       127.0.0.1/16                       N/A             N/A

I see these all interfaces with -n asic0 as well as -n aisc1 

Is this expected?

**Comment by gechiang** [comment]
@arlakshm Can you answer @anamehra in regard to his question?

**Comment by gechiang** [comment]
Reassign this to @arlakshm since he is the implementor for this show cmd for multi-asic support and it is best that he answer this questions  directly without going through 3rd party (me) :)

**Comment by abdosi** [comment]
Already fixed.
