### ISSUE TITLE
[restapi] status failed error

### ISSUE THREAD

**Issue by prsunny** [sonic-net/sonic-buildimage#6446]
**Description**

restapi feature should be enabled only for required deployments. All other deployments/roles should have the feature as disabled. There is monit reporting status failed.

ERR monit[975]: 'restapi|restapi' status failed (1) -- '/usr/sbin/go-server-server' is not running in host

**Steps to reproduce the issue:**
1. Load Sonic image with Restapi built
2.
3.

**Describe the results you received:**

ERR monit[975]: 'restapi|restapi' status failed (1) -- '/usr/sbin/go-server-server' is not running in host

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
    SONiC.20191130.57
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by bingwang-ms** [comment]
Same issue is observed on 202012.
```
root@str-msn4600c-acs-02:/# supervisorctl status
dependent-startup                FATAL     can't find command 'python3'
restapi                          STOPPED   Not started
rsyslogd                         STOPPED   Not started
start                            STOPPED   Not started
supervisor-proc-exit-listener    FATAL     Exited too quickly (process log may have details)
```
It seems caused by missing ```python3```.
