### ISSUE TITLE
lldpRemManAddrTable SNMP failure due to DHCP on Mgmt interface

### ISSUE THREAD

**Issue by tbgowda** [sonic-net/sonic-buildimage#6636]
**Description**

Sonic node configured with DHCP fails the SNMP query for OID : 1.0.8802.1.1.2.1.4.2 (lldpRemManAddrTable)

**Steps to reproduce the issue:**
1. Have a Sonic box connected either back-to-back or with LLDP enabled peer.
2. Remove static IP address on Mgmt interface if configured. Make sure there is no entry for MGMT_INTERFACE in config_db.json.
3. Reload lldp service 
4. Query SNMP for the OID provided above on Sonic box: snmpwalk -v 2c -c public <Mgmt IP> 1.0.8802.1.1.2.1.4.2

**Describe the results you received:**

iso.0.8802.1.1.2.1.4.2 = No Such Object available on this agent at this OID

**Describe the results you expected:**

Expected the sonic node to return LLDP information for the SNMP query

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue seems to be with the way lldpd configuration file is formed and the presence of IPv6 address in the redisDB. When the SNMP query comes in the code that handles it is unable to decode the IPv4 address from redisDB since it also has IPv6 address.

It looks like IPv6 issue was addressed by changing the lldpd configuration in two places:

a. Does this one fix it for 1.0.8802.1.1.2.1.3.8: https://github.com/Azure/sonic-snmpagent/pull/106 ?
b. This one seems to disallow IPv6 addresses altogether if there is a static IP: https://github.com/Azure/sonic-buildimage/pull/5699 ?

On chassis with issue:

[lldpcli] # show chassis
-------------------------------------------------------------------------------
Local chassis:
-------------------------------------------------------------------------------
Chassis:
  ChassisID:    mac 02:0a:99:b9:bb:7e
  SysName:      sonic
  SysDescr:     Debian GNU/Linux 9 (stretch) Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64
  TTL:          120
  MgmtIP:       192.168.122.56
  MgmtIP:       fd00:c0:a8:7a:1::4d
  Capability:   Bridge, on
  Capability:   Router, on
  Capability:   Wlan, off
  Capability:   Station, off
-------------------------------------------------------------------------------

root@sonic:/# cat /etc/lldpd.conf
configure system hostname sonic
pause

127.0.0.1:6379> HGETALL LLDP_LOC_CHASSIS
 1) "lldp_loc_sys_cap_supported"
 2) "28 00"
 3) "lldp_loc_sys_cap_enabled"
 4) "28 00"
 5) "lldp_loc_sys_desc"
 6) "Debian GNU/Linux 9 (stretch) Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64"
 7) "lldp_loc_sys_name"
 8) "sonic"
 9) "lldp_loc_man_addr"
10) "192.168.122.56,fd00:c0:a8:7a:1::4d"
11) "lldp_loc_chassis_id"
12) "02:0a:99:b9:bb:7e"
13) "lldp_loc_chassis_id_subtype"
14) "4"

    **Output of `show version`:**
    branch 201911

**Comment by lguohan** [comment]
can @abdosi take a look is it a 201911 image?

**Comment by abdosi** [comment]
@tbgowda 

For the MIB snmpwalk -v 2c -c public 1.0.8802.1.1.2.1.4.2 (Remote Peer)  the data is generated from table LLDP_ENTRY_TABLE from APPDB . Can you provide o/p of that table when issue is seen .

Above information is for Local Table/Mib.

**Comment by tbgowda** [comment]
@abdosi , thanks for looking at this issue. The reason why I gave the local chassis info is because that is what is being sent to the remote end through LLDP, I should have been clearer in my description of the issue. 

In any case, here is the output from the LLDP_ENTRY_TABLE.

 127.0.0.1:6379> hgetall LLDP_ENTRY_TABLE:Ethernet0
 1) "lldp_rem_index"
 2) "1"
 3) "lldp_rem_port_id"
 4) "Ethernet0"
 5) "lldp_rem_chassis_id_subtype"
 6) "4"
 7) "lldp_rem_time_mark"
 8) "2470"
 9) "lldp_rem_sys_name"
10) "sonic"
11) "lldp_rem_chassis_id"
12) "02:23:05:95:5a:71"
13) "lldp_rem_sys_desc"
14) "Debian GNU/Linux 10 (buster) Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64"
15) "lldp_rem_port_id_subtype"
16) "7"
17) "lldp_rem_sys_cap_enabled"
18) "28 00"
19) "lldp_rem_man_addr"
20) "192.168.122.242,fd00:c0:a8:7a:1::2d"
21) "lldp_rem_port_desc"
22) "Ethernet0"
23) "lldp_rem_sys_cap_supported"
24) "28 00"

**Comment by abdosi** [comment]
@tbgowda this issue should be fixed now in both master and 201911.
Please confirm.
