### ISSUE TITLE
ARP entry is not cleared after shutdown peer port

### ISSUE THREAD

**Issue by Junchao-Mellanox** [sonic-net/sonic-buildimage#6856]
#### Description

Say we have Ethernet0 and it is connected to another switch Eth/1. Shutdown Eth/1 and wait for Ethernet0 operational status change to down.  After that, see the ARP entry for Ethernet0 is not cleared even if we wait a few minutes. 

However, if we shutdown Ethernet0, all ARP entry for Ethernet0 is cleared soon.

#### Steps to reproduce the issue:
1. Shutdown peer port
2. Wait for port down and Issue comamnd `show arp` 
3. The ARP entry for the down port is still there.

#### Describe the results you received:

The ARP entry for down port should be cleared

#### Describe the results you expected:

The ARP entry for down port is not cleared

Tested with master 202012.fa7d636 and 201911.9345fff and 201911.78c44d1, all share the same result,

**Comment by prsunny** [comment]
This is an expected kernel behavior. ARP entry is not impacted by oper status. On another note, if there is an ECMP group and if a neighbor is oper down, orchagent takes care of removing it from the ECMP group. In summary, kernel neighbor entry stays during oper down and get eventually cleaned by garbage collector based on on other factors like the total number of entries.

**Comment by Junchao-Mellanox** [comment]
Thanks for the explanation.

**Comment by Junchao-Mellanox** [comment]
@antoninamelnyk could you please share your view on this issue?
