### ISSUE TITLE
Build is failing when using multiple jobs

### ISSUE THREAD

**Issue by stepanblyschak** [sonic-net/sonic-buildimage#7349]
#### Description

Recently we found out that the build is not stable when using parallel build. Observed on recent 202012 5bdbfcfb2647cf1db59401e82807c748838ffee4.

#### Steps to reproduce the issue:
1. make init
2. make configure PLATFORM=mellanox
3. make SONIC_BUILD_JOBS=12 target/sonic-mellanox.bin

#### Describe the results you received:

```
[ 01 ] [ target/debs/buster/linux-headers-4.19.0-12-2-common_4.19.152-1_all.deb ]
[ 02 ] [ target/debs/buster/sonic-device-data_1.0-1_all.deb ]
[ 03 ] [ target/debs/buster/kdump-tools_1.6.1-1_all.deb ]
[ 04 ] [ target/debs/buster/ntp_4.2.8p12+dfsg-4+deb10u2_amd64.deb ]
[ 05 ] [ target/debs/buster/libtac2_1.4.1-1_amd64.deb ]
[ 06 ] [ target/debs/buster/monit_5.20.0-6_amd64.deb ]
[ 07 ] [ target/debs/buster/openssh-server_7.9p1-10+deb10u2_amd64.deb ]
[ 01 ] [ target/debs/buster/linux-headers-4.19.0-12-2-common_4.19.152-1_all.deb ]
[ 02 ] [ target/debs/buster/sonic-device-data_1.0-1_all.deb ]
[ 03 ] [ target/debs/buster/kdump-tools_1.6.1-1_all.deb ]
[ 04 ] [ target/debs/buster/ntp_4.2.8p12+dfsg-4+deb10u2_amd64.deb ]
[ 05 ] [ target/debs/buster/libtac2_1.4.1-1_amd64.deb ]
[ 06 ] [ target/debs/buster/monit_5.20.0-6_amd64.deb ]
[ 07 ] [ target/debs/buster/openssh-server_7.9p1-10+deb10u2_amd64.deb ]
[ 01 ] [ target/debs/buster/linux-headers-4.19.0-12-2-common_4.19.152-1_all.deb ]
[ 02 ] [ target/debs/buster/sonic-device-data_1.0-1_all.deb ]
[ FAIL LOG START ] [ target/debs/buster/sx-complib_1.mlnx.4.4.2508_amd64.deb-install ]
dpkg: error: dpkg frontend lock is locked by another process
[  FAIL LOG END  ] [ target/debs/buster/sx-complib_1.mlnx.4.4.2508_amd64.deb-install ]
make: *** [slave.mk:527: target/debs/buster/sx-complib_1.mlnx.4.4.2508_amd64.deb-install] Error 1
make: *** Waiting for unfinished jobs....
[ 01 ] [ target/debs/buster/linux-headers-4.19.0-12-2-common_4.19.152-1_all.deb ]
[ 02 ] [ target/debs/buster/ntp_4.2.8p12+dfsg-4+deb10u2_amd64.deb ]
[ 03 ] [ target/debs/buster/monit_5.20.0-6_amd64.deb ]
[ 04 ] [ target/debs/buster/openssh-server_7.9p1-10+deb10u2_amd64.deb ]
[ 05 ] [ target/debs/buster/libnl-3-200_3.5.0-1_amd64.deb ]

```

#### Describe the results you expected:

Build passes with SONIC_BUILD_JOBS > 1

#### Output of `show version`:

```
Not relevant
```

#### Output of `show techsupport`:

```
Not relevant
```

#### Additional information you deem important (e.g. issue happens only occasionally):

Commit hash 5bdbfcfb2647cf1db59401e82807c748838ffee4

**Comment by anshuv-mfst** [comment]
Hi @liushilongbuaa - could you please take a look, thanks.

**Comment by liushilongbuaa** [comment]
https://github.com/Azure/sonic-buildimage/pull/7401, This PR maybe help. Can you have a try?

**Comment by stepanblyschak** [comment]
@liushilongbuaa I'll try and reply, thanks.
@qiluo-msft Which autoupdate service are you referring to? How does build servers environment affect if the build is running inside docker? I can try to narrow it down but I am afraid this issue exists for few month already, so it might not be a quick finding.

**Comment by liushilongbuaa** [comment]
https://github.com/Azure/sonic-buildimage/pull/8373
