### ISSUE TITLE
SAIREDIS Record when facing continuous SAI events is not compressing and rotating the record causing /var/log partition to completely run out of space.

### ISSUE THREAD

**Issue by gechiang** [sonic-net/sonic-buildimage#8162]
#### Description
With the continuously L2 MAC station move testcase running observed sairedis record file does not get properly rotated.
If the events is non stop one can see the /var/log partition gets completely occupied by the current sairedis record.
syslog seems to be rotating fine at a rate of every 10 minutes with my L2 MAC station move trigger.  This is not the case with SAI REDIS Record.
This issue is found in master and 202012 branches.  We confirm if this is also an issue with 201911 branch later and update this case.

Although by the time the /var/log partition storage gets completely depleted, it does nto seems to impact the normal router acticities.  But once this occured, we will loose all previous logs thus it is a debuggability issue.

#### Steps to reproduce the issue:
1. Trigger something that continuosly generate SAI events that gets logged into sairedis record. Such as coninously L2 MAC station move.
2. Check that the sapce of /var/log decreases via "df -h" command.
3. Eventually you will observe the /var/log partition completely run out of storage space. Also, sairedis record continue to grow uncontrolled...

#### Describe the results you expected:
Expect that the sairedis recod gets properly rotated instead of growing uncontrolled...

**Comment by zhangyanzhao** [comment]
Platform issue, log need cleanup regularly. Need someone from MSFT to take a further look. @lguohan

**Comment by bacrossland** [comment]
I've opened a PR on sonic-swss to fix this issue: https://github.com/Azure/sonic-swss/pull/2299
