### ISSUE TITLE
LLDP keeps failing when we remove a port and add it back immediately

### ISSUE THREAD

**Issue by tomer-israel** [sonic-net/sonic-buildimage#9445]
#### Description
when we remove a port and add it back immediately - lldp is keep failing
warning message keeps appearing:
...
[WARN/lldp] unable to send packet on real device for Ethernet4: No such device or address
...

#### Steps to reproduce the issue:
remove a port and immediately add the port back, for example:

redis-cli -n 4 del "PORT|Ethernet0"; sleep 0.1; redis-cli -n 4 hset "PORT|Ethernet0"   admin_status up alias etp1 index 1  lanes      0,1,2,3 speed 100000

#### Describe the results you received:
lldp on this port is not up and cannot recover.
warning message keeps appearing:
[WARN/lldp] unable to send packet on real device for Ethernet4: No such device or address

#### Describe the results you expected:
lldp is up on this port without any error/warning messages

#### Output of `show version`:
SONiC Software Version: SONiC.master.51908-dirty-20211117.173456
Distribution: Debian 11.1
Kernel: 5.10.0-8-2-amd64
Build commit: 0fa687a45
Build date: Wed Nov 17 17:53:00 UTC 2021
Built by: AzDevOps@sonic-build-workers-000WKI

Platform: x86_64-mlnx_msn3700c-r0
HwSKU: ACS-MSN3700C
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1852X03897
Model Number: MSN3700-CS2F
Hardware Revision: A3
Uptime: 12:33:58 up 2 min,  1 user,  load average: 0.85, 0.54, 0.21

Docker images:
REPOSITORY                    TAG                                  IMAGE ID       SIZE
docker-dhcp-relay             latest                               181edee4cf5c   435MB
docker-teamd                  latest                               c0b9086b7bc8   434MB
docker-teamd                  master.51908-dirty-20211117.173456   c0b9086b7bc8   434MB
docker-platform-monitor       latest                               b622500122c6   800MB
docker-platform-monitor       master.51908-dirty-20211117.173456   b622500122c6   800MB
docker-syncd-mlnx             latest                               58655f148c7b   1GB
docker-syncd-mlnx             master.51908-dirty-20211117.173456   58655f148c7b   1GB
docker-sonic-mgmt-framework   latest                               787c350fc6c9   577MB
docker-sonic-mgmt-framework   master.51908-dirty-20211117.173456   787c350fc6c9   577MB
docker-snmp                   latest                               a71cecd4f1b3   464MB
docker-snmp                   master.51908-dirty-20211117.173456   a71cecd4f1b3   464MB
docker-sonic-telemetry        latest                               b6f2b5e5dee8   510MB
docker-sonic-telemetry        master.51908-dirty-20211117.173456   b6f2b5e5dee8   510MB
docker-sflow                  latest                               8342262b1c51   435MB
docker-sflow                  master.51908-dirty-20211117.173456   8342262b1c51   435MB
docker-orchagent              latest                               305d1f3ed227   453MB
docker-orchagent              master.51908-dirty-20211117.173456   305d1f3ed227   453MB
docker-nat                    latest                               3fc2b03adb87   437MB
docker-nat                    master.51908-dirty-20211117.173456   3fc2b03adb87   437MB
docker-router-advertiser      latest                               275ea1f0c3b3   422MB
docker-router-advertiser      master.51908-dirty-20211117.173456   275ea1f0c3b3   422MB
docker-mux                    latest                               be026fa51c16   474MB
docker-mux                    master.51908-dirty-20211117.173456   be026fa51c16   474MB
docker-macsec                 latest                               103bd94e3f7b   438MB
docker-macsec                 master.51908-dirty-20211117.173456   103bd94e3f7b   438MB
docker-fpm-frr                latest                               ff014bfe5756   453MB
docker-fpm-frr                master.51908-dirty-20211117.173456   ff014bfe5756   453MB
docker-lldp                   latest                               7bfa8ba4dd0f   462MB
docker-lldp                   master.51908-dirty-20211117.173456   7bfa8ba4dd0f   462MB
docker-database               latest                               296b9dc2cb36   422MB
docker-database               master.51908-dirty-20211117.173456   296b9dc2cb36   422MB

#### Output of `show techsupport`:
[syslog.zip](https://github.com/Azure/sonic-buildimage/files/7661137/syslog.zip)

#### Additional information you deem important (e.g. issue happens only occasionally):
this issue has the same symptoms this issue and maybe has the same root cause:
https://github.com/Azure/sonic-buildimage/issues/6164

**Comment by tomer-israel** [comment]
I think that the problem is related to the aggregation of events on lldpd:
https://github.com/lldpd/lldpd/blob/690e447ea0a9cd488b953b95b3f1c86c8a526e03/src/daemon/event.c#L738

delete link event is "overwritten" by new link event -> lldpd is not removing the lldp info of this port and recreating it -> the socket of this lldp port is been used -> the ifindex of this port was updated but lldpd is using the old socket which was created with the old ifindex.

**Comment by zhangyanzhao** [comment]
wait for #6164

**Comment by ZhaohuiS** [comment]
The issue should be fixed in https://github.com/sonic-net/sonic-buildimage/pull/9519.
