### ISSUE TITLE
[DPB] swss docker crashes when doing DPB in DellEMC Z9332f

### ISSUE THREAD

**Issue by aravindmani-1** [sonic-net/sonic-buildimage#9663]
#### Description

- swss docker exits in DellEMC Z9332f platform when doing DPB from 1x100G(4) to 4x100G mode.

#### Steps to reproduce the issue:
1. Load latest master image.
2. Breakout the default 1x400G mode to 1x100G(4) and save the config
3. Breakout 1x100G(4) to 4x100G mode and observe swss docker exits.

#### Describe the results you received:
    -----Breakout mode available----------------
        "Ethernet0": {
                "index": "1,1,1,1,1,1,1,1",
                "lanes": "33,34,35,36,37,38,39,40",
                "breakout_modes": {
                    "1x400G": [
                        "etp1"
                    ],
                    "2x200G[100G,40G]": [
                        "etp1a",
                        "etp1b"
                    ],
                    "4x100G[50G]": [
                        "etp1a",
                        "etp1b",
                        "etp1c",
                        "etp1d"
                    ],
                    "1x100G(4)": [
                        "etp1"
                    ]
                }    
    root@sonic:~# config interface breakout Ethernet0 "1x100G(4)" -y -f
    
    Running Breakout Mode : 1x400G 
    Target Breakout Mode : 1x100G(4)
    
    Ports to be deleted : 
     {
        "Ethernet0": "400000"
    }
    Ports to be added : 
     {
        "Ethernet0": "100000"
    }
    
    After running Logic to limit the impact
    
    Final list of ports to be deleted : 
     {
        "Ethernet0": "400000"
    } 
    Final list of ports to be added :  
     {
        "Ethernet0": "100000"
    }
    Note: Below table(s) have no YANG models:
    KDUMP, SNMP, SNMP_COMMUNITY, 
    Below Config can not be verified, It may cause harm to the system
     {}
    Do you wish to Continue? [y/N]: y
    Breakout process got successfully completed.
    Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
    root@sonic:~# config save -y
    Running command: /usr/local/bin/sonic-cfggen -d --print-data > /etc/sonic/config_db.json
    root@sonic:~# 
    root@sonic:~# bcmcmd "ps ce"
    ps ce
                     ena/        speed/ link auto    STP                  lrn  inter   max   cut             loop
               port  link  Lns   duplex scan neg?   state   pause  discrd ops   face frame  thru?    FEC     back
           ce0( 20)  !ena   4  100G  FD   SW  No   Forward          None   FA    KR4  9122    No       NONE      
    drivshell>
    root@sonic:~# 
    root@sonic:~# docker ps
    CONTAINER ID   IMAGE                                COMMAND                  CREATED      STATUS             PORTS     NAMES
    59f728a3f434   docker-snmp:latest                   "/usr/local/bin/supe…"   4 days ago   Up 2 minutes                 snmp
    017af558e8ef   docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe…"   4 days ago   Up 2 minutes                 mgmt-framework
    d0aab816a579   docker-sonic-telemetry:latest        "/usr/local/bin/supe…"   4 days ago   Up 2 minutes                 telemetry
    4ad7a6a63e02   docker-router-advertiser:latest      "/usr/bin/docker-ini…"   4 days ago   Up 2 minutes                 radv
    b18245fa9a29   docker-lldp:latest                   "/usr/bin/docker-lld…"   4 days ago   Up 2 minutes                 lldp
    a41d41b0a984   docker-syncd-brcm:latest             "/usr/local/bin/supe…"   4 days ago   Up 2 minutes                 syncd
    26582d78b64d   docker-teamd:latest                  "/usr/local/bin/supe…"   4 days ago   Up 2 minutes                 teamd
    13cc5f21f153   docker-orchagent:latest              "/usr/bin/docker-ini…"   4 days ago   Up 2 minutes                 swss
    40b4b44aa4dc   docker-fpm-frr:latest                "/usr/bin/docker_ini…"   4 days ago   Up 2 minutes                 bgp
    f00607937a07   docker-platform-monitor:latest       "/usr/bin/docker_ini…"   4 days ago   Up 2 minutes                 pmon
    ce283bb9aebb   docker-database:latest               "/usr/local/bin/dock…"   4 days ago   Up About an hour             database
    root@sonic:~# 
    root@sonic:~# config interface breakout Ethernet0 "4x100G[50G]" -y -f
    
    Running Breakout Mode : 1x100G(4) 
    Target Breakout Mode : 4x100G[50G]
    
    Ports to be deleted : 
     {
        "Ethernet0": "100000"
    }
    Ports to be added : 
     {
        "Ethernet0": "100000",
        "Ethernet2": "100000",
        "Ethernet4": "100000",
        "Ethernet6": "100000"
    }
    
    After running Logic to limit the impact
    
    Final list of ports to be deleted : 
     {} 
    Final list of ports to be added :  
     {
        "Ethernet2": "100000",
        "Ethernet4": "100000",
        "Ethernet6": "100000"
    }
    Note: Below table(s) have no YANG models:
    KDUMP, SNMP, SNMP_COMMUNITY, 
    Below Config can not be verified, It may cause harm to the system
     {}
    Do you wish to Continue? [y/N]: y
    Breakout process got successfully completed.
    Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
    root@sonic:~# config save -y
    Running command: /usr/local/bin/sonic-cfggen -d --print-data > /etc/sonic/config_db.json
    root@sonic:~# 
    root@sonic:~# docker ps
    CONTAINER ID   IMAGE                                COMMAND                  CREATED      STATUS              PORTS     NAMES
    59f728a3f434   docker-snmp:latest                   "/usr/local/bin/supe…"   4 days ago   Up About a minute             snmp
    017af558e8ef   docker-sonic-mgmt-framework:latest   "/usr/local/bin/supe…"   4 days ago   Up 5 minutes                  mgmt-framework
    d0aab816a579   docker-sonic-telemetry:latest        "/usr/local/bin/supe…"   4 days ago   Up 5 minutes                  telemetry
    b18245fa9a29   docker-lldp:latest                   "/usr/bin/docker-lld…"   4 days ago   Up 5 minutes                  lldp
    40b4b44aa4dc   docker-fpm-frr:latest                "/usr/bin/docker_ini…"   4 days ago   Up 5 minutes                  bgp
    f00607937a07   docker-platform-monitor:latest       "/usr/bin/docker_ini…"   4 days ago   Up 5 minutes                  pmon
    ce283bb9aebb   docker-database:latest               "/usr/local/bin/dock…"   4 days ago   Up About an hour              database
    root@sonic:~# 
    root@sonic:~# cd /var/core
    root@sonic:/var/core# ls
    root@sonic:/var/core# 
    --------from config_db, it is observed that 2 ports tries to access the same lanes(35,36)----
    port deletion has to happen properly to avoid the crash.
        "PORT": {
            "Ethernet0": {
                "alias": "etp1",
                "index": "1",
                "lanes": "33,34,35,36",
                "speed": "100000"
            },
            "Ethernet2": {
                "alias": "etp1b",
                "index": "1",
                "lanes": "35,36",
                "speed": "100000"
            },

#### Describe the results you expected:

- Breakout mode should work when switching from 1x100G(4) to 4x100G mode.
- 

#### Output of `show version`:
    root@sonic:~# show ver
    
    SONiC Software Version: SONiC.master.61869-dirty-20211228.224253
    Distribution: Debian 11.2
    Kernel: 5.10.0-8-2-amd64
    Build commit: 13582aaa6
    Build date: Tue Dec 28 22:50:21 UTC 2021
    Built by: AzDevOps@sonic-build-workers-0010S0
    
    Platform: x86_64-dellemc_z9332f_d1508-r0
    HwSKU: DellEMC-Z9332f-O32
    ASIC: broadcom
    ASIC Count: 1
    Serial Number: 1SQXCW2
    Model Number: 0J5HDG
    Hardware Revision: A00
    Uptime: 13:18:58 up  1:07,  1 user,  load average: 0.80, 0.90, 0.71
#### Output of `show techsupport`:
[sonic_dump_sonic_20220103_131938.tar.gz](https://github.com/Azure/sonic-buildimage/files/7800787/sonic_dump_sonic_20220103_131938.tar.gz)

**Comment by aravindmani-1** [comment]
Also, it is being mentioned that "None" field could be used in platform.json. Breakout CLI doesn't work when None is included.
https://github.com/Azure/SONiC/blob/master/doc/dynamic-port-breakout/sonic-dynamic-port-breakout-HLD.md

    root@sonic:~# show interface breakout
    {
        "Ethernet0": {
            "index": "1,1,1,1,1,1,1,1",
            "lanes": "33,34,35,36,37,38,39,40",
            "breakout_modes": {
                "1x400G": [
                    "etp1"
                ],
                "2x200G[100G,40G]": [
                    "etp1a",
                    "etp1b"
                ],
                "4x100G[50G]": [
                    "etp1a",
                    "etp1b",
                    "etp1c",
                    "etp1d"
                ],
                "None(4)+1x100G(4)": [
                    "etp1"
                ]
            },
            "default_brkout_mode": "1x400G",
            "Current Breakout Mode": "1x400G",
     ^Z
    [3]+  Stopped                 show interface breakout
    root@sonic:~# config interface breakout Ethernet0 "None(4)+1x100G(4)" -y -f
    
    Running Breakout Mode : 1x400G 
    Target Breakout Mode : None(4)+1x100G(4)
    
    Ports to be deleted : 
     {
        "Ethernet0": "400000"
    }
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/dist-packages/portconfig.py", line 275, in _str_to_entries
        groups_list = [re.match(BRKOUT_PATTERN, i).groups() for i in bmode.split("+")]
      File "/usr/local/lib/python3.9/dist-packages/portconfig.py", line 275, in <listcomp>
        groups_list = [re.match(BRKOUT_PATTERN, i).groups() for i in bmode.split("+")]
    AttributeError: 'NoneType' object has no attribute 'groups'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/bin/config", line 8, in <module>
        sys.exit(config())
      File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/config/main.py", line 3547, in breakout
        add_ports = get_child_ports(interface_name, target_brkout_mode, breakout_cfg_file)
      File "/usr/local/lib/python3.9/dist-packages/portconfig.py", line 323, in get_child_ports
        mode_handler = BreakoutCfg(interface, breakout_mode, port_dict[INTF_KEY][interface])
      File "/usr/local/lib/python3.9/dist-packages/portconfig.py", line 241, in __init__
        self._breakout_mode_entry = self._str_to_entries(bmode)
      File "/usr/local/lib/python3.9/dist-packages/portconfig.py", line 277, in _str_to_entries
        raise RuntimeError('Breakout mode "{}" validation failed!'.format(bmode))
    RuntimeError: Breakout mode "None(4)+1x100G(4)" validation failed!
    root@sonic:~#

**Comment by yxieca** [comment]
@zhenggen-xu can you get someone to help @aravindmani-1. It appears that in this particular case, because Ethernet0 is seemingly unchanged, so it was NOT removed in running configuration, as result, the new ports cannot be added.

Ports to be deleted : 
 {
    "Ethernet0": "100000"
}
Ports to be added : 
 {
    "Ethernet0": "100000",
    "Ethernet2": "100000",
    "Ethernet4": "100000",
    "Ethernet6": "100000"
}

**Comment by prgeor** [comment]
++@praveen-li

**Comment by zhangyanzhao** [comment]
@samaity can you please help to take a look? Thanks.

**Comment by zhenggen-xu** [comment]
This seems to be related to the optimization we did in https://github.com/Azure/sonic-utilities/blob/master/config/main.py#L3591.  we probably need improve the logic so that we not only check speed but also lanes for example.  @samaity

**Comment by samaity** [comment]
@oleksandrivantsiv any idea? did you change anything in [sonic-utilities](https://github.com/Azure/sonic-utilities) repo regarding the recent changes done in [portconfig](https://github.com/Azure/sonic-buildimage/pull/9278) logic?

**Comment by samaity** [comment]
> @samaity can you please help to take a look? Thanks.

Just built the master image. Checking  if any recent changes in [portconfig](https://github.com/Azure/sonic-buildimage/pull/9278) logic have any effect on this error?  Will get back soon.

**Comment by prgeor** [comment]
@samaity any update?

**Comment by zhangyanzhao** [comment]
@aravindmani-1 will provide the platform.jason file

**Comment by zhangyanzhao** [comment]
@praveen-li  will talk to Sangita

**Comment by aravindmani-1** [comment]
> @aravindmani-1 will provide the platform.jason file

[platform_json.zip](https://github.com/sonic-net/sonic-buildimage/files/9882057/platform_json.zip)

**Comment by zhenggen-xu** [comment]
@aravindmani-1  As mentioned before,  the issue seemed to be here:  https://github.com/sonic-net/sonic-utilities/blob/4a3d49d359f787cae896d65fa882fbaaac6e57f2/config/main.py#L4146 ,  can you remove the below a few lines of code for optimization and try while new logic implementing is not available yet? 

```
    for item in matched_items:
        del_intf_dict.pop(item)
        add_intf_dict.pop(item)
```

**Comment by aravindmani-1** [comment]
> config interface breakout Ethernet0 "1x100G(4)" -y -f

Removing those lines didn't help.

**Comment by aravindmani-1** [comment]
> @aravindmani-1 As mentioned before, the issue seemed to be here: https://github.com/sonic-net/sonic-utilities/blob/4a3d49d359f787cae896d65fa882fbaaac6e57f2/config/main.py#L4146 , can you remove the below a few lines of code for optimization and try, while new logic implementing is not available yet?
> 
> ```
>     for item in matched_items:
>         del_intf_dict.pop(item)
>         add_intf_dict.pop(item)
> ```

Removing those lines didn't help.

**Comment by zhenggen-xu** [comment]
Please include the CLI output.  There were two issues in the ticket:
1,  Port with same speed before and after breakout would be ignored.  This should be fixed after removing the 3 lines.
2,  `None` field in CLI.   This need to be supported, and currently it was not implemented.

**Comment by aravindmani-1** [comment]
Thanks @zhenggen-xu. Removing those 3 lines resolved the first issue(Port with same speed before and after breakout would be ignored)

**CLI output:**
        root@sonic:~# config interface breakout Ethernet0 "1x100G(4)" -y -f
        
        Running Breakout Mode : 1x400G
        Target Breakout Mode : 1x100G(4)
        
        Ports to be deleted :
         {
            "Ethernet0": "400000"
        }
        Ports to be added :
         {
            "Ethernet0": "100000"
        }
        
        After running Logic to limit the impact
        
        Final list of ports to be deleted :
         {
            "Ethernet0": "400000"
        }
        Final list of ports to be added :
         {
            "Ethernet0": "100000"
        }
        Breakout process got successfully completed.
        Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
        root@sonic:~#
        root@sonic:~#
        root@sonic:~# config save -y
        Running command: /usr/local/bin/sonic-cfggen -d --print-data > /etc/sonic/config_db.json
        root@sonic:~# config interface breakout Ethernet0 "4x100G[50G]" -y -f
        
        Running Breakout Mode : 1x100G(4)
        Target Breakout Mode : 4x100G[50G]
        
        Ports to be deleted :
         {
            "Ethernet0": "100000"
        }
        Ports to be added :
         {
            "Ethernet0": "100000",
            "Ethernet2": "100000",
            "Ethernet4": "100000",
            "Ethernet6": "100000"
        }
        
        After running Logic to limit the impact
        
        Final list of ports to be deleted :
         {
            "Ethernet0": "100000"
        }
        Final list of ports to be added :
         {
            "Ethernet0": "100000",
            "Ethernet2": "100000",
            "Ethernet4": "100000",
            "Ethernet6": "100000"
        }
        Breakout process got successfully completed.
        Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
        root@sonic:~# config save -y
        Running command: /usr/local/bin/sonic-cfggen -d --print-data > /etc/sonic/config_db.json
        root@sonic:~# show interface status
          Interface                            Lanes    Speed    MTU    FEC    Alias    Vlan    Oper    Admin                                             Type    Asym PFC
        -----------  -------------------------------  -------  -----  -----  -------  ------  ------  -------  -----------------------------------------------  ----------
          Ethernet0                            33,34     100G   9100    N/A    etp1a  routed    down     down  QSFP-DD Double Density 8X Pluggable Transceiver         N/A
          Ethernet2                            35,36     100G   9100    N/A    etp1b  routed    down     down                                              N/A         N/A
          Ethernet4                            37,38     100G   9100    N/A    etp1c  routed    down     down                                              N/A         N/A
          Ethernet6                            39,40     100G   9100    N/A    etp1d  routed    down     down                                              N/A         N/A

**Comment by praveen-li** [comment]
@Aravind, Kindly raise PR for the same and assign review to Sangita.


Thanks,

Regards
Praveen
________________________________
