### ISSUE TITLE
"DEVICE_METADATA" - "bgp_asn" support

### ISSUE THREAD

**Issue by qiluo-msft** [sonic-net/sonic-buildimage#9739]
My understanding of currently SONiC behaviors:
1. supporting missing "DEVICE_METADATA" - "bgp_asn"
   - The case appears in https://github.com/Azure/SONiC/wiki/L2-Switch-mode
   - /etc/frr/bgpd.conf will have a `router bgp` line, which is not valid
2. supporting "DEVICE_METADATA" - "bgp_asn" with a value "None"
   - The case appears if /etc/sonic/minigraph.xml miss <DeviceMiniGraph> <CpgDec> <Routers>
   - /etc/frr/bgpd.conf will have a `router bgp None` line, which is not valid
3. supporting "DEVICE_METADATA" - "bgp_asn" with a int value
   - The normal L3 switch config

So right now, we need to fix sonic-device_metadata.yang to support above behaviors. In future, ideally we need to improve the first 2 cases, let /etc/frr/bgpd.conf handles them gracefully.

_Originally posted by @qiluo-msft in https://github.com/Azure/sonic-buildimage/issues/9640#issuecomment-1000919304_

**Comment by qiluo-msft** [comment]
@arlakshm @shi-su Could you help check?

**Comment by zhangyanzhao** [comment]
Qi is working with Arvind on this
